### ISSUE TITLE
Does gulp-typescript support the `--emitDecoratorMetadata` compiler option

### ISSUE THREAD

**Issue by ifyio** [ivogabe/gulp-typescript#100]
Does gulp-typescript support the `--emitDecoratorMetadata` compiler option of typescript 1.5.0-beta (http://blogs.msdn.com/b/typescript/archive/2015/04/30/announcing-typescript-1-5-beta.aspx)

**Comment by ivogabe** [comment]
Yes, you can use `emitDecoratorMetadata: true` as an option.

**Comment by ifyio** [comment]
Ok I'm currently using it like so...

```
gulp.task('build-ts', [], function() {
  
  return gulp.src(paths.typescript)
    .pipe(plumber())
    .pipe(changed(paths.output, {extension: '.js'}))
    .pipe(sourcemaps.init())
    .pipe(ts({
      declarationFiles: false,
      noExternalResolve: true,
      target: 'es5',
      module: 'commonjs',
      emitDecoratorMetadata: true,
      typescript: typescript
    }))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(paths.output));
});
```

Is this expected to work?

**Comment by ivogabe** [comment]
Yes (provided that you've installed typescript@1.5.0-beta), except that you can't use gulp-changed with gulp-typescript, since typescript needs to have all files, it needs them for type info.

**Comment by ifyio** [comment]
I see. Ok thanks.
