### ISSUE TITLE
Add support for rootDir in tsconfig.

### ISSUE THREAD

**Issue by Zoltu** [ivogabe/gulp-typescript#103]
In my `tsconfig.json`: `"rootDir": "./source",`
Error: `gulp-typescript: rootDir isn't supported. Use the base option of gulp.src instead.`

**Comment by ivogabe** [comment]
You should use the base option of gulp.src instead, like this:
```javascript
gulp.src('lib/**/**.ts', { base './lib' });
```
Note that the `base` property defaults to the place where the glob begins, in this example `lib`. But that solution isn't possible if your using `tsProject.src`. I've added support for the rootDir option to `tsProject.src`

**Comment by Zoltu** [comment]
Thanks!  I am currently using a `tsconfig.json` for project management (atom-typescript).  My goal is to not have to manage my gulp options and files separate from atom-typescript so that my development builds result in the same output as my build server builds.
