### ISSUE TITLE
How to use ES6 modules

### ISSUE THREAD

**Issue by Onigirium** [ivogabe/gulp-typescript#105]
To use ES6 modules feature, I just tried [this](https://github.com/ivogabe/gulp-typescript#typescript-version) and seemed working fine except the below error was outputted.
  
`Cannot compile external modules unless the '--module' flag is provided.`

What to do next?

**Comment by ivogabe** [comment]
You have to specify `target: 'ES6'`, `module: 'commonjs'` or `module: 'amd'` as an extra option. Did that solve your problem?

**Comment by Onigirium** [comment]
Solved! Thank you!
