### ISSUE TITLE
Trouble with sourcemaps and babel.

### ISSUE THREAD

**Issue by Zoltu** [ivogabe/gulp-typescript#106]
Using `gulp-sourcemaps` isn't working for me.

```
gulp.task('build-ts', function() {
	var options = {
		declarationFiles: false,
		noExternalResolve: true,
		noLib: false,
		target: 'ES6',
		typescript: require('typescript')
	};
	return gulp.src(paths.ts)
		.pipe(sourcemaps.init())
		.pipe(tsCompile(options)).js
		.pipe(es6Compile(babelOptions))
		.pipe(sourcemaps.write({ includeContent: true, sourceRoot: '/' + paths.root }))
		.pipe(gulp.dest('output'));
});
```

I am compiling to ES6 then using babel to compile to ES5.  This is because I am using `system` module type which isn't supported in TypeScript 1.5-beta and the option isn't accessible through `gulp-typescript` since it isn't in the enum used for mapping `target` to `module`.

The problem is, the above results in the souremap being ES6, not TypeScript.  It is unclear what exactly the problem is, very possibly due to the fact that I have two step transpilation.  Is this a known incompatibility?  If so, is there a workaround?

If I do `includeContent` the sourcemap ends up pointing at a .js file.  It points at the right path, but the file it needs to be mapped to is .ts, not .js.  If I keep includeContent = true, I can get my source maps in chrome but they are the ES6 output of the tsCompile step, not the TS input to that step (which is what I expected).

**Comment by ivogabe** [comment]
Can you try the master from GitHub? I've done some fixes to source maps in the previous week. Also gulp-typescript now supports all targets that TypeScript supports.

**Comment by Zoltu** [comment]
Appears to be fixed.  I now get .ts files.
