### ISSUE TITLE
typescript error 6053 when noExternalResolve is set to true

### ISSUE THREAD

**Issue by will-mitchell** [ivogabe/gulp-typescript#116]
Getting the following errors when noExternalResolve is set to true. The files do exist at the paths listed in the error. It works fine when noExternalResolve is set to false or when using tsc from the command line. I've included a link to the test project below.

will@linux:~/Source/test$ gulp compile-typescript
[13:21:29] Using gulpfile ~/Source/test/gulpfile.js
[13:21:29] Starting 'compile-typescript'...
Compiling TypeScript Files
[gulp] src/server/test.spec.ts
src/server/test.spec.ts(1,1): 6053 File '/home/will/Source/test/.d.ts/mocha/mocha.d.ts' not found.
src/server/test.spec.ts(2,1): 6053 File '/home/will/Source/test/.d.ts/chai/chai.d.ts' not found.
src/server/test.spec.ts(4,24): 2307 Cannot find module 'mocha'.
src/server/test.spec.ts(5,23): 2307 Cannot find module 'chai'.
src/server/test.spec.ts(8,1): 2304 Cannot find name 'describe'.
src/server/test.spec.ts(9,2): 2304 Cannot find name 'it'.
will@linux:~/Source/test$ 

link to test project: https://onedrive.live.com/redir?resid=CACC86F87A96E367%2131461

**Comment by ivogabe** [comment]
That's the expected behavior. `noExternalResolve` means that we don't look for (resolve) files outside of the input from `gulp.src` (external). That means that if not all files are included in `gulp.src`, you'll get errors that a file cannot be found.
