### ISSUE TITLE
LogReporter for unmangled TypeScript compiler output

### ISSUE THREAD

**Issue by MizzleMo** [ivogabe/gulp-typescript#120]
Would it be possible to add a logReporter that outputs the TypeScript compiler output untouched?  Currently, the "error|warn" is missing and it changes a TS code from TSXXXX to XXXX.  This causes [Visual Studio Code](http://code.visualstudio.com) to no longer parse the output correctly to surface the errors in the editor.  I imagine this is impacting other editors/plugins that also parse the output.

**Comment by ivogabe** [comment]
Thanks for reporting. I was already thinking about changing the default reporter, so I've done that. The `longReporter` can also be used with VS Code if I'm not mistaken.

**Comment by MizzleMo** [comment]
Thanks for the quick fix!  FYI, longReporter is not working for me in VSCode 0.1.0 (only released version) on gulp-typescript 2.7.3
