### ISSUE TITLE
Reference files in definitions referencing wrong location

### ISSUE THREAD

**Issue by designxtek** [ivogabe/gulp-typescript#121]
When I run gulp typescript my generated type definition file references the wrong path.

I have _references.ts with:
`/// <reference path="../typings/d3/d3.d.ts" />`

When the definition is generated for _references.ts to lets say myApp.d.ts it outputs
`/// <reference path="typings/d3/d3.d.ts" />`

It doesn't take in the `..`

**Comment by ivogabe** [comment]
Can you post your project or a minimal sample that reproduces this issue?

**Comment by designxtek** [comment]
https://github.com/designxtek/GulpTest

1. Pull
2. run npm install on src/
3. run gulp on src/
4. Look at src/MyProject/bs.tang.common.d.ts and see that the reference path doesn't match

Thanks

**Comment by ivogabe** [comment]
This is because of the way how TypeScript handles paths. TypeScript doesn't know of the `gulp.dest` call, so it can't write the right relative paths, it expects that the files will be written under `src`. You can solve it by changing your gulp file to:
```javascript
gulp.task('compileCommonTS', function() {
	var tsResult = gulp.src(tsProject.common.reference)
						.pipe(ts({ out: paths.common + tsProject.common.js, target: 'ES5', declaration: true }));	
	// "paths.common + tsProject.common.js" instead of "tsProject.common.js"			
	return merge([
        tsResult.dts.pipe(gulp.dest('./')),
        tsResult.js.pipe(gulp.dest('./'))
    ]);
});
```

**Comment by designxtek** [comment]
thanks!

**Comment by designxtek** [comment]
Is there a way to have it know which directory it is running from? 
I want it to stay in `/src/MyProject/bs.tang.common.d.ts`

**Comment by ivogabe** [comment]
You can add that directory to the `out` option.

**Comment by designxtek** [comment]
Thanks

**Comment by designxtek** [comment]
:+1:
