### ISSUE TITLE
Version 1.5.0-beta issues 1.4 warnings?

### ISSUE THREAD

**Issue by donnut** [ivogabe/gulp-typescript#122]
I've installed typescript 1.5.0-beta locally and globally. If I run the gulp.task listed below, warnings are issued suggesting tsc version 1.4 is executed.
One example of such warning/error is:
`ts/DOMIO.ts(236,13): 1153 'let' declarations are only available when targeting ECMAScript 6 and higher.`

When I run `tsc` on the command-line (v1.5.0-beta) there are no warnings/error. I seems that when running the gulp-typescript task, another tsc version is executed. As far as I am aware there is no 1.4 version on my system anymore.
Below I've listed some fragments. 

Is there a way to determine which tsc gulp-typescript is executed?

gulpfile.js
```
gulp.task('build', function() {
    var tsProject = tsc.createProject('tsconfig.json');
    var tsResult = tsProject.src()
                            .pipe(tsc(tsProject));


    return tsResult.js
                   .pipe(sourcemaps.write('.'))
                   .pipe(gulp.dest('./dist'));
});
```
tsconfig.json
```
{
    "compilerOptions": {
        "target": "es3",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts",
        ...
    ],
    "files": [
        "./dst/htmlparser2.d.ts",
        ...
    ]
}
```

**Comment by ivogabe** [comment]
See the [readme](https://github.com/ivogabe/gulp-typescript#typescript-version). gulp-typescript doesn't use the `tsc` command but uses the typescript api that is installed locally.

**Comment by donnut** [comment]
Thanks for your response. I've read the readme, but I specified the typescript version wrongly. This works:
```
gulp.task('build', function() {
    var tsProject = tsc.createProject('tsconfig.json', {
        "typescript": require('typescript')
    });
    var tsResult = tsProject.src()
                            .pipe(tsc(tsProject));
    return tsResult.js
                   .pipe(sourcemaps.write('.'))
                   .pipe(gulp.dest('./dist'));
});
```
Thanks again.
