### ISSUE TITLE
ES5 is emitted when targeting ES6

### ISSUE THREAD

**Issue by Ixonal** [ivogabe/gulp-typescript#129]
As I understand it, tsc should be able to emit ES6 code if target is set to "ES6", however I tried it with this plugin and it still appears to be outputting ES5 code.

**Comment by ivogabe** [comment]
Setting `target: "es6"` will just work. Which version of TS are you using? Using TS1.5 might help, since that version has better support for ES6.

**Comment by Ixonal** [comment]
I tried it with and without pulling in the typescript library (^1.5.0-beta) from npm, which seem to have the same effect. tsc also isn't a known command in the command prompt, so I'm not really sure where the compiler it's trying to use is located so that I can update it. Either way, you're saying that this plugin should just be calling an existing install of the TypeScript compiler?

**Comment by ivogabe** [comment]
By default it uses TypeScript 1.4.1, which is installed as a dependency of gulp-typescript. You can override that by installing a different version locally using `npm install typescript` and then adding a new option to your gulpfile like `typescript: require('typescript');`. You can see the readme for more details.

**Comment by Ixonal** [comment]
ahh, ok. Got it working, then. Sorry about the false alarm.
