### ISSUE TITLE
How to display tsc output?

### ISSUE THREAD

**Issue by tkrotoff** [ivogabe/gulp-typescript#134]
With v2.6.0 I could see tsc output/errors inside my console, things like:
```Shell
ExpenseReport.ts(66,28): 7006 Parameter 'expense' implicitly has an 'any' type.
ExpenseReportsHttpService.ts(7,25): 2304 Cannot find name 'ExpenseReportJsonOutput'.
app.ts(6,15): 7006 Parameter '$componentMapperProvider' implicitly has an 'any' type.
```

Now, even with fullReporter, I do not get tsc output anymore.

**Comment by ivogabe** [comment]
I tested it and I can still see errors. Can you create a small example (gulpfile and typescript files) that can reproduce this?

Which reporter you use shouldn't matter (as long as you don't use nullReporter), since that will only change how errors are shown, not which errors.

**Comment by tkrotoff** [comment]
See https://github.com/tkrotoff/gulp-typescript-issues and https://github.com/tkrotoff/gulp-typescript-issues/commit/8266b2814db83acd506b7ce3c89aa4a351771fcf

```Shell
$ cat node_modules/gulp-typescript/package.json | grep 'version'
  "version": "2.5.0",
$ gulp scripts
[00:29:13] Using gulpfile ~/gulp-typescript-issues/gulpfile.js
[00:29:13] Starting 'scripts'...
gulp-typescript-issues/app/app.ts(2,18): 7006 Parameter 'name' implicitly has an 'any' type.
[00:29:14] scripts: .tmp/app/app.js.map
[00:29:14] scripts: .tmp/app/app.js
[00:29:14] scripts: 2 items
[00:29:14] Finished 'scripts' after 1.14 s
$ npm update
[...]
$ cat node_modules/gulp-typescript/package.json | grep 'version'
  "version": "2.7.5",
$ gulp scripts
[00:30:16] Using gulpfile ~/gulp-typescript-issues/gulpfile.js
[00:30:16] Starting 'scripts'...
[00:30:18] scripts: .tmp/app/app.d.ts
[00:30:18] scripts: .tmp/app/app.js.map
[00:30:18] scripts: .tmp/app/app.js
[00:30:18] scripts: 3 items
[00:30:18] Finished 'scripts' after 1.32 s
```

On my real project I have the same problem with `ts.createProject` and `fullReporter`.

**Comment by ivogabe** [comment]
I found it, an error about the project root directory is hidden, as it's automatically fixed by gulp-typescript. But when an error is generated, further errors are blocked. I've moved the error filter. The hidden error won't block the generation of other errors any more.

**Comment by tkrotoff** [comment]
Thx, it works now
