### ISSUE TITLE
removeComments compiler option seems to be ignored when using typescript 1.5.0-beta

### ISSUE THREAD

**Issue by milkshakeuk** [ivogabe/gulp-typescript#135]
Specifying the option for removing comments when using gulp-typescript with the latest released version of typescript (1.5.0-beta), the comments are not removed.

Here are some of ways I have tried and failed.

```JSON
// package.json
    "devDependencies": {
        "gulp": "^3.8.11",
        "gulp-clean": "^0.3.1",
        "gulp-typescript": "^2.7.5",
        "typescript": "^1.5.0-beta"
    }

// tsconfig.json
    {
        "compilerOptions": {
            "module": "amd",
            "removeComments": true,
            "target": "ES5"
        }
    }
```

```javascript
    var ts = require('gulp-typescript');
    var options = { typescript: require('typescript') };
    var tsProject = ts.createProject('tsconfig.json', options);
```
or
```JavaScript
    var ts = require('gulp-typescript');
    var options = {
            module: "amd",
            removeComments: true,
            target: "ES5",
            typescript: require('typescript') 
        };
    var tsProject = ts.createProject(options);
```

It is however honouring the option when I don't try to override the default compiler provided by gulp-typescript.

any ideas?

**Comment by milkshakeuk** [comment]
To be clear I am referring to the reference blocks at the top of the .ts files which I would normally expect to be removed from the compiled .js files i.e.

```javascript
/// <reference path="../Interfaces/IView" />
/// <reference path="./BaseView" />
/// <amd-dependency path="/js/libs/hgn.js!app/templates/home" name="compiler"/>
```

**Comment by ivogabe** [comment]
It looks like the command line interface (`tsc --removeComments`) behaves the same. Normal comments are removed, but special comments, like these references and amd dependencies, are preserved. To remove these I'd use a minifier plugin or `gulp-replace`.

**Comment by milkshakeuk** [comment]
I wonder why the behaviour of remove comments was changed for the latest release. It doesn't make sense for the reference type comment blocks to remain in the j's files.

**Comment by ivogabe** [comment]
If you'd like that to change, you should report it at the Microsoft/TypeScript repo.

**Comment by milkshakeuk** [comment]
done [#3283](https://github.com/Microsoft/TypeScript/issues/3283).
