### ISSUE TITLE
Add type error count

### ISSUE THREAD

**Issue by joshuacc** [ivogabe/gulp-typescript#138]
I'm in the process of migrating a Grunt build over to Gulp. One feature of grunt-ts that I'm missing in gulp-typescript is a summary showing how many type errors there are:

```
>> 99 non-emit-preventing type warnings
>> Type errors only.
```

This is particularly helpful when dealing with a project that started off in vanilla JS so that developers can work on gradually lowering that number.

**Comment by ivogabe** [comment]
Thanks for the suggestion, I'll try to implement that soon.
