### ISSUE TITLE
Thoughts / ideas / progress on File-based compiler?

### ISSUE THREAD

**Issue by DavidSouther** [ivogabe/gulp-typescript#140]
https://github.com/ivogabe/gulp-typescript/blob/master/lib/compiler.ts#L166

Any work from anyone knocking out that TODO? I see mutterings of discussions across the web about that, but it really seems like the TypeScript API is heavily focused on giving it the project directory, and asking any other tools to stay out of the way.

**Comment by ivogabe** [comment]
It's being implemented in #130. As of TypeScript 1.5 it is supported to compile single files. You will not see your type errors, but you will get syntax errors. The emit is not based on type info, so the compilation is safe enough for quick debugging, also because compile times have a big decrease.

**Comment by DavidSouther** [comment]
Cool, thanks for the update on that! I'll keep an eye there, and on 1.5.
