### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by DanielRosenwasser** [ivogabe/gulp-typescript#142]
An explicit license would be ideal to ensure that those writing tools/making major contributions around gulp-typescript could do so without the risk of violating copyright.

**Comment by ivogabe** [comment]
I had only added the license to the package.json file, now I've also added it to the readme, I think that's the place where you'd expect it. Is there any specific reason why you're asking this? Just curious

**Comment by DanielRosenwasser** [comment]
Thanks! There are certain implications if you hold implicit copyright (as opposed to explicitly specifying a license). It's just a lot easier to for people who need to deal with certain bureaucratic issues when it comes to contributing.

**Comment by chharvey** [comment]
@ivogabe — I agree with @DanielRosenwasser . It’s conventional (maybe even expected) for npm packages to have a `LICENSE` file that contains the actual text of the license. Specifically, the [MIT License](https://choosealicense.com/licenses/mit/), which this project uses, requires the license text to be distributed with the source code. I can open a PR if you’d welcome it.

**Comment by ivogabe** [comment]
I missed that, would be great if you could open a PR!
