### ISSUE TITLE
Near silent failure if paths incorrect

### ISSUE THREAD

**Issue by mprobst** [ivogabe/gulp-typescript#144]
I have a project that has this layout:

```
lib/foo.ts # ... and more
test/foo_test.ts # etc.
build/lib/foo.js
build/test/foo_test.js
```

That is, I compile TS sources from `lib` into `build/lib`, and from `test` into `build/test`. The tests obviously refer to files from `lib`, using `../lib/foo` (which matches the path layout both before and after compile).

This fails when using gulp-typescript like so:

```
gulp.task('test.compile', ['compile'], function(done) {
  return gulp.src(['test/*.ts', 'typings/**/*.d.ts'])
      .pipe(sourcemaps.init())
      .pipe(ts(tsProject))
      .on('error', onError)
      .js.pipe(sourcemaps.write())
      .pipe(gulp.dest('build/test'));
});
```

The error message is only `TypeScript: emit failed.`. With a lot of debugging, I was able to figure out that there once was an error message about e.g. `lib/foo.ts` not being under the path `test`, and was then able to deduct that I have to give a base dir and write to `build`:

```
gulp.task('test.compile', ['compile'], function(done) {
  return gulp.src(['test/*.ts', 'typings/**/*.d.ts'], {base: '.'})
      .pipe(sourcemaps.init())
      .pipe(ts(tsProject))
      .on('error', onError)
      .js.pipe(sourcemaps.write())
      .pipe(gulp.dest('build/'));  // '/test/' comes from base above.
});
```

I understand why this is an issue (writing files from unrelated source roots that were found by the TypeScript compiler), but this would really benefit from a better error message and/or better behaviour.

FYI: I'm compiling separately because I don't want the `.d.ts` files from my tests to end up with my main build artefacts. Maybe there's a better solution to this overall?

**Comment by ivogabe** [comment]
Thanks for reporting. You're right about the rootDir error. That error is hidden because gulp-typescript will (re)calculate all paths, but it does prevent emit when you are using the `noEmitOnError` option.  I'll try to fix this soon, as a temporary solution I'd suggest turning `noEmitOnError` off.
