### ISSUE TITLE
Support the `exclude` property

### ISSUE THREAD

**Issue by ivogabe** [ivogabe/gulp-typescript#145]
See Microsoft/TypeScript#3188

**Comment by jdiprizio** [comment]
Thanks for this but there are two issues with your implementation (as per the original referenced TypeScript pull request):
- the property name is `exclude` and not `excludes`
- it does not use glob patterns (unless I'm mistaken, your implementation requires values such as `node_modules/**` which are not supported by TypeScript's implementation)

**Comment by ivogabe** [comment]
You're right about that, I've fixed it.
