### ISSUE TITLE
Task hangs with gulp-watch

### ISSUE THREAD

**Issue by LPGhatguy** [ivogabe/gulp-typescript#147]
It seems that the typescript module can't handle however `gulp-watch` transforms the stream.

Here's a minimal example, using `gulp-notify`, `gulp-typescript`, and `gulp-watch`.

```
var gulp = require("gulp");
var notify = require("gulp-notify");
var typescript = require("gulp-typescript");
var watch = require("gulp-watch");

gulp.task("default", function() {
	return gulp.src("src/server/scripts/**/*.ts")
		.pipe(notify("Pre-Watch"))
		.pipe(watch("src/server/scripts/**/*.ts"))
		.pipe(notify("Post-Watch"))
		.pipe(typescript())
		.pipe(notify("Post-TypeScript"))
		.pipe(gulp.dest("build/client/js"))
		.pipe(notify("Scripts done!"));
});
```

The only messages that appear are "Pre-Watch" and "Post-Watch", meaning that `gulp-typescript` is getting hung up doing something?

**Comment by ivogabe** [comment]
See #82

**Comment by LPGhatguy** [comment]
Sounds like a good day to dump `gulp-watch`, thanks.
