### ISSUE TITLE
(question): Can a custom compiler be added to a tsProject?

### ISSUE THREAD

**Issue by ttowncompiled** [ivogabe/gulp-typescript#148]
I've created my tsProject
```
var tsProject = gulpTsc.createProject('./tsconfig.json');
```
and I want to use a custom compiler. I tried,
```
var tsProject = gulpTsc.createProject('./tsconfig.json', {
    typescript: require('typescript')
});
```
but then the compiler options specified in tsconfig.json ceased to exist.

What's the correct way of both providing compiler options through tsconfig.json and using my own custom typescript compiler?

**Comment by ivogabe** [comment]
The example you gave should be working, what exactly doesn't work? Can you give the contents of your configuration file?

**Comment by ttowncompiled** [comment]
I apologize, I think it was an error on my end. I just logged the project and saw my compiler options.

I did try to accomplish the same thing using filter settings though,
```
var cp = require('child_process');
var gulp = require('gulp');
var gulpTsc = require('gulp-typescript');

var tsProject = gulpTsc.createProject('./tsconfig.json');

// ==========
// needed to execute local commands

function exec(cmd, args, callback) {
  var proc = cp.spawn(cmd, args);
  proc.stdout.on('data', function(buf) {
    process.stdout.write(buf);
  });
  proc.stderr.on('data', function(buf) {
    process.stderr.write(buf);
  });
  proc.on('close', function() {
    callback();
  });
}


// ==========
// compile

gulp.task('install.typings', function(done) {
  exec('./node_modules/tsd/build/cli.js', ['reinstall'], done);
})

gulp.task('build', ['install.typings'], function(done) {
  var tsResult = gulp.src('./modules/**/*.ts')
      .pipe(gulpTsc(tsProject, {
          typescript: require('typescript')
        }));
  console.log(tsProject);
  return tsResult.js.pipe(gulp.dest('./dist/modules'));
});
```
This won't build and throws an output error, 'could not find .../modules/foo_dir/foo.ts. Make sure you don't rename a file before you pass it to ts.filter()'

The file is at that location and hasn't been renamed. Is there a difference between what I posted above (which does work, that was my bad) and what is posted here (which doesn't work and I'm pretty sure I didn't cause this one haha).

**Comment by ivogabe** [comment]
The second argument of the `gulpTsc` method should contain the filter settings, not extra compiler settings. You can only specify these settings in the createProject call.

**Comment by ttowncompiled** [comment]
Gotcha. Thank you very much for taking the time to clarify.
