### ISSUE TITLE
Compile ignores secondary subdirectories.

### ISSUE THREAD

**Issue by chocolatechipui** [ivogabe/gulp-typescript#149]
I'm using gulp-typescript v2.7.5. Here's my task:

```
gulp.task('compile', function() {
  var tsResult = gulp.src([
    "./src/ts/core.ts",
    "./src/ts/expose-$.ts",
    "./src/ts/extend.ts",
    "./src/ts/strings.ts",
    "./src/ts/feature-detection.ts",
    "./src/ts/collection/each.ts",
    "./src/ts/collection/unique.ts",
    "./src/ts/collection/eq.ts",
    "./src/ts/collection/index.ts",
    "./src/ts/collection/is.ts",
    "./src/ts/collection/css.ts"])
    .pipe(ts({
		  target: "es5",
		  sourceMap: false,
      out: 'chocolatechip.js',
      removeComments: true
      }));
  return tsResult.js.pipe(gulp.dest('js'));
});
```
All the files in ```"./src/ts/collection``` get ignored. I could take the files out of "collection" but I have so many files and I would expect that I can organize them in subdirectories and then access them for parsing as above. Is this a bug or am I not doing something right?

**Comment by ivogabe** [comment]
That might be related to how gulp handles file paths. What happens when you change your gulp.src call to:
```javascript
gulp.src([ /* ... */ ], { base: "./src/ts" })
```

**Comment by chocolatechipui** [comment]
I'm at WWDC but I'm going to put together some test cases to sort out whats happening better.

**Comment by ivogabe** [comment]
Since WWDC is over, have you tried the base option? Did it solve your issue?

**Comment by chocolatechipui** [comment]
Actually I just took a different approach to work around it, so I'm fine now.

**Comment by jarroddungan** [comment]
FYI I had the same problem, added the {base: '...'} option and it worked great.
