### ISSUE TITLE
Not using TS 1.5 when it should

### ISSUE THREAD

**Issue by robertbaker** [ivogabe/gulp-typescript#151]
I followed the directions to use TS 1.5 and it seems that with the tsconfig.json

note: $.typescript is gulp-typescript
```
gulp.src([path.join(conf.paths.src, '/app/**/*.ts')])
  .pipe($.typescript(tsProject))

var tsProject = $.typescript.createProject('tsconfig.json', {
        sortOutput: true,
        typescript: require('typescript')
    });

    "typescript": "Microsoft/TypeScript",

tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "removeComments": true,
        "sourceMap": true,
        "target": "ES5"
    },
     "exclude": [
        "node_modules",
         "bower_components"
     ]
}

```

I'm getting cannot find type def errors all over the place.

I removed the reference path comments.

I have my tsd typings in .tmp/typings, which is not excluded.

Running, tsc from my project root outputs js files with no errors.

**Comment by ivogabe** [comment]
You should add references to the definition files or add them to the `gulp.src` call. In the next version you can use `tsProject.src()` instead of `gulp.src()`, that will load all files as specified in the tsconfig file.
