### ISSUE TITLE
Referenced files crash gulp-typescript on TS 1.5

### ISSUE THREAD

**Issue by zlumer** [ivogabe/gulp-typescript#152]
`gulp-typescript` v2.7.6
`typescript` v1.5.0-beta local and global.

Compile task:
```js
gulp.task('compile', function()
{
	var proj = typescript.createProject('src/tsconfig.json');
	proj.typescript = require('typescript');
	proj.sortOutput = true;
	return gulp.src('src/**/*.ts')
		.pipe(typescript(proj))
		.pipe(concat('index.js'))
		.pipe(gulp.dest('www/js/'))
	;
});
```

Line causing errors:
```ts
///<reference path="./Screen.ts" />
```

Now, if I compile it as-is, gulp-typescript gets filenames using internal TypeScript 1.4, returning referenced file names as `filename`. However, TypeScript 1.5 is looking for `fileName` (notice the capitalization). This crashes my build task.

For me, the problem was solved by replacing `typescript` in `gulp-typescript/node-modules` with an updated version.

Do you have plans to switch to v1.5 soon?

**Comment by ivogabe** [comment]
After the createProject call you can't modify the options any more. You should use the following:

```javascript
var proj = typescript.createProject('src/tsconfig.json', {
  typescript: require('typescript'),
  sortOutput: true
});
```

I plan to use the latest stable release as the default compiler version, so when TS 1.5 is released, I will make that default.

Did that solve your problem?

**Comment by zlumer** [comment]
Yes, it helped, thank you.

Has it always been like that? I think `proj.typescript = require('typescript');` worked in previous versions (I haven't used `tsconfig.json` before).

**Comment by ivogabe** [comment]
I'm not sure whether it worked in previous versions, maybe it worked but that wasn't intentional. You can find the supported public api in the readme.
