### ISSUE TITLE
Errors in angulars d.ts files 

### ISSUE THREAD

**Issue by tbekaert** [ivogabe/gulp-typescript#153]
I have a small project written with Angular.js 1.x and Typescript and I'm trying to use your plugin but I keep getting errors from the angular declaration files, which I get from the [DefinitelyTyped repo](https://github.com/borisyankov/DefinitelyTyped/tree/tsc-1.5.0-alpha)

Here is my app structure:
```
app/
   - **/*.js // my project typescript files
assets/
   types/
      - **/*/d.ts // my declaration files in differents folders
   js/
      - out.js // my compiled file
gulpfile.js
```

My package.json devDependecies:
```
"gulp": "^3.8.11",
"gulp-plumber": "^1.0.0",
"gulp-typescript": "^2.7.6",
"typescript": "1.5.0-beta"
```

And finaly, my gulp task:
```
var onError = function (err) {
  gutil.beep();
  console.log(err);
  this.emit('end');
};

var tsProject = typescript.createProject({
  target: 'ES5',
  out: 'assets/js/out.js',
  noImplicitAny: true,
  declarationFiles: false,
  noExternalResolve: true,
  noEmitOnError: false,
  isolatedCompilation: true,
  typescript: require('typescript')
});

gulp.task('ts', function () {
  var tsResult = gulp.src(['app/**/*.ts', 'assets/types/**/*.d.ts'], {base: '.'})
    .pipe(plumber({ errorHandler: onError }))
    .pipe(typescript(tsProject));

  return tsResult.js.pipe(gulp.dest(path.js));
});
```

When compiling, I get lots of errors (around 400) from all d.ts files such as `assets/types/angularjs/legacy/angular-scenario-1.2.d.ts(166,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'angular' must be of type 'IAngularStatic', but here has type 'IAngularStatic'.` (which is a strange error BTW)
Anyway, I get a `TypeScript: emit succeeded (with errors)` message but my out.js files is not generated.

Did anyone see where I've done something wrong?

**Comment by ivogabe** [comment]
It might be failing because you have two definition files for angular. Both declare a variable angular, with type IAngularStatic, but there are two different versions of IAngularStatic (one per file).

Also I see you're using isolatedCompilation, what happens when you turn that off?

**Comment by tbekaert** [comment]
I didn't thought about that!

I've changed my gulp.src like this:
```
gulp.src([
  path.ts.app + '**/*.ts',
  path.ts.types + 'angularjs/angular.d.ts',
  path.ts.types + 'angular-ui-router/angular-ui-router.d.ts',
  path.ts.types + 'angular-translate/angular-translate.d.ts',
  path.ts.types + 'angular-material/angular-material.d.ts',
  path.ts.types + 'jquery/jquery.d.ts'
], {base: '.'})
```
And there is no error left !

Thanks for your time
