### ISSUE TITLE
Extremely long builds

### ISSUE THREAD

**Issue by BSick7** [ivogabe/gulp-typescript#155]
I tried this `gulp-typescript` plugin to run my builds and it took extremely long to execute.

I am using the following repository: https://github.com/wsick/minerva

Branch: gulp (using `gulp-tsc`)
Local `gulp default`: 2.46s

Branch: gulp-typescript (using `gulp-typescript`)
Local `gulp default`: 38s

**Comment by ivogabe** [comment]
Thanks for reporting. With your example I was able to reproduce it. Investigating it now.

**Comment by ivogabe** [comment]
I found the cause. `source-map` has a bad performance when there are a lot of files with source maps. The source maps of every input file was used to calculate the output source map. That's necessary when you use a preprocessor with source map support. I'll release a new version with a fix for this issue soon.
