### ISSUE TITLE
error TS2339: Property 'origin' does not exist on type 'Location'.

### ISSUE THREAD

**Issue by indapublic** [ivogabe/gulp-typescript#158]
OSX 10.10.4, MS Visual Code 0.3.0 (lib.d.ts is locating inside application)

gulp script:

```
gulp.task('test2', function (callback) {
	var res = gulp.src([
		'source/ts/docmaster/document/Explorer.class.ts'
	])
		.pipe(typescript({
			declarationFiles: true,
			// noExternalResolve: true
		}));
		
	return merge([
		res.dts.pipe(gulp.dest('source/ts/d.ts')),
		res.js.pipe(gulp.dest('source/ts/d.ts'))
	])
});
```

Compile says

```
error TS2339: Property 'origin' does not exist on type 'Location'.
```

for my code

```
window.location.origin
```

**Comment by ivogabe** [comment]
That looks like an issue of TypeScript, can you report it there? Maybe it's already reported, so you can do a quick search first.

**Comment by indapublic** [comment]
But compiling by tsc is successfully

**Comment by ivogabe** [comment]
Then I'll need more information of your project. Is it located on GitHub or can you create a small example that can reproduce this behavior?

**Comment by indapublic** [comment]
Of course. I created [small example](https://github.com/indapublic/gulp-typescript-test)

**Comment by ivogabe** [comment]
Probably your installed `tsc` has version 1.5 beta. gulp-typescript uses 1.4 at the moment, but you can use 1.5 beta (see readme). `origin` looks to be added in 1.5, so you have to use the beta of 1.5
