### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by NekR** [ivogabe/gulp-typescript#159]
Ability to provide ```"jsx"``` property for compiler options. Right now I cannot use ```gulp-typescript``` with ```ntypescript``` and ```jsx``` property.

**Comment by ivogabe** [comment]
Can you test it with the `tsx` branch from GitHub?

**Comment by NekR** [comment]
@ivogabe it works with ``tsx`` branch and also tried again with version on npm and realized that I forgot to add '.tsx' flies to ``gulp.src``. However, neither old version (npm) nor new (tsx branch) does not correctly emits .jsx files with option ```"jsx": "preserve"```, they emits .js files.
```"jsx": "react"``` works fine with both old and new versions.

**Comment by NekR** [comment]
Might it be some npm cache?

**Comment by ivogabe** [comment]
I haven't released it on NPM yet. I have fixed the extension problem, I'll try to release a new version on NPM later this week.

**Comment by NekR** [comment]
Thanks for the update!

**Comment by cstefan** [comment]
I think there is an issue with type casting
ex:
var tvId: string = <any>inputEl.value.trim();

How can we use both typescripts type casting and the jsx syntax?

**Comment by ivogabe** [comment]
@cstefan In short, you must use the .tsx extension instead of .ts and typecasts must use the new `as` operator: `foo as Bar` instead of `<Bar> foo`. (You can still use the old cast syntax in .ts files). See the TypeScript repo for more details.

**Comment by ashwinr** [comment]
+1, @ivogabe any update on when this is available on npm?

**Comment by ivogabe** [comment]
Just released it as 2.8.0

**Comment by nripendra** [comment]
Can anyone provide me direction on how to compile tsx file with v 2.8.0? I'm getting error "File {filename} must have extesion .ts or .d.ts"

**Comment by ivogabe** [comment]
@nripendra Are you using TS 1.5.3 or typescript@next (development version of ts 1.6)? 1.5.3 doesn't support jsx

**Comment by nripendra** [comment]
Got it thank you. I downloaded latest from the github repo, and assigned to typescript option.
