### ISSUE TITLE
Plans to support Typescript 1.5

### ISSUE THREAD

**Issue by olivr70** [ivogabe/gulp-typescript#160]
Hi,

is anyone working on or has plans to add Typescript 1.5 support to gulp-typescript ? 

Olivier

PS : I can contribute, but I am not fluent enough in node/gulp/typescript to start it myself

**Comment by ivogabe** [comment]
You can already use 1.5. You can see the details in the [readme](https://github.com/ivogabe/gulp-typescript#typescript-version). When 1.5 stable is released, it'll be the default, but now 1.5 is only a beta.
