### ISSUE TITLE
gulp cwd+base combined option use not working

### ISSUE THREAD

**Issue by mgcrea** [ivogabe/gulp-typescript#161]
Nothing is emitted when I use the [gulp base option](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase).

```js
var gdebug = require('gulp-debug');
gulp.task('scripts', function() {
    var tsResult = gulp.src('scripts/**/*.ts', {cwd: 'app', base: 'app'}).pipe(gdebug()).pipe(ts(tsProject));
    return merge([ 
        tsResult.dts.pipe(gdebug()),
        tsResult.js.pipe(gdebug())
    ]);
});
```

It does work if I remove the base option.

**Comment by ivogabe** [comment]
It should work when the files are inside a subdirectory of the base property. For example, this should work:
```javascript
gulp.src('scripts/client/**/*.ts', {base: 'scripts'})
```
I'm not sure whether your config is supported by gulp. If it is, I'll take a look at how this can be fixed.

**Comment by mgcrea** [comment]
@ivogabe, not sure why using both `cwd` + `base` would be unsupported as it's the only way to properly decorrelate the base folder from a search glob. I've been using it for a couple of years without any issue with a lot of different gulp plugins. This setup does emit valid vinyl file objects.

Would love to help with a workaround but the source code is a bit hard to navigate (+ not yet fluent in typescript). I'd gladly have a try if you can point me in the right direction.

**Comment by ivogabe** [comment]
I've done some testing, and I found that the cwd from the file was used to calculate the absolute base path, but instead process.cwd() should be used. I've fixed that, so your config should be working with the next version
