### ISSUE TITLE
Add an option to get back a proper vfs object stream 

### ISSUE THREAD

**Issue by mgcrea** [ivogabe/gulp-typescript#163]
The current exotic API (that returns an object {js, dts}) is breaking any gulp setup relying on pre-hooked transforms using stream combination [stream-combiner-2](https://github.com/substack/stream-combiner2). For instance, check [this file](https://github.com/ng-tools/factory-angular-channels/blob/master/lib/channels/scripts/base.js), that can be piped as a transform anywhere (after a watch, via gulp-inject, etc.).

Having a `merge: true` or `stream: true` options forcing this plugin to return a merged stream of objects would be great. For now, it looks like the base object emits source files.

**Comment by ivogabe** [comment]
I've been thinking to change the base object to a combined stream by default in the next major version (as that would be a breaking change). Currently that stream only streams js files. The different streams make it easier to add more plugins after gulp-typescript, as you might want to minify your js files (but not the definition files).

**Comment by rayshan** [comment]
+1

This is my use case:

```js
gulp.task("scripts", function () {
    var tsProject = gp.typescript.createProject("tsconfig.json");

    var vendorScripts = [
        // ...
    ];

    var tsResult = tsProject.src()
        .pipe(gp.typescript(tsProject));

    return tsResult.js
        .pipe(gulp.src(vendorScripts))
        .pipe(gp.concat('main.js'))
        .pipe(gulp.dest("build/assets/scripts"));
});
```

`gulp.src` is supposed to add files to pipeline at any point: 
https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#380

But output currently doesn't include compiled typescript files.

**Comment by ivogabe** [comment]
@rayshan I don't think that's related to this issue. I did a quick test and it was working for me.

**Comment by rayshan** [comment]
@ivogabe it's happening consistently for me. I tried 2.8 and HEAD. I also tried to use just 1 vendor script src and remove all compilerOptions. Any other info I can provide? Should I open a new issue?

**Comment by ivogabe** [comment]
@rayshan Yes, create a new issue and include your gulpfile, tsconfig, and directory structure.

**Comment by RehanSaeed** [comment]
+1. This seems to be the most actively developed TypeScript Gulp plugin but right now it does not conform to Gulp's way of doing things. My use case is that I want to use gulp-typescript in the middle of my gulp task and only for .ts files using gulp-if.

Right now, I'm using [gulp-tsc](https://www.npmjs.com/package/gulp-tsc) instead.

```
var typeScriptProject = typescript.createProject({
    noImplicitAny: true,                    // Warn on expressions and declarations with an implied 'any' type.
    suppressImplicitAnyIndexErrors: false,  // Suppress noImplicitAny errors for indexing objects lacking index signatures.
    target: "ES5",                          // Specify ECMAScript target version: 'ES3' (default), 'ES5' or 'ES6'. 
    module: "system", charset               // Specify module code generation: 'commonjs', 'amd', 'umd' or 'system'.
});
gulp.task("build-js", ["clean-js", "lint-js"], function () {
    return gulp                             // Return the stream.
        .src(source.paths)                  // Start with the source paths.
        .pipe(plumber())                    // Handle any errors.
        .pipe(gulpif(
            environment.isDevelopment(),    // If running in the development environment.
            sourcemaps.init()))             // Set up the generation of .map source files for the JavaScript.
        .pipe(gulpif(                       // If the file is a TypeScript (.ts) file.
            "**/*.ts",
            typescript(typeScriptProject))) // Compile it to JavaScript (.js) using typeScriptProject for quicker incremental compilation.
        .pipe(concat(source.name))          // Concatenate JavaScript files into a single file with the specified name.
        .pipe(sizeBefore(source.name))      // Write the size of the file to the console before minification.
        .pipe(gulpif(
            !environment.isDevelopment(),   // If running in the staging or production environment.
            uglify()))                      // Minifies the JavaScript.
        .pipe(sizeAfter(source.name))       // Write the size of the file to the console after minification.
        .pipe(gulpif(
            environment.isDevelopment(),    // If running in the development environment.
            sourcemaps.write(".")))         // Generates source .map files for the JavaScript.
        .pipe(gulp.dest(paths.js));         // Saves the JavaScript file to the specified destination path.
});
```

**Comment by ivogabe** [comment]
@RehanSaeed The gulpfile you posted should work fine with gulp-typescript. The resulting stream only contains the javascript files, not the definition files. For you, that should be working fine. 

The downside of merging the two streams is that it either can breaks existing gulpfiles (if we do it by default), or it requires a new non-standard option, what I want to prevent.

**Comment by RehanSaeed** [comment]
@ivogabe Excellent, it was not clear to me reading the doc. Perhaps an example with more traditional gulp.src -> typescript -> gulp.dest could be added to make it more clear for others.

**Comment by ivogabe** [comment]
@RehanSaeed I've updated the readme and added such example
