### ISSUE TITLE
How to configure typescript 1.5 and tsconfig file

### ISSUE THREAD

**Issue by pherbel** [ivogabe/gulp-typescript#164]
I would like to add tsconfig file and I want to use the typescript 1.5.0-beta.
I have not found any documentation how I can configure these two things together.

**Comment by lnlwd** [comment]
Same problem here, i need to use typescript 1.5.0-beta and this plugin uses 1.4.1...

**Comment by ivogabe** [comment]
You can use this:
```javascript
var tsProject = ts.createProject('tsconfig.json', { typescript: require('typescript') });
```
And install typescript as a (dev) dependency with the version you want to use. When 1.5 (stable) is released, I'll release a new version of gulp-typescript with 1.5 as default.

**Comment by pherbel** [comment]
Thank you for your help. 
It will help until you will update the package with 1.5. Actually the 1.5 is released today.

**Comment by ivogabe** [comment]
Working on it (#167)

**Comment by ivogabe** [comment]
New version is released on NPM

**Comment by pherbel** [comment]
Thanks
