### ISSUE TITLE
tsconfig.json "files" are relative to the tsconfig file and not rootDir

### ISSUE THREAD

**Issue by wereHamster** [ivogabe/gulp-typescript#165]
I have set `rootDir:"src"` and the `files` array contains files like `src/foo/bar.ts`. When I use `tsProject.src()`to generate the source list for gulp, it fails with `error TS6053: File XXX not found`. The problem is that the plugin considers the files to be relative to the `rootDir` instead of the config file. The relevant code is in the implementation of `Project.prototype.src` which resolves the files relative to `base` instead of `configPath`.

https://github.com/ivogabe/gulp-typescript/blob/82b7ad2a8c1e043fb5b0f7a69ac975048d9509ef/lib/project.ts#L129-L130

**Comment by ivogabe** [comment]
Thanks for reporting, fixed.
