### ISSUE TITLE
Unknown options in readme

### ISSUE THREAD

**Issue by dsebastien** [ivogabe/gulp-typescript#168]
The following options, mentionned in the project's readme file don't seem to exist anymore w/ TypeScript 1.5.3:
* declarationFiles (becomes declaration?)
* sortOutput
* noExternalResolve (becomes noResolve?)

**Comment by ivogabe** [comment]
These are unofficial settings, `declarationFiles` is an alias of `declaration` (it's there for backward compatibility). `sortOutput` & `noExternalResolve` are extra settings to make the integration between gulp and typescript better.

**Comment by dsebastien** [comment]
Okay I get it, which explains why I could still use these in combination with gulp-typescript and not anymore now that I put all TS compiler options in tsconfig.json :)

I guess you could probably bump the major of gulp-typescript at some point and remove all that / push to use tsconfig.json as I guess that's the way to go now.

Thanks!

**Comment by ivogabe** [comment]
I've split the options paragraph in two sections, one with official options and one with the unofficial. I'll revisit these options when I do a new major release, but I don't think they can all be removed, as a part of them were added to make the integration between gulp & ts better.
