### ISSUE TITLE
Intellisense in gulpfile.js

### ISSUE THREAD

**Issue by varghesep** [ivogabe/gulp-typescript#173]
I have a ASP.NET MVC6 project created in Visual Studio 2015. In the gulpfile.js, I'm using gulp-typescript like below:

``` javascript
var gulp = require("gulp"),
    rimraf = require("rimraf"),
    concat = require("gulp-concat"),
    cssmin = require("gulp-cssmin"),
    uglify = require("gulp-uglify"),
    ts = require("gulp-typescript"),
    project = require("./project.json");
```

When I type **ts.** to see the methods it supports, I don't see **createProject**. How can I get intellisense for gulp-typescript in Visual Studio 2015?

**Comment by ivogabe** [comment]
I'm not sure how intellisense works in VS2015. I do know that in VSCode you can just grab a definition file (.d.ts) from Definitely Typed to get JavaScript intellisense, but I don't know whether that works in VS 2015.

Is intellisense working for `gulp`? Does VS show you that `ts` is callable?

**Comment by varghesep** [comment]
You can get intellisense in VS 2015 for JavaScript if you use d.ts. But in this case, gulpfile.js is created by the VS ASP.NET template and is used by the build. I don't know whether creating a typescript for gulpfile.js and referencing other d.ts would help? In my opinion, the VS should support intellisense for JavaScript.

**Comment by ivogabe** [comment]
It shouldn't matter that the file is generated and used by the build. Can you try to add a d.ts file and reference that from your gulpfile?

**Comment by ivogabe** [comment]
@varghesep Is this still an issue?

**Comment by varghesep** [comment]
Sorry for the late response. 

It is working now although I did not have to do anything. I use the latest [http://www.microsoft.com/en-us/download/details.aspx?id=48738](ASP.NET and Web Tools) which might have made the reference. What I see is that VS 2015 is loading the intellisense files and show the definition also correctly. 

![intellisense](https://cloud.githubusercontent.com/assets/12233474/9840475/4991a108-5a58-11e5-9be6-66448c636799.png)

**Comment by ivogabe** [comment]
Good to hear that!
