### ISSUE TITLE
Missing references to definitions in output

### ISSUE THREAD

**Issue by jedmao** [ivogabe/gulp-typescript#175]
Input:
```ts
///<reference path="../typings/postcss/.d.ts" />
import postcss from 'postcss';
```

Output:
```js
import postcss from 'postcss';
declare var _default: postcss.Plugin;
```

Notice that there is no reference comment at the top. Here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es6",
    "declaration": true,
    "newLine": "LF",
    "noResolve": true,
    "outDir": "build",
    "rootDir": "."
  }
}
```

And here's how I'm using it in my gulp task:

```js
import filter from 'gulp-filter';
import gulp from 'gulp';
import { merge } from 'event-stream';
import ts from 'gulp-typescript';
import { compilerOptions } from '../tsconfig';

export default () => {
	const libResult = gulp.src(
			[
				'typings/**/*.d.ts',
				'typings/postcss/.d.ts',
				'lib/**/*.ts',
				'test/**/*.ts'
			],
			{ base: compilerOptions.rootDir })
		.pipe(ts(compilerOptions));

	return merge(
		libResult.dts
			.pipe(filter(['**', '!test/**']))
			.pipe(gulp.dest(compilerOptions.outDir)),
		libResult.js.pipe(gulp.dest(compilerOptions.outDir))
	);
};
```

I could swear I saw the reference comments at some point, but I have no idea how I made that happen. I definitely tried adding `removeComments: false` to my `tsconfig.json`, but that didn't work. I even tried `true`, just for shits.

Any ideas?

**Comment by ivogabe** [comment]
It might be a bug of TypeScript. Have you tried using `tsc`? If `tsc` also doesn't emit the reference comment, it's an issue of TypeScript.

Besides that, gulp-typescript has built-in support for [tsconfig](https://github.com/ivogabe/gulp-typescript#using-tsconfigjson) files. That shouldn't matter for this issue, but it's just a minor improvement for your gulpfile.

**Comment by jedmao** [comment]
`tsc` also didn't emit the reference comments, but that's because the reference paths were wrong in the first place! Really wish it threw some errors in that case. Ah well! Thanks.

**Comment by jedmao** [comment]
Oh! And thanks for helping me [simplify my typescript task](https://github.com/jedmao/postcss-triangle/blob/6b428fd0f89011373858db02813bff6f554293a8/.tasks/gulp-typescript.js).
