### ISSUE TITLE
experimentalDecorators

### ISSUE THREAD

**Issue by MartyIX** [ivogabe/gulp-typescript#177]
Hi,

I'm trying to allow `--experimentalDecorators` flag. I read documentation and I didn't find any information about the option. Can I allow the flag?

Thank you!

**Comment by ivogabe** [comment]
Yes, you can add that option like this:
```javascript
[...].pipe(ts({
    experimentalDecorators: true
});
```

**Comment by MartyIX** [comment]
That works. Thank you very much!
