### ISSUE TITLE
output paths are wrong

### ISSUE THREAD

**Issue by venil7** [ivogabe/gulp-typescript#178]
```
gulp.task('build-ts', function() {
  gulp.src('src/**/*.ts', { base: 'src/' })
    .pipe(typescript({
      out: 'app.js',
      outDir: 'build',
      target: 'ES5',
      module: 'commonjs'
    }))
    .js
    .pipe(gulp.dest('build'));
});
```

the above task generates two `(2)` app.js output files, one empty in `build/app.js`, and one compiled js in `build/Home/myusername/sources/path/to/project/app.js`

**Comment by ivogabe** [comment]
I didn't have time to dive into this earlier. I've tried to reproduce it, but I couldn't get your behavior. I do have some questions about your configuration. I see you're using the `out` option, which cannot be used with external modules, and you're using `module` and `outDir`, which can only be used with external modules. Are you using external modules? That is, are you using `import ... = require(...)` or `import ... from '...'`? If so, you shouldn't be using the `out` option as you can't just concat commonjs files. If not, you shouldn't be using `outDir` and `module`. In both cases, removing the unnecessary option(s) should fix your problems.

**Comment by venil7** [comment]
Thanks, I didn't know `out` and `module` where mutually exclusive, everything is working now
happy to close the issue.
