### ISSUE TITLE
gulp.watch significantly slows compilation

### ISSUE THREAD

**Issue by myitcv** [ivogabe/gulp-typescript#182]
According to [the docs](https://github.com/ivogabe/gulp-typescript#incremental-compilation) `gulp.watch` should be used for incremental compilation. 

This is, however, significantly slower than using `tsc --watch`. 

Consider a `tsconfig.json` similar to this:

```json
{
  "compilerOptions": {
    "target": "es6",
    "declaration": false,
    "noImplicitAny": true,
    "removeComments": false,
    "noLib": false,
    "sourceMap": true,
    "jsx": "react",
  }
}
```

and a `gulp` task similar to:

```javascript
var shell = require("gulp-shell");

gulp.task("ts_watch", shell.task([
        "tsc --watch"
]));
```

re-compilation speed is improved significantly.

Unless I'm incorrectly using the steps outlined in the docs?

Thoughts?

**Comment by ivogabe** [comment]
Can you post your gulpfile?

**Comment by myitcv** [comment]
I've spotted where I think the problem might be (and it's on my side). Apologies, let me revert once I've tested my hypothesis.

**Comment by myitcv** [comment]
Apologies, it turns out this is something of my own making. Closing
