### ISSUE TITLE
piping with other js

### ISSUE THREAD

**Issue by npenin** [ivogabe/gulp-typescript#186]
Hi,

I would like to build one big script with my typescript files on one hand and vanilla javascript on the other hand.

I wrote the following flow, but it generates me only a scripts.js file with the content of papaparse only. I don't know whether the bug comes from your plugin or gulp directly.
```js
var tsResult =
    gulp.src(scripts)
        .pipe(cache('scripts'))
        .pipe(remember('scripts'))
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject));

    merge([
        tsResult.js.pipe(gulp.src('assets/js/services/papaparse.min.js')).pipe(concat('scripts.js')).pipe(sourcemaps.write()).pipe(gulp.dest('assets/js'))
```

Am I missing something ?

Thanks,
Nicolas

**Comment by ivogabe** [comment]
It took me a while to get it working, but it turns out that you have to set the `passthrough` options:
```javascript
[...].pipe('...', { passthrough: true })
```
Did that solve your question?

**Comment by npenin** [comment]
I'll try it on monday, thanks for your help.

**Comment by rayshan** [comment]
This may be the same problem I noted here: https://github.com/ivogabe/gulp-typescript/issues/163#issuecomment-130001445

Where exactly do you add `passthrough`? I tried at `.pipe(gulp.src(vendorScripts))` and it didn't help. @npenin's code is missing `]`

**Comment by ivogabe** [comment]
My previous comment was wrong, it's a setting of gulp.src:
```javascript
[...].pipe(gulp.src('...', { passthrough: true }))
```

**Comment by npenin** [comment]
Hello everyone,

Sorry for the late reply. I tested, but still no chance to have my source map generated. Here is my full task (with passthrough) :
```js
var gulp = require('gulp');
var watch = require('gulp-watch');
var ts = require('gulp-typescript');
var merge = require('merge2');
var cache = require('gulp-cached');
var remember = require('gulp-remember');
var sourcemaps = require('gulp-sourcemaps');
var concat = require('gulp-concat');

gulp.task('scripts', function ()
{
    var tsResult =
    gulp.src(scripts)
        .pipe(cache('scripts'))
        .pipe(remember('scripts'))
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject));

    merge([
        tsResult.js.pipe(gulp.src('assets/js/services/papaparse.min.js', {passthrough:true})).pipe(concat('scripts.tmp.js')).pipe(concat('scripts.js')).pipe(sourcemaps.write({ includeContent: true, sourceRoot: '/payment/assets/js' })).pipe(gulp.dest('assets/js')),
        tsResult.dts.pipe(concat('scripts.d.ts')).pipe(gulp.dest('assets/js'))
    ]);
});
```

**Comment by npenin** [comment]
I indeed have the same issue as @rayshan mentioned. The output of my task only outputs papaparse.min.js.

**Comment by ivogabe** [comment]
I'm afraid you can't use gulp-sourcemaps with pass through gulp.src. The problem is that the new files don't go through `sourcemaps.init`, so they don't have a source map. A quick look at the code tells that you also can't add init after the second gulp.src, as existing source maps will then be overwritten. I'll report an issue there.

@npenin I'm not sure whether I understand you correctly, did the `passthrough` option fix everything but the source maps or does it still give the same problems?

**Comment by npenin** [comment]
I have the same output with or without `passthrough`

**Comment by ivogabe** [comment]
I reported the issue about source maps here: floridoo/gulp-sourcemaps#147

@npenin I'll take a look

**Comment by ivogabe** [comment]
It turns out that it's not supported in gulp 3, but you have to use [gulp 4](http://demisx.github.io/gulp4/2015/01/15/install-gulp4.html). Does that solve it your problem?

**Comment by npenin** [comment]
I think I'll wait for it to be officially released as I am not the only one working on the project.

**Comment by ivogabe** [comment]
Good point. You can use [gulp-add-src](https://github.com/urish/gulp-add-src) as an alternative, or merge2.

**Comment by npenin** [comment]
I tried gulp-add-src, but it does not support sourcemaps. 

AFAIK, merge2 neither.

**Comment by ivogabe** [comment]
You can use something like this:
```javascript
merge2([
  gulp.src('..')
    .pipe(sourcemaps.init())
    .pipe(ts()),
  gulp.src('..')
    .pipe(sourcemaps.init())
]).pipe(concat('..'))
  .pipe(sourcemaps.write())
  .pipe(gulp.dest('..'));

**Comment by npenin** [comment]
you are awesome ! It worked. Thanks a lot !

**Comment by ivogabe** [comment]
@npenin Glad it helped! You might want to add a return statement before the first `merge`, then your task will exit correctly.

@rayshan Has this issue been solved for you too?

**Comment by rayshan** [comment]
Thanks guys. Yes I got it to work as well with merge2. Also don't want to go to gulp 4 until release. Here's my task for prosperity:

```js
gulp.task("scripts", function () {
    var tsProject = gp.typescript.createProject("tsconfig.json");

    const vendorScriptPaths = [
        "node_modules/mousetrap/mousetrap.js",
        "node_modules/velocity-animate/velocity.js",
        "node_modules/velocity-animate/velocity.ui.js",
        "node_modules/screenfull/dist/screenfull.js"
    ];

    var tsResultStream = tsProject.src()
        .pipe(gp.sourcemaps.init())
        .pipe(gp.typescript(tsProject)).js;

    var vendorScriptsStream = gulp.src(vendorScriptPaths)
        .pipe(gp.sourcemaps.init());

    return merge(vendorScriptsStream, tsResultStream) // need to be in sequence
        .pipe(gp.concat("main.js"))
        // disable for dev as it doesn't work w/ concat
        // https://github.com/terinjokes/gulp-uglify/issues/105
        //.pipe(gp.uglify())
        .pipe(gp.sourcemaps.write("./"))
        .pipe(gulp.dest("build/_assets/scripts"));
});
```
