### ISSUE TITLE
for in of ref output.js

### ISSUE THREAD

**Issue by jnath** [ivogabe/gulp-typescript#189]
Hello and thx for this plugin gulp.

I note while my dev this line is very strange.

`ref` is not a path of file,

maybe `references[ref]` is

https://github.com/ivogabe/gulp-typescript/blob/master/release/output.js#L189

it's possible to bugfix that ?

thx

**Comment by ivogabe** [comment]
Thanks for the detailed report. It was indeed a bug. I'll try to release a new version with the fix later this week.
