### ISSUE TITLE
error TS5009: Cannot find the common subdirectory path for the input files.

### ISSUE THREAD

**Issue by robianmcd** [ivogabe/gulp-typescript#193]
I am trying to compile some typescript files without concatenating them using the following gulpfile

```JavaScript
var gulp = require('gulp');
var ts = require('gulp-typescript');


gulp.task('ts', function () {
    return gulp.src(['src/**/*.ts'])
        .pipe(ts()).js
        .pipe(gulp.dest('build'));
});
```

And I am getting the following error:

```
error TS5009: Cannot find the common subdirectory path for the input files.
Could not find input file c:\Rob\Dropbox\Transfer\Presentations\angular2\ng2-test\src\app\app.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "c:/Rob/Dropbox/Transfer/Presentations/angular2/ng2-test/src/"
sources = ["app/app.ts"]
Could not find input file c:\Rob\Dropbox\Transfer\Presentations\angular2\ng2-test\src\home\home.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "c:/Rob/Dropbox/Transfer/Presentations/angular2/ng2-test/src/"
sources = ["home/home.ts"]
Could not find input file c:\Rob\Dropbox\Transfer\Presentations\angular2\ng2-test\________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "c:/Rob/Dropbox/Transfer/Presentations/angular2/ng2-test/src/"
sources = ["../________________empty.ts"]
[21:24:13] TypeScript: 1 global error
```

Here is my project zipped up https://dl.dropboxusercontent.com/u/20066539/Forum%20Links/Other/ng2-test.zip

Any idea what is going wrong?

**Comment by ivogabe** [comment]
I've tried to reproduce it with your example, without success. Are you sure you have the latest versions of your dependencies installed?

@DanielRosenwasser Do you have any idea why the error `error TS5009: Cannot find the common subdirectory path for the input files.` is shown? Source files are `src/app/app.ts`, `src/home/home.ts` and `src/________________empty.ts` (added by gulp-typescript).

**Comment by robianmcd** [comment]
Just tried this again from a different computer and everything is working fine. I'm sure I had the latest dependencies when it wasn't working because I deleted the node_modules and ran `npm install` again.   I also tried install gulp-typescript 2.8.0 and got the same problem. Maybe npm was being flakey or maybe I had some networking issues on the PC that was causing the issue.

If I have typescript installed globally will gulp-typescript use that or will it always install it's own version locally? I'll try reinstalling typescript on the computer that was seeing this error tonight.

**Comment by DanielRosenwasser** [comment]
Pinging @mhegazy and @vladima. Seems like `src` should be the "common subdirectory path".

@robianmcd have you tried explicitly feeding `--rootDir` as a compiler option?

**Comment by DanielRosenwasser** [comment]
Let us know which version of TypeScript you have on each computer @robianmcd.

**Comment by mhegazy** [comment]
@DanielRosenwasser is correct 'src' should have been identified as the common source root. If you have a repro we should log an issue for it on the ts side.

**Comment by ivogabe** [comment]
gulp-typescript automatically handles the root directory, setting the `rootDir` option is not necessary.

TypeScript is installed as a dependency of gulp-typescript, as long as you don't overwrite it it will default to TS 1.5.3. You can see in the readme how you can use a different version or fork of TypeScript.

@robianmcd Can you try to create another example that reproduces your problem? Or has it been solved for you?

**Comment by robianmcd** [comment]
I tried this again from the computer that was experiencing the problem and it is still happening.

I'm using TS 1.5.3 on both computers. The one causing the issue is running Windows 8. The other one is Windows 7.

I tried specifying the rootDir as `'src'` but got the same problem.
If  I add the `out` flag I don't get any errors. e.g.: `{out: 'build'}`


Here is the same sample project including the node_modules folder created from the computer having the issue: https://dl.dropboxusercontent.com/u/20066539/Forum%20Links/Other/ng2-test-with-node_modules.zip

Can anyone reproduce the issue by running `gulp ts` on this project?

**Comment by DanielRosenwasser** [comment]
Did not catch the issue on my Windows 10 box.

**Comment by ivogabe** [comment]
I've tried it on Windows 8, I couldn't reproduce it. Which version of node (`node -v`) are you using?

**Comment by robianmcd** [comment]
@ivogabe that was it! I had v0.11.10 installed. Upgraded to v0.12.7 and now I'm not seeing any errors anymore.

Thanks!
