### ISSUE TITLE
Suggestion: To support switch:    --module UMD

### ISSUE THREAD

**Issue by bradws** [ivogabe/gulp-typescript#194]
Can we get UMD support as per [Typescript 1.5](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript)?

Is it on the horizon ?

Cheers.

**Comment by ivogabe** [comment]
You can already do that, `.pipe(typescript({ module: 'umd' }))`

**Comment by bradws** [comment]
Oh i see. Thanks.
