### ISSUE TITLE
Help with getting modules working in Node with UMD

### ISSUE THREAD

**Issue by bradws** [ivogabe/gulp-typescript#195]
Sorry, but how do i use 'returnExports.js' in Node ? Is this a module/script loader?
Do I need to 'require' this file somewhere in order for the module system to work? If so, where?

My Typescript config is:
        noImplicitAny: true,
		module: 'umd',
		target: 'ES5'

I have 2 files:

constants.ts:
export const Greeting = "Hello, there!";
test.ts:
import * as MyConstants from 'constants'
console.log( "Greeting=" + MyConstants.Greeting );

....but I get "Greeting=undefined".

**Comment by ivogabe** [comment]
The file you're referring to is just an example of how to use UMD. TypeScript emits code that'll look like that.

Does changing `'constants'` to `'./constants'` fix it? Node requires that you write relative dependencies explicitly with `./`

**Comment by bradws** [comment]
Yes that works perfectly. I'm a bit new to all this....
Thank-you very much !
