### ISSUE TITLE
In some cases noEmitOnError=true is not work and build failed with "Process terminate with code 8"

### ISSUE THREAD

**Issue by vtkalek** [ivogabe/gulp-typescript#198]
Hi,

I found an issue. I'm using watched tasks within my gulpfile.js which should not be inerrupted(fail) on errors. We use watchers to make continuous build (when you change file and save it, watcher is automatically run tslint and tscompile to check the file for errors) And this wathers should work 'forever' errors should not interrupt them. 
So i have to setup the option noEmitOnError to true. Doing this we get error messages in console but watchers are continue they work. 
And it was working fine, until yesterday when we decided to try to make some errors in ts files and see if watch tasks be stable. We just take one of the files and replace this string:
 export interface ILocalizableError {
        getDetails(resourceProvider: IStringResourceProvider): ErrorDetails;
    }
to this:
 interface ILocalizableError {
        getDetails(resourceProvider: IStringResourceProvider): ErrorDetails;
    }

just removed 'export'.

And then our watch task tried to build and terminate with error in gulp-typescript/release/output.js file, on line 187: var references = file.original.ts.referencedFiles.map(function (file) { return tsApi.getFileName(file); });

Error message: 
var references = file.original.ts.referencedFile.map(function.......
TypeError: Cannot read property 'ts' of undefined.....

We have file.original equals to undefined.

This is the issue because out watcher process is interrupted and discontinue with message: 
"Process terminate with code 8".
When we set noEmitOnError to true ts build should not fire any errors to the pipe and terminate the process.

Maybe i should somehow catch errors in this declarations?:
  var tscResult = srcResult
        .pipe(ts({
            sortOutput: true,
            target: "ES5",
            declarationFiles: true,
            noEmitOnError: dontEmitTSbuildErrors
            //out: projectPath + "/obj/" + outFileName + ".js"
        }));

I tried to use .on('error', function (error) {}) but with no result.

Hope you'll have some solution for this....

**Comment by ivogabe** [comment]
Are you using external modules (ES6) or namespaces? When you use the `export` keyword top level (not inside a `module` or `namespace` statement), you're probably using external modules. `sortOutput` shouldn't be used with external modules. Does removing the `sortOutput` option solve you're issue?

**Comment by vtkalek** [comment]
Hi,
We have to use 'sortOutput' parameter because we have huge amount of ts files dependent of each other. So if i remove sortOutput then our final concatenated js file will not work because of wrong sequence of code inside. 
So this is not the option for us... aka removing the sortOutput did not solve our problem.

**Comment by ivogabe** [comment]
Have you tried using the latest version? The error you're seeing will now be suppressed. If you still see some error or if the wrong output is generated, can you give some more details on your project?

**Comment by tanrax** [comment]
+1

Errors no found

gulp.task('typescript', function() {
    var tsResult = gulp.src([
		sURLResources + 'typescript/*.ts',
		sURLResources + 'typescript/**/*.ts'
	])
	.on('error', function (err) {
		notify.onError({
			title: 'Typescript',
			message: '<%= error.message %>',
			sound: 'beep'
		})(err);
		this.emit('end');
		console.error('Typescript', err.message);
	})
	.pipe(ts(tsProject));
 
    return merge([
        tsResult.dts.pipe(gulp.dest(sURLResources + 'typescript/definitions')),
        tsResult.js.pipe(gulp.dest(sURLResources + 'js'))
    ]);
});

**Comment by ivogabe** [comment]
@tanrax I'm not sure what your issue is and whether it's related to this thread. What I do see is that the error event listener is placed before TypeScript compilation. Because of that you won't see any TypeScript errors, you need to place the `.on('error', ...)` call after the TS compilation.

**Comment by tanrax** [comment]
Sorry if this is not the place :P

Could you give me an example, please?

**Comment by ivogabe** [comment]
@tanrax
```typescript
	var tsResult = gulp.src([
		sURLResources + 'typescript/*.ts',
		sURLResources + 'typescript/**/*.ts'
	])
	.pipe(ts(tsProject))
	.on('error', function (err) {
		notify.onError({
			title: 'Typescript',
			message: '<%= error.message %>',
			sound: 'beep'
		})(err);
		this.emit('end');
		console.error('Typescript', err.message);
	});
```
