### ISSUE TITLE
isolatedModules fails because of path backslashes on windows

### ISSUE THREAD

**Issue by arogg** [ivogabe/gulp-typescript#199]
i get an error when using gulp typescript with isolatedmodules option on windows (ts compiler just throws an assert error, without any further details). what I did was merely trying to duplicate the gulp-typescript isolated modules test in the repository as far as possible.. it is this line that causes the problem:

    return typescript.transpile(input, compilerOptions, fileName, diagnostics);

when I replace the line with:

    return typescript.transpile(input, compilerOptions, fileName.replace(/\\/g,"/"), diagnostics);

everything works.

the error that occurs without the change is:

Debugger listening on port 5858
error: uncaughtException: Debug Failure. False expression: Output generation failed date=W
ed Sep 02 2015 20:06:25 GMT+0200 (Mitteleuropäische Sommerzeit), pid=4804, uid=null, gid=n
ull, cwd=C:\Users\alex\abschluss\trunk\Projects\WebCRM\Innosoft.WebCRM\angular_app\app\for
mConfigEditor\non_public, execPath=C:\Program Files\nodejs\node.exe, version=v0.12.0, argv
=[C:\Program Files\nodejs\node.exe, C:\projects\JSBuildHelper\JSBuildHelperNew\jsOut\app\g
ulpfile.js], rss=134455296, heapTotal=106360832, heapUsed=70966216, loadavg=[0, 0, 0], upt
ime=3565.0425066
Error: Debug Failure. False expression: Output generation failed
,    at Object.assert (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\typescript\
bin\typescript.js:1418:23)
,    at Object.transpile (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\typescri
pt\bin\typescript.js:36822:18)
,    at Object.transpile (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\gulp-typ
escript\release\tsapi.js:87:23)
,    at FileCompiler.inputFile (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\gu
lp-typescript\release\compiler.js:175:34)
,    at CompileStream._write (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\gulp
-typescript\release\main.js:46:31)
,    at doWrite (_stream_writable.js:301:12)
,    at writeOrBuffer (_stream_writable.js:288:5)
,    at CompileStream.Writable.write (_stream_writable.js:217:11)
,    at write (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\node_modul
es\readable-stream\lib\_stream_readable.js:623:24)
,    at flow (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\node_module
s\readable-stream\lib\_stream_readable.js:632:7)
,    at DestroyableTransform.pipeOnReadable (C:\projects\JSBuildHelper\JSBuildHelperNew\no
de_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
,    at DestroyableTransform.emit (events.js:104:17)
,    at emitReadable_ (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\no
de_modules\readable-stream\lib\_stream_readable.js:448:10)
,    at emitReadable (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\nod
e_modules\readable-stream\lib\_stream_readable.js:444:5)
,    at readableAddChunk (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2
\node_modules\readable-stream\lib\_stream_readable.js:187:9)
,    at DestroyableTransform.Readable.push (C:\projects\JSBuildHelper\JSBuildHelperNew\nod
e_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)

Error: Debug Failure. False expression: Output generation failed
    at Object.assert (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\typescript\b
in\typescript.js:1418:23)
    at Object.transpile (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\typescrip
t\bin\typescript.js:36822:18)
    at Object.transpile (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\gulp-type
script\release\tsapi.js:87:23)
    at FileCompiler.inputFile (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\gul
p-typescript\release\compiler.js:175:34)
    at CompileStream._write (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\gulp-
typescript\release\main.js:46:31)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at CompileStream.Writable.write (_stream_writable.js:217:11)
    at write (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\node_module
s\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\node_modules
\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\projects\JSBuildHelper\JSBuildHelperNew\nod
e_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\nod
e_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\node
_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\projects\JSBuildHelper\JSBuildHelperNew\node_modules\through2\
node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\projects\JSBuildHelper\JSBuildHelperNew\node
_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
Press any key to continue...

**Comment by ivogabe** [comment]
Thanks for reporting!

**Comment by arogg** [comment]
I see you did path.normalize to try to fix it. but that won't work. On windows that leaves the backslashes, because the method is os specific... you need to convert the backslashes to slashes, even on windows to fix the bug.

**Comment by ivogabe** [comment]
Sorry, you're correct about that. Fixed it.
