### ISSUE TITLE
TypeScript 1.6 breaking changes and gulp-typescript versioning

### ISSUE THREAD

**Issue by kostrse** [ivogabe/gulp-typescript#202]
Upcoming release of TypeScript 1.6 introduces some breaking changes that can affect compilation of existing code (Microsoft/TypeScript#3755).

Could you, please, before making the v1.6 as dependency by default, bump the *minor* version (not build number) of the plugin?

So, it could be possible to stick with TS 1.5 for a while with semver:
```
"gulp-typescript": "~2.8.0"
```

**Comment by ivogabe** [comment]
I plan to release new versions of TypeScript always with a new minor version. Besides that, you can always override the default compiler, at the moment every version starting at 1.4.1 is supported. That way you can still use the latest version of gulp-typescript.

**Comment by kostrse** [comment]
:+1:  Thanks, just wanted to confirm to avoid unpredicted build failure after `npm update` in future.
