### ISSUE TITLE
TypeScript version

### ISSUE THREAD

**Issue by ctoran** [ivogabe/gulp-typescript#207]
I followed the [instructions](https://github.com/ivogabe/gulp-typescript#typescript-version) to use the nightly build of TypeScript with gulp-typescript. However, when I enable `emitDecoratorMetadata` (targeting ES6) I get some broken emit in the output which is clearly a TS bug. This bug does not produce when I compile with latest `tsc`. How can I know what installation/version of typescript is being used by gulp-typescript?

**Comment by ivogabe** [comment]
If you specify a different typescript version, you can find it in your node_modules directory. Open `./node_modules/typescript/package.json` (relative to project root) and look for the `version` key.

**Comment by ctoran** [comment]
Thanks.
