### ISSUE TITLE
Compiling files out of rootDir

### ISSUE THREAD

**Issue by mazhlekov** [ivogabe/gulp-typescript#214]
Hello guys, I have a simple question. I'm using typescript@1.6.2 with this config: 

Project
&nbsp;&nbsp;&nbsp;&nbsp; Client
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Main.ts
&nbsp;&nbsp;&nbsp;&nbsp; Shared
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Foo.ts

Client/tsconfig.json: 
```javascript
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",

    "noImplicitAny": false,
    "declaration": false,
    "removeComments": true,

    "outDir": "build",
    "rootDir": "src",
    "sourceMap": false,

    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
In Client/src/Main.ts I have 
import { Something } from "../../Shared/src/Foo";

When I run tsc in Client folder it generates this project in the build folder:

Build
&nbsp;&nbsp;&nbsp;&nbsp;Client
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Main.js
&nbsp;&nbsp;&nbsp;&nbsp;Shared
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Foo.js

I want the exact same result using gulp-typescript. I tried with this code but without success.
```javascript
var tsProject = ts.createProject('tsconfig.json', {
    typescript: require('typescript')
});

gulp.task('compile', function(callback) {
    var tsResult = tsProject.src() 
        .pipe(ts(tsProject));

    return merge([ 
        tsResult.dts.pipe(gulp.dest(dest)),
        tsResult.js.pipe(gulp.dest(dest))
    ]);
});
```

**Comment by ivogabe** [comment]
What result do you currently get with gulp-typescript?

**Comment by mazhlekov** [comment]
I get files only from Client/src/

**Comment by mazhlekov** [comment]
Build folder looks like this:
&nbsp;&nbsp;&nbsp;&nbsp; Client
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Main.js

**Comment by ivogabe** [comment]
That's because only the input files are emitted as output. Your tsconfig file is located in the client directory, `tsProject.src()` only loads these files. You could use something like this:
```javascript
gulp.src(['Project/Client/src/**/*.ts', 'Project/Shared/src/**/*.ts'], { base: 'Project' })
```

**Comment by mazhlekov** [comment]
Yes I could do something like this. But I want tsc to dinamically resolve imported files. Can I include somehow files that are outside rootDir into output ?

**Comment by ivogabe** [comment]
No, the problem is that such feature wouldn't fit well in the gulp system. You can subscribe to #190 though, a similar request is done there

**Comment by mazhlekov** [comment]
:+1: Thank you very much, Ivo. Have a nice day! :computer:

**Comment by ivogabe** [comment]
You too!
