### ISSUE TITLE
No longer processing ".tsx"

### ISSUE THREAD

**Issue by phestermcs** [ivogabe/gulp-typescript#216]
Yesterday I was using 2.9.0, and ".tsx" files were being returned from ```tsproject.src()```.
This morning i ran npm update for another package, and it also updated gulp-typescript to 2.9.1, and now ".tsx" files are not being returned by ```tsproject.src()```  via ```var tsproject = ts.createProject('tsconfig.json');```

I changed my package.json to excplicitly require 2.9.0, did npm update, and now its working again.

Here's my tsconfig file
```json
{
  "compilerOptions": {
    "target": "es6",
    "sourceMap": true,
    "experimentalAsyncFunctions": true,
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by ivogabe** [comment]
Released as `v2.9.2`
