### ISSUE TITLE
Declaration files not being generated

### ISSUE THREAD

**Issue by arkon** [ivogabe/gulp-typescript#218]
As far as I can tell, the recent switch from `declarationFiles` to `declaration` wasn't fully implemented, so the option doesn't really do anything.

**Comment by ivogabe** [comment]
Can you share your gulpfile? Setting `declaration` works on my projects.

**Comment by arkon** [comment]
Hmm yeah, I'm not actually sure why it's not working after I looked through the code so more...

Here's a condensed version of my Gulpfile:

```JavaScript
'use strict';

var gulp = require('gulp'),
    ts   = require('gulp-typescript');

// TypeScript settings
var tsProject = ts.createProject({
    removeComments : true,
    declaration    : true,
    target         : 'ES5',
    module         : 'amd',
    jsx            : 'react'
});

var paths = {
    src       : 'src',
    src_ts    : ['!src/**/*.d.ts', 'src/**/*.{ts,tsx}'],
    dest      : 'build',
};

// Compiles TypeScript files
gulp.task('tsc', function () {
    return gulp.src(paths.src_ts, { base: paths.src })
        .pipe(ts(tsProject))
        .js.pipe(gulp.dest(paths.dest));
});
```

**Comment by ivogabe** [comment]
You're only using the javascript output stream, and thus discarding the definition files. Something like this should work:
```javascript
gulp.task('tsc', function () {
    var tsResult = gulp.src(paths.src_ts, { base: paths.src })
        .pipe(ts(tsProject));
    return merge2([
        tsResult.js.pipe(gulp.dest(paths.dest)),
        tsResult.dts.pipe(gulp.dest(paths.dest))
    ]);
});
```
You need to install & require `merge2` for this. See the readme for more examples.

**Comment by arkon** [comment]
Whoops, you're right @ivogabe! Worked perfectly fine -- thanks for the help!
