### ISSUE TITLE
Error on string interpolation

### ISSUE THREAD

**Issue by pchad2002** [ivogabe/gulp-typescript#219]
When the TypeScript 1.6 string interpolation character is encounter, `, an error is thrown. For example, the following TypeScript line `Sorry could not find the promo code ${code}\. Please check try again.` throws the exception:   Error: Unexpected character "`" on src\scripts\registration.ts line 577.  

When I compile the same code on the command line it works. 

Thanks.

**Comment by ivogabe** [comment]
Which version of gulp-typescript and TypeScript are you using? It looks like you're using an older version of TypeScript. I've used template strings a lot in my projects, without problems

**Comment by pchad2002** [comment]
Thanks for the quick response and sorry for wasting your time, the branch I cloned had an older version...
