### ISSUE TITLE
Sometimes gulp-typescript doesn't generate any files when using typescript@next

### ISSUE THREAD

**Issue by kenotron** [ivogabe/gulp-typescript#223]
Now Typescript at 1.8.0-dev.20151028, with gulp-typescript, I've been able to repro a bug where gulp-typescript just doesn't output anything.

**Comment by kenotron** [comment]
With the included TS 1.6.2, works fine. I would see the "dist" directory being generated. But with the typescript@next, it wouldn't generate anything. Strange thing is: if I renamed my importanceType.ts to bar.ts, it would generate it fine. I am very confused as to why the name of the file / module would make gulp-typescript work / not work.

Just to give more details, I have my directory structure as such:

```
foo/
  node_modules/
  src/
    foo.ts
    importanceType.ts
  package.json
  gulpfile.js
```
---

my gulpfile.js is
```js
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('default', function () {
    return gulp.src('src/**/*.ts')
        .pipe(ts({
			typescript: require('typescript'),
            "target": "ES5",
			"module": "commonjs",
			"jsx": "react",
			"sourceMap": true,
			"experimentalDecorators": true,
			"declaration": true,
			"removeComments": true
        }))
        .pipe(gulp.dest('dist'));
});
```
---
my importanceType.ts
```js
enum importanceType {
	Low = 0,
    Normal = 1,
    High = 2
};

export default importanceType;
```
---

**Comment by ivogabe** [comment]
Thanks for reporting, I'll take a look at this. Can you also run the `tsc` command on your project, to see whether this is a bug of gulp-typescript or TypeScript?

**Comment by kenotron** [comment]
tsc works fine in the command line.

**Comment by kenotron** [comment]
Forgot to type in foo.ts contents:

```js
import importanceType from './importanceType'
```

**Comment by kenotron** [comment]
Doing some sleuthing and debugging. Seems like the input.ts's commonSourceDirectory is getting this for fileNames:

Array[4]
0:"E:\workspace\testmodules-backup\packages\foo\src\foo.ts"
1:"E:\workspace\testmodules-backup\packages\foo\src\importanceType.ts"
2:"E:\workspace\testmodules-backup\packages\foo\src\________________empty.ts"
3:"src/importanceType.ts"

where as ts@1.6.2 gives this:

0:"E:\workspace\testmodules-backup\packages\foo\src\foo.ts"
1:"E:\workspace\testmodules-backup\packages\foo\src\importanceType.ts"
2:"E:\workspace\testmodules-backup\packages\foo\src\________________empty.ts"

Something went wonky with the input.ts

**Comment by kenotron** [comment]
I think I might have a fix: the problem is that ts@next started passing in relative paths to the getSourceFile in the compiler host. You need to simulate the behavior for ts@1.8.0-dev.20151028+... I'll work up a PR for you I think to fix this.

**Comment by robertbaker** [comment]
This seems related to https://github.com/Microsoft/TypeScript/issues/5455

**Comment by robertbaker** [comment]
@kenotron seems right, tsc runs fine for me, 1028 and 1029 have the same issue.

**Comment by ivogabe** [comment]
Looks like the old behavior has been reverted in Microsoft/TypeScript#5462. @kenotron does using the latest TypeScript build solve this issue?

**Comment by kenotron** [comment]
So, by not doing anything, you have dodged a bullet there :) Yes I think this is fixed with typescript@next.
