### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by zhouhao27** [ivogabe/gulp-typescript#225]
I have a gulp task which compile my ts script like this:

    /// <reference path="../libs/phaser/typescript/phaser.d.ts"/>
    /// <reference path="states/preload.ts"/>

    class Game extends Phaser.Game {
	constructor() {
            super(800, 600, Phaser.AUTO, 'content', null);
            this.state.add('preload',States.PreloadState,true);
      }
    }

var mygame = new Game();

There is an error message:

> src/scripts/main.ts: line 4, col 1, 'class' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).

But it works in browser. What can I do with the error message? Thanks.

By the way, I think the error is generated by my jshint task:

    gulp.task('jshint', function() {
	return gulp.src(scriptsSrc)
		.pipe(jshint())
		.pipe(jshint.reporter('default'));
    });

**Comment by ivogabe** [comment]
I think this question is related to jshint, not gulp-typescript. It looks like you need to specify the esnext option, though I'd advise to use tslint (with gulp-tslint) to lint TypeScript code.

**Comment by zhouhao27** [comment]
Thanks, gulp-tslint works.
