### ISSUE TITLE
Incremental compiling not working

### ISSUE THREAD

**Issue by Foxandxss** [ivogabe/gulp-typescript#227]
So, I am transpiling all my typescript source into a `temp` folder so I can run karma on it. I have the following code:

```javascript
var testProject = $.typescript.createProject('tsconfig.json');

gulp.task('build-tests', function() {
  var tsResult = gulp.src('src/**/*.ts')
    .pipe($.sourcemaps.init())
    .pipe($.typescript(testProject));

  return tsResult.js
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('temp'));
});

gulp.task('watch', ['build-tests'], function() {
  gulp.watch('src/**/*.ts', ['build-tests']);
});
```

So I run watch, and every time I change one file, all the files gets transpiled again instead of just the one I modified.

I am doing / understanding this correctly? Thanks.

**Comment by ivogabe** [comment]
I think you expect something different from incremental compilation. In TypeScript, incremental compilation means that some information of the previous build is reused. For instance, unchanged files are not parsed again and the project structure (references & imports) are reused if possible. This can speed up compilation up to 50%. If you need more performance, you could use `isolatedModules` instead. You'll loose type checking, but only changed files will be recompiled. Unchanged files are still emitted in the stream, you can use a different gulp plugin to remove these if necessary.

**Comment by Foxandxss** [comment]
Yeah, so I was understanding it wrong. Thanks for the explanation.
