### ISSUE TITLE
Is it possible to create a single d.ts file from a bundle of TS classes? 

### ISSUE THREAD

**Issue by marcuswhit** [ivogabe/gulp-typescript#229]
I don't see any obvious way that this can be done, but please let me know if I've missed something.

Thanks.

**Comment by ivogabe** [comment]
If you're not using external modules, you can use the `out` or `outFile` option. It's not yet possible to bundle definition with external modules, see Microsoft/TypeScript#4433. In the meantime you can use [dts-generator](https://github.com/SitePen/dts-generator). If you distribute your package on NPM, you don't have to bundle these definition files at all (see the [wiki](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages))

**Comment by marcuswhit** [comment]
That's very useful re NPM, I'll look into that! Thanks.

**Comment by vytenisu** [comment]
Also there is "npm-dts" package. When using WebPack: "npm-dts-webpack-plugin".

**Comment by cancerberoSgx** [comment]
Last time I tried, the only one that I had success with was https://github.com/TypeStrong/dts-bundle, my two cents
