### ISSUE TITLE
Building Angular2 project with `noExternalResolve: true` is slower

### ISSUE THREAD

**Issue by bmayen** [ivogabe/gulp-typescript#230]
I have a project which enumerates all of the Angular2 type definition files in the tsconfig.json files array. This allows me to build using the `noExternalResolve` option without the Typescript compiler complaining that it cannot find Angular modules. The behavior I'm seeing is that this approach is slower than excluding the type definitions from tsconfig and setting `noExternalResolve:false`.

I have a `tsProject` instance for incremental builds which produce the following results:
1) `noExternalResolve:true` without type definitions listed: ~500ms (with errors)
2) `noExternalResolve:true` with type definitions listed: ~1.5s
3) `noExternalResolve:false` without type definitions listed: ~900ms

My understanding is that the expected behavior is for option 2) to be faster than 3). Am I missing something?

**Comment by ivogabe** [comment]
That's strange.. The only reason I can think of is that you're passing unreferenced files to the compiler. What happens when you don't use noExternalResolve but do list type definitions?

**Comment by bmayen** [comment]
Never mind, I found the problem. The tsProject was getting recreated on each watch execution, causing the type definitions to reload each time.
