### ISSUE TITLE
Definitions not created

### ISSUE THREAD

**Issue by theduke** [ivogabe/gulp-typescript#231]
I'm using the recommended code for creating both the js files and the definitions:

```javascript
var tsResult = tsProject.src()
                    .pipe(ts(tsProject));

return merge([
        tsResult.js.pipe(gulp.dest('build/js')),
        tsResult.dts.pipe(gulp.dest('dist/definitions')), 
    ]);
```
While the js building works fine, 
no definitions show up.

**Comment by ivogabe** [comment]
Have you turned the declaration option on? (`declaration: true`)

**Comment by tlancina** [comment]
Same issue.
```
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('default', function () {
    return gulp.src('app.ts')
        .pipe(ts({
            target: 'es5',
            module: 'commonjs',
            declaration: true
        }))
        .pipe(gulp.dest('.'));
});
```

Minimally reproduces it, but here's a small repo as well: https://github.com/tlancina/gulp-typescript-issue

**Comment by bgrieder** [comment]
Same issue but I had it working using this following script (the babel step is specific to my set-up and has nothing to do with this issue)

    var tsProject = ts.createProject('tsconfig.json', {
        typescript: require('typescript')
    });
   
    gulp.task('build:release', function () {
        var tsres = tsProject.src()
            .pipe(sourcemaps.init())
            .pipe(ts(tsProject));
    
        return merge([
            tsres.dts
                .pipe(gulp.dest('dist/typings')),
            tsres.js
                .pipe(babel({
                    presets: ['es2015']
                }))
                .pipe(sourcemaps.write('.'))
                .pipe(gulp.dest('dist/js'))
        ]);
    });


My first attempt was looking like that of @tlancina . I guess this should be better documented

**Comment by ivogabe** [comment]
@tlancina looks like you forgot to pipe the `.dts` stream. See the readme or the code of @bgrieder. The default stream only contains javascript files

**Comment by tlancina** [comment]
@ivogabe thanks! It might be nice to put a note by `declaration` mentioning this.  But really the fault is mine for not reading the docs thoroughly.

**Comment by Ixonal** [comment]
I hate to resurrect a closed issue, but I'm having a similar problem, but I'm not seeing the issue... Here's my build module:

```javascript
var gulp = require("gulp"),
    config = require("./config"),
    
    typescript = require("gulp-typescript"),
    plumber = require("gulp-plumber"),
    debug = require("gulp-debug"),
    rename = require("gulp-rename"),
    uglify = require("gulp-uglify"),
    sourcemaps = require("gulp-sourcemaps"),
    
    merge = require("merge2");

function build(globs) {
  var tsResult = gulp.src(globs)
                     .pipe(plumber())
                     .pipe(debug({ title: "Building" }))
                     .pipe(sourcemaps.init())
                     .pipe(typescript(config.settings.typescript));
              
  return merge([
    tsResult.dts.pipe(debug({ title: "Definition" }))
                .pipe(gulp.dest(config.locations.dts)),
    tsResult.js.pipe(uglify(config.settings.uglify))
               .pipe(debug({ title: "Distribution" }))
               .pipe(sourcemaps.write("."))
               .pipe(gulp.dest(config.locations.dist))
  ]);
}

gulp.task("build", function() {
  return build(config.globs.src);
});

exports.build = build;
```

And this is the settings for the typescript plugin:

```javascript
typescript: {
  module: "system",
  declaration: true,
  removeComments: true,
  emitDecoratorMetadata: true,
  experimentalAsyncFunctions: true,
  experimentalDecorators: true,
  isolatedModules: true,
  allowJs: true,
  typescript: typescript
}
```

The debug for "Building" and "Distribution" show the correct number of files, but the one for "Definition" shows 0, implying that nothing is moving through the dts pipe. Anyidea what's up?

**Comment by BibbyChung** [comment]
@Ixonal

I have the same problem. I try to compile and get the definitions. Finally I set up the tsconfig.json 
`"isolatedModules": false`
or use this code in gulpfile.json
`.pipe(ts(ts.createProject(tsconfigPath, { "isolatedModules": false })))`

help to solve your problem...

**Comment by yahiko00** [comment]
After an entire afternoon, I think that **I've found out what happens**.
I use `gulp-uglify` version 3.0.0.

We need to explicitely set `declaration` to `true` in the _gulpfile.js_:
    const tsProject = ts.createProject(config, { "declaration": true });
    const tsResult = tsProject.src()
        .pipe(gulpif(debug, sourcemaps.init()))
        .pipe(tsProject());

    return merge([
        tsResult.js
            .pipe(gulpif(debug, sourcemaps.write()))
            .pipe(gulp.dest(dest)),
        tsResult.dts
            .pipe(gulp.dest(dest))])
        .on("error", gutil.log);

Otherwise, even if `declaration` is set to `true` in the _tsconfig.json_, it is not taken into account, and `declaration` remains to its default value, `false`.

**Comment by andrerpena** [comment]
I have tested it intensively in the current versions of `gulp-typescript` and `typescript` and I can assure you that the recommended code for generating definitions will only work (in the case you're using a `tsconfig.json` file), if the `tsconfig.json` file has `declarations:true`

**Comment by lordazzi** [comment]
Not using inherited and not generating declarations :s
