### ISSUE TITLE
Sourcemaps not using correct paths

### ISSUE THREAD

**Issue by mikecann** [ivogabe/gulp-typescript#237]
Hi,

Im having issue with sourcemaps. My task looks like

```
gulp.task('background-scripts', function () {
  var tsResult = gulp
    .src(['src/scripts/background/**/*.ts', 'src/scripts/common/**/*.ts', 'src/scripts/typings/**/*.ts'])
    .pipe(sourcemaps.init())
    .pipe(ts({
      target: "ES5",
      sortOutput: true,
      sourceMap: true,
      outFile: 'Background.js'
    }));

  return tsResult.js
    .pipe(sourcemaps.write('.', { sourceRoot: 'src' }))
    .pipe(gulp.dest('release/js'));
});
```

But the generated map looks like:

```
{"version":3,"sources":["common/helpers/LiveReloadClient.ts","background/Background.ts","common/helpers/AppHelpers.ts","common/signals/Signal.ts"],"names":["LiveReloadClient","LiveReloadClient.constructor","LiveReloadClient.listen","AppHelpers","AppHelpers.constructor","AppHe 
...
```

Note the the paths are incorrect as they cant be found from the 'release/js' directory.

Any help would be greatly appreciated.

Thanks.
Mike

**Comment by ivogabe** [comment]
I think you need to set sourceRoot to `'../../src/'`. The sourceRoot is added in the map file at the end. Source files will then be resolved in the correct directory. Can you get it working this way?

Otherwise, gulp-sourcemaps has also an option that just embeds the source code in the map files.

**Comment by mikecann** [comment]
Ahhhh.. Got it....

At the top of the sourcemap the file still looks like:

```
{"version":3,"sources":["common/helpers/LiveReloadClient.ts","background/Background.ts","common/h..
```

but what I didnt notice that the sourceroot is applied to the bottom of the map:

```
...l,null,null,null],"sourceRoot":"../../src/"}
```

Sorry for the confusion and thanks for your help, keep up the great work!

Mike
