### ISSUE TITLE
Source Root Directory in Output Path when using tsconfig.json

### ISSUE THREAD

**Issue by jamespchadwick** [ivogabe/gulp-typescript#240]
Running into a rather interesting issue when working with the Aurelia team to resolve some issues I was having with the TypeScript build.  It appears as though when building using tsconfig.json the root directory is being appended to the output path.  For example, when building the typescript in 'src' and outputting the javascript to 'dist', the compiled javascript will be sent to 'dist/src'.  [Here is an example gulpfile] (https://github.com/cmichaelgraham/skeleton-navigation-typescript-vscode/blob/master/build/tasks/build.js) from the Aurelia team which suffers from the same issue.

**Comment by ivogabe** [comment]
The directory that contains the tsconfig file is automatically set as the base directory. You can move that file to the src directory or set the sourceRoot property in the compilerOptions section of the tsconfig.json file to 'src'. Does one of these options solve your issue?

**Comment by jamespchadwick** [comment]
I really would rather not move the tsconfig.json as I believe its rightful place is in the root directory of the projects (much like config.json and packages.json).  

I tried adding the sourceRoot to the compiler options of tsconfig.json and was met with the message and the issue persisting:
> sourceRoot isn't supported any more. Use sourceRoot option of gulp-sourcemaps instead.

Taking that suggestion into consideration, I updated my call to gulp-sourcemaps to include the sourceRoot option, but to no avail

**Comment by ivogabe** [comment]
Sorry, I meant the rootDir option instead of sourceRoot.

**Comment by glen-84** [comment]
> I really would rather not move the tsconfig.json as I believe its rightful place is in the root directory of the projects (much like config.json and packages.json).

And what if you wanted to build the e2e tests into `test\e2e\dist`, like the skeleton project does with Babel?

To me it seems more appropriate to put the tsconfig file in the `src` folder. The reason why I personally don't do it this way yet is because I don't want to rely on the atom-typescript-specific `filesGlob` functionality, so I'm currently using `exclude` with tsconfig in the project root. If I move tsconfig to `src`, then I'd have to manually list `files` or use `filesGlob` until [this](https://github.com/Microsoft/TypeScript/issues/1927) enhancement is implemented.

TBH, I'm in two minds about this.

**Comment by jamespchadwick** [comment]
@ivogabe that appears to have done the trick!

**Comment by jon49** [comment]
I'm having a bit of trouble with this also.

My file structure is like so:

```
- project
  - ts
  - js
```

So, I call the `tsc` command line from `js`:

```
tsc -m commonjs --outDir ./ -p ../ts --rootDir ../ts
```

It continues to copy the parent `ts` directory.

So, I tried this in the `ts` directory and it seems to work now:

```
tsc -m commonjs --outDir ../js --rootDir ts
```

Not sure if that is a bug or not.

**Comment by jon49** [comment]
Also, for some reason it rebuilds the who project. Seems to defeat the purpose of watch :-(

**Comment by ivogabe** [comment]
@glen-84 I usually put tests in the lib directory, something like this:
```
lib/
  client/
    ..
  test/
    ..
  tsconfig.json
```

**Comment by glen-84** [comment]
I guess your `lib` is my `src`. I suppose it's something to consider. Thanks.

**Comment by ivogabe** [comment]
> I guess your `lib` is my `src`.

Yes, that's right. Let me know wether this works for you
