### ISSUE TITLE
Question : How to use this module with Angular2 ?

### ISSUE THREAD

**Issue by maxime1992** [ivogabe/gulp-typescript#246]
I'm currently trying to build a gulp workflow for Angular2.
I know there's plenty out there already, but i'd like to learn gulp and do it on my own.

When i run `gulp`, i get this error : 
![image](https://cloud.githubusercontent.com/assets/4950209/11635616/3afc25ac-9d18-11e5-8c82-d76cfcc0b635.png)

I tried 3 differents code : 

1 -----------
```javascript
var gulp = require('gulp');

var ts = require('gulp-typescript');
var tsProject = ts.createProject('./src/tsconfig.json');

gulp.task('default', function () {
	var tsResult = tsProject.src() // instead of gulp.src(...) 
		.pipe(ts(tsProject));
	
	return tsResult.js.pipe(gulp.dest('release'));
});
```

2 -----------
```javascript
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('default', function () {
    return gulp.src('src/app/app.ts')
        .pipe(ts({
            target: 'es5',
            module: 'commonjs',
            declaration: true
        }))
        .pipe(gulp.dest('test/ok.js'));
});
```
3 -----------
```javascript
var gulp = require('gulp');
var ts = require('gulp-typescript');
var merge = require('merge2');  // Require separate installation 
gulp.task('scripts', function() {
	var tsResult = gulp.src('src/app/app.ts')
		.pipe(ts({
			declaration: true,
			noExternalResolve: true
		}));
 
	return merge([
		tsResult.dts.pipe(gulp.dest('release/definitions')),
		tsResult.js.pipe(gulp.dest('release/js'))
	]);
});
```

I have no idea why it does not detect angular. Thanks !

**Comment by ivogabe** [comment]
I think you don't need the definition files, so you don't have to use the third configuration. Angular uses decorators, you can enable them using `experimentalDecorators: true` (in your tsconfig file or in the gulpfile, in the ts call). You also need to set `emitDecoratorMetadata: true` for dependency injection. Finally, for resolving typings for Angular, you need to set `module: 'commonjs'` (if you use a CommonJS bundler) or `moduleResolution: 'node'` if you want some other module loader, SystemJS or AMD.

**Comment by maxime1992** [comment]
Indeed, it solves some errors !

Here's the new gulp file :
```javascript
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('default', function () {
    return gulp.src('src/app/app.ts')
        .pipe(ts({
            target: 'es5',
            moduleResolution: 'node',
            declaration: true,
            experimentalDecorators: true,
            emitDecoratorMetadata: true
        }))
        .pipe(gulp.dest('ok.js'));
});
```

But it seems there's still one error :
![image](https://cloud.githubusercontent.com/assets/4950209/11650139/a915f7fc-9d86-11e5-85bc-3c118d83d55c.png)

I think it's related to this thread https://github.com/ivogabe/gulp-typescript/issues/41 but i couldn't figure out a solution.

**Comment by ivogabe** [comment]
How do you want to bundle your modules? When you use external modules (what you should), you have to bundle them with Browserify, Webpack, AMD or SystemJS. Most Angular developers use SystemJS, but you can also use my bundler [small](https://github.com/ivogabe/small) (based on CommonJS), which integrates nicely with Gulp.

**Comment by maxime1992** [comment]
I'm using systemJS. 

My work is on gitlab : https://gitlab.com/maxime1992/angular2-quickstart
It was private because i didn't want to publish something which is not clean but at least you can see the code :)

**Comment by ivogabe** [comment]
Then you can set `"module": 'systemjs'` in your tsconfig file. TypeScript 1.8 can automatically bundle these files, see #243

**Comment by maxime1992** [comment]
Ok, i followed https://github.com/ivogabe/gulp-typescript/issues/243 and i found @ghpabs work.
It seems to fit my need so i forked it and i'm going to work from this repo.
Thanks again for your help @ivogabe :+1: !

**Comment by ghpabs** [comment]
Hey @maxime1992 I'm glad it works for you. Feel free to contribute back to the project if you want.

**Comment by maxime1992** [comment]
@ghpabs i forked it, we'll see if i feel comfortable enough to contribute but i would be glad to ! :)
