### ISSUE TITLE
Files referenced through import directive are not compiled.

### ISSUE THREAD

**Issue by edvinv** [ivogabe/gulp-typescript#252]
It looks like that when using gulp-typescript, files that are referenced  with import directive are not compiled. 
Take a look at following structure with gulp-typescript compilation output:
```
.
│   gulpfile.js
│   package.json
├───apps
│   │   app.ts
│   │   tsconfig.json
│   └───bin
│       └───apps
│               app.js
├───libs
│       lib.ts
```
App.ts contains:
```typescript
import {foo} from "../libs/lib";
foo();
```
As you can see in bin directory is only app.js but lib.js is missing. If I run tsc from apps folder, lib.js is also correctly generated.

gulpfile.js
```javascript
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('build', function () {
  var tsProject = ts.createProject('./apps/tsconfig.json');
  var tsResult = tsProject
    .src()
    .pipe(ts(tsProject));

  return tsResult.js
    .pipe(gulp.dest('./apps/bin'));
});
```

**Comment by ivogabe** [comment]
This is by design. A gulp plugin transforms the input files, and resolved files are not input files. But there is a suggestion to add these files, see #190.

**Comment by edvinv** [comment]
thx for info.
