### ISSUE TITLE
Declaring modules

### ISSUE THREAD

**Issue by heruan** [ivogabe/gulp-typescript#254]
How can I generate a module declaration `.d.ts` file such as:
```javascript
declare module 'my-plugin' {
  // declarations go here
}
```
when building plugins with Gulp?

**Comment by ivogabe** [comment]
With TypeScript this is not possible at the moment. You could use something like [dts-generator](https://github.com/SitePen/dts-generator).

**Comment by heruan** [comment]
AFAIK `dts-generator` nor `dts-bundle` have Gulp support, unfortunately. I'm new to TypeScript, but how one is supposed to create a `.d.ts` module declaration if the official compiler doesn't support that?

**Comment by ivogabe** [comment]
You could do something like this:
```javascript
...
var dts = require('dts-generator');

gulp.task('compile', function() { ... });
gulp.task('definitions', function(done) {
	dts.generate({
		// Options
	}).then(done);
});
```
Besides that, are you publishing your library on NPM? If so, you don't have to export the declaration file wrapped in a `declare module`. You can instead use the generation files generated by TypeScript, combined with the [typings](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages) field of the `package.json` file.

**Comment by heruan** [comment]
Thank you @ivogabe, that works out. Unfortunately `dts-generator` creates a single `.d.ts` file with _multiple_ `declare module 'my-module/file' {}` definitions, where I need a single `declare module 'my-module' {}` definition.

My library will be published on JSPM, it's part of Aurelia for client-side web applications.

**Comment by ivogabe** [comment]
Good to hear that. I'm not sure wether it's possible to wrap it in a single module declaration. Closing this in favor of SitePen/dts-generator#52, as they will probably know that better.
