### ISSUE TITLE
problem with tsconfig.json include files above current directory level.

### ISSUE THREAD

**Issue by wudong** [ivogabe/gulp-typescript#257]
with gulp-typescript version ^2.10.0 
the tsconfig.json looks like this. it is in the directory of `src/ts-manage` and references the files in `src/ts`

```
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "../../build/js"
  },

  "files": [
    "../ts/domain/enum.ts",
    "../ts/domain/model.ts",
    "manage.ts"
  ]
}
```

and running with the gulp-typescript

```
gulp.task('typescripts', function () {
    var tsResult = tsProject.src()
        .pipe(debug({title: 'tsproject:'}))
        .pipe(ts(tsProject))
        .on("error", handleError);

    return tsResult.js
        .pipe(debug({title: 'tsjs:'}))
        .pipe(concat(getBuild().typescripts.main))
        .on("error", handleError)
        .pipe(isProduction ? uglify(uglifyOptions) : gutil.noop())
        .on("error", handleError)
        .pipe(gulp.dest(getBuild().typescripts.dir));
});
```
Here is the output:
```
[12:03:49] Starting 'typescripts'...
[12:03:49] tsproject: src/ts/domain/enum.ts
[12:03:49] tsproject: src/ts/domain/model.ts
[12:03:49] tsproject: src/ts-manage/manage.ts
[12:03:49] tsproject: 4 items
[12:03:50] tsjs: ../../build/js/ts-manage/manage.js
[12:03:50] tsjs: 1 item
[12:03:50] Finished 'typescripts' after 1.23 s
```

from the gulp-debug pipe, it looks that the files that are not in the current directory level is filtered out from the `tsResult.js`. Is this done intentionally or a bug?

**Comment by ivogabe** [comment]
The directory containing the `tsconfig.json` file is considered to be the root directory, so that's intentional. I'll investigate what `tsc` does in such scenario. If `tsc` allows this, this is a bug.

**Comment by wudong** [comment]
`tsc` does allow it. 
running `tsc` directly with the `tsconfig.json` produce the desired result.

**Comment by ianbytchek** [comment]
Getting this too.

**Comment by ivogabe** [comment]
@wudong @ianbytchek Can you try this again with #276? You can install that branch with:
```
npm install ivogabe/gulp-typescript#tsconfig-files
```
