### ISSUE TITLE
Proposal: Add color to output

### ISSUE THREAD

**Issue by SetTrend** [ivogabe/gulp-typescript#258]
I got forwarded here from Microsoft/TypeScript#6363:
<br/>
It's currenty hard to read TypeScript errors in VS Code:

![errors 1](https://cloud.githubusercontent.com/assets/9283914/12127104/99089e0c-b3f5-11e5-989e-93c11f91b98a.png)
<br/>
There is a `--pretty` option for TypeScript, but AFAIK it can't be used when using `gulp-typescript`.

So I'd like to suggest to add color to the output of `gulp-typescript`.
<br/>
I'd like to suggest to give colors so the message and code positions can easily be read, too (not just the - rather uninformative - constant word "error", like it is output by `tsc` when applying the `--pretty` compiler option):

![errors 2](https://cloud.githubusercontent.com/assets/9283914/12127169/fcb69c6a-b3f5-11e5-9685-438ae84f14be.png)
*(Suggested colors are: green for code position, red for error keyword/code and dark yellow for the error message.)*

**Comment by ivogabe** [comment]
Errors are already colored in gulp-typescript, though it seems VSCode ignores these. I'm not sure why, but you can try to add the `--color` flag (like `gulp --color tscProject`).

For a better integration between gulp and VSCode, you could also use a problem matcher, see [Using VSCode with gulp-typescript](http://dev.ivogabe.com/using-vscode-with-gulp-typescript/).

**Comment by SetTrend** [comment]
You are absolutely right. After giving it another thought today I realized that coloring the errors in the Output panel is a sole task of VS Code's Problem Matcher functionality.

So I amended my corresponding suggestion at Microsoft/vscode#1801 a few minutes ago.
