### ISSUE TITLE
How NOT to concat multiple transpiled JS files into a bundle.

### ISSUE THREAD

**Issue by bartvanderwal** [ivogabe/gulp-typescript#261]
How do I just transpile all `*.ts` files to similarly named *.js files in the same location.
E.g. the default behavior of Visual Studio NTVS, but now using gulp (as I'm in a Gulp pipeline where I'm then running mocha).

I can see options to concatenate stuff into one file when I search around on the internet, but that's NOT what I want now. This used to work for me previously, but I cannot get back this behavior.

**Comment by ivogabe** [comment]
When you're not using `gulp-concat` and you haven't set the `out` and `outFile` options, you should get one JS file per TS file.

**Comment by bartvanderwal** [comment]
Okay, thanks for the confirmation.

It would be good if this was specified in the TypeScript docs. Always a good practice to specify all defaults.

I might be missing something, but right now I feel that you are just expected to somehow just know this. But it can raise a lot of doubts when for instance having the issues that tsc is not compiling for some reason, but just silently failing. In the meantime I was able to fix that last issue (though I forgot the specifics).
