### ISSUE TITLE
Reference paths break if TS declaration files are stored in separate folder

### ISSUE THREAD

**Issue by SetTrend** [ivogabe/gulp-typescript#264]
When declaration files are supposed to be stored in a separate output folder, references in those `.d.ts` files break because `gulp-typescript` currently doesn't support this.

```javascript
return merge(ts.js.pipe(pi.sourcemaps.write("."
                                           , { includeContent: false
                                             , sourceRoot: `.${srcRoot}`  // relative to .js output folder
                                             }))
              .pipe(gulp.dest(outputFolder))
            ,  ts.dts.pipe(gulp.dest(`${outputFolder}/headers/`))  // <-- IMPORTANT LINE --!
```

See [SetTrend/TS18N](https://github.com/SetTrend/TS18N) demo project for reference ...
<br/>
I suggest to provide an option for having declaration files stored in a separate folder, so `gulp-typescript` may amend the corresponding reference paths in the generated code files.

I propose to replace the boolean `declaration` option with a `declarationPath` string option.

The path to be set here is suggested to be the relative path between the generated `.js` file and its corresponding `.d.ts` file. This would match the behaviour of `gulp-sourcemaps`.

```javascript
.pipe(pi.typescript({ noImplicitAny: true
                    , target: "ES5"
                    , module: "commonjs"
                    , declarationPath: `./headers/`  // relative to .js output folder
                    , removeComments: true
                    , noEmitOnError: true
                    , typescript: require("typescript")
                    }));

```

* `declarationPath: null` (default value) would not generate `.d.ts` files.
* `declarationPath: "."` and `declarationPath: ""` would generate declaration files in the same folder as the generated `.js` files (standard case).
* Any other value amends all references to `.d.ts` files pointing to (relative) locations within the project.

Your thoughts?

**Comment by ivogabe** [comment]
This cannot be implemented in gulp-typescript as TypeScript handles these paths. Can you log an issue there?

**Comment by SetTrend** [comment]
I'm sorry - my mistake. I was believing it is the gulp plug-in that's taking care of the paths.

I sure will. Thank you.
