### ISSUE TITLE
sourceRoot removed from options

### ISSUE THREAD

**Issue by fogzot** [ivogabe/gulp-typescript#265]
gulp-typescript warns about "Use sourceRoot option of gulp-sourcemaps instead." and that's OK with me, but removing the `sourceRoot` from the project options makes difficult to use a single `tsconfig.json` for both gulp and tsc. Before my code was just:

    var result = tsProject
        .src()
        .pipe(sourcemaps.init())
        .pipe(tsc(tsProject));

    return result.js
        .pipe(sourcemaps.write('.', {sourceRoot: tsProject.options.sourceRoot}))
        .pipe(gulp.dest('.'));

What about a switch in `tsc.createProject` that says "I know, I will use sourceRoot support in sourcemaps, just let it in options and don't bother giving me a warning"?

**Comment by ivogabe** [comment]
You can override the sourceRoot setting like this:
```javascript
var tsProject = ts.createProject('tsconfig.json', { sourceRoot: undefined });
```

**Comment by fogzot** [comment]
Yes, but that's the opposite of I wanted to do. I wanted to be able to use `options.sourceRoot` as the `sourceRoot` parameter in the `sourcemaps.write()` call without having to keep its value in two places (tsconfig.json and glupfile.js).

**Comment by ivogabe** [comment]
You can access the config in your tsconfig with `tsProject.config.compilerOptions.sourceRoot`.

**Comment by fogzot** [comment]
So I was just looking at the wrong place. Thanks.
