### ISSUE TITLE
Suggestion: load options from tsconfig

### ISSUE THREAD

**Issue by andy-hanson** [ivogabe/gulp-typescript#268]
The following `gulpfile.js` results in an error:

	'use strict'

	const gulp = require('gulp')
	const ts = require('gulp-typescript')

	const config = `./src/tsconfig.json`
	const project = ts.createProject(config)

	gulp.task('build', () =>
		project.src()
		.pipe(ts(project))
		.pipe(gulp.dest('lib')))

Here's `src/tsconfig.json`:

	{
		"module": "umd"
	}

The output of `gulp build` is:

	src/foo.ts(1,17): error TS1148: Cannot compile modules unless the '--module' flag is provided.

The following fixes the error:

	ts.createProject(config, require(config))

I think it should just load the config by default.

**Comment by ivogabe** [comment]
Your configuration is wrong, it should look like this:
```json
{
  "compilerOptions": {
    "module": "umd"
  }
}
```

**Comment by andy-hanson** [comment]
Thanks!
