### ISSUE TITLE
Use latest typescript 1.7.5 (instead of 1.7.3)

### ISSUE THREAD

**Issue by danelkhen** [ivogabe/gulp-typescript#269]
Is it possible to update the typescript dependency for this?

In particular, before this version there is some bug that creates multiple file monitors, which causes sluggishness in file system access. Issue here:

https://github.com/Microsoft/TypeScript/issues/6016

**Comment by ivogabe** [comment]
You shouldn't use the watch option of TypeScript in gulp. Instead you can use `gulp.watch`. But I have updated TypeScript as you suggested.

**Comment by danelkhen** [comment]
Thanks!

I am using the `gulp.watch` option, but since this was a bug in typescript, i wasn't sure if it might be affecting my dev env (there's some delay when writing to filesystem). Thanks again!
