### ISSUE TITLE
const enums in TypeScript: I want to add argument checking to gulp-typescript - questions

### ISSUE THREAD

**Issue by SetTrend** [ivogabe/gulp-typescript#272]
Hi Ivo,

I'd like to add a check for invalid `tsconfig` arguments to `gulp-typescript`.

Latest TypeScript editions work with const enums and I believe that the current code won't work with these.

Unfortunately, when I try to compile the `gulp-typescript` project by running the `default` task, I get a very long list of errors.

Would you mind helping me to get `gulp-typescript` to compile on my machine?

Here's a copy of VS Code output panel after running the `default` task:
[Output.zip](https://github.com/ivogabe/gulp-typescript/files/104175/Output.zip)

Your help is very much appreciated.

Cheers,
Axel

**Comment by ivogabe** [comment]
> Latest TypeScript editions work with const enums and I believe that the current code won't work with these.

TypeScript is compiled with `--preserveConstEnums`, so these const enums are emitted in the generated JavaScript.

> Unfortunately, when I try to compile the gulp-typescript project by running the default task, I get a very long list of errors.

It looks like the tests are failing because the line endings are written twice. It might be an issue with `\r\n` vs `\n`, as the build is passing on Mac and Linux. Can you debug that or should I do that?

**Comment by SetTrend** [comment]
> TypeScript is compiled with `--preserveConstEnums`, so these const enums are emitted in the generated JavaScript.

Ah, thanks for pointing this out to me. I was indeed wondering how you've been able to evaluate the `const enum` values.

Nonetheless, I'm thinking about adding a validation for enum values to `gulp-typescript`. Currently, when providing invalid arguments to `gulp-typescript`, it just silently drops the parameters. That left me clueless for a while when I misspelled one of the arguments.

> It looks like the tests are failing because the line endings are written twice.

Yes, it looks like your observation is correct. That's a shame. I'm working on Windows, and it uses `\r\n` line endings.

**Comment by ivogabe** [comment]
Hi Axel, I think that this can be closed?

**Comment by SetTrend** [comment]
Hi Ivo,

yes, please close. I got distracted by other issues in other Github projects which I then wanted to fix or get fixed first. Then I unfortunately forgot about gulp-typescript due to the different discussions I got involved in. Perhaps I'll eventually add a check to gulp-typescript in my spare time later on.

Regarding const enums, perhaps you might want to vote for my TypeScript proposal to merge TypeScript `const enum` and `enum`? `https://github.com/Microsoft/TypeScript/issues/6695`
