### ISSUE TITLE
"Module" compile option not working for me

### ISSUE THREAD

**Issue by ntoscano** [ivogabe/gulp-typescript#273]
I'm using gulp-typescript v2.10.0, typescript v1.7.5

I'm trying to set the module option to "umd", but the compiler seems to be ignoring the module option completely.

<pre>
var typescriptCompilerOption = {
  module: 'umd',
  sortOutput: true,
  declarationFiles: true,
  removeComments: true,
  target: 'ES5',
  noEmitOnError: false
};
</pre>

Changing the value of the module option has no effect on the compiled files, while changing the other options, such as removeComments, seems to work just fine. 

Any ideas as to what I'm doing wrong? Let me know if you need any more information from me. 

Thanks in advance.

**Comment by ivogabe** [comment]
Do your source files include import or export statements?

**Comment by ntoscano** [comment]
Yes, both. Do you need another code sample?

**Comment by ivogabe** [comment]
I cannot see what's going on, so a small project that can reproduce this would be useful. Can you try to make one? `module` works here fine.

**Comment by ivogabe** [comment]
Since this has been inactive for some time, is this still an issue?
