### ISSUE TITLE
destination file empty

### ISSUE THREAD

**Issue by jmls** [ivogabe/gulp-typescript#279]
so, I have this gulp task

```javascript
var ts = require('gulp-typescript');
var gulp = require('gulp');

gulp.task('typescript', function () {
	return gulp.src('src/server/**/*.ts')
		.pipe(ts({
			noImplicitAny: true,
			out: 'build.js',
			module: 'commonjs'
		}))
		.pipe(gulp.dest('src'));
});
```
and when I modify a .ts file in src/server I get 
```html
[10:05:37] Starting 'typescript'...
src/server/node/index.ts(211,29): error TS7017: Index signature of object type implicitly has an 'any' type.
[10:05:37] Finished 'typescript' after 684 ms
```

(so I know it's picking up the file). After fixing that error, the src/build.js file does get created (if I delete it, it is created after modifying the .ts file) but it has 2 blank lines, nothing else

I have only 1 .ts file at the moment

Am I missing something blindingly obvious ?

thanks

**Comment by jmls** [comment]
ah, figured it out. 

"out:build.js" is not compatible with "module:commonjs"

I removed the "out" option and now it works fine

thanks

**Comment by ivogabe** [comment]
That's correct. You can use something like Browserify to create a bundle.

**Comment by tomitrescak** [comment]
@ivogabe so what modules are supported to create the bundle? I have following config but am getting empty file (I use ES6 style imports in my files):

```
  "compilerOptions": {
    "target": "es5",
    "declaration": false,
    "noImplicitAny": true,
    "removeComments": false,
    "noLib": false,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "sourceMap": false,
    "outFile": "../dist/bundle.js"
  },
```

**Comment by ivogabe** [comment]
You can only use `outFile` with systemjs or amd as module kind.

**Comment by tomitrescak** [comment]
Thanks for your reply
