### ISSUE TITLE
output ordering varies between tsc and gulp-typescript with tsconfig.json

### ISSUE THREAD

**Issue by johncrim** [ivogabe/gulp-typescript#280]
I've posted a variation on this here:
http://stackoverflow.com/questions/35274909/typescript-output-order-gulp-equivalent-to-tsc-with-tsconfig-json
since I'm not positive whether this is a bug or expected.

My fundamental problem is that `tsc` with a tsconfig.json file, and `gulp-typescript` with the same tsconfig.json file produce different output ordering for a non-trivial directory of typescript files. Developers should be able to switch between the two build processes arbitrarily and remain confident that they didn't miss an output ordering bug.

gulp-typescript has great gulp integration features; but tsc has a nice watch feature and tools integration (eg http://dev.ivogabe.com/using-vscode-with-gulp-typescript/ ). I'd like to be able to use them interchangeably, but with this issue I can't (with confidence).

I've seen this on at least 2 different, non-trivial projects. However I tried to create a trivial project that reproduces this issue a few minutes ago, and I was unable to. I don't know how the ordering rules differ between tsc and gulp-typscript with a tsconfig.js, so I don't know how to create a simple repro case.

Ideally gulp-typescript would use typescript's ordering logic and consistent output between the two tools would be automatic (assuming no gulp stream filtering or similar).

My tsconfig.json and gulpfile.js are similar to the following:

tsconfig.json

```
{
  "compilerOptions": {
    "declaration": false,
    "preserveConstEnums": true,
    "outFile": "out/out.js",
    "sourceMap": true,
    "target": "es5",
    "noEmitOnError": true
  },
  "exclude": [
    "node_modules",
    "out"
  ]
}
```

gulpfile.js

```
"use strict";
var gulp = require('gulp');
var typescript = require('gulp-typescript');

var tsProject = typescript.createProject('tsconfig.json');

gulp.task('typescript:compile', function () {
    var tsResult = tsProject.src()
        .pipe(typescript(tsProject));

    return tsResult.js.pipe(gulp.dest('out'));
});
gulp.task('default', ['typescript:compile']);
```

**Comment by ivogabe** [comment]
tsc and gulp-typescript are both using the same api, so it's strange that you're seeing this. Are you using the same version of TypeScript in both cases? The only cause I could think of is that the files are passed to the compiler in a different order.

Do the files that are emitted in a different order have cyclic references? Eg a references b, b references a.

**Comment by heroboy** [comment]
Hi, I have a question maybe relate to the issue.
In document:
> outDir (string) - Move output to a different (virtual) directory. Note that you still need gulp.dest to write > output to disk.

but what about `outFile`? I find if in `tsconfig.json` has a `outFile`, I must write `return tsResult.js.pipe(gulp.dest('release'));`, then it write the output file defined in `tsconfig.json`, and ignore the `gulp.dest('release')`. So I am very confused where to describe the output location.

So I think maybe we should write like this `tsResult.pipe(tsResult.output())`. `tsResult.output()` return a output stream that write files to the location defined in tsconfig.json or typescript options. Let typescript itself to detemine how to output files.

**Comment by ivogabe** [comment]
Is this still an issue?
