### ISSUE TITLE
Version bump with TypeScript 1.7.5

### ISSUE THREAD

**Issue by lelandmiller** [ivogabe/gulp-typescript#281]
I am having issues pulling in gulp-typescript as a git dependency through npm due to the submodules being too large. I was wondering if it would be possible to have a version tagged with the updates to typescript.

**Comment by ivogabe** [comment]
[Released](https://github.com/ivogabe/gulp-typescript/releases/tag/v2.11.0). You can also specify a different version of the compiler (for instance a nightly or beta). See the readme for more details.

**Comment by lelandmiller** [comment]
Thank you for the fast turnaround. Sorry, can't believe I missed that.
