### ISSUE TITLE
Bug in tryReuseStructureFromOldProgram method

### ISSUE THREAD

**Issue by ml054** [ivogabe/gulp-typescript#285]
var oldRootNames = oldProgram.getRootFileNames();
            if (!ts.arrayIsEqualTo(oldRootNames, rootNames)) {
                return false;
            }

I have different file order between subsequent runs of watches resources. The only thing I'm changing is inserting extra line to one of watched files. If we compare oldRootNames and rootNames as sets there are equal. 

As result it can't reuse old structure for application. 

Code that I'm trying to run is here:
https://github.com/ayende/ravendb/tree/v4.0/src/Raven.Studio

**Comment by ivogabe** [comment]
That piece of code looks like code of TypeScript, not gulp-typescript. Is that correct? If so, can you report it there?

**Comment by ml054** [comment]
You are absolutely right.
