### ISSUE TITLE
"suppressOutputPathCheck": true,

### ISSUE THREAD

**Issue by laurelnaiad** [ivogabe/gulp-typescript#286]
I didn't even know about this compiler option... I discovered it while digging around in the typescript source trying to figure out why I kept getting random failures to emit.

I guess somehow typescript was concluding that source files would be overwritten by transpiling my code on behalf of gulp-typescript. I know they won't be....

So I guess this option asks typescript to stop trying to decide if the source files will be overwritten... I guess in my case, I was trying to transpile the project "as if" it would be landing in the same directory (even though I'm piping the results elsewhere).

Anyway, just a tip... might be helpful for folks who get unexplained failures to emit. :)

**Comment by ivogabe** [comment]
Are you suggesting to put this option on by default or adding it to the readme? You can already set it in the settings object or your tsconfig file and gulp-typescript will pass it to TypeScript.
