### ISSUE TITLE
use compiler options without module option

### ISSUE THREAD

**Issue by thelordofthetimes** [ivogabe/gulp-typescript#287]
with module option, we have four value in enum {  'commonjs', 'amd', 'umd', 'system' }

all of them compile typescript to module. sample as i can not compile angular 2 and my code to one file

any idea to compile all source to one file ?

**Comment by ivogabe** [comment]
You can use a module loader, such as Browserify, Webpack, Small, SystemJS, R.JS or Rollup.

**Comment by thelordofthetimes** [comment]
yes, of course we can use bundle or loader. but we have problems when we use many dependent library

   - with bundle as browserify, we must determine compiled file, then add to bundle. this is repeated work. we are early do this with 'import' keyword in typescript and some work which compiler do to resolve source with 'moduleResolution' option. more module mean that more boring work repeated and easy to wrong

   - with loader as systemjs, module will load in runtime. more and more module make loading process slower

would you like to add option to wrap everything to one file ?

**Comment by ivogabe** [comment]
With TypeScript 1.8, you can use the `outFile` option to generate one file when you use systemjs or amd. Is that what you want?

**Comment by thelordofthetimes** [comment]
no, it is not

i want use typescript without module loader. i make two way modeling with two file

[typescript-with-module-loader.txt](https://github.com/ivogabe/gulp-typescript/files/139619/typescript-with-module-loader.txt)
[typescript-without-module-loader.txt](https://github.com/ivogabe/gulp-typescript/files/139620/typescript-without-module-loader.txt)


   - typescript-with-module-loader.txt are standard way, it use typescript with module loader
   - typescript-without-module-loader.txt are my way. it use typescript without module loader

**Comment by ivogabe** [comment]
I'm afraid that's not possible with TypeScript. I cannot implement such in gulp-typescript if it is not implemented in TypeScript. Can you post this on the TypeScript repository? There might be already an issue that's tracking this.

**Comment by thelordofthetimes** [comment]
i think so,

you can read specifications about typescript module here [typescript spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#11). they only support for module loader

thanks you for support
