### ISSUE TITLE
it doesn't compile files if you change file extension

### ISSUE THREAD

**Issue by lega911** [ivogabe/gulp-typescript#288]
This works:
```js
gulp.task('compile_typescript', function () {
    return gulp.src('./src/**/*.ts')
        .pipe(typescript({
            noImplicitAny: false
        }))
        .pipe(gulp.dest('tmp'))
});
```
This doesn't work
```js
gulp.task('compile_typescript', function () {
    return gulp.src('./src/**/*.es')
        .pipe(typescript({
            noImplicitAny: false
        }))
        .pipe(gulp.dest('tmp'))
});
```

any other extentions don't work: "*.es.js", "*.es6.js", ...

**Comment by ivogabe** [comment]
`tsc` doesn't support that either, as far as I know. With TS 1.8, it is possible to add JavaScript files when you set the `allowJs` option.

**Comment by lega911** [comment]
I tried "allowJs: true", tsc doesn't compile TS with this option (it seems only ES3 is allowed)

**Comment by djabraham** [comment]
They have a compiler option, and I think it was even allowed in tsconfig at one time, but for some reason support was later removed. I think it can still be sent through the API, as it is considered internal.

allowNonTsExtensions

**Comment by djabraham** [comment]
Until better support arrives, you might be able to hack the tsc compiler itself (one of the great advantages to open-source :)

ts.supportedExtensions = [".ts", ".tsx", ".d.ts"];
var extensionsToRemove = [".d.ts", ".ts", ".js", ".tsx", ".jsx"];

depending on the version you have in node_modules, it may also have this..

ts.supportedJavascriptExtensions = [".js", ".jsx"];

**Comment by ivogabe** [comment]
If allowNonTsExtensions is still suported, you can add that option and it should be working. Otherwise, you should post this at the repository of TypeScript, as I don't want to add such non-standard option.

**Comment by lega911** [comment]
allowNonTsExtensions can't help me, it doesn't compile TS (works the same as allowJs).
Also it gives me "TypeScript: emit failed" and "noEmit" does't fix it

https://rawgit.com/Microsoft/TypeScript/master/lib/typescriptServices.js
this one can compile TS from any source/filename, so it's possible

**Comment by djabraham** [comment]
The tsservices module is intended for running in the background of an ide or performing custom processing such as linting. Maybe that switch is exclusive to services then. I would ask the ts team to add it to the compiler, they are pretty active.

In the meantime copy typescript into a local modules folder and try the hack. Or fork it and submit a pull request, if you are so inclined. But be aware of their requirements for submissions.

**Comment by lega911** [comment]
> I would ask the ts team to add it to the compiler, they are pretty active.

I don't think so, there are a lot of questions like [this](http://stackoverflow.com/questions/33074964/how-can-i-compile-typescript-1-6-or-later-string-to-javascript-string-not-f)
and extern projects like https://github.com/teppeis/typescript-simple

I just wanted "compile" ES5/6 to ES3 (babel gives bad result)

It seems the easiest way is renaming files before compiling.

**Comment by djabraham** [comment]
That sounded a bit critical. I don't work for MS, nor am I shilling for them, but I think it's fair to say that ~10.5k commits over 3 years is active. 

Given that TS originally supported only client-side code, plus the fact that they now attempt to support just about every major eco system, including React JSX (via TSX), I am personally pleased by their progress. 

I happen to prefer this project within my own; however, this alternative may support the options mentioned earlier. So :+1: for variety as well.

**Comment by lega911** [comment]
>  is active

Yes, I meant that someone has already proposed this feature (with no result)

Look, ``` tsc --allowJs src/ext/router.es.js --outFile tmp/ext/router.js ``` does almost what I want, why gulp-typescript can't do this?

**Comment by djabraham** [comment]
They have lot's of proposals to work on at the moment. Perhaps there are other ways of doing it, in which case I don't think it's a high priority. 
```
var ext_replace = require('gulp-ext-replace');

gulp.task('change', function() {
  gulp.src('styles/*.css')
      .pipe(ext_replace('.es.js', '.ts'))
       .pipe(typescript({
            noImplicitAny: false
       }))
      .pipe(gulp.dest('dist'))
});
```

**Comment by lega911** [comment]
Thank you, but I've already made a gulp plugin for self, that does this:
```js
gulp.task('ts', function() {
    return gulp.src('./src/**/*.es.js')
       .pipe(typescript({
            allowJs: true
       }))
      .pipe(gulp.dest('tmp'))
});
```
gulp-typescript gives no result for this code, it gives error: TypeScript: emit failed
so probably I need to reopen the issue.
