### ISSUE TITLE
gulp-typescript does not find the tsconfig.json

### ISSUE THREAD

**Issue by bastienJS** [ivogabe/gulp-typescript#291]
I use gulp-typescript 2.12.0

When I execute this:

```
var ts = require('gulp-typescript'); 
var tsProject = ts.createProject('tsconfig.json');
```

I get this error:

, no such file or directory 'C:\testapp\tsconfig.json'

How can I tell gulp-typescript the location of the tsconfig.json?

I HAVE to put the tsconfig.json inside the scripts folder as I am using asp.net core project.

**Comment by ivogabe** [comment]
You should replace `'tsconfig.json'` with `'scripts/tsconfig.json'`

**Comment by bastienJS** [comment]
Great service man, such a quick answer!

I just tried another way:

var tsProject =  require('./scripts/tsconfig.json'); // ts.createProject('tsconfig.json');


// compile task:
```
    return gulp
  .src(paths.ts.appSource)
  .pipe(ts(tsProject.compilerOptions))
  .pipe(gulp.dest(paths.ts.appDest));
```

**Comment by ivogabe** [comment]
CreateProject is cleaner and does support incremental compilation. Require is a bit hacky in my opinion, so I prefer createProject.

**Comment by bastienJS** [comment]
Ok then I will follow your advise. Thanks.

**Comment by bastienJS** [comment]
I tr

**Comment by bastienJS** [comment]
The code leads to a compile exception:

```
var tsProject =   ts.createProject('scripts/tsconfig.json');
gulp.task('compile-ts', function () {
     return gulp
  .src(paths.ts.appSource)
  .pipe(ts(tsProject.compilerOptions))
  .pipe(gulp.dest(paths.ts.appDest));
});
```

```
scripts\app.component.ts(1,1): error TS1148: Cannot compile modules unless the '--module' flag is provided with a valid module type. Consider setting the 'module' compiler option in a 'tsconfig.json' file.
scripts\app.component.ts(1,25): error TS2307: Cannot find module 'angular2/core'.
```

With my before approach, everything works. Above all my tsconfig.json has the module property set to 'system'.

Any idea whats wrong?

**Comment by ivogabe** [comment]
You must remove `.compilerOptions`, then everything should be working.

**Comment by bastienJS** [comment]
ah then it works. Hm... I thought I saw this somewhere with you code. Thanks!
