### ISSUE TITLE
Typescript@next

### ISSUE THREAD

**Issue by jcristovao** [ivogabe/gulp-typescript#301]
I'm sorry if this is more of npm / package.json question, but what is the typical workflow when you want to use, let's say, typescript 1.9 alpha with gulp-typescript?

Do you work on a local copy?
Local repo?

Would it make sense to keep a separate branch (of gulp-typescript) with this dependency bumped, and also some patches that would only apply to this (future) version of typescript, as it might be for example #299 ? (I would not mind maintaining it)

**Comment by ivogabe** [comment]
You can use multiple versions of TypeScript using the current version of gulp-typescript. You can find in the [readme](https://github.com/ivogabe/gulp-typescript#typescript-version) how to configure it.

**Comment by jcristovao** [comment]
You are entirely right, and I had gone through the documentation but had managed to not notice that :(

Sorry for the noise
