### ISSUE TITLE
Ignore files using tsconfig.json?

### ISSUE THREAD

**Issue by nicosampler** [ivogabe/gulp-typescript#302]
hello,
  have a question, i'm using createProject configuration with tsconfig.json and I need the transpiler ignore some files.

**source structure:**
* server
  * client
    * client.controller.ts
    * client.controller.spec.ts

i want ignore client.controller.spec.ts

using gulp.src i can use a pattern like this: !(*.spec|*.integration).ts, but i don't know how do the same using tsProject.src()

**gulpfile.js**
```
gulp.task('typescript', ['clean:built'], function () {

    var tsProject = plugins.typescript.createProject('./tsconfig.json');
    var tsResult = tsProject.src()
        .pipe(plugins.sourcemaps.init({ loadMaps: true }))
        .pipe(plugins.typescript(tsProject));

    return merge2([
        tsResult.dts.pipe(gulp.dest("built")),
        tsResult.js.pipe(plugins.sourcemaps.write(".")).pipe(gulp.dest("built"))
    ]);
});
```

**tsconfig.json**

```
{
    "compilerOptions": {
        "target": "es5",
        "declaration": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "noImplicitAny": false,
        "preserveConstEnums": true,
        "removeComments": false,
        "sourceMap": true,
        "outDir": "./built",
        "experimentalDecorators": true
    },
    "exclude": [
        "coverage",
        "node_modules",
        "typings"
    ]
}
```
Thanks in advance.

**Comment by ivogabe** [comment]
You cannot do that with `tsProject.src`, as tsconfig does not support globs. You should use `gulp.src` in such case. Though in most cases, it does not give a big increase in speed if you ignore certain files from the compilation. Especially when you compile these sources in a different task, compilation might even be slower.

**Comment by nicosampler** [comment]
Thanks for the prompt response!!
Ok, so i can use ```createProject('./tsconfig.json')``` and even use ```gulp.src()``` with a specific pattern and it still works with the tsconfig params?

**Comment by ivogabe** [comment]
Yes, that should indeed be working.

**Comment by nicosampler** [comment]
thanks so much!!

**Comment by Pzixel** [comment]
@ivogabe can you explain, please, why it is not possible, I don't get it. For example I have a `.ts` file with declarations only (but which is not `.d.ts` file), and compiler produces empty `.map` and `.js` files. But I want to reference those declarations in another modules which should be compiled. Why I cannot forbid these empty files to be generated?

**Comment by ivogabe** [comment]
@Pzixel At the time of this issue the tsconfig file did not support globs. However you can use them now, in the `include` and `exclude` properties. See https://www.typescriptlang.org/docs/handbook/tsconfig-json.html.
