### ISSUE TITLE
Make gulp-typescript on tsconfig.json compatible with tsc

### ISSUE THREAD

**Issue by konrad-garus** [ivogabe/gulp-typescript#303]
I have a TS 1.8 project with some configuration in tsconfig.json. Since tsc understands module dependencies, I only need to point to the entry point(s) and the compiler will analyze everything for me and do the right thing:

```
{
    "files": [ "./server/app.js" ]
}
```

When I just run `tsc` from command line, I end up with the whole application (numerous files) in the output directory.

When I run gulp-typescript:

```
const typescript = require('gulp-typescript');
const tsProject = typescript.createProject('tsconfig.json');

gulp.task('typescript', function() {  
    return tsProject.src()
        .pipe(typescript(tsProject))
        .pipe(gulp.dest('release'));
});
```

... it only processes that one file. Even `filesGlob` does not seem to get it to include all the files.

**Comment by ivogabe** [comment]
Resolving other files is tracked by #190. The rationale behind the current behavior is that the compiler transforms the input files, like most gulp plugins do.

`filesGlob` is a non-standard option in tsconfig, which is not supported by gulp-typescript. Instead you can use `gulp.src(..)`, which can accept a glob.
