### ISSUE TITLE
pushes unneeded files into the stream when options are - module: amd, out: file.js, noExternalResolve: false

### ISSUE THREAD

**Issue by DmitryEfimenko** [ivogabe/gulp-typescript#304]
**Expected behavior:**
Should not pull a file in the output file when the following options are used:
```
module: 'amd',
out: 'file.js',
noExternalResolve: false
```
**Reasoning:**
Just like described in the docs under section [Resolving files](https://github.com/ivogabe/gulp-typescript#resolving-files):
> Files that are resolved when noExternalResolve is off, won't be pushed to the output stream, unless you are using the out option.

Well, I'm using module `amd` and I need to use `out` option so that `define` functions are generated with unique names. However, it results in resolved files also being pushed into the stream, which is not desirable.

**Your gulpfile:**
```javascript
gulp.task('client-modules', function () {
    var tsProject = $.typescript.createProject({
        removeComments: true,
        module: 'amd',
        outFile: 'app.js',
        noExternalResolve: false
    });
    
    var tsResult = gulp.src(globs.clientModules.concat(globs.types))
        .pipe($.typescript(tsProject));
        
    return tsResult.js
        .pipe(gulp.dest(destinations.client));
});
```

**tsconfig.json**
not related

**Code**

file /common/misc.ts
```typescript
class Misc {

}
export = Misc;
```
file /feature1/a.ts
```typescript
import Misc = require('../common/misc');
class A {
    constructor(private misc: Misc) {}
    // actual Misc is not used. Only its type definitions
}
export = A;
```
file /feature1/b.ts
```typescript
import Misc = require('../common/misc');
class B {
    constructor(private misc: Misc) {}
    // actual Misc is not used. Only its type definitions
}
export = B;
```
After running the gulp task I get something like this:
```javascript
define("common/misc", ["require", "exports"], function (require, exports) {
    // common/misc code
    // This code should not be here. It should be in a separate file so that it can be
    // reused by other features of the website
});
define("feature1/a", ["require", "exports"], function (require, exports) {
    // feature one/a code...
});
define("feature1/b", ["require", "exports"], function (require, exports) {
    // feature one/b code...
});
```

**Comment by ivogabe** [comment]
When you use `out` or `outFile`, all files are emitted. That is by design. However, when you remove `outDir` and use something like gulp-concat, you will not get those unneeded files.

**Comment by DmitryEfimenko** [comment]
I saw that this is by design. Though I think it's incorrect when using module `amd`. I cannot remove `out` and use `gulp-concat` because in this case it'll come out as this:
```javascript
define(["require", "exports"], function (require, exports) {
    // feature one/a code...
});
define(["require", "exports"], function (require, exports) {
    // feature one/b code...
});
```
Notice that `define` functions don't have names (first param), which is required when having multiple amd modules in a single file.

**Comment by ivogabe** [comment]
Could you use gulp-amd-optimizer? Or gulp-name-amd? I cannot change this, since it would be a large breaking change and it might not even be possible with TypeScript.

**Comment by DmitryEfimenko** [comment]
That looks like it could solve this issue. I'll give it a try right now and let you know how it went.

**Comment by DmitryEfimenko** [comment]
So both of these options didn't work for me. `gulp-amd-optimizer` was throwing an error that I could not figure out quickly, and `gulp-name-amd` does not take path into consideration and only uses file name so you may end up with duplicate module names.

I searched around more and could not find a decent solution, which led me to trying to switch to `module: 'system'`, which looked promising, but I quickly stumbled in the exact same issue. Running gulp-typescript without `out` parameter generates unnamed `System.register()` functions, which leads to the error when these are placed in a single file.

What is the reason of pulling all resolved deps into the stream when `out` option is used? I can't see the logic. It would seem to me that `noExternalResolve` should have dominance.

**Comment by ivogabe** [comment]
> What is the reason of pulling all resolved deps into the stream when out option is used? I can't see the logic. It would seem to me that `noExternalResolve` should have dominance.

First of all, `noExternalResolve: false` means that all files are resolved and provided to TypeScript. TypeScript will use these files for type checking and it will also emit all files. Setting this to true would cause error messages that a file cannot be found.

Unneeded files are filtered out after the compilation. That works when you don't set `outFile`, but when you set that option only one file is emitted. Thus, it was not possible to filter these files when `outFile` was set. It might now be possible to emit only specific files, though I'm not sure about that. I cannot change this now as it would be a breaking change, though I can change it in a next major version when #190 is solved.

**Comment by ivogabe** [comment]
I've taken a look at this, and it isn't possible to do this with the TypeScript API. So we have to keep the current behavior for this situation.
