### ISSUE TITLE
IntelliJ debugger seams loosing track of files?

### ISSUE THREAD

**Issue by Renader** [ivogabe/gulp-typescript#311]
I have a project with ts sources, they compile to /build folder. Sourcemaps are enabled and inlined.
If i set a breakpoint in .ts file it wont work. (Google Chrome, IDEA Debug Plugin)
If i set the breakpoint in a generated js file everything works as expected.  

Sourcemaps work, setting breakpoints in chrome->sources-> any.ts => works.

How to tell intellij that a breakpoint in a ts file shall be synced to the js output?

**Comment by ivogabe** [comment]
How is this related to gulp-typescript? Is there something that behaves differently between tsc and gulp-typescript?

**Comment by Renader** [comment]
Obviously i dont think this is a real issue with gulp-typescript. But i was hoping for the expertise of the present users here. Most programmers have a workflow where they just put the compiled .ts files next to the sources - i think debugging would work in this scenario. But if the files are moved to a build directory my idea looses track. Anyone has a similar setup and uses debugging?

**Comment by Renader** [comment]
I could solve my issue by doing the following:
1. inline sourcemaps will cause problems. u must exclude them in order to get debugging running.
2. make sure you mapped your build-output in the debugging settings to  the localhost:XXXX adress. 

thats it.
