### ISSUE TITLE
Error list is different between tsc and gulp-typescript

### ISSUE THREAD

**Issue by ChrisGrigg** [ivogabe/gulp-typescript#313]
**Expected behavior:**

When I run"tsc" in my Angular 2 project only relevant errors are listed.

**Actual behavior:**

When I run "gulp transpile-ts" in my Angular 2 project erroneous errors are listed such as:

- "error TS2304: Cannot find name 'ol'." (there is a d.ts file for openlayers, the only way to get rid of this error is to "import * as ol from './openlayers'" and include the /// reference ...)

- "error TS2339: Property 'find' does not exist on type Array." (I can see the find method exists in the "lib.es6.d.ts" file)

**Your gulpfile:**

var tsProject = ts.createProject('tsconfig.json');
gulp.task('transpile-ts', function() {
    var tsResult = gulp.src(paths.allTypeScript)
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject));'
    return tsResult.js
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(paths.dest_js));
});
  
**tsconfig.json**

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts"
  ]
}

Thanks so much

**Comment by ivogabe** [comment]
It looks like you did not list all source files. What is the value of `paths.allTypeScript`? You might mis the typings directory or something like that.

**Comment by ivogabe** [comment]
You could also use `tsProject.src()` instead of `gulp.src()`, that would resolve all files, like `tsc` does.

**Comment by ChrisGrigg** [comment]
Ok thanks that works now :)
