### ISSUE TITLE
Source ts file overwrite issue

### ISSUE THREAD

**Issue by atilkan** [ivogabe/gulp-typescript#318]
When i save a "ts" file, it builds the file and reloads the file in my IDE. Brokes all my code folding and goes to top of the file. 
typescript task runs multiple time after saving.

**Expected behavior:**
Should not touch the original source file. 

**Actual behavior:**
Overwrites the original source file.

**Your gulpfile:**
```
var typescript = require('gulp-typescript');

gulp.task('js', function() {
    gulp.src('app/**/*.js')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(reload({
            stream: true
        }));
});

gulp.task('typescript', function() {
    return gulp.src('src/typescript/**/*.ts')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(typescript({
            removeComments: true,
            sourceMap: true,
            target: 'ES5'
        }))
        .pipe(uglify())
        .pipe(rename("Menu-1.0.min.js"))
        .pipe(gulp.dest('app/js/'));
});

gulp.watch('app/js/**/*.js', ['js']);
gulp.watch('src/typescript/**/*.ts', ['typescript']);

```

**Comment by ivogabe** [comment]
I cannot reproduce this, gulp-typescript does not write to the file system. Though it looks like you should replace `rename` with gulp-concat. Can you give some more details?

**Comment by atilkan** [comment]
The problem was typescript task was running multiple times. I had to dive deep to solve but no luck. cost me 1 week. 
Finally i removed all packages and installed them manually on command line. I had to do this a couple of times. This time i deleted gitattributes too. I really don't know if relevant but it is ok now. 
One time i did not run gulp and tried to edit a ts file and it was doing the same thing. 
For short the problem is not caused by this plugin.

**Comment by atilkan** [comment]
After trying different editor, removing plugins. Removing every file and reinstalling. I guess i found my problem. 
Dropbox should not be open while working. It detect file change and makes task run twice. This is more reasonable explanation for me.
