### ISSUE TITLE
Compile all *.server.ts files but leave *.client.ts files untouched ? 

### ISSUE THREAD

**Issue by daslicht** [ivogabe/gulp-typescript#319]
Hi,
lets say we have the following naming schema of files:

```
main.server.ts
main.client.ts
```
Is it possible to compile to just compile all *.server.ts files and leave the *.client.ts files untouched ?

related:
http://stackoverflow.com/questions/36436676/how-to-compile-all-files-with-the-extension-server-ts-only

**Comment by ivogabe** [comment]
You cannot do that with `tsProject.src()`, but you can use `gulp.src('**/*.server.ts')` instead.

**Comment by daslicht** [comment]
Will this only compile ``` '**/*.server.ts' ```` and leave the ```client.ts``` files untouched ?

**Comment by ivogabe** [comment]
Yes, that's correct.

**Comment by daslicht** [comment]
Thank you very much , finally I understand how things work together!
My current plan was to use tsify + browserify to bundle the client code.
Is there also a way do this with gulp and how would we have to use the bundle in teh browser?
Do we need a loader such as Systemjs or is the bundle just usable like with browserify?

**Comment by ivogabe** [comment]
You can bundle AMD or SystemJS directly with TypeScript. Though, you need a loader at runtime. You can also bundle at compile time such that you would not need a loader at runtime (or a very small one). You can use browserify for that, but that doesn't integrate nicely with gulp in my opinion. You can also try [Small](https://www.npmjs.com/package/small) instead, which you can add easily to your gulpfile.

**Comment by daslicht** [comment]
Thank you very much , let me try this !

**Comment by daslicht** [comment]
Is there somewhere an example how to compile all ts files but keep them individually, please ?
The Example in teh docs compile alle files into one output file?

**Comment by daslicht** [comment]
Hi,
I have tried this now:
```
var gulp = require('gulp');
var ts = require('gulp-typescript');
var merge = require('merge2');

var tsProject = ts.createProject({
    declaration: true,
    noExternalResolve: true,
    },
    'tsconfig.json'
);

gulp.task('scripts', function() {
    var tsResult = gulp.src('**/*.ts')
                    .pipe(ts(tsProject));

    return merge([ // Merge the two output streams, so this task is finished when the IO of both operations are done.
        tsResult.dts.pipe(gulp.dest('release/definitions')),
        tsResult.js.pipe(gulp.dest('release/js'))
    ]);
});
gulp.task('watch', ['scripts'], function() {
    gulp.watch('**/*.ts', ['scripts']);
});
```

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "allowJs": true
    },
   "exclude": [
        "node_modules",
        "typings"
    ]
}

```

When I now run ```gulp watch``` the typings folder is still included?
Do I import the ```tsconfig``` the wrong way?

**Comment by daslicht** [comment]
I just tried teh following , but it compiles all ts files even the *.clinet.tys files, what do I miss please?

```
var gulp = require('gulp');
var ts = require('gulp-typescript');
var merge = require('merge2');

var tsProject = ts.createProject('tsconfig.json');

gulp.task('scripts', function() {
    var tsResult = tsProject.src('**/*.server.ts')
                    .pipe(ts(tsProject));

    return merge([
        tsResult.dts.pipe(gulp.dest('release/definitions')),
        tsResult.js.pipe(gulp.dest('release/js'))
    ]);
});


gulp.task('watch', ['scripts'], function() {
    gulp.watch('**/*.server.ts', ['scripts']);
});
```

**Comment by ivogabe** [comment]
You should use `gulp.src('**/*.server.ts')` instead of `tsProject.src('**/*.server.ts')`. `tsProject.src` doesn't accept an argument.

**Comment by daslicht** [comment]
Thanks that seam to work !
When using small, does it resolve oll imports automatically or do I have to include all client files to be bundled manually ?

**Comment by ivogabe** [comment]
Small will find all imports if you specify the `externalResolve` option, like `externalResolve: ["node_modules"]`

**Comment by frederickfogerty** [comment]
Hey all. Is there a way to **preferentially** select an extension over another with gulp/typescript when compiling? E.g. I have the following possible extensions: `.ts`, `.web.ts`, `.native.ts`. I would like to have a "web" build pick up `.web.ts` files first, then `.ts`, and likewise for native. 

Thanks in advance for your help.
