### ISSUE TITLE
Fails to create empty folder under OSX

### ISSUE THREAD

**Issue by djabraham** [ivogabe/gulp-typescript#321]
When I build under Windows, the ```server``` sub-folder appears as expected. Under OSX, not so much. Technically, the ```server``` folder is empty because it has no files in it. If I put a ts file in it, then the folder is always output.

**project-root**

    root
    ├─ dist
    │  └─ project
    │     ├─ models
    │     │  └─ model.js    
    │     └─ scripts
    │        └─ class.js    
    ├─ src
    │  └─ project
    │     ├─ server        << this goes missing in dist
    │     │  ├─ models
    │     │  │  └─ model.ts
    │     │  └─ classes
    │     │     └─ class.ts
    │     ├─ tsconfig.json
    │     └─ tsd.d.ts
    └─ gulpfile.js

**gulpfile.js**

    var del = require('del');
    var gulp = require('gulp');
    var ts = require('gulp-typescript');

    var tsSampleProject = ts.createProject('./src/sample/tsconfig.json');
    gulp.task('default', function() {
      var tsResult = tsSampleProject.src().pipe(ts(tsSampleProject));
      return tsResult.js.pipe(gulp.dest('./dist/sample'));
    });

**tsconfig.json**

    {
      "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": false,
        "inlineSourceMap": false,
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "suppressImplicitAnyIndexErrors": true,
        "declaration": false,
        "newLine": "LF"
      },
      "exclude": [
        ".exclude",
        ".archive"
      ]
    }

If I compile without gulp, from the command prompt, then it works ok too.

    tsc --rootDir . -p src/sample --outDir dist/sample

Not sure where this might originate. But a folder is lost somewhere in translation. I only confirmed this at the project root, and didn't explore whether this occurs for a deeper folder.

**Comment by ivogabe** [comment]
I think this should work if you add `rootDir` to your tsconfig file.

**Comment by djabraham** [comment]
Strange that this is only necessary under OSX. When I added the following to ```tsconfig.json```, it then outputs the missing folder.

    "rootDir": "."

**Comment by ivogabe** [comment]
It should work the same on Windows. Are you sure you have the latest version installed? In previous versions, this was not handled correctly.

**Comment by djabraham** [comment]
I was on ```@2.12.1``` on windows and ```@2.12.2``` on osx. 

I updated windows, so now it works the same way as OSX. Sorry, I didn't even think to try that. I will start adding the ```rootDir``` to ```tsconfig.json``` from now on.

Thanks again!
