### ISSUE TITLE
gulp-typescript substantially slower than tsc

### ISSUE THREAD

**Issue by dylanscott** [ivogabe/gulp-typescript#326]
I realize this is a bit of a vague issue, but I'd really love to get some ideas how I could speed this up. I have an existing build that I'm adding TypeScript to, and noticing substantial performance differences between compiling with gulp-typescript vs. tsc. The actual numbers:

```bash
time tsc
tsc  1.65s user 0.07s system 139% cpu 1.232 total
```

```bash
time gulp compile:typescript
gulp compile:typescript  6.25s user 0.92s system 116% cpu 6.134 total
```

The gulp task is pretty minimal:
```javascript
const gulp = require('gulp')
const typescript = require('gulp-typescript')
const tsProject = typescript.createProject('tsconfig.json', {
  typescript: require('typescript')
})
gulp.task('compile:typescript', function() {
  return tsProject.src()
    .pipe(typescript(tsProject)).js
    .pipe(gulp.dest('app'))
})
```

As is the `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": false,
    "outDir": "app",
    "rootDir": "server-src",
    "noImplicitAny": true
  },
  "exclude": [
    ".git",
    "node_modules",
    "typings/browser.d.ts",
    "typings/browser",
    "typings/main",
  ]
}
```

Some random other stuff that could potentially be contributing:
* As I mentioned I'm adding TypeScript to an existing project. The source directory contains a lot of es6 files with `.js` extensions, but only a couple of TypeScript files.
  * I would hope that using `tsProject` and the same `tsconfig.json` would ensure they're scanning the same files though, and I've monitored the build dir with `fswatch` and confirmed that both `tsc` and `gulp compile:typescript` are writing the same set of output files.

**Comment by ivogabe** [comment]
Are you using the latest version? A previous version had a performance issue which has been fixed.

**Comment by dylanscott** [comment]
Yep, sorry forgot to include that information. Versions:
* gulp-typescript: `2.13.0`
* gulp: `3.9.1`
* tsc: `1.8.9`

**Comment by ivogabe** [comment]
Thanks for the info. Then the issue I refered to is not the issue here. What happens wehn you replace `tsProject.src()` by `server-src/**/*.ts`? Does that give normal times?

**Comment by dylanscott** [comment]
Ah interesting - that does give normal times. I was just doing some basic profiling and noticing that an inordinate time was being spent globbing. Maybe this is related to [glob-stream#24](https://github.com/gulpjs/glob-stream/issues/24)? Haven't actually dug into the code but I could imagine this project using negated globs to handle `tsconfig.json` `exclude`s.

Happy to close this out. Seems like an unfortunate interaction with glob perf, and while it'd be nice to use `tsconfig.json` as-is here, specifying an include glob seems like a reasonable compromise. Really it would be nice if `tsc`/`tsconfig.json` supported include globs.

**Comment by ivogabe** [comment]
I think you are correct with your analysis. I thought I fixed it with e0233467d7c9d8e156546d3c392d5257f9dc088d, but apparently it is still too slow in your case. I'd like to keep this open until this is fixed.

Can you time the following tasks:
```javascript
gulp.task("a", function() {
  return gulp.src("server-src/**/*.ts");
});
gulp.task("b", function() {
  return gulp.src(["**/*.ts", "!node_modules/**"]);
});
gulp.task("c", function() {
  return gulp.src(["**/*.ts", "!node_modules/**/*"]);
});
gulp.task("d", function() {
  return gulp.src("**/*.ts");
});

**Comment by dylanscott** [comment]
Sure. I've included times as reported by gulp and by the system. It looks like excluding `node_modules` has no effect on globbing time, which seems consistent with [this comment](https://github.com/gulpjs/glob-stream/issues/24#issuecomment-68167101) on glob-stream#24 (negation is done post-read). This seems hard to get around as long as `vinyl-fs.src`/glob-stream is used. Poking around the TypeScript compiler a little they seem to traverse the file system manually rather than using globs. Perhaps it would be possible for the project returned by `createProject` to implement `src()` by delegating to [`ts.Program#getSourceFiles()`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L1626). I know very little about TypeScript internals though so I don't know how reasonable that is. The gulp-typescript compiler seems to have a reference to the `Program`.

```bash
$ time gulp a
[11:08:45] Using gulpfile ~/.../gulpfile.js
[11:08:45] Starting 'a'...
[11:08:45] Finished 'a' after 27 ms
gulp a  1.53s user 0.19s system 103% cpu 1.651 total
```

```bash
$ time gulp b
[11:08:53] Using gulpfile ~/.../gulpfile.js
[11:08:53] Starting 'b'...
[11:08:56] Finished 'b' after 2.7 s
gulp b  4.15s user 1.25s system 124% cpu 4.345 total
```

```bash
$ time gulp c
[11:09:10] Using gulpfile ~/.../gulpfile.js
[11:09:10] Starting 'c'...
[11:09:13] Finished 'c' after 2.67 s
gulp c  4.12s user 1.01s system 118% cpu 4.323 total
```

```bash
$ time gulp d
[11:09:18] Using gulpfile ~/.../gulpfile.js
[11:09:18] Starting 'd'...
[11:09:20] Finished 'd' after 2.74 s
gulp d  4.13s user 0.93s system 116% cpu 4.359 total
```

**Comment by ivogabe** [comment]
Thanks for the numbers. I hope to take a look at the referenced issue after next week, maybe I can create a fix there.

This cannot be created using the TypeScript API, since that is synchronous, whereas it should be asynchronous in Gulp. Making it sync would slow down other tasks.

**Comment by dylanscott** [comment]
Sounds good, thanks for your help!

**Comment by alexdresko** [comment]
Just wanted to add another voice to this. Not complaining.. gulp-typescript certainly works.. it's just way slow compared to tsc. Will be happy to help however I can.

**Comment by ivogabe** [comment]
@alexdresko You could take a look at gulpjs/glob-stream#24, that issue is probably the cause of this one.

**Comment by BastianGanze** [comment]
I really don't want to complain, but is it normal that the transpiling of one file takes an entire second without using watch? 
gulp.src("test.ts") <- Just doing that, no glob shenanigans.
I am using a SSD and a fairly powerful CPU, this should be in the range of milliseconds, shouldn't it?

**Comment by roymiloh** [comment]
I'm experiencing slowness with `tsProject.src()` as well. When changing from `tsProject.src()` to `gulp.src([globs])` it works much better, although `tsc -w` is the fastest.

**Comment by alekkowalczyk** [comment]
I'm using gulp.src on a folder with 4 ts file and it takes almost 3 seconds, really slow.

**Comment by m1sh2** [comment]
I updated my `gulp-typescript` `2.13.0` -> `2.13.6` and speed is the same, 48 seconds...

**Comment by lucastheisen** [comment]
I have a project (simple angular quickstart example) that seems to demonstrate this issue.  When compiling with:

* `gulp.src(<positive_glob>)` it takes ~1 second.
* `gulp.src(<negative_glob>)` it takes ~4-11 second.
* `tsProject.src()` it takes ~4-11 seconds.

On top of that, `tsProject.src()` does not emit any errors, but both `gulp.src(...)` versions emit a bunch of `error TS2304: Cannot find name 'Promise'` and `error TS2304: Cannot find name 'Map'` errors.  You can find my project here: 

https://github.com/lucastheisen/test-js-maven/tree/gulp-typescript-326

or clone:

`git clone https://github.com/lucastheisen/test-js-maven.git`

and checkout the `gulp-typescript-326` branch.

**Comment by m3kka** [comment]
Any news regarding this issue?

I am too finding gulp-typescript considerably slower than tsc compilation, and we're kinda forced to use a gulp plugin :/

**Comment by dylanscott** [comment]
Don't want to steal any of this project's thunder, but in case it's useful to anyone I ended up porting my typescript watch task to just fork off a `tsc --watch` process. It's [a bit of a hack](https://gist.github.com/dylanscott/18b9fa1432d80d0cfcf16f9c6711671d) (parses the `tsc` output to make the task output more consistent with other gulp watch tasks) but I've been using it for over a month on a real project without any issues. It took my incremental compile times from ~25 seconds to about 3 to 4 seconds.

**Comment by ivogabe** [comment]
This is probably related to a known performance issue of `tsProject.src()`, can you try to replace that with `gulp.src('lib/**/*.ts')` or something like that?

**Comment by alexdresko** [comment]
Problem is, `'lib/**/*.ts` isn't the same as what I have in my `tsconfig.json` and I don't particularly want to have to keep them manually synchronized.

**Comment by m3kka** [comment]
After a bit of debugging apparently the sourcemap creation is the problem :/

The incremental build jump up from ~2.2s to a whooping ~10s/~12s

**Comment by ivogabe** [comment]
@m3kka How does your gulpfile look? Do you have gulp plugins between `init()` of gulp-sourcemaps and gulp-typescript?

**Comment by m3kka** [comment]
@ivogabe Answered in the wrong issue. 
My problem was not using `--outFile` but `gulp-concat` now the performance are quite better.

Thank you for the lead.

**Comment by ivogabe** [comment]
In ff163bfc1571e458f5d8e8a68c5a49c3869de123, I've removed the glob that `tsProject.src` used. The TypeScript api is now used to resolve the files. That proces is synchronous, but it will still be faster in most situations. Another benefit is that the behavior is now exactly the same as `tsc`, previously there were some edge cases that didn't work correctly. Since I believe that `tsProject.src` caused the performance issues mentioned in this topic, I think that this can be closed. If someone still experiences performance problems, please open a new issue.

**Comment by ivogabe** [comment]
Oops, I was referring to 98eca4ab34cb02e54589e40e9871cda59dce36cb.

**Comment by combmag** [comment]
@ivogabe when this will be released?

**Comment by ivogabe** [comment]
@combmag [a few minutes ago](https://github.com/ivogabe/gulp-typescript/releases/tag/v2.14.0) 😄

**Comment by alexdresko** [comment]
Much faster. 1.14 seconds for my current project.

**Comment by GrzegorzKaczan** [comment]
After switching to gulp-typescript 3.0.1 and typescript 2.0.3 we again see substantial performance drop. Compilation time for our project increased from ~8s to ~15s.

We are using lib as proposed in newer version so:
```
var tsResult = gulp.src('lib/*.ts')
        .pipe(tsProject());
```

I've created separate mini project as a test case. It does a compilation on 10000 small `tsx` components. I am on `Ubuntu 16.04`
I can confirm timings when using `tsc` are much faster for this test case as well. So it is not a problem of typescript itself.

libs used | compilation time
------------ | -------------
gulp-typescript@2.14.1, typescript@2.0.3|15s
gulp-typescript@3.0.1, typescript@1.8.10|8s
tsc@2.0.3|5s


Test is available at:
[https://github.com/GrzegorzKaczan/gt-test/archive/master.zip](https://github.com/GrzegorzKaczan/gt-test/archive/master.zip)
`$ npm install`
