### ISSUE TITLE
Emitted decorator metadata is different when --isolatedModules is set

### ISSUE THREAD

**Issue by jpsfs** [ivogabe/gulp-typescript#333]
Hi,

I'm facing an issue while compiling an Angular 2 application with the IsolatedModules flag set to true.
If IsolatedModules is set to false everything works as expect.

The emitted decorator metadata is different. If I use tsc directly I have no problem.

I've prepated a repo that easily reproduces the issue.
Just download it, run npm install && typings install.

See diferences on decorator.js when executing **gulp build** and **tsc**.

**TypeScript Version:** 

1.8.10

**Code**

```ts
import * as ng from "angular2/core";

@ng.Decorator({
...
})
export class MyClass{
     constructor(private el: ng.ElementRef) {
     }
}
```

**Expected behavior:**
If the isolatedModules flag is set to false:
```js
...
MyClass = __decorate([
      ng.Directive({
            selector: '[my-selector]',
      }), 
      __metadata('design:paramtypes', [ng.ElementRef]) // <<<<<<<<<<<<<<<<<<<
], MyClass);
```

**Actual behavior:** 

If the isolatedModules flag is set to true:

```js
...
MyClass = __decorate([
      ng.Directive({
            selector: '[my-selector]',
      }), 
      __metadata('design:paramtypes', [Object]) // <<<<<<<<<<<<<<<<<<<<<<<
], MyClass);
```

https://github.com/Microsoft/TypeScript/issues/8355

**Comment by ivogabe** [comment]
Closing as this is probably an issue with TypeScript (Microsoft/TypeScript#8355)

**Comment by mheiber** [comment]
fixed in TypeScript: https://github.com/Microsoft/TypeScript/pull/9232
