### ISSUE TITLE
TS2304: Cannot find name xxx but no errors with tsc

### ISSUE THREAD

**Issue by Ibrahim-Islam** [ivogabe/gulp-typescript#334]
**Expected behavior:**
Complete successfully without any errors like running `npm run tsc` does

**Actual behavior:**
Error messages logged includes:
```
error TS2304: Cannot find name 'Promise'
error TS2304: Cannot find name 'Map'
error TS2304: Cannot find name 'MapConstructor'
error TS2304: Cannot find name 'Iterator'
```
96 semantic errors
emit succeeded (with errors)

**Your gulpfile:**
*Include your gulpfile, or only the related task (with `ts.createProject`).*
https://github.com/angular/angular2-seed/blob/systemjs/gulpfile.js
```javascript
//Typescript Config;
var tsProject = ts.createProject(tsConfig.compilerOptions);

//compile app typescript files
gulp.task('compile:app', function(){
  return gulp.src('src/**/*.ts')
    .pipe(ts(tsProject))
    .pipe(gulp.dest('./dist'))
    .pipe(connect.reload());
});
```

**tsconfig.json**
*Include your tsconfig, if related to this issue.*
https://github.com/angular/angular2-seed/blob/systemjs/tsconfig.json

**Code**

*Include your TypeScript code, if necessary.*
https://github.com/angular/angular2-seed/tree/systemjs/src

**Comment by ivogabe** [comment]
The problem is that the definition files from the `typings` directory aren't passed to TypeScript with that configuration (https://github.com/angular/angular2-seed/blob/b476ad20d00cc7452a315f5f85d1b6c499644743/gulpfile.js#L45). So this is a configuration problem. You can fix this by changing that line to:
```typescript
return gulp.src(['src/**/*.ts', 'typings/browser/**/*.d.ts'])
```

**Comment by Ibrahim-Islam** [comment]
Thanks for the quick reply. This works now as expected. But why does `tsc` work then without any errors?
