### ISSUE TITLE
does not generate d.ts file even when declaration is set to true

### ISSUE THREAD

**Issue by nehaverma8** [ivogabe/gulp-typescript#335]
The gulp-typescript task does not generate d.ts file even when I have set declaration:true in tsconfig.json. When I run tsc at the folder where tsconfog.json is present, my application.d.ts is generated. 

**Expected behavior:**
application.d.ts should be generated. 
**Actual behavior:**
application.d.ts is NOT generated. 
**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript

gulp.task('compile-ts', function () {
    var sourceTSFiles = [
           config.paths.ts.allTS
    ];
    var tsResult = gulp
        .src(sourceTSFiles)
		.pipe(sourcemaps.init())
        .pipe(tsc(tsproject));
		console.log(tsResult);
    return tsResult.js
		.pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(config.paths.ts.tsOutputPath));
});

```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "declaration": true,
    "sourceMap": true,
    "outFile": "build/js/application.js"
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "typings"
  ]
}


```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by ivogabe** [comment]
You should use the `tsResult.dts` stream to get the definition files:
```javascript
    return merge([
        tsResult.dts.pipe(gulp.dest(config.paths.ts.tsOutputPath)),
        tsResult.js.pipe(sourcemaps.write('.'))
            .pipe(gulp.dest(config.paths.ts.tsOutputPath))
    ]);
```

**Comment by nehaverma8** [comment]
Works. Thanks!!
