### ISSUE TITLE
gulp not updating js files correctly

### ISSUE THREAD

**Issue by rulick76** [ivogabe/gulp-typescript#336]
hey,
i don't know what is exactly the problem but using gulp sometimes works and sometimes not.

i'm starting with a templete boilerplate that contains a dev folder with typescript files and assets folder.
i have also package.jason and gulp file
everyting was working good until i decided to create sub folder under my dev folder for the porpuse of modularity and than gulp stop working...if i changing now something in one of my angular2 components ,the js parallel component not being updated...
i tried to run again gulp(after removing the app and src folders ) but the new app folder cames with a dev folder underneath ...
only when i remove also the node_moduls with the app and src folders and run again npm install and than run gulp it is starting to work again but after couple of changes again stop....

**Comment by ivogabe** [comment]
It's hard to say why that doesn't work. Can you share your project? Is it somewhere on GitHub? You can also mail it if you prefer that.

**Comment by rulick76** [comment]
Wow thanks for your quick reply

I have attached a tmplate project with dev folder that contains type script
and assets folder for styles...
after running npm install (package.json is there sa well) and then gulp
(gulp file is there also)
the expected behaviour is that an app folder will be created and will
include parallel fies to the dev folder in js format , and that an source
folder parallel to assets ...
after running gulp an app folder is created but another dev folder is being
created underneath the new app folder....
and sometimes it is genereting the folders as expected and then stop
working

**Comment by rulick76** [comment]
Hey Ivo :)
any assumptions?

Thanks!

**Comment by ivogabe** [comment]
I haven't had time for it, though it looks that the attachment is missing. I think you cannot send it by replying to the GitHub notifications mail, but you can submit one on the website.

**Comment by rulick76** [comment]
I sent the attachment via the mail not via git hub...
what will be the best approach to send you the file?

Thanks!

**Comment by ivogabe** [comment]
You can open [this issue](https://github.com/ivogabe/gulp-typescript/issues/336) in the browser and then attach the file, as described [here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by ivogabe** [comment]
Is this still an issue?
