### ISSUE TITLE
outFile doesn't respect gulp.dest location

### ISSUE THREAD

**Issue by ribizli** [ivogabe/gulp-typescript#338]
**Expected behavior:**
`outFile` should be placed relative to the `dest` folder. (It is the behaviour in version 2.13.0, not working anymore in 2.13.1)
**Actual behavior:**
`outFile` is placed relative to project root folder.
**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
var tsProject = ts.createProject(tsConfig.compilerOptions, {typescript: require('typescript')});
gulp.task('compile', function () {
    return gulp.src(config.compile)
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(config.targetDir));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "version": "1.8.9",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": true,
    "outFile": "bundle.js"
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by ivogabe** [comment]
I think this was solved in 9859e4795337da6b490a2c7fbb87565b59a42dd8.

**Comment by ivogabe** [comment]
Can you try v2.13.1? It should contain the fix for your issue.

**Comment by ribizli** [comment]
As you can see in the OP, I discovered the issue when I upgraded to the latest (2.13.1) version.

**Comment by ivogabe** [comment]
Sorry, I meant 2.13.2. Can you try that version?

**Comment by ribizli** [comment]
The version `2.13.2` put my bundle files now beside the dist folder not inside it ;(

For the record: `config.targetDir` is set to `../target/dist`, and the `bundle.js` file was created in the `../target` folder.

**Comment by ribizli** [comment]
But I can leave with this situation: I set the `outFile: 'dist/bundle.js`, so it will generated into the `dist` folder.

**Comment by ivogabe** [comment]
Thanks for the details. I have fixed it. The issue was that when the project contained only files in a subdirectory, the base path was incorrect. Can you verify that this has solved your issue? If so, I'll release this update on NPM.

**Comment by falsandtru** [comment]
I got a similar problem in v2.13.**2**, but its fixed in the master branch :)

**Comment by falsandtru** [comment]
@ivogabe Could you release the next version? It also would be helpful for easy verifying.

**Comment by ivogabe** [comment]
Yes, it's released now.

**Comment by TheTedAdams** [comment]
Thanks for quick response on this. It broke our build yesterday and we couldn't figure out why our built files were ending up in `/users/[me]/projects/[project-name]/users/[me]/projects/[project-name]/built`. Then this morning after a fresh `npm install` it miraculously worked!

**Comment by ivogabe** [comment]
Sorry for the inconvenience, good to hear it's working again!

**Comment by falsandtru** [comment]
My CI process has succeeded. Thanks a lot :tada:

**Comment by ribizli** [comment]
I'll test it only on Monday, but thanks anyway.
