### ISSUE TITLE
gulp.dest creates output in the wrong directory

### ISSUE THREAD

**Issue by rina-sleeping** [ivogabe/gulp-typescript#341]
I upgraded gulp-typescript version 2.10.0 to 2.13.4, then this issue occurred.
gulp.dest('repro') outputs into the wrong  directory.

**Expected behavior:**
repro/repro.js is created.

**Actual behavior:**
repro/app/repro.js is created.

**Your gulpfile:**

```
gulp.task('repro_test', () =>{
     gulp.src([
      'src/app/*.ts',
      'src/typings/bluebird/bluebird.d.ts',
    ])
     .pipe(ts({
          "module": "commonjs",
          "target": "es5",
          "out": "repro.js",
          declaration: true,
          noExternalResolve: true
    }))
    .pipe(gulp.dest('repro'));
});
```

Using follwing gulpfile,
```
gulp.task('repro_test', () =>{
     gulp.src([
      'src/typings/bluebird/bluebird.d.ts',
      'src/app/*.ts',
    ])
     .pipe(ts({
          "module": "commonjs",
          "target": "es5",
          "out": "repro.js",
          declaration: true,
          noExternalResolve: true
    }))
    .pipe(gulp.dest('repro'));
});
```
gulp.dest outputs 'repro/typings/bluebird/repro.js'
I think that wrong directory may be related to the first read file by gulp.src().

**Comment by ivogabe** [comment]
Could you test this with the version here on GitHub? It should contain a fix for your problem.

**Comment by rina-sleeping** [comment]
I tried the GitHub version, and It fixed!
Thank you.
