### ISSUE TITLE
Compiling files importing "typescript" fails when using typescript@next

### ISSUE THREAD

**Issue by larrifax** [ivogabe/gulp-typescript#343]
I'm trying to compile a file that imports something from "typescript", but it fails because the ```undefined``` literal is not defined in ```node_modules/typescript/lib/typescript.d.ts```.

Compiling the file using ```tsc --m commonjs --target ES5 myfile.ts``` succeeds, so this must be an issue with gulp-typescript.

I'm using typescript version ```1.9.0-dev.20160513```

**Expected behavior:**
File compiles successfully.

**Actual behavior:**
```
C:/code/node_modules/typescript/lib/typescript.d.ts(1558,50): error TS2304: Cannot find name 'undefined'.
C:/code/node_modules/typescript/lib/typescript.d.ts(1564,48): error TS2304: Cannot find name 'undefined'.
C:/code/node_modules/typescript/lib/typescript.d.ts(1940,64): error TS2304: Cannot find name 'undefined'.
```
**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
const gulp = require("gulp");
const plugins = require("gulp-load-plugins")({ lazy: true });

gulp.task("build", () => {
    return gulp.src("**/*.ts")
        .pipe(plugins.typescript({
            module: "commonjs",
            target: "es5"
        }))
        .pipe(gulp.dest("compiled"));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json

```

**Code**

*Include your TypeScript code, if necessary.*
```typescript
import { SourceFile } from "typescript";

export function test(source: SourceFile) {
    return source;
}
```

**Comment by ivogabe** [comment]
You must also reference that in your gulpfile, see the [readme](https://github.com/ivogabe/gulp-typescript#typescript-version). Does that solve your issue?

**Comment by larrifax** [comment]
doh! That seems to have fixed the issue. It's weird that the issue emerged when I updated Typescript. Maybe npm v3 is the culprit.

**Comment by MeirionHughes** [comment]
How did you fix this? I've updated one of my projects to 2.0 and I'm getting this exact error message too.
