### ISSUE TITLE
tsconfig.json doesn't seem to be used properly

### ISSUE THREAD

**Issue by AlexandreRoba** [ivogabe/gulp-typescript#345]
Dear all Gulpers,

I have a working ts.config file configured. When I run tsc from the command line such as:
```bash
tsc
```
this generates an output such as
```
js
├── app.js
├── app.js.map
├── handlers
│   ├── noise.js
│   └── noise.js.map
├── models
│   ├── INoise.js
│   ├── INoise.js.map
│   ├── Noise.js
│   └── Noise.js.map
└── routes
    └── v1
        ├── NoiseRoutes.js
        ├── NoiseRoutes.js.map
        ├── UserRoutes.js
        ├── UserRoutes.js.map
        ├── index.js
        └── index.js.map
```
This used the tsconfig file which is located at the root of the project from where the tsc is executed.

then I have install gulp-typescript and configured a gulp file such as:
```js
var gulp = require('gulp');
var rimraf = require('gulp-rimraf');
var ts = require('gulp-typescript');
var debug = require('gulp-debug');

var tsProject = ts.createProject('tsconfig.json');

gulp.task('clean', function () {
    return gulp.src('./js', {read: false})
        .pipe(rimraf());
});

gulp.task('build', ['clean'], function () {
    var tsResult = tsProject.src()
        .pipe(debug({title:'input'}))
        .pipe(ts(tsProject));

    return tsResult.js
        .pipe(debug({title:'output'}))
        .pipe(gulp.dest('./js'));
});
```
this gulpfile is at the same level as my tsconfig file.

When I run gulp such as:
```bash
13:38 $ gulp build
(node:2683) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[13:41:41] Using gulpfile ~/projects/tamtamme.io/gulpfile.js
[13:41:41] Starting 'clean'...
[13:41:41] Finished 'clean' after 23 ms
[13:41:41] Starting 'build'...
[13:41:41] input src/app.ts
[13:41:41] input typings/main.d.ts
[13:41:41] input 2 items
[13:41:42] output js/src/app.js
[13:41:42] output 1 item
[13:41:42] Finished 'build' after 1.25 s
```

i'm getting this as output
````
js
└── src
    └── app.js
```
The referenced ts file from the app.ts file are not compiled...
It looks like tsconfig is not used...I'm expecting, when using a tsconfig file, to get the same output as just using tsc... I'm a wrong? Do I have to duplicate my tsconfig file in my gulpfile? Then what is the point of supporting the tsconfig option in the gulp task?

Thanks for any help you could provide me.

**Comment by ivogabe** [comment]
I think you want #190. You could use `gulp.src` instead of `tsProject.src`, or you could remove the `files` property from your tsconfig file, and use `excludes` instead.

**Comment by AlexandreRoba** [comment]
Hi ivogabe,

thanks for the tip. Indeed that seemed to works.
I ended by following the blog post from Dan Wahlin http://weblogs.asp.net/dwahlin/creating-a-typescript-workflow-with-gulp.

This basically made me remove the files property from the tsconfig and to use gulp.src as you suggest with an array with filesGlob. But this seems in my humble opinion a little bit counter productive. Is there any reason why the  tsc compilation made by gulp-typescript not behaving like tsc when using tsconfig?

I found the same difficulty to have to use gulp-sourcemaps in order to get the sourcemap generated. tsc does not when specified to true in the tsconfig.json.

Now my gulpfile.js looks like:
```js
'use strict';

var gulp = require('gulp');
var rimraf = require('gulp-rimraf');
var tsc = require('gulp-typescript');
var debug = require('gulp-debug');
var sourcemaps = require('gulp-sourcemaps');


var Config = require('./gulpfile.config');

var config = new Config();
var tsProject = tsc.createProject('tsconfig.json');

gulp.task('clean', function () {
    return gulp.src('./js', {read: false})
        .pipe(rimraf());
});

gulp.task('build', ['clean'], function () {
    var sourceTsFiles = [
        config.allTypeScript,
        config.libraryTypeScriptDefinitions];


    var tsResult = gulp.src(sourceTsFiles)
        .pipe(sourcemaps.init())
        .pipe(tsc(tsProject));

    tsResult.dts.pipe(gulp.dest(config.tsOutputPath));
    return tsResult.js
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(config.tsOutputPath));
});
````

and the gulpfile.config.js looks like:
```js
'use strict';

var GulpConfig = (function () {

    function gulpConfig() {
        this.source = './src/';
        this.tsOutputPath = './js';
        
        this.allTypeScript = this.source + '/**/*.ts';

        this.typings = './typings/';
        this.libraryTypeScriptDefinitions = './typings/main/**/*.ts';
    }

    return gulpConfig;
})();
module.exports = GulpConfig;
```

Thanks for your help.

**Comment by AlexandreRoba** [comment]
Hello ivogabe,

thanks for the support and for this plugin. I manage to have it working following your guidance and the documentation.

If I might make a suggestion I would modify the plugin in order to use the tsconfig as the compiler does. Ideally I would make the API of the plugin to be only tsconfig.json. After all all compiler options are (or should be) available through this object.a Build task could look like something:

```js
var gulp = require('gulp');
var tsc = require('gulp-typescript');

gulp.task('build', function () {
    //Building the folder projectX containing a tsconfig.json
    gulp.src(['./projectX'])
        .pipe(tsc())
        .pipe(gulp.dest('/')) //where '/' would be the root folder of the outDir

    //Building from a tsconfig.json file directly
    gulp.src(['./projectX/tsconfig.json'])
        .pipe(tsc())
        .pipe(gulp.dest('/')) //where '/' would be the root folder of the outDir
});
```

What do you think of this? I have not much experience with building gulp plugin but do you think this is doable? If so we could create a specific plugin for this? like gulp-typescript-tsconfig...

thanks again for the excellente work you have done and your availability :)

**Comment by ivogabe** [comment]
I personally always use the `excludes` property of the tsconfig file, instead of `files`. That works as expected with gulp-typescript.

gulp-sourcemaps is a different plugin, since that is standard in the gulp world. This makes it easy to use multiple plugins, with full source map support. In general, gulp requires some more configuration, but it also has more possibilities. When using gulp, you're probably using it because you need multiple plugins so the extra effort is worth it.

When I implemented tsconfig support, I had the same idea as you in my mind. I chose not to implement that, because it has several drawbacks. For instance, you cannot add a gulp plugin, like gulp-sourcemaps, before the TypeScript compilation. Also incremental compilation is a bit harder when the tsconfig file is an input file.

**Comment by AlexandreRoba** [comment]
Thanks for the feed back. Quick questions some what related. 

As you can see on my solution, I now have to specify on my gulp task the files I want to compile specificaly instead of letting typescript to resolve the files itself based on the files it uses. As I simply ask to take all the ts files it includes the ts files that contains only an interface... Those files are now also compiled and translated in "Almost" empty json files...

The ts file INoise.ts containing
```typescript
import * as mongoose from 'mongoose';

export interface INoise extends mongoose.Document{
    what: [string],
    when: Date,
    where: [number]
}
```

transpile to:
```js
"use strict";

//# sourceMappingURL=INoise.js.map
```
 which is useless... :(

Any advice on how to avoid this?

Thanks again for your help

**Comment by ivogabe** [comment]
I don't think you can do anything to prevent that. When you would use `tsc`, you would also get such almost empty files. For purity, I understand that this is not nice, but in practice I don't think it's a real issue.

**Comment by lilred** [comment]
>When I implemented tsconfig support, I had the same idea as you in my mind. I chose not to implement that, because it has several drawbacks. For instance, you cannot add a gulp plugin, like gulp-sourcemaps, before the TypeScript compilation. Also incremental compilation is a bit harder when the tsconfig file is an input file.

IMHO - if someone is using a `tsconfig.json` file, then they're probably relying on the compiler to handle both source maps and incremental compilation.

**Comment by ivogabe** [comment]
@lilred Source maps and incremental compilation are working with the current implementation. Source maps are working the same way as all other gulp plugins that support source maps.

**Comment by ivogabe** [comment]
I think that this can be closed?
