### ISSUE TITLE
Code snippets on npmjs.com are heavily indented

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ivogabe/gulp-typescript#346]
![image](https://cloud.githubusercontent.com/assets/3335181/15328524/000c59f0-1c0a-11e6-945b-0c0fc04f49e1.png)

Browser: Chrome 50
OS: Windows 10

Ignoring the tabs vs spaces debate, would you be against me submitting a PR changing your snippets to spaces?

**Comment by ivogabe** [comment]
👍 Sound like a good idea
