### ISSUE TITLE
implement 'realpath' in Host to properly resolve symlinks

### ISSUE THREAD

**Issue by vladima** [ivogabe/gulp-typescript#349]
With https://github.com/Microsoft/TypeScript/pull/8486 it is now possible to follow symlinks obtained as a result of module resolution to its actual location. In order to support this custom implementations of `CompilerHost` should expose `realpath` function which will be called by the compiler as an epilogue of node module resolution.

**Comment by pgonzal** [comment]
For context, the `realpath` function is a fix for a real bug that my project encountered when using the "npm link" command.  For a repro, try running build.cmd from this archive:

[NpmLinkRepro2.tar.gz](https://github.com/ivogabe/gulp-typescript/files/270406/NpmLinkRepro2.tar.gz)

**Comment by kruncher** [comment]
I am experiencing the symlink issue whilst using TypeScript with `gulp-typescript`.

I tried following the following advise from the readme of this project:
```
npm install typescript@next
...
Or in combination with a tsconfig file:

var tsProject = ts.createProject('tsconfig.json', {
    typescript: require('typescript')
});
```

However the issue still persists and I am not entirely sure whether `gulp-typescript` is using the latest development build or the older one that still exhibits this issue.

Many thanks

**Comment by ivogabe** [comment]
@kruncher symlinks were not supported yet when you wrote that, that was what this issue was tracking. You can now try the latest version, which should support them.
