### ISSUE TITLE
In some cases, `file.sourceMap.file` and `file.relative` do not match, preventing SourceMaps from working

### ISSUE THREAD

**Issue by jvilk** [ivogabe/gulp-typescript#351]
**Scenario:** Running `gulp-typescript` followed by `gulp-uglify` with sourcemaps enabled on the file `src/index.ts` with no `baseDir` or `outDir` specified.

**Issue:** SourceMaps refer to compiled JavaScript, not to TypeScript source files.

**Underlying issue:**

When `baseDir` and `outDir` are not specified, TypeScript may remove directories from output files. For example, `src/index.ts` may be compiled as `index.js`.

When this occurs, gulp-typescript emits a sourcemap for the (virtual) file `src/index.js` (as it does a simple extension substitution on the input filename), but emits the (virtual) file `index.js`. As a result, plugins further down the chain do not properly merge their sourcemaps with TypeScript's source map.

**Solution:**

Always explicitly set `sourceMap.file` to the virtual file name that TypeScript uses.

**Workaround:**

Properly set `baseDir` and `outDir` explicitly so that these two virtual filenames align.

**Comment by ivogabe** [comment]
Thanks for reporting! Given that you have done some good debugging, could you create a pull request?

**Comment by electricessence** [comment]
++

**Comment by jvilk** [comment]
I gave up on fixing the problem, but anyone who works on this should feel free to use the tests I defined in the closed PR above.

**Comment by ivogabe** [comment]
This should be fixed in version 3.0, since the path generating has been rewritten and should now match the specification of gulp-sourcemaps.
