### ISSUE TITLE
No output in case of watch

### ISSUE THREAD

**Issue by imperugo** [ivogabe/gulp-typescript#361]
**Expected behavior:**
Hi, I'm compiling my TS project using `gulp-typescript` and it works fine. Every time I start the gulp project I've my output without any issue.
The problem happens when I use the same task with `gulp-watch`.

**Actual behavior:**
Everytime I change any `.ts` file the `gulp.watch` runs the typescript compilation task and, looking the output,everything seems to be ok.
Here the console output after the watch

```console
[10:21:45] Starting 'typescript:serve'...
[10:21:45] Finished 'typescript:serve' after 940 μs
```

The problem is related to the output. Nothing changes in my destination folder, it seems gulp-typescript compiles in memory and it doesn't copy the files (or doesn't compile and says the opposite).

To be more accurate, the `gulp-typescript` task is the same I run when I start my application and in this case it works perfectly.

Here my gulp task:

```javascript

// define some compiler options https://www.npmjs.com/package/gulp-typescript
let tsOptions = {
    outDir: ".tmp/node/",
    noImplicitAny: true,
    target: "es6",
    experimentalDecorators: true,
    sourceMap: true,
    removeComments: true,
    declaration: false, // generate typescript definitions
    module: "commonjs" // possible values ["AMD", "commonjs", "UMD", "system"]
};

let tsFiles = [
    "typings/index.d.ts",
    "typings/globals/**/*.d.ts",
    "typings/modules/**/*.d.ts",
    path.join(conf.paths.src, '/node/**/*.ts')
];

gulp.task("typescript:serve", () => {
    let tsResult = source
        .pipe(ts(tsOptions));

    let result = tsResult
        .js
        .pipe(gulp.dest(path.join(conf.paths.tmp, "/node")));

    return result;
});

gulp.task('watch:serve', ['nodemon:serve'], () => {
    let srcFolder = path.join(conf.paths.src, "/**/*.ts");

    gulp.watch(srcFolder, ['typescript:serve']);
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "experimentalDecorators": true,
        "sourceMap": true,
        "moduleResolution": "classic",
        "removeComments": true,
        "outDir": ".tmp/node/"
    },
    "exclude": [
        "postman",
        "node_modules",
        "build",
        ".vscode",
		"dist",
		".tmp"
    ],
    "filesGlob": [
        "typings/**/*.ts",
		"src/**/*.ts"
    ],
    "atom": {
        "rewriteTsconfig": false
    }
}

```

Just a note about my gulp structure (maybe it could be helpful to investigate the problem).
All my tasks are placed into a gulp directory and are loaded using `wrench`.
Here the code

```javascript
wrench.readdirSyncRecursive('./gulp').filter(function(file) {
    return (/\.(js|coffee)$/i).test(file);
}).map(function(file) {
    require('./gulp/' + file);
});
```

Any hint?

**Comment by ivogabe** [comment]
Where did you define `source`?

**Comment by imperugo** [comment]
Sorry I forgot it.
Here the code

```javascript
let source = gulp.src(tsFiles);
```

**Comment by ivogabe** [comment]
Did you define that outside of the task? If so, that doesn't work, you cannot reuse a stream in different runs. You should move that code to inside the task.

**Comment by imperugo** [comment]
Yeah, you got it.
That was the problem.

Thanks so much!
