### ISSUE TITLE
Pass the sourceMap flag to the tsc in order to get the same result.

### ISSUE THREAD

**Issue by electricessence** [ivogabe/gulp-typescript#364]
If you don't do this, `gulp-typescript` does not render the same `*.js.map` contents when paired with `gulp-sourcemaps` and therefore if ever used in conjunction with `tsc.exe` the maps will differ and generate unnecessary and confusing git commits where there may have been zero code changes but hundreds of files (`*.js.map`) have changed.

**Comment by ivogabe** [comment]
That happens [here](https://github.com/ivogabe/gulp-typescript/blob/c0a743fc68edf3e03f1d9485366fe22faa7de0f8/lib/main.ts#L178). Is there something else that needs to be set?

**Comment by electricessence** [comment]
Ok so your documenation even says not to set .sourceMap=true in the config and to use the gulp-sourcemaps plug-in.  Am I missing something here?  Because when I:
```typescript
import * as typescript from "gulp-typescript";

function getOptions(
	destination:string,
	target:EcmaTarget,
	module:ModuleType,
	declaration:boolean):IMap<any>
{
	return {
//		tscPath: PATH.TSC,
		outDir: destination,
		noImplicitAny: true,
		module: module,
		target: target,
		removeComments: true,
		sourceMap: true,
		declaration: !!declaration,
		noEmitHelpers: true
	}
}

export function fromTo(
	from:string,
	to:string,
	target:EcmaTarget,
	module:ModuleType,
	declaration?:boolean):Promise<void>
{
	return gulp
		.src([from + '/**/*.ts'])
		.pipe(typescript(getOptions(to, target, module, declaration)))
		.pipe(gulp.dest(to))
}
```

The above does not produce source maps!

**Comment by electricessence** [comment]
https://github.com/electricessence/TypeScript.NET/blob/master/gulp/tsc.ts

Here is my actual source code.  Keep in mind that I use gulp-tsc in the function above because I have to and I changed it here to test passing the sourceMap flag.  It did not render any source maps.

If I use gulp-sourcemaps, the results don't match the tsc.exe flag.

**Comment by ivogabe** [comment]
`gulp-sourcemaps` lacks in the example code that you mentioned, it should be:
```typescript
import * as typescript from "gulp-typescript";
import * as sourcemaps from "gulp-sourcemaps";

function getOptions(
    destination:string,
    target:EcmaTarget,
    module:ModuleType,
    declaration:boolean):IMap<any>
{
    return {
//      tscPath: PATH.TSC,
        outDir: destination,
        noImplicitAny: true,
        module: module,
        target: target,
        removeComments: true,
        declaration: !!declaration,
        noEmitHelpers: true
    }
}

export function fromTo(
    from:string,
    to:string,
    target:EcmaTarget,
    module:ModuleType,
    declaration?:boolean):Promise<void>
{
    return gulp
        .src([from + '/**/*.ts'])
        .pipe(sourcemaps.init())
        .pipe(typescript(getOptions(to, target, module, declaration)))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(to))
}
```
The source maps should then be generated. To get them working in a browser, you might need to set the `sourceRoot` option in `sourcemaps.write`. I also removed `sourceMap: true` in your code, since that is not required.

**Comment by electricessence** [comment]
:| I posted the actual source.  The sample I showed you shows my attempt to trigger the tsc to render the sourcemaps.

I'll say this again: ***tsc.exe --sourceMap (or using tsconfig.json) DOES NOT render the same result as gulp-sourcemaps***

That is why I'm asking you to please ***re-enable*** the ability.
The code you've provided is not alien me, I already have this block of code attempting to do this, ***and it is broken.***

**Comment by electricessence** [comment]
AGAIN: Because the results are not the same, if I have to use gulp-typescript to render my files with source maps or if the tsc renders them the resultant files ***are not the same*** and end up flip-flopping git checkins for all my ```*.js.map``` files.

**Comment by electricessence** [comment]
There is NO reason that you should block config options like --sourceMap since these options change over time.  Just let them pass through so if a new option is introduced it still does it.

If people want to purely use 'gulp-sourcemaps' with 'gulp-typescript', let them...  But don't enforce it.
Or find a way to make the output the same.

**Comment by electricessence** [comment]
Ok so back to this problem...
Without anything but ```sourceMap:true``` TSC renders source-maps that look like this:
```json
{"version":3,"file":"extends.js","sourceRoot":"","sources":["extends.ts"],"names":[],"mappings":"AAAA;;;GAGG;;;;;;;;;;IAEH,mBAAwB,CAAK,EAAE,CAAK;QAEnC,GAAG,CAAA,CAAC,IAAM,CAAC,IAAI,CAAC,CAAC;YAAC,EAAE,CAAA,CAAC,CAAC,CAAC,cAAc,CAAC,CAAC,CAAC,CAAC;gBAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC;QACtD,gBAAgB,IAAI,CAAC,WAAW,GAAG,CAAC,CAAC,CAAC,CAAC;QAGvC,CAAC,CAAC,SAAS,GAAG,CAAC,KAAG,IAAI;cACnB,MAAM,CAAC,MAAM,CAAC,CAAC,CAAC;cAChB,CAAC,EAAE,CAAC,SAAS,GAAG,CAAC,CAAC,SAAS,EAAE,IAAU,EAAG,EAAE,CAAC,CAAC;IAClD,CAAC;IATD;+BASC,CAAA"}
```
But gulp-sourcemaps renders it like this:
```json
{"version":3,"sources":["extends.ts"],"names":[],"mappings":"AAAA;;;GAGG;;;;;;;;;;IAEH,mBAAwB,CAAK,EAAE,CAAK;QAEnC,GAAG,CAAA,CAAC,IAAM,CAAC,IAAI,CAAC,CAAC;YAAC,EAAE,CAAA,CAAC,CAAC,CAAC,cAAc,CAAC,CAAC,CAAC,CAAC;gBAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC;QACtD,gBAAgB,IAAI,CAAC,WAAW,GAAG,CAAC,CAAC,CAAC,CAAC;QAGvC,CAAC,CAAC,SAAS,GAAG,CAAC,KAAG,IAAI;cACnB,MAAM,CAAC,MAAM,CAAC,CAAC,CAAC;cAChB,CAAC,EAAE,CAAC,SAAS,GAAG,CAAC,CAAC,SAAS,EAAE,IAAU,EAAG,EAAE,CAAC,CAAC;IAClD,CAAC;IATD;+BASC,CAAA","file":"extends.js","sourceRoot":""}
```

You should notice that the placement of some of the parameters is not in the same order.
Which as I mentioned, will cause the map to appear 'changed' even though it hasn't.
Also, the paths to files will be different for sub folders.

**Comment by ivogabe** [comment]
It might be possible to change the ordering, but I need to take a look at that. I'm not sure whether gulp-sourcemaps or gulp-typescript defines that.

I think that the paths of files in subdirectories are correct, as per the [gulp-sourcemaps docs](https://github.com/floridoo/gulp-sourcemaps#plugin-developers-only-how-to-add-source-map-support-to-plugins). You might be able to use their `mapSources` option to correct these paths.

**Comment by electricessence** [comment]
You do notice that there are quite a few options that do not match?  And what you don't see here is that the relative referencing to any source file is all wonky.  I've dealt with this for 2 years and gave up on gulp-typescript because of it.

I can get done what I want mostly now, but if I want the code to look like the tsc with a tsconfig I have to use gulp-tsc.

**Comment by ivogabe** [comment]
What options do you mean exactly? Almost all compiler options are directly passed to TypeScript. I hope to take a look at the source map paths next week. Have you had luck with `mapSources` of gulp-sourcemaps?

**Comment by jeremyjh** [comment]
I'm also struggling with this exact issue. I guess I expect that if I pass a `tsconfig.json` to `gulp-typescript` via createProject, that it would use those settings when it invokes tsc. But it does not generate sourcemaps as configured in `tsconfig.json`. To get sourcemaps I have to resort to gulp-sourcemaps and like @electricessence has pointed out, the generated maps do not match the ones created by typescripts. This breaks me because my editor is using tsc directly to regenerate files as I work, so I'll end up with some files formatted by one source or the other and Chrome can't handle it.

**Comment by ivogabe** [comment]
I did some testing today and the current behavior of gulp-typescript matches with gulp-sourcemaps. The paths of source maps can be easily configured by setting the sourceRoot property of gulp-sourcemaps. I clarified this in the readme and uploaded some examples in https://github.com/ivogabe/gulp-typescript-sourcemaps-demo.
