### ISSUE TITLE
Apparently declarations don't work at all...

### ISSUE THREAD

**Issue by electricessence** [ivogabe/gulp-typescript#365]
https://github.com/electricessence/TypeScript.NET/blob/master/gulp/tsc.ts#L141-L148

If I change my code from using gulp-tsc to gulp-typescript I get no declaration files even when I set the module type to "none".

**Comment by ivogabe** [comment]
It looks that you ignore the `.dts` stream, see the second example [here](https://github.com/ivogabe/gulp-typescript#basic-usage).

**Comment by electricessence** [comment]
Whoa.. Ok... This is new to me.  I will check it out.

**Comment by electricessence** [comment]
I have to say that this approach is not only more confusing but requires another dependency. ```merge2``` :-1:

**Comment by ivogabe** [comment]
If you need to run another plugin after gulp-typescript, like minifying or bundling, you really need two separate streams. These plugins should not run on the definition files. And most users use gulp because it's easy to add multiple plugins. Though I'm thinking to return a full stream, with all files. Then `.js` contains the javascript files and `.dts` the definition files. Then you would have three streams. See #163

**Comment by electricessence** [comment]
Okay and on top of that... Your ```gulp-typescript``` declarations say:
```declarationFiles``` instead of ```declarations``` :(

**Comment by ivogabe** [comment]
`declarationFiles` was the old name but it's still supported. `declarations` is the official name.

**Comment by electricessence** [comment]
Ok so I'm slowly narrowing this down.  Admittedly, I'm quite frustrated how convoluted this all is.
I am continually struggling making no progress.

Can you please provide a sample that includes:

- ES6 with modules
- SourceMaps
- And declarations

**Comment by electricessence** [comment]
Ok... So this is what i have and so far is the closest result I've been able to get instead of using tsc:
```typescript
var tsResult = gulp.src(source)
	.pipe(sourcemaps.init())
	.pipe(typescript(options));

if(options.declaration || options.declarationFiles)
{
	return merge(
		[
			tsResult.dts,
			tsResult.js
				.pipe(sourcemaps.write('.', sourceMapOptions))
		])
		.pipe(gulp.dest(to));
}

return tsResult
	.pipe(gulp.dest(to));
```

**Comment by electricessence** [comment]
Ok so my final solution is this:
https://github.com/electricessence/TypeScript.NET/blob/master/gulp/TypeScriptRenderer.ts

I'm finally able to get all my dist files to work as I need them to.  Thank you.
Still having issues with sourcemaps not matching.  But I'll be fine for now.
