### ISSUE TITLE
Support for new baseUrl and path

### ISSUE THREAD

**Issue by born2net** [ivogabe/gulp-typescript#366]
getting this error:

```
error TS5023: Unknown compiler option 'baseUrl'.
error TS5023: Unknown compiler option 'paths'.
```

via config

```
var gulp = require('gulp');
var typescript = require('gulp-typescript');
var tsProject = typescript.createProject('tsconfig.json');
```

as this lib uses 1.8 and yet seems like more and more people now use typescript@next as it is the requirement for Angular 2

I recommend we move the project away from ts 1.8 and into @next

regards

Sean

**Comment by ivogabe** [comment]
You can already use typescript@next, see https://github.com/ivogabe/gulp-typescript#typescript-version

**Comment by born2net** [comment]
tx but I meant as default lib since this lib is part of a distribution bundle and so it created a conflict for users installing my open source app

regards

**Comment by ivogabe** [comment]
I cannot do that, as a lot of users want to use a stable release. That's why I made it configurable. So you can configure your project with a nightly build.

**Comment by born2net** [comment]
can I configure my package.json to pull the nightly build?

**Comment by ivogabe** [comment]
Yes, just do `npm install typescript@next --save-dev` and it will be added to your package.json file. Don't forget to update your gulpfile and you can use the latest features of TypeScript.

**Comment by JeroenNelen** [comment]
@ivogabe not sure if this is the right place, but I have installed typescript 2.0.3 in my project and am trying to run it as follows:
`return tsProject.src()
        .pipe(ts(tsProject))
        .pipe(gulp.dest('build'));`

With the tsconfig.json, in which I use some new compiler options: 
`"skipLibCheck": true, 
        "typeRoots": ["node_modules/@types"], 
        "strictNullChecks": true`

however gulp throws errors:
error TS5023: Unknown compiler option 'skipLibCheck'.
error TS5023: Unknown compiler option 'typeRoots'.
error TS5023: Unknown compiler option 'strictNullChecks'.

Am I overlooking something?

kind regards,
