### ISSUE TITLE
allow comment line to certain functions

### ISSUE THREAD

**Issue by ajithr** [ivogabe/gulp-typescript#369]
I have set removeComments as true in my config file. So it will remove all comment lines from typescript to javascript file. I need to allow certain comment line for some functions and other need to be removed.

```
// allow comment
/* istanbul ignore if  */
if (condition) {
}
// remove comment
```

is there any option available in gulp-typescript for this scenario?

**Comment by ivogabe** [comment]
At the moment there is not such option. I cannot add such option if it is not supported in TypeScript, so you should open a request there. But it might be easier to turn `removeComments` off.
