### ISSUE TITLE
Rest parameters are not translated

### ISSUE THREAD

**Issue by kwypchlo** [ivogabe/gulp-typescript#370]
**Expected behavior:**
`buildPath: (...args) => args.join('/')`
rest parametrs are translated to something like this:
```
buildPath: function () {
                var args = [];
                for (var _i = 0; _i < arguments.length; _i++) {
                    args[_i - 0] = arguments[_i];
                }
                return args.join('/');
            }
```
**Actual behavior:**
`buildPath: (...args) => args.join('/')`
is translated to
```buildPath: function(args) {
return args.join('/');
}```


**Your gulpfile:**
```
var tsConfig = {   allowJs: true,   out: 'scripts.js',   target: 'ES5',   module: 'system' }
```

**Comment by ivogabe** [comment]
I cannot reproduce that, but it looks like a problem with your configuration. Can you send your whole gulpfile, and tsconfig.json file, if present?

**Comment by kwypchlo** [comment]
Well, tsc compiles the file correctly. Strange thing that only the rest parameters are not compiled in my job, everything else seems fine.

```
'use strict';

var gulp = require('gulp');
var config = require('../../config/gulp-config.js');
var ts = require('gulp-typescript');

function compileEs() {
    var tsConfig = { allowJs: true, out: 'scripts.js', target: 'ES5', module: 'system' };

    return gulp.src(config.compileEs.src)
            .pipe(ts(tsConfig)).on('error', config.errorHandler('ts'))
            .pipe(gulp.dest(config.compileEs.dest));
}

gulp.task('compile-es', function () {
    return compileEs();
});
```

**Comment by kwypchlo** [comment]
Ok I think I got it @ivogabe 

Try it out:

```javascript
/**
 * @param {string<Array>} args
 */
function test1(...args) {
  return args;
}

/**
 * @param {string[]} args
 */
function test2(...args) {
  return args;
}

/**
 * @param {string} args
 */
function test3(...args) {
  return args;
}
```

These get translated to this:
```javascript
/**
 * @param {string<Array>} args
 */
function test1() {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i - 0] = arguments[_i];
    }
    return args;
}
/**
 * @param {string[]} args
 */
function test2(args) {
    return args;
}
/**
 * @param {string} args
 */
function test3(args) {
    return args;
}
```

What really happened is comments are taken into consideration.
On ts playground https://www.typescriptlang.org/play/ they are not.

I believe this is a bug and should be fixed right?

**Comment by ivogabe** [comment]
Thanks for the example code, I could reproduce it. It also appears to happen with `tsc`, version 1.8.10. That's the default version in gulp-typescript. I've tested it with a nightly build, and it is already fixed there. So this is a bug of TypeScript, which has been fixed but not released in a stable release. You can install the nightly build using `npm install typescript@next --save-dev` and [configure gulp-typescript](https://github.com/ivogabe/gulp-typescript#typescript-version) for it.

**Comment by kwypchlo** [comment]
Well that's extremely cool @ivogabe, sorry I didn't catch that myself. I tested the file with the tsc compiler but it must have been some other version than 1.8.10 (which is strange btw because I updated it just before the test).

Thanks!
