### ISSUE TITLE
Add support for the glob-style pattern matching in TypeScript 2.0

### ISSUE THREAD

**Issue by glen-84** [ivogabe/gulp-typescript#375]
See https://github.com/Microsoft/TypeScript/pull/5980 and https://github.com/Microsoft/TypeScript/pull/8841

**Comment by szimek** [comment]
Now that TypeScript 2.0 beta version is released, maybe it could be possible to release beta version of gulp-typescript?

**Comment by ivogabe** [comment]
@szimek You can already use the beta of TypeScript (see [readme](https://github.com/ivogabe/gulp-typescript#typescript-version)), only globs are not supported yet.

**Comment by ivogabe** [comment]
This should be working in gulp-typescript 2.14 and 3.0

**Comment by glen-84** [comment]
Awesome! Thanks. =)
