### ISSUE TITLE
tsProject.src() throws errors (gulp.src() doesn't) when using tsconfig.json without "exclude node_modules" section

### ISSUE THREAD

**Issue by kimbaudi** [ivogabe/gulp-typescript#377]
**Expected behavior:**

I expected `tsProject.src()` and `gulp.src()` to compile .ts files without throwing a bunch of syntax errors from `node_modules` when using `tsconfig.json` without adding "exclude node_modules" section in `tsconfig.json`.

**Actual behavior:**

`tsProject.src()` throws a bunch of syntax errors from `node_modules` (i.e., .d.ts error TS1005: '=' expected, ';' expected). However, `gulp.src()` works fine. The only way to get `tsProject.src()` to work is to add "exclude node_modules" section to `tsconfig.json`. I can leave it out when using `gulp.src()`. Why is that? 

**Your gulpfile:**

```javascript
var tsProject = ts.createProject('tsconfig.json');

gulp.task('script', function () {
    var tsResult = tsProject // tsProject throws errors, but gulp doesn't 
        .src(['wwwroot/app/**/*.ts', 'typings/index.d.ts'])
        .pipe(ts(tsProject));

    return tsResult
        .js
        .pipe(gulp.dest('release'));
});
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}
```

> Note: I have to add the following in `tsconfig.json` when using `tsProject.src()`, but I can leave it out when using `gulp.src()`

````json
,
  "exclude": [
    "node_modules"
  ]
```` 

**Question**

- Why does `tsProject.src()` throw errors (while `gulp.src()` doesn't) when "exclude" isn't added to `tsconfig.json`?
- What is the difference between using `tsProject.src()` and `gulp.src()` for `tsconfig.json`?
- Why does the [Using tsconfig.json][1] section suggest using tsProject.src() instead of gulp.src()?

```javascript
gulp.task('scripts', function() {
    var tsResult = tsProject.src() // instead of gulp.src(...) 
        .pipe(ts(tsProject));
 
    return tsResult.js.pipe(gulp.dest('release'));
});
```
[1]: https://www.npmjs.com/package/gulp-typescript#using-tsconfigjson

**Comment by kimbaudi** [comment]
My gulpfile passes `['wwwroot/app/**/*.ts', 'typings/index.d.ts']` to `tsProject.src()`

```javascript
gulp.task('script', function () {
    var tsResult = tsProject // does not only compile .ts files under wwwroot/apps... compiles everything 
        .src(['wwwroot/app/**/*.ts', 'typings/index.d.ts'])
        .pipe(ts(tsProject));
```
Although my `tsconfig.json` file doesn't exclude `node_modules`, I was expecting **gulp-typescript** to only compile .ts files under _wwwroot/app_ directory as well as _typings/index.t.ts_ when I call `tsProject.src()` and pass in the argument `['wwwroot/app/**/*.ts', 'typings/index.d.ts']`.

So does that mean I shouldn't pass any arguments when I use `tsProject.src()`? And only pass arguments when I use `gulp.src()`?

It seems that **gulp-typescript** will use `tsconfig.json` as long as you pipe tsProject (i.e., `.pipe(ts(tsProject))`). It really doesn't matter whether I use `tsProject.src()` or `gulp.src()` for using `tsconfig.json`.

The only thing that matters when using `tsProject.src` or `gulp.src` is specifying the location for compiling .ts files (unless I add "exclude" to my `tsconfig.json`).

**Comment by shershen08** [comment]
When switcing to using tsconfig with I get also strange errors like this:
```
error TS5023: Unknown compiler option '_readableState'.
error TS5023: Unknown compiler option 'readable'.
error TS5023: Unknown compiler option 'domain'.
error TS5023: Unknown compiler option '_events'.
error TS5023: Unknown compiler option '_eventsCount'.
error TS5023: Unknown compiler option '_maxListeners'.
error TS5023: Unknown compiler option '_writableState'.
error TS5023: Unknown compiler option 'writable'.
error TS5023: Unknown compiler option 'allowHalfOpen'.
error TS5023: Unknown compiler option '_transformState'.
error TS5023: Unknown compiler option '_destroyed'.
error TS5023: Unknown compiler option '_transform'.
```
which where not there when I used inline config

my gulp config looks like this
```
var APP_BUILD = './dist';
var tsProject = ts.createProject('tsconfig.json');

gulp.task('ts', function () {
    var tsFiles = ['./src/js/**/*.ts', 'typings/**/*.d.ts'];
    var tsResult = tsProject.src(tsFiles) 

    return tsResult
        .pipe(ts(tsResult))
        .pipe(gulp.dest(APP_BUILD));
```

**Comment by ivogabe** [comment]
Your configuration is invalid, you're effectively using the stream of files as the compiler options. You should write this:
```javascript
gulp.task('ts', function () {
    return tsProject.src()
        .pipe(tsProject())
        .pipe(gulp.dest(APP_BUILD));
```
Also note that `tsProject.src` does not take an argument. If you want to specify a glob instead of resolving files based on your `tsconfig.json` file, you can use `gulp.src(tsFiles)`.

**Comment by shershen08** [comment]
Thank you for your fast answer!
I've fixed the incorrect file stream usage, but now I have this in the gulpfile.js
```
var APP_BUILD = './dist';
var tsProject = ts.createProject('./tsconfig.json'); // I've also tried without './'

gulp.task('ts', function () {
    return tsProject.src()
        .pipe(tsProject())
        .pipe(gulp.dest(APP_BUILD));
```
but this still gives me ``` TypeError: tsProject is not a function ```

my tsconfig.json is
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noImplicitUseStrict": true,
    "preserveConstEnums": true,
    "noImplicitAny":false,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "other-ts-goodies"
  ],
  "include" : ["./src/js/**/*.ts", "typings/**/*.d.ts"],
  "compileOnSave": true
}
```

**Comment by ivogabe** [comment]
Then you're probably using an older version (`2.*`). In the version 2, you needed to write `ts(tsProject)`, which has been replaced by `tsProject()` in version 3.

**Comment by shershen08** [comment]
Yay! I've updated the TS version to 2.x and then the plugin to 3.x and it started working.

**Comment by shershen08** [comment]
One last thing - what is the correct equivalent of specifying the single output file ?
When I used gulp config I did this:
```
.pipe(typescript({
        out: 'myOutputFile.js',
```

But trying similar with tsconfig.json doesn't work:
```
    return tsProject.src()
        .pipe(tsProject())
        .pipe(ts({out: 'charting.js'}))
```
I also tried to up the out property in tsconfig.json, that didn't work either. What I get is smth like

```
...
[16:59:55] TypeScript: 2 semantic errors
[16:59:55] TypeScript: emit failed
error TS6054: File .../base/dataService.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
...several lines like this...
[16:59:56] TypeScript: 9 options errors
[16:59:56] TypeScript: emit succeeded (with errors)
```
So it basically converts all the .ts files into .js but doesn't 'build' then into one resulting .js file.

**Comment by ivogabe** [comment]
You should set the option in your tsconfig file or you can set it like this: `var tsProject = ts.createProject('tsconfig.json', { out: 'charting.js' });`. In your second code block, you're compiling your code twice, which causes that you're passing the compiled JavaScript to the compiler. You should still add `.pipe(gulp.dest('dist'))` to write the file to the disk.

`out` has been replaced by `outFile`; the first option will still work, but it is advised to use `outFile` from now on.

**Comment by grofit** [comment]
I still get this with latest TS (2.3.2) and gulp-typescript (3.1.6):

### gulp stuff
```js
var tsProject = ts.createProject("tsconfig.json", { module: module, declaration: withTypings || false });

    var tsResult = gulp.src([paths.source])
        .pipe(ts(tsProject()));
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "removeComments": true,
    "target": "es5",
    "moduleResolution": "node",
    "lib": ["es2016"]
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by ivogabe** [comment]
@grofit Your probably passing files to the compiler which should not be compiled. These files can be included because they are a part of `paths.source` or because they are (indirectly) referenced by some other files. TypeScript resolves imported files and `@types` automatically but that's hard to say without seeing the project. Though I think that your behaviour is correct.

**Comment by grofit** [comment]
Yeah I appreciate its not easy to diagnose without all the info, if it helps my source bit is:
```
module.exports = {
  source: "src/**/*.ts",
  output: "dist"
};
```

So it should only be including *.ts files from within the src directory, and I have checked and there is nothing but *.ts files in there, however one file in there `index.ts` just contains a list of re-exports and no actual logic of any kind, not sure if that would cause any issues?

**Comment by ivogabe** [comment]
@grofit Which files give errors? Are those in `node_modules/@types`?

**Comment by grofit** [comment]
It doesnt provide a filename just:

```
[08:05:33] Starting 'build-common'...
error TS5023: Unknown compiler option '_readableState'.
error TS5023: Unknown compiler option 'readable'.
error TS5023: Unknown compiler option 'domain'.
error TS5023: Unknown compiler option '_events'.
error TS5023: Unknown compiler option '_eventsCount'.
error TS5023: Unknown compiler option '_maxListeners'.
error TS5023: Unknown compiler option '_writableState'.
error TS5023: Unknown compiler option 'writable'.
error TS5023: Unknown compiler option 'allowHalfOpen'.
error TS5023: Unknown compiler option 'js'.
error TS5023: Unknown compiler option 'dts'.
error TS5024: Compiler option 'project' requires a value of type string.
```

I also have `node_modules` ignored in my tsconfig (well in the exclude bit)

**Comment by ivogabe** [comment]
Oh, that's a different problem. You're passing a stream of files (namely `tsProject()`) to gulp-typescript when you write `ts(tsProject())`. The `ts` function expects an object with compiler options, not a stream. You should use `.pipe(tsProject())` instead of `.pipe(ts(tsProject()))`.

**Comment by grofit** [comment]
AMAZING! thanks for clearing that up!
