### ISSUE TITLE
Expose defaultFinishHandler?

### ISSUE THREAD

**Issue by lumaxis** [ivogabe/gulp-typescript#380]
I'm currently trying to write my own reporter to use `node-notifier` to post a native OS notification if a build fails.
My code looks like this:

```javascript
function notifyError() {
  return {
    error: (error) => {
      gutil.log(error.message);
      notifier.notify({
        title: 'TypeScript Build Failed',
        message: error.message,
        sound: true
      });
    },
    finish: undefined
  };
}
```

and I'm calling it like so:

```javascript
.pipe(ts(tsProject, undefined, notifyError()));
```

Generally, everything works but I think I would like to use the `defaultFinishHandler` as my `finish:` function too but that doesn't appear to be possible as it is not exported.
Is this something you would consider changing or maybe do you have other solution ideas? Thanks!

**Comment by ivogabe** [comment]
I think that you could use something like `finish: ts.reporter.defaultReporter().finish()`. You could also listen for errors using `.on('error', () => { ... })`. Does one of these work for you?

**Comment by lumaxis** [comment]
Ha, `finish: ts.reporter.defaultReporter().finish` (without the `()`) works! 🙂

**Comment by ivogabe** [comment]
Great!
