### ISSUE TITLE
Relative "virtual" module resolution ('rootDirs') error discrepancy against "tsc" compilation

### ISSUE THREAD

**Issue by tmeneau** [ivogabe/gulp-typescript#381]
**Description**

Attempting to compile a project with `tsconfig.json` compilerOptions including [virtual directories configured with the `rootDirs` option](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#virtual-directories-with-rootdirs) throws semantic errors through the `gulp-typescript` plugin that do not occur through the `tsc` native compiler. I've created a simple project in an attempt to isolate and demonstrate the discrepancies in behavior [here](https://github.com/tmeneau/gulp-typescript-rootdirs-example).

As indicated in the example project:

1. I'm not clear on whether the issue has to do with my usage of the gulp-typescript plugin, how gulp-typescript consumes the typescript API or an issue with the typescript API itself. I did do enough digging to notice that the `rootDirs` configuration makes it to the [typescript.createProgram call](https://github.com/ivogabe/gulp-typescript/blob/master/lib/compiler.ts#L98), but honestly haven't had a chance to look much deeper than that.

2. I'm relatively new to Typescript, so please forgive me if I'm misusing the gulp-typescript plugin or have an improper tsconfig.json configuration.

Can you shed any light on this discrepancy?

**Expected Behavior**

Compilations through the `gulp-typescript` plugin should reflect identical module resolutions as the `tsc` native compiler with regards to `rootDirs` configured "virtual directories".

**Actual behavior:**

Compilations through the `gulp-typescript` raise errors due to module resolution issues that are not exhibited during `tsc` native compilations.

**Example:**

Please see the example project [here](https://github.com/tmeneau/gulp-typescript-rootdirs-example)

By the way: thanks for the fantastic plugin and for excellent documentation. Both have made working with Typescript through gulp very easy and clean!

**Comment by ivogabe** [comment]
Can you try to upgrade to gulp-typescript 3.0? That version was made for TypeScript 2.0, so your issue might be solved in that version. If that's not the case, let me know and I'll take a proper look at it.

**Comment by tmeneau** [comment]
You're right, the behavior is resolved by upgrading to gulp-typescript 3.0! Thanks @ivogabe!
