### ISSUE TITLE
Error: Cannot find module './typescript/dev'

### ISSUE THREAD

**Issue by jdanyow** [ivogabe/gulp-typescript#383]
**Expected behavior:**

A developer can fork gulp-typescript and execute `gulp`.

**Actual behavior:**

Something is missing in the `typescript\dev`, `typescript\1-4`, `typescript\1-5`, etc directories.

<details>
![details](http://i.imgur.com/5WOUPTG.jpg)
</details>

What do I need to put in those directories?

Thanks for putting this plugin together!

**Comment by ivogabe** [comment]
You must install the git submodules, I guess that's something like `git submodule update --init`. Did that work?

**Comment by ivogabe** [comment]
Might be an idea to add that to the readme.

**Comment by jdanyow** [comment]
By the way, I'm forking because my projects use `typescript@next` so I end up with conflicting versions of typescript installed in my node_modules/typescript and node_modules/gulp-typescript/node_modules/typescript folders which causes a bunch of compiler issues.  I was hoping to create a fork that uses typescript@next, and switches to a peerDependency to resolve this but I'm definitely open to other ideas.  The tsconfig's exclude property doesn't seem to work because of my gulp files that `import * as ts from 'gulp-typescript';` which supersedes `exclude: ['node_modules/gulp-typescript']`

**Comment by jdanyow** [comment]
@ivogabe `git submodule update --init` worked! thanks!

there were some failing tests but could be because I'm on windows.

**Comment by ivogabe** [comment]
You don't need to fork gulp-typescript to use a nightly of TypeScript. The readme describes how you can use a different version of TypeScript.
