### ISSUE TITLE
is there any compress flag

### ISSUE THREAD

**Issue by insetCoad** [ivogabe/gulp-typescript#386]
i want a file with source map and another with no source map and minified . 

but the issu is if i use
`  uglify = require("gulp-uglify")` 
its removing the source map link from the js file .

so is their any way to compress generated js file with the source map ??

**Comment by ivogabe** [comment]
You must use `gulp-sourcemaps` to get source maps. Something like this should work:

```javascript
var gulp = require('gulp');
var typescript = require('gulp-typescript');
var sourcemaps = require('gulp-sourcemaps');
var uglify = require('gulp-uglify');

var tsProject = typescript.createProject(...);

gulp.task('compile', function() {
	return gulp.src('lib/**/*.ts')
		.pipe(sourcemaps.init())
		.pipe(typescript(tsProject))
		.pipe(sourcemaps.write('.'))
		.pipe(gulp.dest('dist/dev'));
});
gulp.task('release', ['compile'], function() {
	return gulp.src('dist/dev/**/*.js')
		.pipe(uglify())
		.pipe(gulp.dest('dist/release'));
});
```
With this configuration, `dist/dev` will contain the unminified file with source maps and `dist/release` the minified file.
