### ISSUE TITLE
tsProject.src() is too slow

### ISSUE THREAD

**Issue by KnisterPeter** [ivogabe/gulp-typescript#390]
Hi,

I have a test project within [paeckchen](https://github.com/paeckchen/paeckchen) which shows the usage with gulp-typescript.
While setting up a watch task I've discovered that it is very slow to use tsProject.src() instead of gulp.src(...).

Maybe thats because of caluclating the base path? But why is it so much slower than gulp with that task?

**Comment by ivogabe** [comment]
See #326, which is blocked by [glob-stream#24](https://github.com/gulpjs/glob-stream/issues/24). It's probably necessary to not use globs with `gulp.src` to resolve all files.

**Comment by m3kka** [comment]
And it was concat!
Performance issues solved on my side. Thank you for the lead!

**Comment by ivogabe** [comment]
#326 has been fixed in the latest release.
