### ISSUE TITLE
Cannot find module angular in gulp-typescript but tsc compiles.

### ISSUE THREAD

**Issue by sergiomichels** [ivogabe/gulp-typescript#393]
**The attempt**:
I'm breaking my components in npm packages, and using the node module resolution, so my typescript components will look like

```
'use strict';
import angular = require('angular');
import ng = angular;

class MyDirective implements ng.Directive { ... }

```

I can compile with success these structures with tsc, but gulp-typescript fails to load the module.

**Expected behavior:**
Compile typescript files with the same behavior of `tsc` command.

**Actual behavior:**

> src\main.ts(1,26): error TS2307: Cannot find module 'angular'.
> [15:13:32] TypeScript: 2 semantic errors
> [15:13:32] TypeScript: emit succeeded (with errors)

I uploaded the sample project in Github so we can see if I'm missing something or this should work as expected.

https://github.com/sergiomichels/gulp-typescript-module

**Comment by pablorsk** [comment]
Just need add this line to `index.ts`
```javascript
/// <reference path="../typings/index.d.ts" />
```

I'm trying make a library too, but I have problem with gulp-typescript. If you like test... #394 

Also, if you need a example making typescript libraries, you can check [this repository](https://github.com/pablorsk/typescript-import-es6-module)

**Comment by ivogabe** [comment]
You use `gulp.src('./src/*.ts')` and thus do not include the typings files; these files are not passed to the compiler. When using `gulp.src(['./src/*.ts', './typings/**/*.d.ts'])` these files are included and you will not get these errors.
