### ISSUE TITLE
gulp-typescript make .d.ts file with references and without interfaces

### ISSUE THREAD

**Issue by pablorsk** [ivogabe/gulp-typescript#394]
**Expected behavior:**
I expect a declaration file with interfaces and classes like:

```javascript
export interface IAnimal {
    name: string;
    move(steps: number): boolean;
}
export declare class Dog implements IAnimal {
    name: string;
    move(steps: number): boolean;
}
```

**Actual behavior:**

But I obtain this:

```javascript
import * as interf from '../interfaces/animal';
export declare class Dog implements interf.IAnimal {
    name: string;
    move(steps: number): boolean;
}
```

**gulpfile.js**

```javascript
gulp.task('compile', function () {
	var tsProjectDts = ts.createProject('tsconfig.json', { sortOutput: true });
	var tsResult = gulp.src('src/**.ts')
		.pipe(ts(tsProjectDts));
	tsResult.dts
		// .pipe(concat('index.d.ts'))
		.pipe(gulp.dest('dist'));
});
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "removeComments": false,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "noImplicitAny": false,
        "module": "commonjs",
        "target": "ES5",
        "experimentalDecorators": true,
        "sourceMap": false,
        "declaration": true,
        "noResolve": false,
        "moduleResolution":"node",
        "outDir": ".tmp"
    },
    "filesGob": [
        "src/**/*.ts",
        "!typings/**",
        "!node_modules/**"
    ]
}
```

## All of this on a simple example

You can check all of this here [**gulp-typescript-example-declaration**](https://github.com/pablorsk/gulp-typescript-example-declaration)

I trying to make a library with respective .d.ts file. #393  #385

**Comment by ivogabe** [comment]
This is the correct behavior of TypeScript, and I cannot change that in gulp-typescript. Though the generated declaration file can be used when you publish it on NPM, you can set the `typings` property of the `package.json` file. If you can't find it, I can post the link later on.

**Comment by pablorsk** [comment]
Thanks @ivogabe, I don't have problem with NPM, just with generated .d.ts file. 

It would be better if the `import` is eliminated and replaced by the code of imported file. Any way for do this?

**Comment by ivogabe** [comment]
No, that's not possible with TypeScript and thus also not in gulp-typescript.
