### ISSUE TITLE
SourceMap's sourceRoot appears incorrect

### ISSUE THREAD

**Issue by MeirionHughes** [ivogabe/gulp-typescript#395]
I'm having trouble with getting sourcemaps to set the correct sourceRoot for files in sub-folders. 

**Given**
`./source/folder/foo.ts`

**Expected behavior:**
`./dist/folder/foo.map` with "../../source"

**Actual behavior:**
`./dist/folder/foo.map` with "../source"

**gulpfile:**
```js
gulp.task('compile:typescript', ['clean:typescript'], function () {
    var project = ts.createProject('tsconfig.json', {
        typescript: require('typescript')
    });

    var tsResult = gulp
        .src(['source/**/*.ts'
        ])
        .pipe(sourcemap.init())
        .pipe(ts(project));

    return merge([
        tsResult.dts.pipe(gulp.dest("dist")),
        tsResult.js
            .pipe(sourcemap.write('.', { sourceRoot: '../source'}))
            .pipe(gulp.dest("dist"))
    ]);
});
```

**tsconfig**
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",        
        "sourceMap": true,
        "noEmitOnError": true,
        "newLine": "LF",
        "declaration": true       
    },
    "exclude": [
      "node_modules"
    ]
}
```

**versions**
```
"gulp-sourcemaps": "^1.6.0",
"gulp-typescript": "^2.13.6",
"typescript": "^2.0.0"
```

Apparently according to this: https://github.com/floridoo/gulp-sourcemaps#write-options (Relative Path) it should correctly set the relative path.

**Comment by MeirionHughes** [comment]
**Workaround:**
```js
.pipe(sourcemap.write('.', {
  sourceRoot: function (file) {
    var relative = path.relative(file.path, path.join(__dirname, "source"));
    var relativeSource = path.join(relative, 'source')
    return relativeSource;
  }
}))
```

**Comment by ivogabe** [comment]
Can you update to gulp-typescript 3.0? Source map generation has been revised there, so your issue might have been fixed. Let me know whether that version works correctly for you.

**Comment by MeirionHughes** [comment]
looks like its even more broken: 
```
  gulp.src(['src/**/*spec.ts', "node_modules/@types/**/index.d.ts"])
    .pipe(sourcemap.init())
    .pipe(tsProject());

  return tsResult.js
    .pipe(sourcemap.write("."))
    .pipe(gulp.dest("spec/"));
```

ALL map files have: 

"sourceRoot":"/source/"

**Comment by ivogabe** [comment]
I did some testing, and the behaviour of gulp-typescript seems to be correct. When you use gulp-sourcemaps without any plugins, all files will have `"sourceRoot": "/source/"`.

If there is some file in a subdirectory of `source`, say `source/a/b.ts`, the source map will have `"sourceRoot": "/source/"` and `"sources": ["a/b.ts"]`. You get the same result when you use gulp-sourcemaps without any plugins, so the behaviour of gulp-typescript 3.0 is correct.

**Comment by MeirionHughes** [comment]
hmm, very odd... I don't even have a "source/" folder. its `src/`

**Comment by ivogabe** [comment]
That appears to be the default value of `sourceRoot`, you can set it manually to `src`:
```javascript
.pipe(sourcemap.write('.', { sourceRoot: "src" }))
```

**Comment by MeirionHughes** [comment]
sorry, yes... brain fart. Unfortunately, that still results the initial issue as described above.

expected behavour:  https://github.com/floridoo/gulp-sourcemaps#write-options
> ```
> gulp.task('javascript', function() {
>   var stream = gulp.src('src/**/*.js')
>     .pipe(sourcemaps.init())
>       .pipe(plugin1())
>       .pipe(plugin2())
>     .pipe(sourcemaps.write('.', {includeContent: false, sourceRoot: '../src'}))
>     .pipe(gulp.dest('dist'));
> });
> ```
> 
> In this case for a file written to dist/subdir/example.js, the source map is written to dist/subdir/example.js.map and the sourceRoot will be ../../src (resulting in the full source path ../../src/subdir/example.js).

**Comment by ivogabe** [comment]
I guess that the documentation is for version 2.0.0-alpha, whereas `npm install gulp-sourcemaps` will install the latest stable release (1.6). So the readme documents a different version, and the handling of the `sourceRoot` might have changed in 2.0.0-alpha.
