### ISSUE TITLE
inlineSources in tsconfig causes TypeScript: emit failed

### ISSUE THREAD

**Issue by fuocor** [ivogabe/gulp-typescript#396]
I'm using the following:
    "typescript":  "^1.8.10" 
    "gulp-typescript": "^2.13.6",

-- gulp task
var tsProject = ts.createProject('src/tsconfig.json', { typescript: typescript });
gulp.task('ts', function (done) {
    //var tsResult = tsProject.src()
    var tsResult = gulp.src([
            "src/*.ts"
    ])
        .pipe(ts(tsProject), undefined, ts.reporter.fullReporter());
    return tsResult.js.pipe(gulp.dest('./wwwroot/dist'));
});

--tsconfig

{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noEmit": false,
    "noImplicitAny": true,
    "outDir": "../wwwroot/",
    "inlineSourceMap": true,
    "target": "es5",
    "inlineSources": true,
    "allowJs": false
  },
  "angularCompilerOptions": {
    "genDir": "./generated",
    "debug": true
  },
  "exclude": [
    "node_modules",
    "typings/index",
    "typings/index.d.ts"
  ]
}

From the commandline tsc works fine

**Comment by ivogabe** [comment]
You should use `gulp-sourcemaps` for source maps generation. You should pass all source map related options to `gulp-sourcemaps` instead, see their documentation. Marking this a bug, since you shouldn't see 'emit failed'.

**Comment by akrivitzky** [comment]
+1 on the bug.  I spent hours trying to figure out why my project wouldn't work with gulp.  Thanks for the issue post.  I would have never found it otherwise.  Definitely, should say something more than "Typescript: emit failed"
