### ISSUE TITLE
incremental compilation optimisation

### ISSUE THREAD

**Issue by SET001** [ivogabe/gulp-typescript#401]
Currently my gulp task looks like this:

```
var tsConfig = require('./tsconfig.json').compilerOptions;
gulp.task('typescript', function(){
	return gulp.src([
			'typings/index.d.ts',
			'client/app/**/*.ts',
			'server/**/*.ts',
			'index.ts',
		], { base: "."})
		.pipe(ts(tsConfig))
		.pipe(debug({title: 'typescript'}))
		.pipe(gulp.dest('.'))
});
```

It takes about 1.52 s for first run and then about 740ms for each next run. I'd like to optimize this process a bit and to compile only files that was changed since last task run (also because I'm using `nodemon` which will restart my server as many times as there were changes and since this task would update each file, then nodemon will restart the application as many times as I have .ts files in my project):

```
var tsConfig = require('./tsconfig.json').compilerOptions;
gulp.task('typescript', function(){
	return gulp.src([
			'typings/index.d.ts',
			'client/app/**/*.ts',
			'server/**/*.ts',
			'index.ts',
		], { base: ".", since(gulp.lastRun('typescript'))})
		.pipe(ts(tsConfig))
		.pipe(debug({title: 'typescript'}))
		.pipe(gulp.dest('.'))
});
```

But then I'll loose my typings beacause they never changin and I'll get multiple typescript compilation errors. How can I solve this?

Also it said:

> 
Instead of calling ts(options), you can create a project first, and then call ts(project) ... When you run gulp watch, the source will be compiled as usual. Then, when you make a change and save the file, your TypeScript files will be compiled in about half the time.

but when I do use project: 

```
var tsProject = ts.createProject('tsconfig.json');
gulp.task('typescript', function(){
	return gulp.src([
			'typings/index.d.ts',
			'client/app/**/*.ts',
			'server/**/*.ts',
			'index.ts',
		], { base: "."})
		.pipe(ts(tsProject))
		.pipe(debug({title: 'typescript'}))
		.pipe(gulp.dest('.'))
});
```

I still have about 1.5s for first run and 740ms for each next. The only difference after using project is that when saving file without making any changes to it - then it takes about 30ms to finish this task. But this does not make much sense, because I want it to compile on change ) What am I missing and how can I optimize incremental compilation process?

**Comment by SET001** [comment]
the `tsconfig.json` file I'm using:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```

**Comment by SET001** [comment]
Also here is my configuration: 

gulp: 4.0.0-alpha.2
gulp-typescript: 2.13.6
tsc: 2.0.0

**Comment by SET001** [comment]
found the solution of how to use it with `since`:

```
const tsConfig = require('./tsconfig.json').compilerOptions;

gulp.task('typescript', function(){
	const typings = gulp.src('typings/index.d.ts');
	const sources = gulp.src([
			'{client,server}/**/*.ts',
			'index.ts',
		], { base: ".", since: gulp.lastRun('typescript')});

	return merge(typings, sources)
		.pipe(ts(tsConfig))
		.pipe(debug({title: 'typescript'}))
		.pipe(gulp.dest('.'))
});
```

the speed changes is barely visible - it is about 600-700ms but I think the difference would be more visible when project became larger

**Comment by ivogabe** [comment]
The problem is that it is not safe to recompile only the changed files. To compile a file, type information of all files is needed and a change in one file can affect the types in other files. So an unchanged file can produce different errors. When you're using `const enum`, you can even get a different JavaScript file.

For faster compilation you can use the `isolatedModules` option. That will stop type analysis, but will transpile your files almost instantly. But you will have to rely on an IDE to get type errors. See also #392.

**Comment by yesman85** [comment]
I wanted to leave a note here for future reference as I ran in this problem today.

My project is about 1150 files with around 250k lines and compilation takes about a full minute.

I wrote a simpler solution to watch changed files and compile just those files:

```
var tsWatchProject = ts.createProject('./tsconfig.watch.json',
    {
        typescript: require('typescript')
    });

gulp.task('typescript-watch',
    function()
    {
        gulp.watch('./**/*.ts')
            .on('change',
                function(file)
                {
                    gulp.src([file.path])
                        .pipe(plumber())
                        .pipe(debug({
                                title: 'compiling '
                            }))
                        .pipe(tsWatchProject())
                        .pipe(gulp.dest('./'))
                        .pipe(print(function(filepath)
                        {
                            return 'compiled ' + filepath;
                        }));
                });
    });
```

where the `tsconfig.watch.json` contains the setting `isolatedModules: true`.
