### ISSUE TITLE
File preprocess with external resolve

### ISSUE THREAD

**Issue by andr2** [ivogabe/gulp-typescript#403]
I want to use preprocess library with gulp-typescript with external resolve.

There is `Host.getSourceFile` function in `host.js`. How can I override `fs.readFileSync` to bypass file-contents through `preprocess` lib?

Or maybe I should use a different approach?

**Comment by ivogabe** [comment]
You cannot integrate it in gulp-typescript in `Host.getSourceFile`. You could however pipe these files through another plugin by opening those files with `gulp.src`. If you cannot write a glob for these files you would benefit from https://github.com/ivogabe/gulp-typescript/issues/190#issuecomment-134703348.
