### ISSUE TITLE
Compile error using declarations: true

### ISSUE THREAD

**Issue by Anjmao** [ivogabe/gulp-typescript#404]
I use declaration: true in my tsconfig to generate d.ts files which I will be using for clients who is using my library. Currently this is not working and I getting a lot of errors, but if I run command tsc it compiles just fine.
**Expected behavior:**
I expect gulp-typescript to work exactly the same as running tsc command from console if I use tsProject.
**Actual behavior:**
Getting error TS2300: Duplicate identifier.
**Your gulpfile:**
```js
var tsProject = ts.createProject('tsconfig.json');
gulp.task('compile', function () {
    var tsResult = tsProject.src()
        .pipe(ts(tsProject));
    return tsResult.js.pipe(gulp.dest('src'));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": true
    },
    "exclude": [
        ".grunt",
        ".vscode",
        "coverage",
        "dist",
        "misc",
        "node_modules",
        "templates"
    ]
}
```

**Comment by Anjmao** [comment]
Ok I figured out how to fix this. I needed to exclude generated d.ts files
```json
"exclude": [
        ...,
       "src/**/*.d.ts
    ]
```

**Comment by ivogabe** [comment]
It appears that TypeScript removes declaration files (`.d.ts`) from the compilation if a source file (`.ts`) exists in the same directory, whereas gulp-typescript does include these files. So this is a bug of the implementation in gulp-typescript.

**Comment by ivogabe** [comment]
As of ff163bfc1571e458f5d8e8a68c5a49c3869de123, gulp-typescript will use the TypeScript api to resolve the files, so gulp-typescript will now behave exactly the same. This case should be working as expected too (in the next release).

**Comment by ivogabe** [comment]
Oops, I was referring to 98eca4ab34cb02e54589e40e9871cda59dce36cb.

**Comment by jtlapp** [comment]
Will this fix correct the problem wherein declaration files are not being written (by any task) under the following circumstances, or am I just doing something wrong?

gulpfile.js:
```
"use strict";

let gulp = require('gulp');
let ts = require("gulp-typescript")
let tsconfig = require("./tsconfig");

gulp.task("watch", () => {
    gulp.watch('src/**/*.ts', ["build"]);
});

gulp.task("build", [
    'build-source',
    'build-demo'
]);

gulp.task("build-source", () => {
    console.log("building src/")
    return gulp.src(['src/**/*.ts'])
    .pipe(ts(tsconfig.compilerOptions)).js
    .pipe(gulp.dest('build/src'))
})

gulp.task("build-demo", () => {
    console.log("building demo/")
    return gulp.src(['demo/**/*.ts'])
    .pipe(ts(tsconfig.compilerOptions)).js
    .pipe(gulp.dest('build/demo'))
})

gulp.task("default", ["watch"]);
```

tsconfig.js:
```
{
    "compilerOptions": {
        "target": "es2016",
        "module": "commonjs",
        "lib": [ "es2016" ],
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "noUnusedLocals": true,
        "outDir": "build",
        "declaration": true,
        "declarationDir": "build/types"
    }
}
```

Everything else builds fine. Thanks!

**Comment by ivogabe** [comment]
You have `.js` in your gulpfile, which gives a stream with only JS files. If you remove that it should work just fine.
