### ISSUE TITLE
No default excludes when using tsconfig.json

### ISSUE THREAD

**Issue by ulrichb** [ivogabe/gulp-typescript#406]
TypeScript has default exclusions (`node_modules`, `bower_components`, `jspm_packages`) if there is no `exclude`-array in the `tsconfig.json`. See [commandLineParser.ts, line 849-868](https://github.com/Microsoft/TypeScript/blob/2305c685607f274992b12ac6a0dc5224b0667e89/src/compiler/commandLineParser.ts#L849-L868).

This works fine with `tsc.exe --project tsconfig.json`.

When using gulp-typescript with `ts.createProject("tsconfig.json")`, I manually have to add e.g. `node_modules` because these default exclusions don't seem to apply.

Using newest gulp-typescript 2.13.6.

**Comment by martin31821** [comment]
I'm experiencing a similar issue, but for me, adding node_modules under `exclude` in `tsconfig.json` doesn't prevent the excluded directories from being compiled.
My tsconfig.json:
```json
{
    "compilerOptions":
    {
        "module": "amd",
        "target": "es2015",
        "noImplicitAny": true,
        "sourceMap": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "outFile": "emm.js"
    },
    "exclude":
    [
        "node_modules"
    ]
}
```

The relevant part of gulpfile.js:
```js
var ts = require("gulp-typescript");
var tsconfig = ts.createProject("tsconfig.json");
gulp.task("tscompile", function () {
    var src = gulp.src(files);
    return src.pipe(ts(tsconfig)).pipe(gulp.dest(destination));
});
```

I'm using Typescript 2.0.3 and gulp-typescript 2.13.6.
I think the behaviour is different for specific typescript versions (?)

**Comment by martin31821** [comment]
Update: 

gulp-typescript brings typescript 1.8.10 as dependency, therefore it will be used instead of the 2.0 version, as supposed by node module resolution rules.

The solution is to add the following piece of code to gulpfile.js:
```js
var typescriptCompiler = require("typescript");

var tsconfig = {
    ...,
    typescript: typescriptCompiler
};

//....
source.pipe(ts(tsconfig))
//...
```

This is most likely not a bug with gulp-typescript itself, as it passes the correct filenames to typescript. It's just using the wrong version.

**Comment by ivogabe** [comment]
Previously, gulp-typescript did not use the TypeScript api to resolve the files of your tsconfig file. As of ff163bfc1571e458f5d8e8a68c5a49c3869de123, gulp-typescript will use the TypeScript api to resolve the files, so gulp-typescript will now behave exactly the same. This case should be working as expected too (in the next release).

**Comment by ivogabe** [comment]
Oops, I was referring to 98eca4ab34cb02e54589e40e9871cda59dce36cb.
