### ISSUE TITLE
Support custom module resolution

### ISSUE THREAD

**Issue by kbrandwijk** [ivogabe/gulp-typescript#407]
I have a usecase where I want to customize module resolution (using `CompilerHost.resolveModuleNames()`) as described [here](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#customizing-module-resolution).

I cannot find any information how to implement this using gulp-typescript. Is this scenario supported?

**Comment by ivogabe** [comment]
That's not (yet) supported in gulp-typescript. However, TypeScript is working on extensibility (also on different areas). So I'd want to see how that is integrated with `tsconfig.json` for instance and then we can use the same design in gulp-typescript.
