### ISSUE TITLE
when will this project be updated to ts 2.0?

### ISSUE THREAD

**Issue by born2net** [ivogabe/gulp-typescript#408]
when will this project be updated to ts 2.0?
TypeScript 2.0 is now the standard so please change in package.json

tx

Sean

**Comment by born2net** [comment]
I am wondering what's the hold up as 2.0 is in major release
regards

**Comment by ivogabe** [comment]
You can already use TS2.0, as you can see in the [readme](https://github.com/ivogabe/gulp-typescript#typescript-version). gulp-typescript still defaults to 1.8 since that's the latest stable release.

**Comment by born2net** [comment]
yes I am aware of that, but I distribute npm packages which ship with TypeScript 2.0, and customers of my projects are getting errors becuase of the peer dependency. 
Here is one of my projects (500+ stars)
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

so sure, I could do it manually for me, but need to take care of customers.
TS 2.0 is a stable release.

Regards,

Sean

**Comment by ivogabe** [comment]
The latest release of 2.0 is a release candidate, `npm install typescript` still defaults to 1.8.10. Why are your users getting errors? Is that just because they didn't configure their project for 2.0?

**Comment by born2net** [comment]
they are getting errors as we are using 2.0 features and during install this lib will compile via 1.8

**Comment by ivogabe** [comment]
But these errors goes away when they install a different version, right?
```
npm install typescript@rc
```
```javascript
var tsProject = ts.createProject('tsconfig.json', { typescript: require('typescript') });
```
I will update gulp-typescript when the stable release of TypeScript 2.0 (probably a few weeks/days) is ready.

**Comment by born2net** [comment]
yes errors go away with 2.0
tx

**Comment by born2net** [comment]
according to ts github, ts 2.0 is already final, see package.json 
https://github.com/Microsoft/TypeScript/blob/master/package.json
or install via npm (no beta)

**Comment by ivogabe** [comment]
No, the master branch on GitHub contains the development of TS2.1 (which you can install with `npm install typescript@next`) but that is not a stable release. The development of TS2.0 is in a different branch and not yet released in a stable release, but I expect that it will be soon. `npm install typescript` does still install 1.8

**Comment by born2net** [comment]
ok tx

**Comment by born2net** [comment]
now it's official: https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/
