### ISSUE TITLE
gulp.watch hangs on syntax error

### ISSUE THREAD

**Issue by weastmann** [ivogabe/gulp-typescript#409]
I recently created a new project with gulp-typescript, and I'm noticing that gulp.watch will hang and not register any more changes when there is a syntax error in a '.ts' file. I've created a minimal project that demonstrates my issue.

```
wfd57-hpab:gulptypescript_debug4 h.pabst$ gulp watch
[16:50:36] Using gulpfile ~/Documents/gulptypescript_debug4/gulpfile.js
[16:50:36] Starting 'watch'...
[16:50:36] Finished 'watch' after 156 ms
[16:50:39] Starting 'compile'...
[16:50:39] Finished 'compile' after 86 ms
[16:50:40] Starting 'compile'...
src/Main.ts(4,3): error TS1109: Expression expected.
```

## Folder structure
<img width="185" alt="screen shot 2016-09-16 at 6 22 44 pm" src="https://cloud.githubusercontent.com/assets/479507/18602837/9e94d38c-7c3a-11e6-948c-15a24fe169a9.png">

## Main.ts with syntax error
```typescript
export default function x() {
    return 0;+ //syntax error
}
```

## gulpfile.js

```javascript
var gulp = require("gulp");
var ts = require("gulp-typescript");

var tsProject = ts.createProject("tsconfig.json", {
    typescript: require("typescript")
});

gulp.task("compile", function() {
    return tsProject.src()
    .pipe(ts(tsProject))
    .js
    .pipe(gulp.dest("./.build/"));
});

gulp.task("watch", function() {
    gulp.watch("**/*.ts", ["compile"]);
});
```

## package.json
```json
{
  "name": "gulptypescript_debug4",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-typescript": "^2.13.6",
    "typescript": "^1.8.10"
  }
}
```

## tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": true,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "noImplicitUseStrict": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [
        "node_modules",
        "typings/browser",
        "typings/browser.d.ts"
    ],
    "filesGlob": [
        "./**/*.ts",
        "./**/*.tsx",
        "!./node_modules/**/*.ts"
    ],
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": true
    },
    "files": [
        "./src/Main.ts"
    ]
}
```
--
If I change my gulpfile to catch the error and end the stream, then the task does not hang, and seems to complete successfully:
```javascript
gulp.task("compile", function() {
    return tsProject.src()
    .on("error", function(){ this.end(); }) //check for error and emit end
    .pipe(ts(tsProject))
    .js
    .pipe(gulp.dest("./.build/"));
});
```

If I keep the above change, then I observe some odd behavior:

1) Remove syntax error from Main.ts and save.
2) start 'gulp watch'
3) Add syntax error to Main.ts and save. Yields:
```
[18:05:34] Starting 'compile'...
src/Main.ts(3,1): error TS1109: Expression expected.
[18:05:34] TypeScript: 1 error
[18:05:34] TypeScript: emit succeeded (with errors)
[18:05:34] Finished 'compile' after 19 ms
```

4) Save the file again with the same syntax error. Yields:
```
[18:14:40] Starting 'compile'...
/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/gulp-typescript/release/compiler.js:169
  for (var _i = 0, diagnostics_2 = diagnostics_1; _i < diagnostics_2.length; _
                                                                    ^
TypeError: Cannot read property 'length' of undefined
    at FileCompiler.inputFile (/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/gulp-typescript/release/compiler.js:169:79)
    at CompileStream._write (/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/gulp-typescript/release/main.js:47:31)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at CompileStream.Writable.write (_stream_writable.js:217:11)
    at DestroyableTransform.ondata (/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at DestroyableTransform.emit (events.js:107:17)
    at readableAddChunk (/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at DestroyableTransform.Readable.push (/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at DestroyableTransform.Transform.push (/Users/h.pabst/Documents/gulptypescript_debug4/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:32)
```
And gulp terminates.

--

Additionally the following behavior occurs:

1) Remove syntax error from Main.ts and save.
2) start 'gulp watch'
3) Add syntax error to Main.ts and save. Yields a syntax error, and the task completes.
4) Change the syntax error to a different one (in this case from "+" to "-") and save. Yields a syntax error, and the task completes. 
5) Replace the new syntax error with the old one and save. Yields a syntax error and the task completes.

You can repeat steps 4 and 5 indefinitely, but anytime the same syntax error is made and saved then the 'compiler.js' error occurs and gulp terminates. No issues occur when saving the file with no syntax errors. 

Any idea what's going on here?

**Comment by ivogabe** [comment]
Because of the syntax error, an error is emitted on the stream. NodeJS wil then break the pipeline of the streams, which means that when the compilation finishes, the finish-event is not passed to `gulp.dest`. Normally you wouldn't notice this since it does (somehow) work when used synchronously, but when you enable the `isolatedModules` option compilation happens file-by-file, which runs asynchronously. Because of this, you have to use `gulp-plumber` when you enable the `isolatedModules` option. This gulp plugin will patch the `pipe` method and prevents that the pipeline breaks. See their documentation for how it works.

**Comment by weastmann** [comment]
Awesome thanks, that works.
