### ISSUE TITLE
How to use tsconfig.rb and reporter?

### ISSUE THREAD

**Issue by urbanmichal** [ivogabe/gulp-typescript#410]
Hi,

I'm trying to call:

var tsProject = ts.createProject( './tsconfig.json', { noEmitOnError: false, suppressImplicitAnyIndexErrors: false }, ts.reporter.longReporter() );

or 

var tsProject = ts.createProject( './tsconfig.json', { noEmitOnError: false, suppressImplicitAnyIndexErrors: false }, "longReporter" );

but any typescript errors aren't shown (reporter isn't working).

**Comment by ivogabe** [comment]
You should pass the reporter as the third argument in `ts()`, like `.pipe(ts(tsProject, undefined, ts.reporter.longReporter()))`.

**Comment by urbanmichal** [comment]
Thanks, works!
Serdecznie pozdrawiam,
Michał Urban | +48 665 990 004 | urban.michal@icloud.com

W dniu 20 wrz 2016 o godz. 14:52 użytkownik Ivo Gabe de Wolff <notifications@github.com> napisał(a):

You should pass the reporter as the third argument in ts(), like .pipe(ts(tsProject, undefined, ts.reporter.longReporter())).
