### ISSUE TITLE
Support skipLibCheck option

### ISSUE THREAD

**Issue by rsauget** [ivogabe/gulp-typescript#412]
**Expected behavior:**
gulp-typescript recognizes option "skipLibCheck" in tsconfig file

**Actual behavior:**
error TS5023: Unknown compiler option 'skipLibCheck'.

**Your gulpfile:**
```javascript
gulp.task('compile', [], function () {
    // TypeScript compile
    return gulp.src(['./Pages/**/*.ts', './typings/index.d.ts'])
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject))
        .js
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('./Scripts/App'));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noEmitOnError": false,
    "noImplicitAny": false,
    "outDir": "./Scripts/App",
    "skipLibCheck": true
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```

**Code**

```typescript
not relevant
```

**Comment by ivogabe** [comment]
`skipLibCheck` is only supported when you use TypeScript 2.0 or later. Gulp-typescript uses the latest stable release of TypeScript, at the moment 1.8. Install a nightly or prerelease version and configure it (see readme) and it should be working.
