### ISSUE TITLE
Version 3 filtering files

### ISSUE THREAD

**Issue by tbuffryslb** [ivogabe/gulp-typescript#415]
**Expected behavior:**
Do not compile node_modules/*.ts

> gulp.src seems not taken into account, 
> tsconfig "exclude" neither 

**Actual behavior:**
Compile node_modules/*.ts

**Your gulpfile:**
var tsProject = ts.createProject('tsconfig.json');
gulp.task('Compile', function(){

   return gulp.src(['app/**/*.ts', 'server/**/_.ts', '!__/_.d.ts', '!node_modules/**'])
    .pipe( tsProject(ts.reporter.longReporter()) )
    .pipe(gulp.dest('build/'))
});

_Include your gulpfile, or only the related task (with `ts.createProject`)._

``` javascript

```

**tsconfig.json**
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "watch": false
    },
    "exclude": [
        "node_modules",
        "typings/main",
        "typings/modules/_",
        "typings/modules/express/index.d.ts",
        "typings/main.d.ts",
        "d.ts"
    ]
}
*Include your tsconfig, if related to this issue._

``` json

```

**Code**

_Include your TypeScript code, if necessary._

``` typescript

```

**Comment by ivogabe** [comment]
These files will be added if they are referenced by some other file, see the [TypeScript FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler). I suspect that you got the same behavior in version 2, can you verify that?

**Comment by tbuffryslb** [comment]
version 2.4.1 produce the same output indeed, version 2.0.0 is not but giving more "not found" modules.
then i will look to let typescript compile the file if he wants, and filter the outputs with a reporter ..
