### ISSUE TITLE
typescript 2.0 @type types not being loaded

### ISSUE THREAD

**Issue by mrohr** [ivogabe/gulp-typescript#422]
when using typescript 2.0 @type definitions from npm, gulp-typescript is failing to recognize types in the node_module @type directories.  I've created a demo repo here that shows the problem:

https://github.com/mrohr/gulp-typescript-2.0-types-demo

when running `tsc` the index.ts compiles fine, but running `gulp` will result in this error:
`src/index.ts(1,11): error TS2304: Cannot find name '$'.`

**Comment by gilamran** [comment]
The command line (tsc) is loading ALL the @types folder automatically without asking you...
gulp-typescript doesn't, try to use `import`

**Comment by ivogabe** [comment]
I'll take a look at this issue this weekend.

**Comment by anderspitman** [comment]
@gilamran using `import` isn't working for me. If I have

```javascript
import * as fs from 'fs';
```

it doesn't work even after doing `npm install @types/node`

**Comment by MeirionHughes** [comment]
my workaround if anyone needs it: 

```
gulp.src([
  paths.source + '**/*.ts', 
  "node_modules/@types/**/index.d.ts",
  "!node_modules/@types/**/node_modules/**/*.d.ts"])
.pipe(ts(project));
```
