### ISSUE TITLE
support for Typescript 2.0 --strictNullChecks

### ISSUE THREAD

**Issue by Hadev-JHH** [ivogabe/gulp-typescript#424]
**Expected behavior:**
support for --strictNullChecks compile option

**Comment by ivogabe** [comment]
`--strictNullChecks` is already supported when you're using the latest release of TypeScript. Make sure you're using the latest versions of TypeScript and gulp-typescript.

**Comment by Hadev-JHH** [comment]
turns out i was mistakenly still running against 1.8
