### ISSUE TITLE
gulp-typescript compiles only the given files and not the imported modules

### ISSUE THREAD

**Issue by gilamran** [ivogabe/gulp-typescript#425]
**Expected behavior:**
Should (Like tsc) compile all the modules tree.

**Actual behavior:**
Compiles only the given (root) file

**Code**
[https://github.com/gilamran/gulp-typescript-test](Example project to demostrate the issue)

**gulpfile:**
```javascript
const gulp = require('gulp');
const gulp_typescript = require('gulp-typescript');

gulp.task('default', () => {
  const tsProject = gulp_typescript.createProject('tsconfig.json');

  const tsResult = tsProject.src()
    .pipe(tsProject());

  return tsResult.js.pipe(gulp.dest('dist'));
});
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "module": "commonjs",
    "target": "es5"
  },
  "files": [
    "./src/main.ts"
  ]
}
```

**Comment by ivogabe** [comment]
This is by design. As a gulp plugin, it transforms the input files. See #190 for a suggestion to resolve referenced files.
