### ISSUE TITLE
"jsx" option not recognized when reading tsconfig.json

### ISSUE THREAD

**Issue by cnshenj** [ivogabe/gulp-typescript#428]
**Expected behavior:** "jsx" option recognized

**Actual behavior:** "jsx" option not recognized

**Your gulpfile:**
*Include your gulpfile, or only the related task (with `ts.createProject`).*
```
gulp.task("ts", function () {
    var project = ts.createProject("./tsconfig.json");
    project.src()
        .pipe(project())
        .pipe(gulp.dest("."))
        .pipe(livereload());
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```
{
    "compilerOptions": {
        "jsx": "react",
        "module": "commonjs",
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "sourceMap": true
    }
}
```

**Comment by ivogabe** [comment]
The `tsx` option works fine here, can you provide some more information?

**Comment by cnshenj** [comment]
I'll reopen if I can repro it.
