### ISSUE TITLE
gulp-typescript 3.x substantially slower than tsc

### ISSUE THREAD

**Issue by GrzegorzKaczan** [ivogabe/gulp-typescript#429]
Created new issues as Ivo suggested.

After switching to gulp-typescript 3.0.1 and typescript 2.0.3 we again see substantial performance drop. Compilation time for our project increased from ~8s to ~15s.

We are using lib as proposed in newer version so:
```
var tsResult = gulp.src('lib/*.ts')
        .pipe(tsProject());
```

I've created separate mini project as a test case. It does a compilation on 10000 small `tsx` components. I am on `Ubuntu 16.04`
I can confirm timings when using `tsc` are much faster for this test case as well. So it is not a problem of typescript itself.

libs used | compilation time
------------ | -------------
gulp-typescript@2.14.1, typescript@2.0.3|15s
gulp-typescript@3.0.1, typescript@1.8.10|8s
tsc@2.0.3|5s

Test is available at:
[https://github.com/GrzegorzKaczan/gt-test/archive/master.zip](https://github.com/GrzegorzKaczan/gt-test/archive/master.zip)
`$ npm install`

**Comment by ivogabe** [comment]
I think that this has been fixed with e30444041c5301b579e5dad7d6bb9be2aff2f75b. Can you try version 3.0.2 on your project and see whether your compilation times are similar to the times of tsc?
