### ISSUE TITLE
strictNullChecks flag not supported?

### ISSUE THREAD

**Issue by bolatovumar** [ivogabe/gulp-typescript#430]
It looks like strictNullChecks flag not supported. Is there a reason for this?

I don't know how this plugin works, but wouldn't adding support for this flag 
just be a matter of passing it to the TypeScript compiler? 

Am I misunderstanding something?

**Comment by ivogabe** [comment]
You can set that option just like all other options, when you're using the latest version.

**Comment by bolatovumar** [comment]
Ok, looks like the issue was with my npm-shrinkwrap.json. I had TS v1.8.10 specified in the shrinkwrap file while my package.json specified v2.0.3. Shrinkwrap was winning over the pacakage.json and I was using an older version of TS while thinking I was using v2.0.3. As a result I was gettings "unrecognized compiler flag" error.

Updating shrinkwrap file resolved the issue. Closing now.
