### ISSUE TITLE
Add support for rootDirs

### ISSUE THREAD

**Issue by tblaisot** [ivogabe/gulp-typescript#434]
**Expected behavior:**
As part of version 2.0.x typescript now support a [rootDirs option](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#virtual-directories-with-rootdirs) tsconfig.json to virtualy merge folders and  use this virtual folder as rootDir.

**Actual behavior:**
Using gulp-typescript i am unable to use this option as the rootDir option is automatically set by gulp-typescript and override my property.

**gulpfile in /**
```javascript
var tsProject = gtypescript.createProject(tsconfigFilePath);
var tsResult = tsProject.src().pipe(tsProject())
```

**tsconfig.json in /src/test/javascript/**
```json
{
  "compilerOptions": {
    "jsx": "react",
    "target": "es5",
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "declaration": false,
    "module": "commonjs",
    "noEmitHelpers": true,
    "experimentalDecorators": true,
    "outDir": "../../../target/compiled-js",
    "traceResolution": true,
    "rootDirs": [
      "./",
      "../../main/javascript/"
    ],
    "types": [
      "..."
    ]
  },
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Main code in /src/main/javascript/url-utils.ts**
```typescript
// ...
```
**Test code in /src/test/javascript/url-utils-spec.ts**
```typescript
import {UrlUtils} from "./url-utils";
//...
```

**Comment by ivogabe** [comment]
`rootDir` and `rootDirs` are not related, their names only look similar, just like Java and JavaScript. gulp-typescript does set `rootDir` automatically, but you can set it yourself like `"rootDir": "../../"`. I tested it and that should solve your issue.

**Comment by tblaisot** [comment]
Thanks @ivogabe for your solution.
It seems that tsc doesn't need rootDir so I was testing without it but like you said you must set rootDir and rootDirs to be able to use gulp-typescript.
Thanks
