### ISSUE TITLE
Same error emitted twice, number of emit errors is doubled

### ISSUE THREAD

**Issue by feng-xiao** [ivogabe/gulp-typescript#438]
**Expected behavior:**
- same error only emit once

**Actual behavior:**
- same error emit twice. It was working pre-3.0 versions

**Your gulpfile:**
_Include your gulpfile, or only the related task (with `ts.createProject`)._

``` javascript
            tsProject = $.typescript.createProject('tsconfig.json'),
            tsResult = tsProject.src()
                .pipe(tsProject());
```

**tsconfig.json**

_Include your tsconfig, if related to this issue._

``` json
{
    "compilerOptions": {
        "charset": "utf8",
        "emitBOM": true,
        "experimentalDecorators": true,

        "pretty": true,

        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "noImplicitAny": false,

        "noEmitOnError": true,
        "noResolve": false,

        "sourceMap":  true, 

        "target": "es5"
    },
    "files": [
   ]
}
```

**Code**

_Include your TypeScript code, if necessary._

``` typescript

```

**Investigation Results**
I looked at your code. I think the problem happens in **compiler.js**, where function _reportDiagnostics_ is called from _inputDone_ and _emitFile_

**Comment by ivogabe** [comment]
@DanielRosenwasser @mhegazy It appears that `ts.emit(..).diagnostics` contains the pre-emit diagnostics too. Is there any way to get the emit diagnostics only? Or should this be filtered manually?

I use `ts.getPreEmitDiagnostics(program)` to get the pre-emit diagnostics and `ts.emit(file, (fileName, content) => { .. }).diagnostics` to get the emit diagnostics.

**Comment by ivogabe** [comment]
I think that this is not an issue anymore with the latest release of TypeScript. If someone still sees this problem, let me know and I'll reopen.

**Comment by amyhickman** [comment]
This is an issue for me, today.  I am using:

npm: 4.4.4
gulp CLI: 1.2.2
gulp: 3.9.1
typescript: 2.2.2
gulp-typescript: 3.1.6

All typescript errors are doubled, unless I use:

    return tsProject.src()
        .pipe(tsProject(ts.reporter.nullReporter())  <-- no errors at all tho

**Comment by kjin** [comment]
Also an issue for me. Setting `noEmitOnError` to `true` causes every error to be emitted twice, once as the relevant error type (semantic, syntax, etc.) and once as an 'emit' error. Using:

* gulp-typescript: 3.2.1
* typescript: 2.4.2

It would be great if only the first set of errors were emitted (not the 'emit' errors). It might be as simple as modifying the `options.noEmitOnError` branch in `typescript.js::emitWorker` to not return any diagnostics. Though as I'm not very familiar with the code, there might be undesirable side-effects that would surface when a different set of options is specified.
