### ISSUE TITLE
Should use project directory as base for projects

### ISSUE THREAD

**Issue by cnshenj** [ivogabe/gulp-typescript#440]
Directory structure:
```
+-- root
   +-- gulpfile.js
   +-- scripts
        +-- tsconfig.json
        +-- lib
             +-- lib.js
        +-- app
             +-- foo.ts
```
**Expected behavior:**
`foo.js` should be in directory `root/app`
**Actual behavior:**
`foo.js` in directory `root`.

This is because `gulp-typescript` uses `scripts/app` as base (by calling `utils.getCommonBasePathOfArray`), which is wrong. It should use project directory `scripts` as base.
`utils.getCommonBasePathOfArray` produces inconsistent outcome. For example, if I add `bar.ts` under `scripts`, the base is `scripts`; if I delete `bar.ts`, the base is `scripts/app`. It should always be set to project directory, which is `scripts`, thus, it will not change as long as `tsconfig.json` isn't moved.

Note: I don't want to use `rootDir` because TypeScript doc clearly says it should only be used "to control the output directory structure with --outDir."
**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
var project = createProject("scripts/tsconfig.json");
var result = project.src().pipe(project());
result.js.pipe(gulp.dest("scripts"));
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json

```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by ivogabe** [comment]
This is intentional, as this handles the interoperability between gulp and TypeScript. This assures that `gulp.dest(dir)` gives the same results as `--outDir dir` with `tsc` (under normal conditions). You should either set `rootDir` or use `gulp.dest("scripts/app")`.

**Comment by cnshenj** [comment]
It is not consistent with what `tsc` does.

1. Without specifying `outDir`, tsc generates output files based on project directory, not the common parent directory of script files.

2. When specifying `outDir`, tsc uses common parent directory of script files as base directory, or `rootDir` as base directory.

What I'm doing is 1, `gulp-typescript` should detect that no `ourDir` is specified, and just use project directory as base directory, like what `tsc` does. TypeScript doc clearly says 'rootDir' should only be used with `outDir`, which I'm not using.

`gulp.dest("scripts/app")` is not an option because it is not stable. As I explained in OP, merely adding/removing a TS source file in `scripts` folder will suddenly change the output directory structure.

**Comment by ivogabe** [comment]
A lot of people use `tsProject.src().pipe(tsProject()).pipe(gulp.dest('dist'))`, and that should give the same results as `tsc --outDir dist ...`. You could say that `gulp.dest` is the gulp-way of the `outDir` option. That's what I meant with my previous comment. Changing this behaviour would break the configurations of all these people.

If you want a stable solution, and you don't want so set `rootDir`, you could also use `gulp.src('scripts/app/**/*.ts')`. Instead of setting `rootDir` in your tsconfig file, you can also set it in the gulpfile: `var project = createProject("scripts/tsconfig.json", { rootDir: "script" });`.
