### ISSUE TITLE
gulp-babel Sourcemaps not working with TypeScript 2.0 via gulp-typescript

### ISSUE THREAD

**Issue by ijabit** [ivogabe/gulp-typescript#441]
https://github.com/babel/gulp-babel/issues/99

I don't know if this issue is for gulp-typescript or gulp-babel, so I posted it in both :)

You can read the other post, but basically after upgrading gulp-typescript to v3.0.2, it now uses backslashes instead of forward slashes in the sourceMap.file property. So if your file is in a subdirectory, this breaks sourcemaps when processing through another layer which is using vinyl-sourcemaps-apply (like gulp-babel is). I think gulp-babel should handle the backslashes, but I also don't think gulp-typescript should be using backslashes since apparently vinyl-sourcemaps-apply can't handle them. You are the experts, let me know who is in the wrong here. Is it gulp-typescript, gulp-babel, or vinyl-sourcemaps-apply, or all of the above??

**Comment by ijabit** [comment]
Bump

**Comment by ivogabe** [comment]
Sorry, didn't have time to take a look at this earlier. Should be fixed with the referenced commit.

**Comment by ijabit** [comment]
Thanks!
