### ISSUE TITLE
Sourcemaps sourcesContent is null with gulp-typescript v3.0.2 and gulp-sourcemaps

### ISSUE THREAD

**Issue by Seaal** [ivogabe/gulp-typescript#444]
**Expected behavior:**

The `sourcesContent` property of the .js.map has the typescript source in it and the `sources` property has a standard path.

**Actual behavior:**

The following is an example sourcemap. The `sources` has a very strange path and the `sourcesContent` is null.

```javascript
{"version":3,"sources":["dashboard/file:/C:/LocalCode/Highfield-Assessment/src/Highfield.Assessment.Playground/app/dashboard/dashboard.component.ts"],"names":[],"mappings":";;;;;;;;;;AAAA,qBAA0B,eAAe,CAAC,CAAA;AAO1C;IAAA;QACW,iBAAY,GAAY,KAAK,CAAC;QAC9B,eAAU,GAAW,CAAC,CAAC;QAEvB,mBAAc,GAAqB;YACtC,EAAE,IAAI,EAAE,SAAS,EAAE,IAAI,EAAE,EAAE,EAAE;YAC7B,EAAE,IAAI,EAAE,UAAU,EAAE,IAAI,EAAE,EAAE,EAAE;YAC9B,EAAE,IAAI,EAAE,OAAO,EAAE,IAAI,EAAE,EAAE,EAAE;YAC3B,EAAE,IAAI,EAAE,OAAO,EAAE,IAAI,EAAE,GAAG,EAAE;YAC5B,EAAE,IAAI,EAAE,KAAK,EAAE,IAAI,EAAE,EAAE,EAAE;SAC5B,CAAC;QAEK,aAAQ,GAAa;YACxB,KAAK,EAAE,GAAG;YACV,MAAM,EAAE,GAAG;YACX,YAAY,EAAE,EAAE;YAChB,SAAS,EAAE,QAAQ;YACnB,SAAS,EAAE,kBAAkB;YAC7B,WAAW,EAAE,IAAI,CAAC,cAAc;SACnC,CAAC;IACN,CAAC;IAvBD;QAAC,gBAAS,CAAC;YACP,WAAW,EAAE,yCAAyC;SACzD,CAAC;;0BAAA;IAqBF,yBAAC;AAAD,CApBA,AAoBC,IAAA;AApBY,0BAAkB,qBAoB9B,CAAA","file":"dashboard.component.js","sourcesContent":[null],"sourceRoot":"app/"}
```

**Your gulpfile:**

```javascript
var $ = require("gulp-load-plugins")({ lazy: true });
var tsProject = $.typescript.createProject("tsconfig.json");

gulp.task("typescript", ["clean-typescript", "lint-typescript", "typings"], function () {

    log("Compiling typescript and adding them to the output");

    var tsSource = [
        "app/**/*.ts",
        "typings/index.d.ts"
    ];

    return gulp.src(tsSource)
        .pipe($.sourcemaps.init())
        .pipe(tsProject())
        .js
        .pipe($.sourcemaps.write(".", { sourceRoot: "app/" }))
        .pipe(gulp.dest("wwwroot/app/"));

});
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "outDir": "/wwwroot/app/",
    "types": [
      "d3"
    ]
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```
gulp-typescript version: 3.0.2
gulp-sourcemaps version: 2.1.1

I had no issues with sourcemaps with v2.14.1, so this seems to be something that has changed in v3.0.0 or later.

**Comment by ivogabe** [comment]
Can you create a small example that demonstrates this and upload it as a .zip? That would make it easier to debug for me.

**Comment by Seaal** [comment]
Okay, after creating a small example for reproduction, I found the issue myself.

When `outDir` is set in tsconfig then the `sources` path is incorrect and the `sourcesContent` is `null`. I'm not sure if this is intended or not (it doesn't seem like it would be). When `outDir` is not set in tsconfig, the sourcemaps work fine.

The example below shows this, try adding and removing the `outDir` parameter and running `gulp`.

[example.zip](https://github.com/ivogabe/gulp-typescript/files/537067/example.zip)

**Comment by ivogabe** [comment]
Thanks for the example. The problem is that you pass an absolute path as the `outDir`. `tsc` would then write the compiled files to `/dist/app` on Unix or `C:/dist/app` on Windows. Because of that, you get very strange paths in `sources`. On a Mac, the values in `sourcesContent` is correct, I think on Linux too, though on Windows not.

When you set `outDir` to `dist/app`, you should get correct source maps. Can you try that?

**Comment by Seaal** [comment]
Changing to a relative path from an absolute path worked perfectly, `outDir` is set and the sourcemaps now work again.

Thanks for the help :smile:
