### ISSUE TITLE
Filtering doesn't work in tsProject.src() in 3.0.2

### ISSUE THREAD

**Issue by sashatk** [ivogabe/gulp-typescript#445]
When I want to compile only some folders, e.g. wwwroot, then all ts files are compiled, that are not inside of wwwroot too. Looks like **_src_** doesn't filter input stream at all - when you use tsProject.
BTW: when you use _gulp.src_ - then filtering works.
I'm using gulp-typecsript 3.0.2

I try to setup folder filering so: `tsProject.src('wwwroot/**/*.ts').`

```
var tsProject = ts.createProject('tsconfig.json');
gulp.task('compile-ts', function () {
  var tsResult = tsProject.src('wwwroot/**/*.ts').pipe(tsProject()); 
  return tsResult.js.pipe(gulp.dest(''));
});
```

 **tsconfig.json:**

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noLib": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "moduleResolution": "node"   
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by ivogabe** [comment]
`tsProject.src()` doesn't support any kind of filtering, so the behaviour you're seeing is correct. You can use `gulp.src()` to find files based on a glob.

**Comment by sashatk** [comment]
Clear, thanks for the answer.

Because according to your example in a description ``` var tsResult = tsProject.src() // instead of gulp.src(...)``` - can think that ```tsProject.src()``` - fully replace ```gulp.src``` - that is not true.

Maybe then would be nice to rewrite your comment in the example.

**Comment by kwpeters** [comment]
I made the same incorrect assumption too and tried to pass glob patterns into `tsProject.src()`.  It would be nice if `tsProject.src()` was a real replacement for `gulp.src()`.

**Comment by ivogabe** [comment]
@kwpeters Why? If you want to pass a glob, you can use `gulp.src(..)`, if you want to use tsconfig to resolve your files you can use `tsProject.src()`.

**Comment by kwpeters** [comment]
@ivogabe, I want to use tsconfig so that my editor finds it and uses the correct settings.  But I also have several different build configurations, each requiring a different set of input file globs.  I think the appropriate answer is to use `gulp.src()` and to read the compiler options by manually `require()`-ing tsconfig.json.  This is a perfectly workable setup.  My only comment is that I also made the mistake of thinking that `tsProject.src()` could accept globbing patterns the same way that `gulp.src()` could.

**Comment by ivogabe** [comment]
You can still use `gulp.src()` when you're using a tsconfig file, the following would work just fine:
```javascript
gulp.src('src/**/*.ts')
    .pipe(tsProject())
    .pipe(gulp.dest('dist'))
```

**Comment by reykjavikingur** [comment]
I'm glad that I can use `tsProject` as part of a conventional gulp task definition. You should make that clear in `README.md`, which currently implies that you have to do everything very differently from the "normal" Gulp way.

**Comment by Martin-Andersen** [comment]
Dont know if I should open a new issue but I have a similar problem.
I have excluded node_modules/@types in tsconfig.json, because I have custom versions of the *.d.ts files.
It's work when compiling with VSCode but when I use gulp-typescript I get a lot of errors because it sees two *.d.ts files for the same library.
I am not the one installing the NPM @types. There are installed as dependencies of protractor.  

```
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6319,11): error TS2300: Duplicate identifier 'WebElementPromise'.
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6467,11): error TS2300: Duplicate identifier 'Session'.
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6574,5): error TS2300: Duplicate identifier 'export='.
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6582,5): error TS2300: Duplicate identifier 'export='.
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6586,3): error TS2300: Duplicate identifier 'export='.
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6610,5): error TS2300: Duplicate identifier 'export='.
C:/projects/kitos/node_modules/@types/selenium-webdriver/index.d.ts(6614,5): error TS2300: Duplicate identifier 'export='.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(9,11): error TS2300: Duplicate identifier 'Driver'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(44,11): error TS2300: Duplicate identifier 'Options'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(276,11): error TS2300: Duplicate identifier 'ServiceBuilder'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(391,11): error TS2300: Duplicate identifier 'Binary'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(429,11): error TS2300: Duplicate identifier 'Driver'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(446,11): error TS2300: Duplicate identifier 'Options'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(505,11): error TS2300: Duplicate identifier 'Profile'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(775,15): error TS2300: Duplicate identifier 'Preferences'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(817,13): error TS2300: Duplicate identifier 'Level'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(840,15): error TS2300: Duplicate identifier 'Entry'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(1145,15): error TS2300: Duplicate identifier 'CancellationError'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(1275,15): error TS2300: Duplicate identifier 'Thenable'.
C:/projects/kitos/typings-custom/selenium-webdriver/index.d.ts(1275,15): error TS2420: Class 'Thenable<T>' incorrectly implements interface 'IThenable<T>'.
``` 

This my tsconfig.json file
```
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true
    },
    "exclude": [
        "node_modules",
        "jspm_packages",
        "bower_components",
        "typings",
        "typings-custom",
        "node_modules/@types"
    ],
    "include": [
        "Presentation.Web/**/*"
    ]
}
```
