### ISSUE TITLE
gulp-typescript compiler option errors (Version : 3.1.0)

### ISSUE THREAD

**Issue by pkapare** [ivogabe/gulp-typescript#450]
**Expected behavior:**

**Actual behavior:**
On running gulp task I am getting following errors:
error TS5023: Unknown compiler option '_readableState'.
error TS5023: Unknown compiler option 'readable'.
error TS5023: Unknown compiler option 'domain'.
error TS5023: Unknown compiler option '_events'.
error TS5023: Unknown compiler option '_eventsCount'.
error TS5023: Unknown compiler option '_maxListeners'.
error TS5023: Unknown compiler option '_writableState'.
error TS5023: Unknown compiler option 'writable'.
error TS5023: Unknown compiler option 'allowHalfOpen'.
error TS5023: Unknown compiler option 'js'.
error TS5023: Unknown compiler option 'dts'.
error TS5024: Compiler option 'project' requires a value of type string.
**Your gulpfile:**
*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript

var paths = {
    source: {
        config: './tsconfig.json'       
    },
    build: {
        config: path.join('dist', argv.app, 'config'),
    }
}
gulp.task('transpile:env', function () {

    var tsProject = tsc.createProject(paths.source.config);
    
    var envfile = env.is.production() ? 'env.config.prod.ts' : 'env.config.dev.ts';
    envfile = 'config/' + envfile;

    var sourcefiles = [envfile];
    var tsResult = gulp.src(sourcefiles)
        .pipe(tsc(tsProject(),tsc.reporter.defaultReporter()));
    return tsResult.js
        .pipe(concat('env.config.js'))
        .pipe(gulp.dest(paths.build.config));
});

```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "listEmittedFiles": false,
    "suppressExcessPropertyErrors": true,
    "listFiles": false,
    "pretty": true,
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
  "exlude":[
    "node_modules",
    "node_modules/@types"
  ]
}

```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by ivogabe** [comment]
Looks like a duplicate of #449. Upgrading to version 3.1.1

**Comment by ivogabe** [comment]
Sorry, that's not the case.

**Comment by ivogabe** [comment]
The problem is in the following expression: `tsc(tsProject(),tsc.reporter.defaultReporter())`. You're now passing a stream (namely `tsProject()`) as the compiler options object. You should write this as `tsProject(tsc.reporter.defaultReporter())`. When you change that line, everything should be working fine.

**Comment by pkapare** [comment]
Perfect! That fixed those errors.

**Comment by ivogabe** [comment]
The old API was `tsc(tsProject)` (not `tsc(tsProject())`), which has been replaced by `tsProject()`. I'll update the post since `accepts` should be `accepted`.
