### ISSUE TITLE
Imported modules that are not specified in files section are not getting processed

### ISSUE THREAD

**Issue by roymiloh** [ivogabe/gulp-typescript#452]
**Expected behavior:**

Let's say I'm having two files, `a.ts` and `b.ts`. Inside `a.ts` I import `b.ts`. My `tsconfig.json` contains `files` section which his value is `["./a.ts"]`. 

> Normally the compiler will attempt to resolve all module imports before it starts the compilation process. Every time it successfully resolves an import to a file, the file is added to the set of files the compiler **will process later on**.

https://www.typescriptlang.org/docs/handbook/module-resolution.html

To have the same output by `gulp-typescript` and `tsc` - `a.js` and `b.js`.

**Actual behavior:**
The output in gulp-typescript is the file specified in tsconfig (from `files` section) only (`a.js`). In contrast, tsc processes the whole tree / set of files (`a.js` and `b.js`).

**Code**
https://github.com/roymiloh/gulp-typescript-no-resolve-example

```
$ npm install
$ npm run build:gulp
$ ls dist
> a.js
$ npm run build:tsc
$ ls dist
> a.js b.js
```

**Comment by ivogabe** [comment]
Looks like the same suggestion as #190?

**Comment by roymiloh** [comment]
Correct, closing.
