### ISSUE TITLE
Expose noImplicitUseStrict option

### ISSUE THREAD

**Issue by biste5** [ivogabe/gulp-typescript#455]
**Expected behavior:**
Using Gulp-Typescript I want to be able to control whether the transpiler should emit "use strict" directives by default or not.
This in TS compiler is possible by using _--noImplicitUseStrict_ option
See also [TS Compiler Options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Actual behavior:**
This configuration option isn't available in Gulp-Typescript. Setting this via tsconfig.json isn't picked up correctly

**Comment by ivogabe** [comment]
Gulp-typescript passes all options through, so `noImplicitUseStrict` should be working. You might be using an older version of TypeScript that does not support this option. Can you check which version of TypeScript you have, and the version in which the option was introduced?

**Comment by biste5** [comment]
I am using TypeScript 2.1.0-dev, so very latest, and I would exclude it's about what you say.

Anyway I do see other issues on getting the file _tsconfig.json_ be read correctly by Gulp-Typescript, so I think I'm doing something wrong in my Gulp task.

I'm posting my _gulpfile.js_ and _tsconfig.json_

```
 "use strict";

  var gulp = require("gulp");
  var ts = require('gulp-typescript');
  var sourcemaps = require('gulp-sourcemaps');

  gulp.task("default", function () {
      var tsProject = ts.createProject('./tsconfig.json');
      return tsProject.src('src/**/*.ts')
        .pipe(sourcemaps.init()) 
        .pipe(ts({
            module: 'amd',
            out: 'MyScript.js'
        }))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('dist'));
    });
```

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "preserveConstEnums": true,
    "declaration": true,
    "sourceMap": true,
    "outDir": "dist",
    "noImplicitUseStrict": true,
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules",
    "**/*.d.ts"]
}
```

Thanks!

**Comment by ivogabe** [comment]
The problem lies in these lines:
```javascript
        .pipe(ts({
            module: 'amd',
            out: 'MyScript.js'
        }))
```
You're not using the created `tsProject` there, causing that all options from your tsconfig file are ignored. You should replace these lines with `.pipe(tsProject())` (provided that you're using version 3.x of gulp-typescript).

**Comment by biste5** [comment]
Yes! Works like a charm!
And I'm feeling dumb ;)

Cheers / bedankt!
