### ISSUE TITLE
Setter property decorator not compiled

### ISSUE THREAD

**Issue by AkhmedovValikhan** [ivogabe/gulp-typescript#458]
I've noticed strange behavior with compilation of decorators attached to setter properties.

The setter decorator is not compiled if setter property located below getter. This issue cannot be reproduced with tsc compiler.

**Chunk of TS code**

```
    public get model() {
        return this.useSampleData.value === "true" ? this._sampleCardData : this._internalModel;
    }
    @Input()
    public set model(value) {
        this._internalModel = value;
    }
```

**Expected result code (tsc)** 
```
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Object)
    ], SampleCompo...
```

**Actual behavior:**
`SampleComponen...`

**tsc version: 2.0.9,
gulp-typescript versoin: 3.0.2,**

**Comment by ivogabe** [comment]
Are you sure you're using the same version of TypeScript in gulp-typescript as when you were testing with `tsc`? If so, can you create a small, but complete, reproduction and upload it here as a zip-file?

**Comment by ivogabe** [comment]
If I'm not mistaken, this was a bug of some TypeScript version, so closing this.
