### ISSUE TITLE
Support for configuration inheritance

### ISSUE THREAD

**Issue by mihe** [ivogabe/gulp-typescript#459]
The new `extends` setting in tsconfig (Microsoft/TypeScript#9876) doesn't seem to be supported by gulp-typescript (3.1.3). If I compile through gulp-typescript using a tsconfig that utilizes said setting, it seems to simply behave as if the inherited settings are simply missing and uses the default values instead.

**Comment by ivogabe** [comment]
Thanks for posting, I wasn't aware of that. I think/hope that the TypeScript API exports some functions for this. Can you try to create a pull request? Otherwise I'll take a look but that might take a while since I'm currently busy with some other work.

**Comment by mihe** [comment]
Unfortunately I'm quite busy as well, and won't have time to look into this any time soon. For the time being I'm fine with simply doing the overriding through the `createProject` options instead.

**Comment by aeisenberg** [comment]
We spent a few hours trying to track this down. Once we figured this out, the workaround is not too bad. If it is not easy to add this feature, I have two suggestions of temporary fixes:

1. Add some documentation to say that `extends` is not supported in the tsconfig files.
2. Add a warning with a meaningful message if an extends property is found.

**Comment by destroyerofbuilds** [comment]
It looks like support for inheritance was added in version [3.2.0](https://github.com/ivogabe/gulp-typescript/releases/tag/v3.2.0).

**Comment by ivogabe** [comment]
> It looks like support for inheritance was added in version 3.2.0.

Yes, 'extends' is now supported and several bugs of it were fixed in version 3.2.1.
