### ISSUE TITLE
Unwanted output sub directory

### ISSUE THREAD

**Issue by fredgate** [ivogabe/gulp-typescript#461]
Context :
- gulp-typesrcipt : 3.1.3 (last version)
- typescript : 2.0.10
- Visual Studio 2015
- Windows 7 64 bits

I have an unwanted sub directory in my destination folder.
Here is the structure of my project, with source and output :

![issue](https://cloud.githubusercontent.com/assets/3648269/20466763/3da3b4e0-af79-11e6-82d9-8c307408a1c6.png)

Important points are :
- my gulp file is at the root of the project
- I have a `ts` directory containing my tsconfig file and a sub directory app containing ts files
- the build output is the wwwroot/js directory

So my gulp file and tsconfig file are not in the same directory (I can not move the tsconfig file at the project root, else intellisense does not work in visual studio)

I want that the compiled app.js file be created in the `wwwroot/js` directory not in the `wwwroot/js/ts` directory.

Here is my gulpfile
```javascript
var tsProject = ts.createProject('ts/tsconfig.json', { rootDir: "app", outFile: 'app.js' });
gulp.task("ts", function () {
  return tsProject
     .src()
     .pipe(tsProject())
     .js
     .pipe(gulp.dest("./wwwroot/js/"));
});
```

My tsconfig
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "sourceMap": true,
    "removeComments": false,
    "emitDecoratorMetadata": true
  },
  "exclude": [
    "../node_modules",
    "../wwwroot"
  ]
}
```

**Comment by ivogabe** [comment]
Thanks for reporting, there appears to be a problem with outFile when the tsconfig file is in a subdirectory. I'll take a proper look at it soon.

**Comment by fredgate** [comment]
Thanks to confirm that it is a bug. I was not sure.

I took a look at source code, and I think that the problem is in the compiler.js file. In the emitFile function, from line 96, a relative base file name is calculated between the locations of the gulpfile and of the tsconfig file. It does not seem relevant.

```
 if (file) {
            base = file.gulp.base;
            if (this.project.options.outDir) {
                var baseRelative = path.relative(this.project.options.rootDir, base);
                base = path.join(this.project.options.outDir, baseRelative);
            }
            baseDeclarations = base;
            if (this.project.options.declarationDir) {
                var baseRelative = path.relative(this.project.options.rootDir, file.gulp.base);
                baseDeclarations = path.join(this.project.options.declarationDir, baseRelative);
            }
}
```

**Comment by lujcon** [comment]
This is a braking change. What is more important gulp-typescript is not compatible with tsc anymore.
Is it possible to specify "outFile" in tsconfig and expect that both gulp-typescript and tsc -p <path> will compile the project to the same folder?

**Comment by ivogabe** [comment]
@lujcon See #480. The new version has the desired behaviour, the old version had wrong behaviour as described in #480. Do you have a setup similar to that issue?

**Comment by ivogabe** [comment]
If I was aware that this would be a breaking change I would have done this in a major release, but I hadn't thought of a configuration like #480. However, when you dive into it it's clear to see that the old behaviour was a bug. (I actually find it strange that it was working..) So I think it's better to leave it this way.
