### ISSUE TITLE
Existing .d.ts file not output

### ISSUE THREAD

**Issue by drew-r** [ivogabe/gulp-typescript#463]
I have a `types.d.ts` file in my project and I'm finding that gulp-typescript does not output it in the DTS stream when I pass it in as source.

Repro by running

```
gulp.task('ts', ['lint'], function () {
 gulp.src(['myService.js', 'types.d.ts'])
    .pipe(debug())
    .pipe(ts.createProject('tsconfig.json'))
    .dts
    .pipe(debug())
    .pipe(gulp.dest('dist/));
});
```

**Expected behavior:**
types.d.ts is logged to console twice 

**Actual behavior:**
types.d.ts is not logged to console twice :)

**Comment by ivogabe** [comment]
The TypeScript compiler will also not (re)emit `.d.ts` files, so this behaviour is correct. If you need to copy these files, you should do that in a separate task. If you need to copy all declaration files from `lib`, that should look something like this:
```javascript
return gulp.src('lib/**/*.d.ts']).pipe(gulp.dest('dist/'))
```

**Comment by drew-r** [comment]
@ivogabe thanks for the clarification
