### ISSUE TITLE
  "noImplicitAny": true and "suppressImplicitAnyIndexErrors":true, still throw errors

### ISSUE THREAD

**Issue by Skuriles** [ivogabe/gulp-typescript#464]
**Expected behavior:**
With  tsconfig 
```
 "noImplicitAny": true,
"suppressImplicitAnyIndexErrors":true,
```

no errors like
`Parameter 'lat' implicitly has an 'any' type.`
should occur

**Actual behavior:**
Errors are still thrown and shown in task runner output

**Your gulpfile:**
```
var gulp = require("gulp");
var sourcemaps = require("gulp-sourcemaps");
var typescript = require("gulp-typescript");

gulp.task("compile:ts:dev",
        function () {
        var tsProject = typescript.createProject('tsconfig.json');
        return gulp
            .src([
                "public/app/**/*.ts",
                "typings/*.d.ts",
                "!public/app/config/config_android.ts"
            ])
            .pipe(sourcemaps.init())
            .pipe(tsProject())
            .pipe(sourcemaps.write("."))
            .pipe(gulp.dest("dist/app"));

    });

```

**tsconfig.json**

`{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "moduleResolution": "node",
    "target": "ES5",
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors":true,
    "sourceMap": true
  }
}`

Am I missing something?

**Comment by Skuriles** [comment]
One thing as additonal info
```
    .pipe(typescript({
        "module": "system",
        "moduleResolution": "node",
        "target": "ES5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true,        
        "typescript": require('typescript')
```

If I do it like this in gulpfile it works without errors. 
This line is needed:
`"typescript": require('typescript')`

**Comment by ivogabe** [comment]
`suppressImplicitAnyIndexErrors` does not suppress all `noImplicitAny` errors. It will only ignore errors when indexing an object without an indexer (like `let x = { a: true }; x["b"] = 1;`). With `noImplicitAny`, TypeScript would report an error at `x["b"]` and `suppressImplicitAnyIndexErrors` suppresses that error.

If you want to suppress all errors of `noImplicitAny`, you should just not set `noImplicitAny` to true.

**Comment by Skuriles** [comment]
hm...
I was pretty sure I tried this option set to false, and the errors still occured.
Now retried again with  "noImplicitAny": false, and it is gone...
Maybe I broke something else. Thanks for fast repsonse!!
