### ISSUE TITLE
TS 2.1.4 not compiling to JS

### ISSUE THREAD

**Issue by pete-hotchkiss** [ivogabe/gulp-typescript#466]
**Expected behavior:**
any and all *.ts files to transpile to Javascript ( and associated .js.map file
**Actual behavior:**
no .ts files are transpiled to javascript
**Your gulpfile:**
```javascript
var typescript = require('gulp-typescript');
...
gulp.task('build-compile', function () {
  if (!typescriptCompiler) {
    typescriptCompiler = typescript.createProject('tsconfig.json', {
      "typescript": require('typescript')
    });
  }
  return gulp.src(paths.dtsSrc.concat(paths.source))
    .pipe(plumber({ errorHandler: notify.onError('Error: <%= error.message %>') }))
    .pipe(changed(paths.output, { extension: '.ts' }))
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(typescript(typescriptCompiler))
    .pipe(sourcemaps.write('.', { includeContent: false, sourceRoot: '/App' }))
    .pipe(gulp.dest(paths.output));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": "app",
    "outDir": "dist",
    "sourceMap": true,
    "target": "es5",
    "module": "amd",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "lib": ["es5", "dom"],
    "baseUrl": "./app"
  },
  "filesGlob": [
    "./app/**/*.ts",
    "./src/**/*.ts",
    "./specs/**/*.ts",
    "./test/**/*.ts",
    "./features/**/*.ts",
    "./typings/index.d.ts",
    "./custom_typings/**/*.d.ts",
    "./jspm_packages/**/*.d.ts",
    "./node_modules/**/*.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": false
  },
  "formatCodeOptions": {
        "indentSize": 4,
        "tabSize": 4,
        "newLineCharacter": "\r\n",
        "convertTabsToSpaces": true,
        "insertSpaceAfterCommaDelimiter": true,
        "insertSpaceAfterSemicolonInForStatements": true,
        "insertSpaceBeforeAndAfterBinaryOperators": true,
        "insertSpaceAfterKeywordsInControlFlowStatements": true,
        "insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
        "placeOpenBraceOnNewLineForFunctions": false,
        "placeOpenBraceOnNewLineForControlBlocks": false
    }
}
```

It would seem that a more recent update of TS from Microsfot ( 2.1.4 ) is no longer transpiling TS files into JS. No errors are thrown in the task runner - it just fails silently.

If I expelicitly downgrade to 2.1.1  ( last known stable version used on my project ) and re-run _gulp-build-compile- the javascript is generated.

any known issues with 2.1.4 ?

**Comment by ivogabe** [comment]
Are you using the latest version of gulp-typescript? I've tried to reproduce this using your gulpfile, but I couldn't reproduce your issue. Your configuration however seems to be using an older version of gulp-typescript, as `typescript(typescriptCompiler)` should be written as `typescriptCompiler()` in 3.x.

**Comment by essuraj** [comment]
the code works for me.. thanks for the snippet ;)

**Comment by ivogabe** [comment]
@essuraj I advise to not use gulp-changed or something similar with gulp-typescript. You can get wrong JavaScript output and you might miss compile errors.

**Comment by ivogabe** [comment]
This is almost a year old, and I haven't heard of similar issues with newer versions of TypeScript. So I assume that this is not an issue anymore. If it is for someone, please let me know.
