### ISSUE TITLE
Inline sourcemaps end up in relative paths in the debugger

### ISSUE THREAD

**Issue by timfish** [ivogabe/gulp-typescript#468]
I'm using inline sourcemaps as in various situations separate map files don't work. Specifically in Chrome remote debug (to Android for example) you can't fetch separate .map files. Admittedly I'm not sure yet whether the issue is with `gulp-typescript` or `gulp-sourcemaps` but when running `tsc` the inline sourcemaps work and this issue only started after an `npm update`. If you think its a `gulp-sourcemaps` issue I'll go and open it there!

I'm using `gulp-typescript@3.1.3` and `gulp-sourcemaps@1.9.1`

**Expected behavior:**
Inline sourcemaps should all be displayed under a single root `src/` in the debugger.

![image](https://cloud.githubusercontent.com/assets/1150298/21044848/2667cef4-bdfe-11e6-9bba-db6431b2b441.png)

**Actual behavior:**
In the debugger only the first directory level of sourcemaps end up in `src/` the rest end up in `dist/src/`. This causes issues with breakpoints and makes sourcemaps more that 1 directory deep nearly useless! 

![image](https://cloud.githubusercontent.com/assets/1150298/21044806/f58193c4-bdfd-11e6-8b56-1498cb7ab861.png)

**Your gulpfile:**
```javascript
var sourcemaps = require('gulp-sourcemaps');
var typescript = require('gulp-typescript');

var typescriptProject = typescriptProject || null;
gulp.task('build-system', function () {
  if (!typescriptProject) {
    typescriptProject = typescript.createProject('tsconfig.json', {
      typescript: require('typescript')
    });
  }

  return gulp.src(['./src/**/!(*.spec).ts', './src/**/*.js'])
    .pipe(changed('./www/dist/', { extension: '.ts' }))
    .pipe(sourcemaps.init())
    .pipe(typescriptProject())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('./www/dist/'));
});
```

**tsconfig.json**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "rootDir": "./src/",
    "outDir": "./www/dist/",
    "inlineSources": true,
    "inlineSourceMap": true,
    "target": "es5",
    "module": "system",
    "declaration": false,
    "noImplicitAny": true,
    "strictNullChecks": false,
    "removeComments": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "include": [
    "./node_modules/@types/**/*.d.ts",
    "./typings/index.d.ts",
    "./typings/custom/**/*.d.ts",
    "./www/jspm_packages/**/*.ts",
    "./src/**/*.ts"
  ],
  "exclude": [
    "./src/**/*spec.ts",
    "node_modules",
    "platforms",
    "www"
  ]
}
```

**Comment by ivogabe** [comment]
You said the problem occurred after doing `npm update`, do you know which version of gulp-typescript did work properly?

**Comment by timfish** [comment]
I've dug into it more and decoded the sourcemaps and it appears to be an issue with `gulp-sourcemaps`
