### ISSUE TITLE
Please add support for new tsconfig "extends" property

### ISSUE THREAD

**Issue by jamesbrobb** [ivogabe/gulp-typescript#473]
Please can you add support for the new tsconfig `"extends"` property:

> A tsconfig.json file can inherit configurations from another file using the extends property.

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Expected behaviour:**

You should be able to extend one tsconfig file with another by adding the `extends` property to the child file

**Actual behaviour:**

The extends property is not currently supported.

**configs/base.json**

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true
  }
}
```

**tsconfig.json**

```json
{
  "extends": "./configs/base",
  "files": [
    "main.ts",
    "supplemental.ts"
  ]
}
```

I've attempted implementing this myself but am having a few issues.

I added the following at line 111 of `project.ts`.

`if (this.config.extends) content.extends = this.config.extends;`

If you log the object returned by `this.typescript.parseJsonConfigFileContent` it has the combined settings from the supplied tsconfig file and the file it extends. So this appears to be working correctly.

**But...**

...the problem i've come across, Is that the creation of the compiler options occurs before the child and parent `tsconfig` files are combined. So the `settings` object that's created and passed to `getCompilerOptions` on line 181 of `main.ts`, does not include the parent tsconfig files `compilerOptions`.

**Comment by ivogabe** [comment]
See #459
