### ISSUE TITLE
Documentation example of isolatedModules?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ivogabe/gulp-typescript#474]
The readme states that `isolatedModules` is an option:

> isolatedModules (boolean) - Compiles files seperately and doesn't check types, which causes a big speed increase. You have to use gulp-plumber and TypeScript 1.5+.

It doesn't clarify why gulp-plumber is needed, or an example of how to use this. Could you please post sample code here and/or in the readme file?

**Comment by ivogabe** [comment]
gulp-plumber is needed as a compile error would break the whole stream. gulp-plumber patches the streams, such that after an error, the stream stays functioning.

You can use it like this:
```javascript
tsProject.src()
  .pipe(plumber())
  .pipe(tsProject())
  .pipe(gulp.dest(..));
```
