### ISSUE TITLE
Source maps have null sourcesContent for all TypeScript files in sub folders

### ISSUE THREAD

**Issue by MisterGoodcat** [ivogabe/gulp-typescript#476]
In version 3.1.3, I'm seeing a very similar behavior as the one described in #256. Source map contents of top-level files are included, but for each and every TypeScript file located in a sub folder, the generated source map only contains "null" entries for the content.

I'm currently trying to find out whether this is a regression after the 3.x release which supposedly fixed the above mentioned issue. I spent some time trying to track this down, but no matter what features and settings of the involved tools I use, there doesn't seem to be a workaround.

Any idea?

**Comment by MisterGoodcat** [comment]
This might be caused by an external tool not handling the rewritten path finding in gulp-typescript 3 correctly, because it seems to be working fine in a repro without using that said tool.

I opened an issue there too: https://github.com/aurelia/cli/issues/455

**Comment by ivogabe** [comment]
The testcase (`test/sourceMaps`) still passes, so I suspect that it is a configuration error. Though if you can provide a small testcase that clearly demonstrates the bug, then I can investigate it.

**Comment by ivogabe** [comment]
Could you try to upgrade to 3.1.4? That includes #472, which might fix your issue.

**Comment by MisterGoodcat** [comment]
Perfect, that fixes it! Thanks also to @nenadvicentic!
