### ISSUE TITLE
Emit only updated files during incremental compilation

### ISSUE THREAD

**Issue by kimamula** [ivogabe/gulp-typescript#478]
TypeScript does not emit unchanged files when using `watch` option.

* https://github.com/Microsoft/TypeScript/issues/3113
* https://github.com/Microsoft/TypeScript/pull/6937

It is likely that this feature is not available in gulp-typescript, as it does not support `watch` option.
It would be nice if gulp-typescript mimic this feature during incremental compilation.

**Comment by kimamula** [comment]
I noticed that this would be quite difficult because

* gulp-typescript does not know `dest` location
* Output of gulp-typescript may be further processed

Sorry.

**Comment by kkovalevskiy** [comment]
@kimamula I suppose that it would be nice have such option in gulp-typescript configuration, it can be pretty useful for incremental builds and we could skip emitting phase for nonchanged files (it can take pretty much time if you have a big project with >3000 .ts files). So, it would be great if such option would exist and can be configurable outside `gulp-typescript`.
