### ISSUE TITLE
definition and javascript files are output in different locations. 

### ISSUE THREAD

**Issue by emilekberg** [ivogabe/gulp-typescript#480]
Ran into an issue today, after some digging, i noticed some behavior difference because gulp-typescript was bumped into an newer version. What is weird is that it's different behaviour for d.ts and js exporting.

I can upload a zip of the workspace to a hostingsite if you can tell me a good one.
**Expected behavior:**
gulp-typescript 3.1.3 behaviour
Files should be output in the specified path, relative to the tsconfig.json:
> {WORKSPACE}/bin/project1.js
> {WORKSPACE}/bin/project1.d.ts

**Actual behavior:**
gulp-typescript 3.1.4 behaviour
Files are not output in the specified path, only the d.ts file is. 
> {WORKSPACE}/../../bin/project1.js
> {WORKSPACE}/bin/project1.d.ts

**Your gulpfile:**
```javascript
'use strict';
const gulp = require('gulp');
const ts = require('gulp-typescript');
const merge = require('merge2');
gulp.task('default', () => {
	let tsProject = ts.createProject('src/project1/tsconfig.json', {
        typescript: require('typescript')
    });

    let tsResult = tsProject.src()
        .pipe(tsProject());

    let js = tsResult.js
        .pipe(gulp.dest(''));

    let dts = tsResult.dts
        .pipe(gulp.dest(''));

    return merge([
        js,
        dts
    ]);
});
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "module": "amd",
    "target": "es5",
    "sourceMap": false,
    "declaration": true,
    "outFile": "../../bin/project1.js",
    "rootDir": "../",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "skipDefaultLibCheck": true,
    "removeComments": true,
    "preserveConstEnums": false,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "**/*.ts"
  ]
}
```

**Folder structure**
![Folder structure](http://i.imgur.com/Q4cf5RR.png)

**Comment by ivogabe** [comment]
I've taken a look at it, and `{WORKSPACE}/../../bin` appears to be the location where the files should be placed. However, the inconsistency was not desired of course. Previous versions of gulp typescript appear to place it in `{WORKSPACE}/bin/` but that was a bug. When you set `outFile` to `../../bin/project1.js`, the relative part of the emitted file should be `../../bin/project1.js`. Previous versions set the relative part of the file to `{WORKSPACE}/bin/project1.js`, which is actually an absolute path. Original bug report: #461.

When you then call `.pipe(gulp.dest(''))`, you're writing the file `../../bin/project1.js` relative to `''`, thus above the project root. It's necessary to write `gulp.dest('src/project1')` there. However, I do think that this is a good argument to introduce something like `tsProject.dest()` which will make this nicer.

**Comment by emilekberg** [comment]
@ivogabe 
Fair enough :) is the tsProject.dest() estimated for some release any soon? it sounds like this is basically what i want, since i setup many projects using tsconfig.json, with their output file decided there. And the path might not be relative the same to the output dir, however i want to use the same gulp script.

Of course, it's solvable, but i think a tsProject.dest() would be the best solution for my case.
