### ISSUE TITLE
not able to transpile my project ts files

### ISSUE THREAD

**Issue by alexus85** [ivogabe/gulp-typescript#481]
**Expected behavior:**
transpile all .ts files in **src/app** directory

**Actual behavior:**
Task is being executed as expected . however the ts files are not being transpiled at all. Neither does it produce any js files nor it create the **build** directory.

**Project directory structure:**

```
src/
   app/ ( contains all the app ts files )
config/
   tsconfig.json
gulpfile.js
package.json
```

**gulpfile:**

```
const gulp = require('gulp');
const del = require('del');
const tsc = require("gulp-typescript");
const sourcemaps = require('gulp-sourcemaps');

var config = {
  jit: {
    root: './build/jit',
    index: 'index-jit.html'
  },
  aot: {
    root:'./build/aot/dist',
    index: 'index-aot.html'
  }
};

 gulp.task("compile:jit", () => {
  let tsProject = tsc.createProject("config/tsconfig.json");

  log("[JIT] Compiling all .ts files")
    let tsResult = tsProject.src()
        .pipe(sourcemaps.init())
        .pipe(tsProject());

    return tsResult.js
        .pipe(sourcemaps.write(".", {sourceRoot: '/src'}))
        .pipe(gulp.dest(tsProject.options.outDir));
});
```

**tsconfig.json**

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "lib": [ "es2015", "dom" ],
        "outDir": "../build/jit/app",
        "suppressImplicitAnyIndexErrors": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "sourceMap": true,
        "typeRoots": [
          "../node_modules/@types/"
        ]
    },
    "include": [
        "../src/**/*.ts"
    ],
    "exclude": [
        "../node_modules",
        "../src/**/*-aot.ts"
    ]
}
```

**versions**
+-- gulp@3.9.1
+-- gulp-cli@1.2.2
+-- gulp-typescript@3.1.4
+-- typescript@2.1.5

The only output I get when running gulp -LLLL compile:jit

```
[23:49:34] Using gulpfile [project_dir]/gulpfile.js
[23:49:34] Starting 'compile:jit'...
[23:49:34] [JIT] Compiling all .ts files
[23:49:34] Finished 'compile:jit' after 75 ms
```

```

**Comment by ivogabe** [comment]
You're probably writing the files to a directory outside of the project root, as `gulp.dest("../build/jit/app")` will put them in a directory `build` above the project root.

Could you replace `.pipe(gulp.dest(tsProject.options.outDir));` with `.pipe(gulp.dest("build/jit/app"))`?

**Comment by alexus85** [comment]
it turned out that the files couldn't be processed cause gulp was not able to read my path, since it was containing a "non-standard" path character.

`C:/[Dev]/Project`

Obviously it was the square brackets causing the issue, When I moved the project directory to C:/Project/ , everything started suddenly working.
