### ISSUE TITLE
Use global TypeScript instead of local

### ISSUE THREAD

**Issue by TheColorRed** [ivogabe/gulp-typescript#482]
I am using the latest version `3.1.4`, and when I use it in my project I get the following error:

>gulp-typescript: TypeScript not installed - install with `npm install typescript --save-dev`
  As of gulp-typescript 3.0, TypeScript isn't bundled with gulp-typescript any more.
  Install the latest stable version with `npm install typescript --save-dev`
  or a nightly with `npm install typescript@next --save-dev`
  More information: http://dev.ivogabe.com/gulp-typescript-3/

I do however, have the extension installed globally.

```
npm install typescript -g
```

Is there anyway that the extension could use the globally installed version instead of the locally installed version?

**Comment by ivogabe** [comment]
It's the design of Node that modules use local dependencies. In this case, gulp-typescript is thus using a local installation of TypeScript. Before 3.0, gulp-typescript was installing a local installation. As of 3.0 you should do it yourself, such that you can easily choose the right version. You can install it using `npm install typescript --save-dev`
