### ISSUE TITLE
applySourceMap uses wrong relative path

### ISSUE THREAD

**Issue by josephst** [ivogabe/gulp-typescript#488]
I'm using gulp-sourcemap to generate source maps with gulp-typescript. My folder structure is as follows:
```
js/
ts/
    foo/
        fizz.ts
    bar/
        buzz.ts
```

Gulp is set up to take files from `ts`, run them through gulp-typescript, and output them to `js` with separate source maps files. The `sources` property of the map files is incorrect; for example, a file that is output to `js/foo/fizz.js.map` has a `source` property of `../ts/foo/fizz.ts` whereas the correct value is `../../ts/foo/fizz.ts`.

The problem is constant regardless of nested folder depth, i.e. `ts/my/really/deep/folder/hello.ts` will be correctly placed in `js/my/really/deep/folder/hello.ts` and `js/my/really/deep/folder/hello.ts.map` but the `source` property of the map still only refers to `../ts/my/really/deep/folder/hello.ts` (up one level, instead of several).

From debugging the code, it looks like the problem is related to [line 89 of `output.ts`](https://github.com/ivogabe/gulp-typescript/blob/master/lib/output.ts#L89). Changing `output.base` to `output.dirname` fixes the problem for me.

**Expected behavior:**
`source` property is set to `../../ts/foo/fizz.ts`

**Actual behavior:**
`source` property is set to `../ts/foo/fizz.ts`.

**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
const gulp = require('gulp');
const ts = require('gulp-typescript');
const sourcemaps = require('gulp-sourcemaps');

const tsProject = ts.createProject('tsconfig.json');

gulp.task('default', () => {
  tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(tsProject())
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./js'));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": true,
        "outDir": "./js",
        "rootDir": "./ts"
    },
    "include": [
        "./ts/**/*.ts"
    ]
}
```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by josephst** [comment]
[Demo of the problem](https://github.com/josephst/gulpts-demo)

**Comment by ivogabe** [comment]
If I'm not mistaken, gulp-sourcemaps' docs say that the `sources` property should be relative to the base folder of the emitted files. In your setup, the base folder would be `/js/` (and the relative part of the file is `foo/fizz.js`. Resolving `../ts/foo/fizz.ts` relative to the base path does yield the correct source location, but I understand that this behaviour is not really desired for you. I think that the `sourceRoot` option might help. I might be mistaken, I'll take a better look at this later.

**Comment by josephst** [comment]
Ooof. Just realized my mistake. I wasn't setting `destPath` in `sourcemaps.write()`. Changed my gulpfile to `sourcemaps.write('.', { includeContent: false, destPath: './js' })` and it's working flawlessly now. Thanks for your help!
