### ISSUE TITLE
"emit failed" error when using the "noEmit: true" flag

### ISSUE THREAD

**Issue by Ventajou** [ivogabe/gulp-typescript#490]
**Expected behavior:**
I use this code:

    let tsProject = ts.createProject('tsconfig.json', { noEmit: true, baseUrl: './node_modules' });

so I expect no code to be emitted and no error shown when running the task.

**Actual behavior:**

I get a `TypeScript: emit failed` which confuses everyone else on my team into thinking there's an error.

**Comment by ivogabe** [comment]
Fixed in the latest prerelease. You can install it with `npm install gulp-typescript@4.0.0-alpha.1`
