### ISSUE TITLE
Although "gulp-typescript" task is running first it's output files are not available for next task

### ISSUE THREAD

**Issue by ranbuch** [ivogabe/gulp-typescript#493]
This is my ```gulpfile.js``` essentials:
```
gulp.task("serve-build", ["optimize"], function() {
// code here
});
gulp.task("optimize", ["inject", "fonts", "images"], function() {
// code here
});
gulp.task("inject", ["build-typescript", "wiredep", "styles", "templatecache"], function() {
// code here
});
gulp.task("build-typescript", function () {
    log("building typescript");
    return tsProject.src()
        .pipe(tsProject())
        .js.pipe(gulp.dest(config.tsDest));
});
```
When running ```gulp serve-build```, as can be notice above, the first task that's actually runs is ```build-typescript``` but when the task that injects the .js files (the output of ```gulp-typescript```) is running the files aren't available - probably not exist yet.

If however I'll run ```gulp build-typescript``` and then ```gulp serve-build``` everything works fine.

I've tried to use ```gulp.src('app')``` instead of ```tsProject.src()``` but it didn't work.

Is there any solution other then running 2 commands for my build?

It sais [here](http://gulpjs.com/) that gulp is

> Using the power of node streams, gulp gives you fast builds that don't write intermediary files to disk.

Can I force ```gulp-typescript``` to immediately write the files on to my disk in a synchronous way?

Thank you.

**Comment by ivogabe** [comment]
`build-typescript` finishes when the files are written to the disk, so I'm not sure why you're seeing this behaviour. A gulp task finishes when the returned stream finishes, and in `build-typescript` you're returning the stream of `gulp.dest(..)`, which finishes when the files are written. Then `inject` should start, then `optimize` and finally `serve-build`. So in theory, this should work.. I can try to take a better look at this soon.

**Comment by ranbuch** [comment]
I've "fixed" this issue like this:
```
gulp.task("serve-build", ["build-typescript"], function() {
    return gulp.start('serve-build-post-typescript');
});
gulp.task("serve-build-post-typescript", ["optimize"], function() {
// code here
});
gulp.task("optimize", ["inject", "fonts", "images"], function() {
// code here
});
gulp.task("inject", ["build-typescript", "wiredep", "styles", "templatecache"], function() {
// code here
});
gulp.task("build-typescript", function () {
    log("building typescript");
    return tsProject.src()
        .pipe(tsProject())
        .js.pipe(gulp.dest(config.tsDest));
});
```

Looks like [this](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md) is the why to go.

It's running ```build-typescript``` twice though.

Thank you for your help.

**Comment by ivogabe** [comment]
It's strange that you need to fix it that way, as in your initial gulpfile, `inject` should start when `build-typescript` is finished, `optimize` after `inject` was finished, and `serve-build` when `optimize` was finished.

Anyway, I do think that this is not an issue with gulp-typescript, so I'll close this here. Maybe you could find some more help at stackoverflow or something like that.
