### ISSUE TITLE
Gulp-typescript seems to generate broken sourcemaps in chrome

### ISSUE THREAD

**Issue by brphelps** [ivogabe/gulp-typescript#498]
I see an issue with certain files emitting sourcemaps that seem to be incompatible with chrome (try adding a breakpoint to line 20 of sample.ts in the chrome debugger). 

https://github.com/brphelps/gulp-typescript-sourcemap-repro

**Expected behavior:**
All sensible lines of code should be able to be breakpoint'ed.

**Actual behavior:**
Things like line 20 in sample.ts fail to be resolved.

**Your gulpfile:**
https://github.com/brphelps/gulp-typescript-sourcemap-repro/blob/master/gulpfile.js

**Comment by brphelps** [comment]
@ivogabe  -- Any recommendations on how to start triaging this issue? From what I can tell it's specific to gulp-typescript as the sourcemap generation is part of the package itself.

**Comment by ivogabe** [comment]
Hard to say.. Since you are using several plugins, could you check whether removing one or more of those plugins fixes your issues?

**Comment by brphelps** [comment]
Sorry, updated the remote. From what I can tell, gulp-typescript is now the only plugin responsible for sourcemap impact.  Note that without ngAnnotate it appears that now line 18 is unresolvable in the repro. Any pointers on where I can start triage, @ivogabe ?

**Comment by ivogabe** [comment]
Sorry for the late reply. Maybe you can compare the source map generated by gulp if you remove all plugins but gulp-typescript, with the source map generated by `tsc`?

**Comment by ivogabe** [comment]
Is this still an issue?
