### ISSUE TITLE
Install of gulp-typescript generates a red "invalid" on the command line

### ISSUE THREAD

**Issue by Marc22** [ivogabe/gulp-typescript#500]
When installing gulp-typescript, the install appears to complete successfully, but the output has the word "invalid" in red after the version number.

>  npm install --save gulp-typescript@3 typescript@2.2.1

+-- gulp-typescript@3.1.6  invalid
`-- typescript@2.2.1

What does this mean?  How can I avoid this?

Thanks,
-Marc

**Comment by daemons88** [comment]
Same issue!!

Regards

**Comment by ivogabe** [comment]
You probably have an older version of gulp-typescript listed in your `package.json` file. You should remove gulp-typescript from the `dependency` section in your `package.json` file. You should also use `--save-dev` instead of `--save`, as it should be installed as a `devDependency`.

**Comment by jkrot** [comment]
gulp typescript requires version 3 you have a line that has typescript installing that needs to be updated.

**Comment by ivogabe** [comment]
Is this still an issue to anyone?
