### ISSUE TITLE
Support custom transformers

### ISSUE THREAD

**Issue by kimamula** [ivogabe/gulp-typescript#502]
In typescript@next, `Program.emit()` accepts a new argument `customTransformers`, which enables to customize the transformation behavior.
https://github.com/Microsoft/TypeScript/pull/13940

Unlike language service plugins, custom transformers currently cannot be specified in tsconfig.json but can only be passed as an argument of `Program.emit()`.

It would be great if gulp-typescript supports custom transformers so that gulp users don't have to use TypeScript API directly.

**Comment by kimamula** [comment]
`Program.emit()` in TypeScript 2.3.1 accepts `customTransformers`.
https://github.com/Microsoft/TypeScript/blob/v2.3.1/lib/typescript.d.ts#L1634

**Comment by ivogabe** [comment]
Good idea. If I'm not mistaken TypeScript has not yet an official way to specify these transforms, and I prefer to stay in line with the configuration options of TypeScript / tsc. I'm afraid this will be a non-standard option as they said they don't want to expose such a functionality in tsc. However they might add it later, and if they add it in a different way it can be very confusing.
