### ISSUE TITLE
Compiling two seperate files and using inheritance causes undefined bug

### ISSUE THREAD

**Issue by Assassinbeast** [ivogabe/gulp-typescript#505]
When i have two different files with **two classes** inside the **same module** and one of the classes inherits from the other class, then it will cause an undefined error.

Below is an example of the file structure
![gulpfile](https://cloud.githubusercontent.com/assets/6762656/25780262/0c4470f8-3325-11e7-89c7-9380271b45d1.png)

I have two files, **GameObject.ts** and **Monster.ts** inside the **dev folder**.

There are two classes **BaseGameObject** and **Monster**.
**Monster** inherits from **BaseGameObject** and both of the classes are inside the module **GameObject**.

I want to compile them both and leave them as two different files and put them inside **release folder**.

Below is the sourcecode. Left are the **ts file** and to the right are the **compiled js file**.
![two files](https://cloud.githubusercontent.com/assets/6762656/25780271/361cd564-3325-11e7-8d91-a6b5a31e9320.png)

And then below is my **index.html file** and browser testing which gives an undefined error
![browser error](https://cloud.githubusercontent.com/assets/6762656/25780282/6b7d3cee-3325-11e7-9527-bece1f90032d.png)

The reason that its undefined, is because in the **monster.js line 19**, its putting in a **BaseGameObject**.

And **BaseGameObject** is undefined because its not in the scope.

The **expected behaviour** on **line 19** should be **GameObject.BaseGameObject**, because the **BaseGameObject** is inside the **GameObject**.

So if i try something else, like putting the **GameObject.ts** inside the **Monster.ts**, then it have the correct behaviour shown below.
![one file seperate modules](https://cloud.githubusercontent.com/assets/6762656/25780334/75cfdc50-3326-11e7-8deb-431a655d56c0.png)
Here we can see that **monster.js line 28** its **catching** the correct object by referencing the **GameObject** first to get the **BaseGameObject**.

And if i put them in the same module, then it will also have the correct behaviour.
![same file same module](https://cloud.githubusercontent.com/assets/6762656/25780357/c1496732-3326-11e7-960a-0369f036aed5.png)

Here, on **monster.js line 25**, its referencing only **BaseGameObject** which is **correct** because the **BaseGameObject** is in the **same scope** and thats why it doens't need to use **GameObject.BaseGameObject**.

Right now, the only way i can achieve this is by making the **Visual Studio 2015 Typescript autocompiler** do the job by autocompile all the **ts** into **js** files which will be put in the same folder like shown below:
![visualstudio typescript autocompile](https://cloud.githubusercontent.com/assets/6762656/25780379/5f354790-3327-11e7-8cbb-e8f820c9f663.png)

Here the **monster.js line 14**, its actually referencing the **GameObject.BaseGameObject** which is correct and expected because **we know at compile time** that the **BaseGameObject** is not in that scope. That means the **BaseGameObject** must be inside the **GameObject** variable.

So after that, i can use **gulp.src()** and take the **js files** and use **gulp.dest()** to put these two inside the **release folder** and run it successfully. 

But i want to use the **gulp-typescript** to compile it because i dont want to be depended on **Visual Studio Typescript autocompiler** and i also dont want **js files** inside my **dev folder**.

So ultimately, Visual Studio compiles it correctly.

If i use the **command line typescript compiler** and type **tsc monster.js**, then it also makes the same error:
![tsc compiler](https://cloud.githubusercontent.com/assets/6762656/25780413/ee8fd2e8-3327-11e7-9283-332f7517c579.png)

Here on **monster.js line 19** it does the same, trying to get the **BaseGameObject** which is undefined because its not in that scope.

I'm not an expert, but i think this is a bug because when **tsc** compiles the typescript, then we know **at compile time** that the **BaseGameObject** is undefined no matter what because it is not in that scope in the typescript or javascript files.

This small example doesn't make much sense, but the reason why i want two seperate files is because i dont want the clients to download all files at once. For example if i have **100 different ts** files which have classes that inherits from **GameObject.BaseGameObject**, then i want the clients only to download the **GameObject.BaseGameObject** they **need** depending on the **url path / site** they are on.

## EDIT: IMPORTANT INFO
I just found out that **gulp-typescript** compiles it correctly in a **asp.net core project**.
I this example, i tested it in a console program, but i dont know why it would have any difference.

**Comment by ivogabe** [comment]
This is a known limitation of TypeScript. The order on which compiled files are written is not strictly defined, so that can vary. Though you can force that some file is emitted before some other file. If file `a.ts` has a dependency on `b.ts` (that is, `b` declares a class that `a` uses), then you should add the following line at the top of `a.ts`:
```typescript
/// <reference path="b.ts" />
```
See the [handbook](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) for more information.

A better solution would be to use a module system. With modules, you explicitly denote which files are dependencies. See the [modules page](https://www.typescriptlang.org/docs/handbook/modules.html) in the handbook. This approach would be better, but would require some work to change your code to modules.
