### ISSUE TITLE
@types are not resolved when using multi-project setup

### ISSUE THREAD

**Issue by samvv** [ivogabe/gulp-typescript#515]
I'm having an odd issue: packages belonging to the @types npm organisation are not resolved when using a multi-project setup where the source files are not in the exact same directory as the `node_modules/` directory (which is almost always the case; most of the time the sources are in `lib/` or `src/`). I've created a repository [here](https://github.com/samvv/gulp-typescript-bug) with a minimal project setup to show how it occurs.

 I've done some research and this seems to be at least partly due to the following piece of code:

```ts
const currentDirectory = utils.getCommonBasePathOfArray(
  rootFilenames.map(fileName => this.project.input.getFile(fileName).gulp.cwd)
);
```

Providing a custom current working directory fixed the issue in my case. I'll submit a PR just to show how it might be fixed.

**Expected behavior:**

No compiler warnings such as `Cannot find module 'path'`.

**Actual behavior:**

Compiler warnings such as `Cannot find module 'path'`.

**Your gulpfile:**

```javascript
const gulp = require('gulp')
const ts = require('gulp-typescript')
const merge = require('merge2')

const proj1 = ts.createProject('one/src/tsconfig.json')
const proj2 = ts.createProject('two/src/tsconfig.json')

gulp.task('compile', () => {
  return merge([
    gulp.src('one/src/**/*.ts').pipe(proj1()).pipe(gulp.dest('one/dist')),
    gulp.src('two/src/**/*.ts').pipe(proj2()).pipe(gulp.dest('two/dist')),
  ])
})

gulp.task('default', ['compile'])
```

**Code**

```typescript
// just doing some @types/node stuff ...

import * as path from "path"

const myPath = path.join('foo', 'baz', 'bar')
```

**Comment by ivogabe** [comment]
I think you can already do this using `gulp.src(.., { cwd: 'one/src' })`, could you try that?

**Comment by samvv** [comment]
If that's the case, then I'm really stupid for opening up a pull request 😆 . And yes, it works. Thanks for explaining!
