### ISSUE TITLE
v3.1.7 published on npmjs.com but not listed as release on github

### ISSUE THREAD

**Issue by BurtHarris** [ivogabe/gulp-typescript#519]
After using the command `npm install -D gulp-typescript`, npm installed version 3.1.7.   However this repository does not show that release on it's [releases page](https://github.com/ivogabe/gulp-typescript/releases), so I'm not sure what's in it.

I'm hoping to find a release of a version with support for `extends` in **tsconfig.json**, but 3.1.7 still seems to be ignoring it.   PR #494.

**Comment by ivogabe** [comment]
Thanks for noticing, I've added the release notes. `extends` was not a part of that release, but it is added in 3.2.0 which I just released.
