### ISSUE TITLE
absolute paths in sourcemap

### ISSUE THREAD

**Issue by baabgai** [ivogabe/gulp-typescript#52]
In the sourcemap files written together with gulp-sourcemaps the TypeScript files end up with absolute paths instead of relativ paths in the sources tag. This leads to errors when Firefox tries to read sourcemap files and to cumbersome long paths in Chrome.
When using gulp-sourcemaps on javascript files the expected relative paths are set.

**Comment by ivogabe** [comment]
Does setting the `sourceRoot` option to `''` solve this? Changing the default value of `sourceRoot` to an empty string might solve this issue. Mentioning @shiwano since he added sourceRoot option.

**Comment by baabgai** [comment]
Setting sourceRoot to empty string did work, thanks!

On Sat, Jan 17, 2015 at 8:48 PM, Ivo Gabe de Wolff <notifications@github.com

**Comment by jon-hall** [comment]
Unfortunately, I'm getting the same issue, and setting sourceRoot to '' doesn't appear to resolve it.  My build step looks like this:

    gulp.task('tsc', [], function () {
        'use strict';
        var tsRes = gulp.src('src/*.ts', { base: './' })
                    .pipe($.sourcemaps.init())
                    .pipe($.typescript({
                        target: 'ES6',
                        sortOutput: true
                    }));

        return tsRes.js
            .pipe($.concat('script.js'))
            .pipe($.sourcemaps.write('.', { includeContent: false, sourceRoot: '' }))
            .pipe(gulp.dest('./dist'));
    });

My TypeScript files are all internal modules present under the 'src' directory, and the generated sourcemap's 'sources' collection ends up containing all absolute paths; while the map file the TypeScript compiler generates when using the --out flag has relative paths.

**Comment by ivogabe** [comment]
Can you set the base property in the options object of gulp-typescript instead of gulp-sourcemaps?

**Comment by jon-hall** [comment]
That solved it, cheers for the help.

**Comment by zivkan** [comment]
I'm also having the same problem. My gulpfile has this:
```javascript
gulp.src("app/**/*.ts")
        .pipe(sourcemap.init())
//        .pipe(typescript({base:"."})).js
        .pipe(concat("app.js"))
        .pipe(uglify())
        .pipe(sourcemap.write(".", { includeContent: false }))
        .pipe(gulp.dest("."));
```

With the typescript line commented out (they're still plain javascript files, I'm trying to migrate to typescript), the map file contains relative paths. With the line uncommented, the map file contains absolute paths.

I tried:
* adding {base:"."} to the call to src()
* adding sourceRoot to sourcemap.write's options
* changing, or removing the base option in the call to typescript
* removing the .js call at the end of the line that calls typescipt

but I haven't found a way to get it to use relative urls with typescript yet.

**Comment by ejmarino** [comment]
I had solve the absolute path problem putting:

sourceRoot : ''

in my typescript project object like this: 

   var typeScriptProject = typescript.createProject({
        declarationFiles: false,
        noExternalResolve: false,
        removeComments: false,
        sourceRoot: ''
    });

but a new problem arise...

I have source files organized in folders but when I put sourceRoot in project properties all the files paths are removed and the file are flattened out. 

This is the section of map file without  sourceRoot:

"sources": [
"C:/Development/FrontEnd/scripts/module.ts",
"C:/Development/FrontEnd/scripts/controllers/controllers.ts"
]

but with sourceRoot = '':

"sources": [
"module.ts",
"controllers.ts"
]

I would expect this kind of result:

"sources": [
"module.ts",
"controllers/controllers.ts"
]
as I get when i sourcemap javascript instead typescript.

**Comment by mircolino** [comment]
I have the same problem as @ejmarino.

With the following directory structure:
```
Source:
./src
    └ main
         └ webapp
                └ src
                    ├ file1.ts
                    └ file2.ts
```
when I execute the following 'test' task:
```javascript
gulp.task('test', function() {
  gulp.src('src/main/webapp/**/*.ts')
    .pipe(sourcemaps.init())
    .pipe(ts({sourceRoot: ''}))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('build/webapp/main/'));
});
```
the directory structure is recreated correctly in the destination folder:
```
Destination:
./build
      └ webapp 
             └ main
                  └ src 
                      ├ file1.js
                      ├ file1.js.map
                      ├ file2.js
                      └ file2.js.map
```
however the .map files are incorrect. With: 
```javascript
.pipe(ts({sourceRoot: ''}))
```
I get no source code inlined in the map and an invalid 'sourceRoot':
```javascript
{
  version: 3,
  sources: ["file1.ts"],
  names: [...],
  mappings: "...",    
  file: "src/file1.js",
  sourceRoot: "/source/",
  sourcesContent: [null]
}
```
with: 
```javascript
.pipe(ts())
```
I get no source code inlined in the map and 'sourceRoot' set to my project root:
```javascript
{
  version: 3,
  sources: ["file1.ts"],
  names: [...],
  mappings: "...",    
  file: "src/file1.js",
  sourceRoot: "C:/Dev/prj/foo/",
  sourcesContent: [null]
}
```
with: 
```javascript
.pipe(ts({sourceRoot: 'src/'}))
```
sort of works. The source code is inlined and 'sourceRoot' is correct. However 'sources' relative path is still missing and, since 'sourceRoot' cannot be changed dynamically for every directory, it'll only work for the first '/src' directory level.
```javascript
{
  version: 3,
  sources: ["file1.ts"],
  names: [...],
  mappings: "...",    
  file: "src/file1.js",
  sourceRoot: "src/",
  sourcesContent: [...]
}
```
in my opinion the final sourcemap file should be as follow (with 'sourceRoot' not present since it's not needed because the source code is inlined):
```javascript
{
  version: 3,
  sources: ["src/file1.ts"],
  names: [...],
  mappings: "...",    
  file: "src/file1.js",
  sourcesContent: [...]
}
```

**Comment by ivogabe** [comment]
Solved by removing the sourceRoot option. Because the sourceRoot property was present in the source map, gulp-concat would add that to the source property of the source map generated by gulp-concat, which resulted in an absolute path. That's now fixed by removing sourceRoot from the source-map generated by TypeScript.

Also I removed the sourceRoot option, since gulp-sourcemap has a sourceRoot option. Gulpfiles should now look like:
```javascript
return gulp.src('lib/**/**.ts')
    .pipe(sourcemaps.init())
    .pipe(ts())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('release'));
```
If you want to provide a sourceRoot option, you can use
```javascript
.pipe(sourcemaps.write('.', { sourceRoot: 'foo' }))
```
