### ISSUE TITLE
TS18003 is yielded if config file is in separate directory

### ISSUE THREAD

**Issue by ishitatsuyuki** [ivogabe/gulp-typescript#527]
**Expected behavior:**

Silently builds.

**Actual behavior:**

Error (non critical though) during `createProject`:

```
error TS18003: No inputs were found in config file 'tsconfig-base.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","bower_components","jspm_packages"]'.
```

**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
  var tsProject = ts.createProject('configs/tsconfig-base.json');
  return gulp.src('./src/test/**/*.ts')
    .pipe(tsProject())
    .pipe(gulp.dest('src/lib-test'));
```

**tsconfig.json**

The file is placed in `configs` directory, which only contains configuration json. As it doesn't contain any `ts` file, the `**/*.ts` default glob fails to match and yields the error.

**Comment by ivogabe** [comment]
Thanks for reporting. The fix is included in the new release, 3.2.1.
