### ISSUE TITLE
Compiling very slow after latest update

### ISSUE THREAD

**Issue by Skuriles** [ivogabe/gulp-typescript#528]
Versions: 
TS: 2.4.1
gulp-typescript: 3.2.0
gulp: 3.9.1

I'm trying to compile a angular 4.2.6 app.

**Expected behavior:**
Compile should be a way faster (around 500 ms max). 
**Actual behavior:**
Compiling the whole app (115 files) takes between 5-8 seconds. Reduced to 4 files to compile => around 2 seconds to compile
tsc makes the same task within 2 seconds (whole app). 

I've removed sourcemap creation, but this didn't improve the speed notably 

**Your gulpfile:**
```gulp.task("compile:ts:dev",
        function () {
            var tsProject = typescript.createProject("tsconfig.json");
            return gulp
                .src([
                    "public/app/shared/constants/**/*.ts",
                    "!public/app/config/config_android.ts"
                ])              
                .pipe(tsProject())              
                .pipe(gulp.dest("dist/app"));
        });
```
**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "moduleResolution": "node",
    "target": "ES5",
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "sourceMap": true
  }
}
```

Any ideas?

**Comment by Skuriles** [comment]
Ok.. Think this can be closed..this is some other bug.
I forgot to add a "return" in my gulp-tsc task and so the time was wrong as it was immediately finished, but the compiling still takes 5-8 seconds. So I have to check for other issue

Sorry for circumstances

**Comment by Skuriles** [comment]
Sorry accidently closed due to wrong information.

**Comment by ivogabe** [comment]
Could you share your project? You can also mail it privately, with NDA if necessary. Then I can profile this regression.

**Comment by Skuriles** [comment]
Sorry, this is not possible (due to restrictions). 
I tested it with gulp-tsc package and got the same results (5-7 seconds) and found some angular 4 issues on github which discuss similar problems. 
So I don't think it is a special problem of your package.  TSC is a little bit faster, but not as fast as expected.
Maybe I have to do further research with typescript and angular.
Do you have any profiling tools you can recommend I can use?
If you want you can close this. I will come back if I have more results

Thanks and sorry for inconvenience

**Comment by ivogabe** [comment]
A performance difference between gulp-typescript and tsc is definitely a bug here. Could you link those issues of Angular here?

I have made some minor changes, I think that they won't make a big difference but they might help. Can you install gulp-typescript from GitHub and check the performance?

**Comment by Skuriles** [comment]
Hm.
I've tried to install the git repo but it fails with "Filenames too long" error. So I've downloaded it and installed it from folder, but now it says "TypeError: Cannot read property 'typescript' of undefined" on compile...
Never installed npm packages directly from git so maybe I did something wrong?

**Comment by ivogabe** [comment]
The TypeError was actually a mistake of mine, which means that you installed it correctly. That should be fixed now, so can you try again?

**Comment by ivogabe** [comment]
The changes are included in the new release, 3.2.1, so can you install that and check whether this solves your performance issues?

**Comment by Skuriles** [comment]
Will do this tomorrow back on work!

**Comment by Skuriles** [comment]
Ok.. updated to latest version: 
1. no compile (typescript) errors
2. Time has decreased from 5-8 to 3-5 seconds. Seems better now

Thank you!
I will have a look at the compile times while working on the project and come back to you if there are any issues.
Great job
