### ISSUE TITLE
TypeScript 1.4

### ISSUE THREAD

**Issue by pspeter3** [ivogabe/gulp-typescript#53]
TypeScript added 1.4 so I'm excited for this update. http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx

**Comment by ivogabe** [comment]
Thanks for reporting. I've updated the plugin to typescript 1.4. It's in the master now, will update it on NPM soon.

**Comment by pspeter3** [comment]
Awesome! Thank you!

**Comment by xealot** [comment]
:+1:

**Comment by sccolbert** [comment]
:+1: 

Thanks for the effort on this project!

**Comment by michel-kraemer** [comment]
+1

Can't wait for the NPM update.

**Comment by mplatings** [comment]
:+1:

**Comment by ivogabe** [comment]
Released on npm!

**Comment by pspeter3** [comment]
Thanks!

**Comment by sccolbert** [comment]
You rock!
