### ISSUE TITLE
Sourcemaps not generated unless path is passed

### ISSUE THREAD

**Issue by Parziphal** [ivogabe/gulp-typescript#535]
**Expected behavior:**
Get sourcemaps generated in the outDir folder, following the example in the readme:
```javascript
// ...
.pipe(sourcemaps.write())
// ...
```

**Actual behavior:**
Sourcemaps are not generated anywhere, unless I specify a path to the write() function:
```javascript
// ...
.pipe(sourcemaps.write('.')) // a dot, since this path is relative to the outDir.
// ...
```

The only difference between the readme and my gulpfile (shown below) is that I use ts.createProject. I don't if that causes the problem, but it should be noted because no sourcemaps are generated at all if a path isn't passed.

**Your gulpfile:**
```javascript
const tsProject = ts.createProject('tsconfig.json');
gulp.task('scripts', () => {
  const tsResult = tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(tsProject());

  return tsResult.js
    .pipe(sourcemaps.write('.')) // <---
    .pipe(gulp.dest(tsProject.config.compilerOptions.outDir));
});
```

**tsconfig.json**
```json
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "dist",
    "sourceMap": true
  },
```

**Comment by Pajn** [comment]
Sourcemaps without path writes them inline as a comment

**Comment by ivogabe** [comment]
As @Pajn said, this is the correct behavior. The advantages of inlining these sourcemaps are that it requires less configuration and it prevents a lot of hassle.
