### ISSUE TITLE
Some properties of `.tsconfig` are ignored in the transpilation

### ISSUE THREAD

**Issue by enjoythelive1** [ivogabe/gulp-typescript#537]
**Expected behavior:**
Compile to es6 if specified in `.tsconfig`

**Actual behavior:**
Compiles to es3

**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
'use strict';

//Dependencies
let gulp = require('gulp'),
    $ = require('gulp-load-plugins')({
        pattern: ['gulp-*', 'del', 'run-sequence']
    }),
    config = require('./config.json'),
    tsConfig = require('../tsconfig.json');


/**
 * Create typescript project build reference for incremental compilation under watch tasks
 *
 * @link https://github.com/ivogabe/gulp-typescript
 */
let tsProject = $.typescript.createProject('tsconfig.json', {
    // Override package version of typescript to use latest compiler version
    typescript: require('typescript')
});
...

/**
 * Compiles typescript app into js
 */
gulp.task('compile', false, () => {
    let tsResult = gulp.src(tsConfig.files)
        .pipe($.sourcemaps.init())
        .pipe(tsProject($.typescript.reporter.longReporter()));

    return tsResult.js
        .pipe($.sourcemaps.write())
        .pipe(gulp.dest('dist'));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "outDir": "dist",
        "importHelpers": true,
        "sourceMap": true,
        "types": [
            "jasmine"
        ],
        "lib": [
            "esnext"
        ]
    },
    "files": [
        "src/**/*.ts",
        "gulp/**/*.ts"
    ]
}

```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by Spongman** [comment]
i'm seeing this also. specifically in my case, the "files" section seems to be ignored which breaks some build scenarios.

**Comment by ivogabe** [comment]
@enjoythelive1 `target` works for me fine, could you create a small reproduction and share it here? And can you make sure you're using the latest version?

@Spongman Are you using `tsProject.src()`? `files` is working here, so there might be something wrong with your setup. Could you share your setup?

**Comment by IanStorm** [comment]
I am facing a similar problem, but related to the `sourceMap` flag.



**Expected behavior:**
No sourcemaps in the output folder, if `sourceMap` is set to `false` in `.tsconfig`.

**Actual behavior:**
`sourceMap` property is always `true`.

**My gulpfile:**
```javascript
var gulp = require("gulp");
var gulpIf = require("gulp-if");
var sourcemaps = require("gulp-sourcemaps");
var ts = require("gulp-typescript");

var tsProject = ts.createProject("tsconfig.json");
var tsOutDir = tsProject.options.outDir;

gulp.task("ts", function() {
    var stream = gulp.src("src/**/*.ts")
        .pipe(gulpIf(tsProject.options.sourceMap, sourcemaps.init()))
        .pipe(tsProject())
        .pipe(gulpIf(tsProject.options.sourceMap, sourcemaps.write(tsOutDir)))
        .pipe(gulp.dest(tsOutDir));
    return stream;
});

gulp.task("build", ["ts"]);
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "outDir": "dist",
        "sourceMap": false
    }
}
```

**Code**
Not necessary.

When adding `console.log(tsProject.options);` to the above code, it's visible that `sourceMap` is always `true`.
I read that for sourcemaps I should use `gulp-sourcemaps`. But at least the parsing of the `.tsconfig` should work, right? Or is there a misunderstanding?

**Comment by ivogabe** [comment]
@IanStorm Sourcemap settings are overridden by gulp-typescript, to interact with gulp-sourcemaps. With your code, you are thus reading the overridden value, not the original value. Anyways, using `tsProject.options` is not documented in the readme and might thus break in the feature.

**Comment by IanStorm** [comment]
@ivogabe 
Okay, that means you're not officially supporting the way I want to use `gulp-typescript`.
However, I think it's not a big problem, as I can override the settings in the gulpfile instead of setting them in the `.tsconfig`. For sure this is not perfectly clean, but it's an acceptable workaround, I guess.
Thanks for the response. :)

**Comment by ivogabe** [comment]
Closing as the reports for `target` and `files` are inactive and the `sourceMaps` behavior is intended.

**Comment by enjoythelive1** [comment]
Actually, the issue I had was not fault of gulp-typescript, but of my IDE which was compiling the ts to js and I didn't know.
