### ISSUE TITLE
The streams produced by the plugin should emit the "end" event rather than "finish".

### ISSUE THREAD

**Issue by lddubeau** [ivogabe/gulp-typescript#540]
**Expected behavior:**

The streams produced by the plugin should emit the `end` event when there is no more data to be read.

**Actual behavior:**

The streams emit the `finish` event.

**Discussion:**

The streams that the plugin produce are [`Readable` streams](https://nodejs.org/api/stream.html#stream_class_stream_readable). The Node documentation does not define a `finish` event for `Readable` streams. It is defined for `Writable` streams (and anything that implements the `Writable` API, like `Duplex`.).

The analogue of `finish` for `Readable` streams is the [`end` event](https://nodejs.org/api/stream.html#stream_event_end), which unfortunately the plugin does not emit.

`finish` was implemented in response to #245.

I'm not just submitting a PR right off the bat because I think this needs discussion before implementation. For one thing, dropping `finish` immediately would break existing code, like for instance the code people have given as workarounds in #295.

**Comment by ivogabe** [comment]
I thought that gulp-typescript previously would emit both events, but that probably broke in some new version of gulp-typescript (or Node?). Anyways, the generated stream is a Duplex stream so it should emit both events and we don't need to break users by removing the `finish` event.

Also, the stream has two fields, `js` and `dts`, which are readable streams. I'm afraid that they also might not fire the end-event.

Feel free to send a PR!

**Comment by lddubeau** [comment]
I was not precise enough in my description.

When I look at the code I see the "full" stream is a [`CompileStream`](https://github.com/ivogabe/gulp-typescript/blob/0ff2cb47b0bef4c59ea4355b686e3db82a126c17/lib/project.ts#L141) and indeed Duplex. However, the `.js` and `.dts` streams are [`CompileOutputStream`](https://github.com/ivogabe/gulp-typescript/blob/adebb92e273eefd848eca1048451b407f7075ec3/lib/project.ts#L181-L184) and only `Readable`. Yet, all the streams [emit `finish`](https://github.com/ivogabe/gulp-typescript/blob/adebb92e273eefd848eca1048451b407f7075ec3/lib/output.ts#L105-L107):

```
		this.streamFull.emit('finish');
		this.streamJs.emit('finish');
		this.streamDts.emit('finish');
```

Neither `streamJs` nor `streamDts` should emit `finish`, as they are `Readable` but not `Writable` or `Duplex`.

Is there something I'm missing?

I'm unlikely to produce a PR for this in the short term, since getting this cleaned up is not a pressing matter for me. I've worked around it, and there are other issues elsewhere in the TS ecosystem that are more pressing to me at the moment. I wanted to file an issue though so that the problem is reported in case someone else runs into it.

**Comment by ivogabe** [comment]
Ah, I see. That last two lines should then be removed. Though that would be something for the next major release.
