### ISSUE TITLE
Error in `test-run` task (tests failure is never detected)

### ISSUE THREAD

**Issue by demurgos** [ivogabe/gulp-typescript#544]
Hi,
I am currently reviewing the code of the library to solve https://github.com/ivogabe/gulp-typescript/issues/543.

It appears that the `test-run` gulp task has an issue. It [calls the `runTest` function](https://github.com/ivogabe/gulp-typescript/blob/6914e2260af59a9ef533df3d6f1da327f8d46efe/gulpfile.js#L143) and expects the result to possibly be a `failure` object.
The problem is that `runtTest` [only calls its callback once](https://github.com/ivogabe/gulp-typescript/blob/6914e2260af59a9ef533df3d6f1da327f8d46efe/gulpfile.js#L126) and without any argument.
It means that `failure` is always undefined in the task function.

Beside, the `done` variable in `runTest` is unused.

My first goal to solve my initial issue was to write a test case exhibiting it. I think that I'll start by updating the gulpfile/test system first to solve these issues.

What do you think about writing the gulpfile in Typescript? It would have prevented this error.
Gulp auto-detects `gulpfile.ts` and pass it through `ts-node` so it does not change anything about the way the tasks are invoked.

**Comment by ivogabe** [comment]
Thanks @demurgos! I merged your PR. At the long term I'd like to move to a test library such as AVA and write the tests in TypeScript, though I haven't had time for that. Though the tests are already a bit more modern now.
