### ISSUE TITLE
gulp-typescript throwing "TypeScript not installed" when Typescript installed locally

### ISSUE THREAD

**Issue by JamesMilnerUK** [ivogabe/gulp-typescript#547]
**Expected behavior:**

TypeScript is found and the TypeScript is compiled to JavaScript in the build directory by gulp-typescript. I have tried reinstalling all dependencies and no luck unfortunately.

**Actual behavior:**

 ```TypeScript not installed```

Even though my package.json has Typescript stated and it has been installed with Yarn.

```
    "typescript": "^2.6.1",
    "webpack": "^3.0.0",
    "webpack-stream": "^4.0.0"
  }
```

**Your gulpfile:**

```javascript
gulp.task('typescript', function () {
  return gulp.src('components/**/*.ts')
      .pipe(ts({
        outFile: 'tsoutput.js'
      }))
      .pipe(gulp.dest('_built/'));
});
```

**Comment by JamesMilnerUK** [comment]
Apologies I hadn't put the typescript property in the right place:

```
gulp.task('typescript', function () {
  return gulp.src('components/**/*.ts')
      .pipe(ts({
        typescript: require("typescript"),
        outFile: 'tsoutput.js'
      }))
      .pipe(gulp.dest('_built/'));
});

```

Might be worth just defaulting to require("typescript") ?

**Comment by ivogabe** [comment]
It should work without setting the `typescript` property. Could you try removing `node_modules` and re-install your dependencies?
