### ISSUE TITLE
outFile sets path incorrectly as of v3.2.1

### ISSUE THREAD

**Issue by itayronen** [ivogabe/gulp-typescript#553]
Hi,
Im having issues with the outFile option.  
It seems that the output file's path is not set as expected.  

It reminds me of a bug that was resolved on version 3.1.4.  
There was an issue about it #461.  

My current version is: 3.2.3  
Interestingly, when im using version 3.1.4, **everything works perfectly**.  
Also 3.1.7 works. It seems to arise on 3.2.1 (3.2.0 seems broken).

**Expected behavior:**
When using outFile, the output file's 'path' property will be set relative to the tsconfig file.  
The file's base path will be at the tsconfig directory. Making the file's 'relative' property equal to the outFile value.
When the file's relative does NOT equal to the outFile value, then gulp.dest() writes the file in an unexpected directory.

**Actual behavior:**
The file's path is apparently set relative to the current working directrory.  
The file's base path is at the tsconfig directory(as expected), making the file's relative path incorrect.

**In my project:**
The gulpfile is at '{CWD}/gulpfile.js'
The tsconfig is at '{CWD}/src/tsconfig.json'.  
outFile is 'bundle.js'.
**The output file's properties:**  
path = '{CWD}/bundle.js' instead of '{CWD}/src/bundle.js'.
base = '{CWD}/src' (as expected).
relative = '../bundle.js' instead of 'bundle.js'.

**Your gulpfile:**
```javascript
let compilerOptions = {
	module: "amd",
	outFile: "bundle.js"
};

let tsProject = ts.createProject(config.tsconfig, compilerOptions);

gulp.src(config.packageEntriesGlob)
	.pipe(tap((file) => {
		console.log(file.path, file.relative, file.base, file.cwd, "\n");
	}))
	.pipe(tsProject())
	.pipe(tap((file) => {
		console.log(file.path, file.relative, file.base, file.cwd, "\n");
	}))
	.pipe(gulp.dest(config.bundles))
```

**tsconfig:**
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "umd",
    "moduleResolution": "node",
    "strict": true,
    "noEmitOnError": true,
    "removeComments": false,
    "emitDecoratorMetadata": true,
	"experimentalDecorators": true,
  }
}
```

**Comment by ivogabe** [comment]
Looks like the same problem as the last posts in #525. This will be part of the next release. Could you try to download gulp-typescript from GitHub?

**Comment by itayronen** [comment]
I tried installing the package using:  
`npm install --save-dev https://github.com/ivogabe/gulp-typescript.git`  
`npm install --save-dev github:ivogabe/gulp-typescript.git`  
`npm install --save-dev git+https://github.com/ivogabe/gulp-typescript.git`  

But npm is stuck on 'rollbackFailedOptional'. Its an NPM bug...
Do you have a tarball file link? Or a beta version uploaded to npm?

**Comment by ivogabe** [comment]
Strange. You can now install the prerelease with `npm install gulp-typescript@4.0.0-alpha.1`

**Comment by itayronen** [comment]
Sorry for the late answer.
This version (4.0.0-alpha.1) works as expected :)
