### ISSUE TITLE
Reference path for generated definitions is incorrect

### ISSUE THREAD

**Issue by optical** [ivogabe/gulp-typescript#56]
Reference paths in the compiled definitions file are not correct if the output folder is not the same as the source, unless you copy all existing .d.ts files in as a separate task. When you invoke tsc directly and specify the `outDir`, the generated .d.ts files will have the correct paths. This explanation is probably as clear as mud, so hopefully the examples below make the issue more apparent.

Assuming we have a single typescript file, `file.d.ts`, and a definitions file `tsd.d.ts`, all situated in /src/.

file.ts

    /// <reference path="tsd.d.ts" />
    import fs = require('fs');
    
tsd.d.ts
`declare module 'fs' {}`

If our code is in /src/, and we want to place the compiled js in /dist/, along with the definitions, we'd invoke tsc:

`tsc -d --module commonjs --outdir dist .\src\file.ts`
The resulting definition in dist/file.d.ts has a relative path to tsd.d.ts in src.
`/// <reference path="../src/tsd.d.ts" />`

Using gulp-typescript I am attempting to compile using a task like this

	var gulp = require('gulp');
	var eventStream = require('event-stream');
	var tsc = require('gulp-typescript');

	gulp.task('tsc', function () {
		var options = {
			declarationFiles : true,
			sourceRoot: 'src'
		};

		var result = gulp.src(['src/**/*.ts'])
			.pipe(tsc(options));
			
		return eventStream.merge(
			result.dts.pipe(gulp.dest('dist')),
			result.js.pipe(gulp.dest('dist')));
	});

However, the resulting definition in /dist/file.d.ts has a reference of
`/// <reference path="tsd.d.ts" />`

Since these .d.ts files in /src/ aren't copied as a part of the built, the path is wrong as the file is missing. To workaround this we've got a separate step in the build to copy them into /dist/ before running `dts-bundle`. We didn't have this problem using gulp-tsc, as it allows you to specify a `basePath` option which will fix up the reference paths. 

Perhaps there is an option I am missing, or a better approach to solving this, as have a separate step to move over the .d.ts files doesn't feel right and isn't necessary when using tsc directly.

**Comment by ivogabe** [comment]
Thank for reporting. This is kind of how gulp works, when the compilation is done the files are handled to the next plugin and gulp-typescript doesn't know what happens next. So it also doesn't know where the files will be saved. I think this can be solved by adding an option like referencePathRoot, which you can set to '../src' for example. Would that solve your problems?

**Comment by optical** [comment]
Apologies for the delay.

Yes I think that would be the solution here. I'd probably go with outDir to mirror the tsc parameters, but probably doesn't matter too much.

**Comment by ivogabe** [comment]
outDir is implemented in #97
