### ISSUE TITLE
createProject (and tsproject()) ignoring tsconfig file

### ISSUE THREAD

**Issue by CBuntrock** [ivogabe/gulp-typescript#560]
Description: I create a simple gulpfile with passing a path to a tsconfig file but the parameter gets ignored at all.

**Expected behavior:**
Task complains missing tsconfig

**Actual behavior:**
files are getting transpiled (with default settings?)

**Your gulpfile:**
var gulp = require('gulp');
var ts = require('gulp-typescript');
var tsProject = ts.createProject('test123IdontExist.json');

gulp.task('default', ['watch']);

gulp.task('compile', function() {
	var tsResult = tsProject.src().pipe(tsProject());
	tsResult.js.pipe(gulp.dest('L:\\'));

	gulp.src('src/*.html').pipe(gulp.dest('L:\\'));
});

gulp.task('watch', function() {
	gulp.watch('src/*.*', ['compile']);
});

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript

```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json

```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by ivogabe** [comment]
Don't you get a message `The specified path does not exist: [..].json`?
