### ISSUE TITLE
gulp-typescript doesn't resolve @types in outter node_modules

### ISSUE THREAD

**Issue by FunkMonkey** [ivogabe/gulp-typescript#563]
**Expected behavior:**
With a project structure like this, which uses [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/)
```
- workspace
  - node_modules
    - @types
      - node
  - packages
    - package-to-compile
      - tsconfig.json
```

there should not be compiler errors like `error TS2304: Cannot find name 'require'.` or ` error TS2688: Cannot find type definition file for 'node'.` (after adding `node` to `types` in `tsconfig.json`.

**Actual behavior:**

Getting  `error TS2304: Cannot find name 'require'.`

**Your gulpfile:**

```javascript
const gulp = require( "gulp" );
const typescript = require( "gulp-typescript" );

const SRC_GLOB =  "./src/**/*.ts";

var tsProject = typescript.createProject( 'tsconfig.json' );

gulp.task( "build:scripts", function() {
  return gulp.src( SRC_GLOB )
    .pipe( tsProject() )
    .pipe( gulp.dest( "build" ) );
});
```

**tsconfig.json**

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "target": "es2015"
    },
}
```

**Code**

```typescript
import { Observable } from 'rxjs';
import { IPluginLoadInfo } from './iplugininfo';

export default {
  require( { id }: IPluginLoadInfo ) {
    const mod = require( id );
    return Observable.of( { id, factory: mod.default || mod } );
  }
};
```

--------------------------

Just using `tsc` works flawlessly, so it must be something inside `gulp-typescript`!

**Comment by FunkMonkey** [comment]
Ups. Just saw #515 and the solution was just to do `gulp.src( SRC_GLOB, { cwd: 'src' } )`.

Thanks anyway!

**Comment by FunkMonkey** [comment]
Nope, didn't work after all (just didn't do anything in the end because the `SRC_GLOB` was wrong then of course). Could it be related to #422 ?

**Comment by ivogabe** [comment]
I haven't used yarn workspaces myself, so I'm not familiar with those. Could you create a basic example that illustrates the problem, which I can clone and install to see the bug?

**Comment by FunkMonkey** [comment]
Sorry, I was quite busy. I'll test it once I have a little time at the end of september and will creat that basic example for you!

Thanks for your patience :)

**Comment by ianbytchek** [comment]
@ivogabe it is. Trying to migrate an old project and can't get my head around this. Works if add symbolic link for `node_modules` inside the build folder.

**Comment by FunkMonkey** [comment]
@ivogabe Alright, I finally managed to create a test case:
https://github.com/FunkMonkey/gulp-typescript-bug

just do
```bash
yarn install
npm run build-gulp
npm run build-tsc
```

I tested it on windows, not sure if the `run` commands work from the workspace on a different OS. If not, just go to `packages/typescript-test` and do `npm build-gulp` or `npm build-tsc` there.

As you see  `npm build-tsc` works, while `npm build-gulp` doesnt...

Thanks a lot!

**Comment by FunkMonkey** [comment]
@ivogabe any update on this? Thanks!

**Comment by FunkMonkey** [comment]
@ivogabe 

OK, I digged a lot and found the problem. For whatever reason typescript does not traverse the parent `node_modules` folders when the `configFilePath` in the parsed compiler options is not an absolute path!! 

The problem lies in [main.ts#222](https://github.com/ivogabe/gulp-typescript/blob/master/lib/main.ts#L222). Just remove `path.basename` there and maybe replace it with `path.resolve( process.cwd(), tsConfigFileName )` or anything else that makes sense. I just tried it and it works.

Thank you very much!

**Comment by MauricioVives** [comment]
I just had the same problem... took me quite a long (and frustrating) time to test options and search for solutions, but I eventually found this issue. Thanks @FunkMonkey for logging it!

**Comment by Norech** [comment]
Another solution is to use yarn nohoist feature with "**/@types/**" path, on the root project.
You will need to install typings dependencies inside of every subprojects, but at least it works without forking gulp-typescript or using tricky gulp files.

It would be great if this issue was fixed. It could avoid to a lot of people to spend a lot of hours to find why theirs projects are not building, and how to fix it.

**Comment by ivogabe** [comment]
Sorry for the late reply. Thanks @FunkMonkey for the debugging! @lddubeau has opened a PR, I'll review that tomorrow. So we'll have this issue fixed soon!
