### ISSUE TITLE
Error when compiling with gulp-typescript.

### ISSUE THREAD

**Issue by mirthlaj** [ivogabe/gulp-typescript#564]
When compiling with gulp-typescript I get an error.
With tsc everything works as expected and no errors are shown.

I am using gulp-typescript@4.0.1 and I also tried version 3.0.2 as suggested here #https://github.com/ivogabe/gulp-typescript/issues/421.

**Expected behavior:**
compiled typescript files
**Actual behavior:**

> [18:20:21] Starting 'default'...
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(468,33): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(468,72): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(747,39): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(747,69): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(747,107): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/src/routes/root.ts(3,7): error TS4023: Exported variable 'router' has or is using name 'Router' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> D:/Code/NodeJS/typescript-template/src/routes/users.ts(3,7): error TS4023: Exported variable 'router' has or is using name 'Router' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> D:/Code/NodeJS/typescript-template/src/server.ts(6,7): error TS4023: Exported variable 'app' has or is using name 'Express' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> TypeScript: 5 semantic errors
> TypeScript: 3 declaration errors
> TypeScript: 3 emit errors
> TypeScript: emit failed
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(468,33): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(468,72): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(747,39): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(747,69): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/@types/bluebird/index.d.ts(747,107): error TS2304: Cannot find name 'Map'.
> D:/Code/NodeJS/typescript-template/node_modules/pg-promise/typescript/pg-promise.d.ts(5,27): error TS2497: Module '"D:/Code/NodeJS/typescript-template/node_modules/pg-promise/typescript/ext-promise"' resolves to a non-module entity and cannot be imported using this construct.
> src\routes\root.ts(3,7): error TS4023: Exported variable 'router' has or is using name 'Router' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> src\routes\users.ts(3,7): error TS4023: Exported variable 'router' has or is using name 'Router' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> src\server.ts(6,7): error TS4023: Exported variable 'app' has or is using name 'Express' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> TypeScript: 6 semantic errors
> TypeScript: 3 declaration errors
> TypeScript: 3 emit errors
> TypeScript: emit failed
> [18:20:36] Finished 'default' after 15 s

**Your gulpfile:**

```
gulp.task('default', () => {
	var src = gulp
		.src(['./src/**/*.ts'])
		.pipe($.typescript({
			declaration: true
		}));
		
	var test = gulp	
		.src(['./test/**/*.ts'])
		.pipe($.typescript({
			declaration: true
		}));
		
	return merge([
		src.pipe(gulp.dest('output/src')),
		test.pipe(gulp.dest('output/test'))
	])
});
```

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript

```

**tsconfig.json**
*Include your tsconfig, if related to this issue.*
```json

{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "output"
    },
    "include": [
        "src/**/*",
        "test/**/*"
    ]
}

```

**Code**

*Include your TypeScript code, if necessary.*
```typescript

const router = express.Router();

```

**Comment by mirthlaj** [comment]
I resolved some errors by running `npm install --save-dev @types/es6-shim`

Now I only have this ones:

> src\routes\root.ts(3,7): error TS4023: Exported variable 'router' has or is using name 'Router' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> src\routes\users.ts(3,7): error TS4023: Exported variable 'router' has or is using name 'Router' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.
> src\server.ts(6,7): error TS4023: Exported variable 'app' has or is using name 'Express' from external module "D:/Code/NodeJS/typescript-template/node_modules/@types/express-serve-static-core/index" but cannot be named.

**Comment by mirthlaj** [comment]
`import * as express from 'express';

import * as root from './routes/root';
import * as users from './routes/users';

const app = express();

app.use('/', root.router);
app.use('/', users.router);

app.listen(process.env.PORT, () => {
    console.log(`Listening on port ${process.env.PORT}`);
});

export default app;`

`import * as express from 'express';

const router = express.Router();

router.get('/', (req, res, next) => {
    res.send({
        message: 'Hello World!'
    });
});

export {router};`

This is my code in those files

**Comment by mirthlaj** [comment]
I solved it by explicitly annotating the router and the express variables.

`const router: express.Router = express.Router();`
and
`const app: express.Express = express();`

**Comment by ivogabe** [comment]
With your configuration, you are not using the tsconfig file. You need to use `ts.createProject('./tsconfig.json')`, see the readme for more information.

**Comment by trusktr** [comment]
I have this issue too. Seems that taking a `tsconfig.json`'s content and passing it into `ts()` simply doesn't cut it. Using `ts.createProject('path/to/project/tsconfig.json')` did do the trick though.

I'm curious why `ts(compilerOptions)` doesn't work though.

[`ts-node`](https://github.com/TypeStrong/ts-node) somehow works fine when I pass it an object which is the `compilerOptions` from my project `tsconfig`. Maybe something to look into.

**Comment by trusktr** [comment]
Ok, I thought something was going wrong. Turns out I only get an issue like the one above during rebuilds. So I made a new issue for that: https://github.com/ivogabe/gulp-typescript/issues/621
