### ISSUE TITLE
All files changed in ./dist, but not with pure tsc

### ISSUE THREAD

**Issue by claudioc** [ivogabe/gulp-typescript#572]
Using:
Gulp 4
TypeScript 2.8.1 (same issue with 2.6.2, though)
Gulp-typescript: 4.x
macOS

**Expected behavior:**
Somehow `tsc -w` understands better what to compile/create in the destination folder and leaves a lot of file untouched when only save on of them.

**Actual behavior:**
Apparently, using `gulp-typescript` all the files are compiled and/or touched. This creates a problem with `ava` (the tester) because it cannot run smoothly only on incrementally-compiled files which means that every time I save _any_ file, ava will detect a change in _all_ files, and runs all the tests again

Before using gulp, I used this npm task to compile and restart my server:

```
    "start": "NODE_ENV=development tsc-watch --outDir ./dist --onSuccess 'npx nodemon -V -w jingo -w config.json jingo -c config.json'",
```

**Your gulpfile:**
```javascript
const gulp = require('gulp')
const ts = require('gulp-typescript')
const spawn = require('child_process').spawn

const tsProject = ts.createProject('tsconfig.json', {
  // With `isolatedModules` compilation goes down from 5 seconds to 1
  isolatedModules: true,
  typescript: require('typescript')
})

let node
const MY_SERVER = ['jingo', '-c', 'config.json']

const server = () => {
  if (node) {
    node.kill()
  }

  node = spawn('node', MY_SERVER, { stdio: 'inherit' })
  node.on('close', code => {
    if (code === 8) {
      gulp.log('Error detected, waiting for changes...')
    }
  })
}

gulp.task('scripts', () => {
  const tsResult = gulp.src('src/**/*.ts').pipe(tsProject())
  return tsResult.js.pipe(gulp.dest('dist'))
})

gulp.task('templates', () => {
  return gulp.src('src/**/*.hbs').pipe(gulp.dest('dist'))
})

gulp.task('watch', done => {
  const tsWatcher = gulp.watch('src/**/*.ts', gulp.series('scripts', 'serve'))
  const hbsWatcher = gulp.watch('src/routes/**/template.hbs', gulp.series('templates', 'serve'))

  tsWatcher.on('change', log)
  hbsWatcher.on('change', log)

  done()

  function log(path) {
    console.log(`File ${path} was changed`)
  }
})

gulp.task('serve', done => {
  server()
  done()
})

gulp.task('default', gulp.series(gulp.parallel('scripts', 'templates'), 'watch', 'serve'))
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "strictNullChecks": false,
    "target": "es6",
    "outDir": "dist/",
    "inlineSourceMap": true,
    "noUnusedParameters": false,
    "noUnusedLocals": true,
    "pretty": true,
    "removeComments": true,
    "allowJs": true,
    "lib": [
      "es2016"
    ],
    "baseUrl": "src",
    "paths": {
      "@server": ["server"],
      "@sdk": ["sdk/index"],
      "@middlewares/*": ["middlewares/*"],
      "@events/*": ["events/*"],
      "@lib/*": ["lib/*"],
      "@routes/*": ["routes/*"]
    }
  },
  "include": [
    "index.ts",
    "src/**/*.ts"
  ],
  "compileOnSave": true,
  "buildOnSave": false
}
```

**Comment by ivogabe** [comment]
We really need to emit all files. If you would for instance run a bundler after gulp-typescript, it would obviously need to have all files on the stream.

There are gulp plugins that filter out the unchanged files. You could add such plugin after gulp-typescript to only write the changed files.

**Comment by kxpvcr** [comment]
`[gulp-changed](https://www.npmjs.com/package/gulp-changed)` comes to mind, we've used it before.

**Comment by ivogabe** [comment]
You could indeed use something like gulp-changed. You would then need to add it *after* gulp-typescript, whereas you'd normally use it before your plugin. gulp-typescript requires to have all sources, as we need have type info of all files.
