### ISSUE TITLE
Is `.vue` files no supported?

### ISSUE THREAD

**Issue by thomthom** [ivogabe/gulp-typescript#578]
I have a project where I am compiling single file Vue components `.vue` files and using TypeScript. Using `tsc` the project compiles without errors. But when I try to set it up via `gulp` and `gulp-typescript` I get errors.

The TypeScript manual says you need to declare a shim: (https://github.com/Microsoft/TypeScript-Vue-Starter#single-file-components)

```
// src/vue-shims.d.ts

declare module "*.vue" {
    import Vue from "vue";
    export default Vue;
}
```

But this doesn't appear to be picked up. Actually, I have some other `.d.ts` files in my `dialogs` directory which I need for `tcs` to compile the project. But when I use `gulp-typescript` I get errors that all relate to that. In addition to not being able to resolve `.vue` files I get errors like:

```
dialogs\runner.ts(113,7): error TS2304: Cannot find name 'sketchup'.
```

But I have a sketchup.d.ts that describe this global object - and `tsc` handles that without problems.

So I'm not sure if this is an issue that relates to resolving `.vue` files, or whether it's related to `gulp-typescript` not picking up the `.d.ts` files?

**Expected behavior:**
That is should compile.

**Actual behavior:**

```
dialogs\runner.ts(16,22): error TS2307: Cannot find module './components/su-button.vue'.
```

**Your gulpfile:**

```
const tsProject = ts.createProject('./tsconfig.json');

function build_dialog(filename) {
  return gulp.src(path.join(paths.sources.dialogs, filename))
    .pipe(tsProject())
    .pipe(gulp.dest(paths.destinations.js));
}

gulp.task('runner', () => {
  return build_dialog('runner.ts');
});

gulp.task('dialogs', [
  'runner',
]);
```

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript

```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compilerOptions": {
        "outDir": "./temp/",
        "sourceMap": true,
        "strict": true,
        "noImplicitReturns": true,
        "module": "es2015",
        "moduleResolution": "node",
        "target": "es6"
    },
    "include": [
        "./dialogs/*.ts"
    ]
}
```

**Code**

*Include your TypeScript code, if necessary.*
```typescript
// runner.ts
"use strict";

import Vue from "vue";
import * as suErrorHandler from "./ts/su-error-handler";

Vue.config.errorHandler = suErrorHandler.vueErrorHandler;
window.onerror = suErrorHandler.globalErrorHandler;

import SUButton from "./components/su-button.vue";
```

**Comment by ivogabe** [comment]
I would guess that `src/vue-shims.d.ts` is not passed to the compiler. That can be caused by the argument to `gulp.src`. Could you try to use `tsProject.src()` instead of `gulp.src(..)`?

Alternatively you could use `gulp.src(path.join(paths.sources.dialogs, filename), 'src/vue-shims.d.ts')`.

**Comment by thomthom** [comment]
Yes, you are right, using `tsProject.src()` allowed it to compile. Though, after that I realized I have another issue. All `.ts` files compile to JS, but the `<script>` elements in `.vue` isn't processed. (That being said, `tsc` also won't follow `.vue` files. So I'm not sure how to set up gulp to process `.vue` files.

Is there a way this `gulp-typescript` package can handle `.vue` files?

**Comment by ivogabe** [comment]
I'm afraid there is no way to compile the `<script>` elements. At least, I don't know of one. However I think its good practice to put your scripts in a `.ts` file.

**Comment by thomthom** [comment]
hmm... is that what people are doing with Vue Single File and TS? I thought Vue Single File was intended to keep everything in the same file.

But I can work with that.
