### ISSUE TITLE
Pipe output directly into browserify

### ISSUE THREAD

**Issue by stefansedich** [ivogabe/gulp-typescript#58]
Is this possible? at the moment I compile my ts to dist/compiled-ts and then run browserified on my index.js in this directory, after my build I then delete the directory.

Does anyone have any nicer tips for doing it in one go without the intermediate directory?

The tasks I am using look something like:

gulp.task('build:typescript', function() {
	var tsResult = gulp.src('./src/**/*.ts')
	   .pipe(ts({
	   	   sortOutput: true,
	       declarationFiles: true,
	       noEmitOnError: true,
	       module: 'commonjs',
	       target: 'ES5'
	   }));

	var js = tsResult.js
	    .pipe(gulp.dest('./dist/ts-build'));

	var dts = tsResult.dts
		.pipe(concat('foo.d.ts'))
		.pipe(gulp.dest('./dist/typings'));

	return es.merge(js, dts);
});

gulp.task('build:browserify', ['build:typescript'], function() {
  	var browserified = transform(function(filename) {
	    var b = browserify(filename);
	    return b.bundle();
	});

	return gulp.src('./dist/ts-build/index.js')
    	.pipe(browserified)
    	.pipe(rename('foo.js'))
    	.pipe(gulp.dest('./dist'));
});

**Comment by ivogabe** [comment]
I don't think that's possible, since browserify doesn't work with gulp input streams if I'm not mistaken. It must open files from the filesystem, so you can't directly pipe to browserify.

**Comment by jedmao** [comment]
@ivogabe that is an accurate statement.

**Comment by stefansedich** [comment]
Cool thanks guys, I was assuming as much but wanted to make sure I had not missed some voodoo magic somewhere.


Cheers
