### ISSUE TITLE
Node versions supported?

### ISSUE THREAD

**Issue by rexxars** [ivogabe/gulp-typescript#584]
Hi,

The `package.json` file does not declare which node versions are supported. I'm trying to use this as part of a project which supports Node 6, but it seems the version of `source-map` that is depended on is node 8 and above. Would you consider downgrading to `source-map@^0.5.6`?

**Comment by ivogabe** [comment]
The new version of `source-map` included some performance improvements, so I would like to keep this version. They are now using WebAssembly, which requires Node 8+. Is there a reason you can't upgrade to Node 8+?

Related: mozilla/source-map#313

**Comment by ivogabe** [comment]
Though we should add an `engine` field to `package.json` to denote this requirement.
