### ISSUE TITLE
compiler errors kill gulp-watch

### ISSUE THREAD

**Issue by Spongman** [ivogabe/gulp-typescript#585]
can't post details, but typescript compiler errors cause gulp-watch to stop responding to file changes.

all packages are up-to-date.

the compiler errors, which are expected, are followed by this (new) suspicious text:
````
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
(node:1256) UnhandledPromiseRejectionWarning: Error: TypeScript: Compilation failed
    at Output.mightFinish (C:\myproject\node_modules\gulp-typescript\release\output.js:130:43)
    at applySourceMap.then.appliedSourceMap (C:\myproject\node_modules\gulp-typescript\release\output.js:43:22)
(node:1256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by k8w** [comment]
+1

**Comment by samjudge** [comment]
Exact same issue here

**Comment by AKApumkin** [comment]
+1, version 4.0.2 has a stable version if anyone needs a quick fix.

**Comment by ivogabe** [comment]
This is an effect of #295. We now crash on compiler errors, which is especially desired in a CI context. However, for a watch build, you don't want to crash. When you install gulp 4, gulp will catch the error for you and continue working.

The solution by Sam is a good option if you cannot upgrade to Gulp 4 yet.

I'll keep this issue open, as you shouldn't get a `UnhandledPromiseRejectionWarning`. I will investigate that.
