### ISSUE TITLE
NPM installs pre released version by default

### ISSUE THREAD

**Issue by dcavanagh** [ivogabe/gulp-typescript#586]
**Expected behavior:**
Expected npm install `--save-dev gulp-typescript` to install version 4 not 5.0.0-alpha.3

maybe this will work?
npm publish --tag next
as described in this [post](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420) 

**Actual behavior:**
installs 5.0.0-alpha.3

**Your gulpfile:**
N/A
*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript

```

**tsconfig.json**
N/A
*Include your tsconfig, if related to this issue.*
```json

```

**Code**
N/A
*Include your TypeScript code, if necessary.*
```typescript

```

**Comment by crash-dive** [comment]
Just wanted to add that, as you would expect, this is also an issue if installing via yarn.

If we run yarn outdated on our repos it complains that we are not using the latest version and suggests we upgrade to the alpha.

**Comment by Neonit** [comment]
**Four months** later. Also got 5 alpha automatically. It's buggy, you really should not distribute this by default.

**Comment by ivogabe** [comment]
Sorry for the late response. It's annoying that npm marks alpha releases as latest and will install them by default. Anyway, I just published 5.0.0, see [the release notes](https://github.com/ivogabe/gulp-typescript/releases/tag/v5.0.0), so this can be closed. I'll keep this in mind for future alpha releases.
