### ISSUE TITLE
Can't resolve `lib.d.ts` when typescript is installed into host package

### ISSUE THREAD

**Issue by whitneyit** [ivogabe/gulp-typescript#59]
Given the following `package.json` file:

```json
{
  "dependencies": {},
  "devDependencies": {
    "typescript": "^1.4.0",
    "gulp-typescript": "^2.3.0"
  }
}
```

The `typescript` package does not get installed into the `./node_modules/gulp-typescript/node_modules` folder and as such the reference to to `lib.d.ts` file fomr [host.js](https://github.com/ivogabe/gulp-typescript/commit/fb36ee1f3cf91b19e08d976ad28e94ae3cc304f3#diff-6d01ce8f4b1bc44373e106ec5db7a765R14) does not find the file.

**Comment by horiuchi** [comment]
:+1:

**Comment by itajaja** [comment]
:+1: happens to me as well...
