### ISSUE TITLE
Function for the Project type which return an array of filenames

### ISSUE THREAD

**Issue by opuzakov** [ivogabe/gulp-typescript#594]
Hello guys. I didn't find any function for the Project type, which return an array of filenames. I want to use this function for the incremental compilation. Is it possible to add this?

**Comment by ivogabe** [comment]
You could do that with an event listener on the stream:

```js
tsProject.src()
  .on('data', (file) => console.log(file.path))
  .pipe(tsProject())
  .pipe(...)
```

This code will log all file paths to the console. Instead you could push them to an array.

As you plan to use this for incremental compilation, I want to warn you that you could get strange behavior, as the TypeScript compiler needs all files for type information. `isolatedModules` might be a simpler and better alternative.

**Comment by opuzakov** [comment]
Thank you for the information
