### ISSUE TITLE
Allow to read declarations from the stream

### ISSUE THREAD

**Issue by pepone** [ivogabe/gulp-typescript#603]
Is there an option to read the declarations from the stream?

I have a setup like this

```
const tsc = require("gulp-typescript");
...
pump([
    gulp.src([path.join(root, "*.ice"), "Client.ts"]),
    // slice2js generated .d.ts declarations and add them to the stream
    slice2js({include: [root], args: ["--typescript"], dest: root}), 
    filter("*.ts"),
      // Can I get TS compiler to use the declarations that are on the stream?
      tsc({....}),
    filter("*"),
    gulp.dest(root)
], cb);
```

**Comment by pepone** [comment]
I see what you say but I think my use case is different, slice2js is generating both JavaScript and TypeScript declarations and putting then in the gulp stream, I was trying to get the TS compiler to use the declarations directly from the gulp stream without need writing them to disk

So that imports in `Client.ts` can be resolve to files in the gulp stream rather than to files from disk

**Comment by ivogabe** [comment]
I see, I think [gulp-filter](https://www.npmjs.com/package/gulp-filter) provides the functionality you need.
