### ISSUE TITLE
TypeError: Cannot destructure property `extends` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by bennyn** [ivogabe/gulp-typescript#604]
**Description:**

The `gulp-typescript` docs [have written](https://github.com/ivogabe/gulp-typescript/tree/v5.0.0#using-tsconfigjson) that you can replace `gulp.src(...)` with `tsProject.src()` to load files based on the tsconfig file. I tried to do that but it does not work. My gulp task `works` uses `gulp.src` and works. My gulp task `fails` uses `tsProject.src` and fails. 😢

**Tested with:**

- `gulp` v4.0.0
- `gulp-typescript` v5.0.0
- `typescript` v3.2.1

**Expected behavior:**

Compiled output

**Actual behavior:**

Compilation error:

> TypeError: Cannot destructure property `extends` of 'undefined' or 'null'.

**gulpfile.js:**

```javascript
const gulp = require('gulp');
const ts = require('gulp-typescript');

const tsConfig = {
  declaration: true,
  files: 'test.ts',
  outDir: 'dist'
};

const tsProject = ts.createProject(tsConfig);

gulp.task('works', function() {
  return gulp.src('test.ts')
    .pipe(tsProject())
    .pipe(gulp.dest(tsConfig.outDir));
});

gulp.task('fails', function() {
  return tsProject.src()
    .pipe(tsProject())
    .pipe(gulp.dest(tsConfig.outDir));
});
```

**test.ts**

```typescript
const text: string = 'Hello World!';
```

**Comment by ivogabe** [comment]
Hi Benny, from your configuration, it seems you're not using the tsconfig file and thus cannot use the `.src()` function. You must use a `tsconfig.json` file to create the tsProject, like so:
```js
const tsProject = ts.createProject('./tsconfig.json');
```

Can you verify whether that works for you?

**Comment by bennyn** [comment]
Thanks for your super fast reply! 

When using ` ts.createProject('./tsconfig.json')` it works! But now I am getting a little confused because your [main.d.ts](https://github.com/ivogabe/gulp-typescript/blob/v5.0.0/release/main.d.ts#L48) indicates that `settings` can be given as first parameter to `ts.createProject`. So why do I need to enter a file path now?

**Comment by ivogabe** [comment]
`createProject` indeed also accepts a settings object. However, the `.src` method can only be used when you passed it a tsconfig file. We need to have the file path of that tsconfig file to be able to resolve files.

For the use case of modifying some options, you can specify those as the second argument:
```js
const tsProject = ts.createProject('./tsconfig.json', { whatever: true });
```
