### ISSUE TITLE
Support tsconfig.json

### ISSUE THREAD

**Issue by jmatthiesen** [ivogabe/gulp-typescript#66]
Here's an upcoming change in the TypeScript compiler: https://github.com/Microsoft/TypeScript/issues/1667

This will bring support for a new tsconfig.json file, which can contain build settings and file paths for use by other tools. I'd like to be able to configure my TypeScript task in Gulp to merely pull in the tsconfig.json file for build settings instead of defining these compiler options, etc. in the gulpfile directly.

**Comment by ivogabe** [comment]
I will include that when TypeScript 1.5 is released. I'm currently thinking about how the api should look.

**Comment by cmichaelgraham** [comment]
I'd like to 2nd the request.  [Atom-TypeScript](https://github.com/TypeStrong/atom-typescript) supports it and it is VERY useful !!  And also I'd like to encourage you to hurry ;)

**Comment by jdanyow** [comment]
:+1:

**Comment by EisenbergEffect** [comment]
@ivogabe Thanks for the great work you are doing here. The Aurelia team would be very interested in seeing you add this feature. Looking forward to it.

**Comment by ivogabe** [comment]
I'll try to take a look at this soon.

@EisenbergEffect May I ask where you are using TypeScript? I thought you were using Babel for Aurelia?

**Comment by EisenbergEffect** [comment]
We are currently working on generating TS definitions from our ES6 code and we are investigating other options for the future which might involve publishing TS source code in addition to ES6 code.

**Comment by cmichaelgraham** [comment]
Here's [a description](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/generating-aurelia-type-definitions.md) of what we're trying to do.  We have the build working from within Atom using the Atom-TypeScript package.

The objective is to replace that part of the process with Gulp via Gulp-TypeScript :)

**Comment by ivogabe** [comment]
I think you can implement this even without using tsconfig.json (as a temporary solution). Are there parts where you get stuck at the moment?

**Comment by cmichaelgraham** [comment]
well, it pulls typescript from github master.  i'm getting an error deep in the typescript compile.  could very well be the merge last night for decorators.

here's the error:

```
mgraham@PRIETO /c/cmg/cmg/aurelia-typescript/aurelia-ts-lib/aurelia-ts (master)
$ gulp scripts
[08:34:28] Using gulpfile c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-t
s\gulpfile.js
[08:34:28] Starting 'scripts'...
c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-ts\node_modules\typescript\
bin\typescript.js:1205
                throw new Error("Debug Failure. False expression: " + (message
                      ^
Error: Debug Failure. False expression: isDeclarationVisible unknown: SyntaxKind
: 208
    at Object.assert (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-ts\no
de_modules\typescript\bin\typescript.js:1205:23)
    at Object.fail (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-ts\node
_modules\typescript\bin\typescript.js:1210:19)
    at determineIfDeclarationIsVisible (c:\cmg\cmg\aurelia-typescript\aurelia-ts
-lib\aurelia-ts\node_modules\typescript\bin\typescript.js:9696:34)
    at isDeclarationVisible (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aureli
a-ts\node_modules\typescript\bin\typescript.js:9702:41)
    at getIsDeclarationVisible (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aur
elia-ts\node_modules\typescript\bin\typescript.js:9128:22)
    at c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-ts\node_modules\type
script\bin\typescript.js:9123:82
    at Object.forEach (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-ts\n
ode_modules\typescript\bin\typescript.js:617:30)
    at hasVisibleDeclarations (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aure
lia-ts\node_modules\typescript\bin\typescript.js:9123:20)
    at Object.isSymbolAccessible (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\a
urelia-ts\node_modules\typescript\bin\typescript.js:9079:57)
    at Object.trackSymbol (c:\cmg\cmg\aurelia-typescript\aurelia-ts-lib\aurelia-
ts\node_modules\typescript\bin\typescript.js:18257:53)
```

**Comment by ivogabe** [comment]
That's strange, will take a look at it. Can you try it with an older version from github?

**Comment by cmichaelgraham** [comment]
Yeah - i'll experiment with that. If you have info on how to get the version as of a particular commit, that would help - bit of a noob on that :smile:

**Comment by ivogabe** [comment]
You can use `"Microsoft/TypeScript#commit"` in your package.json file. It's a good idea to lock versions of dependencies, since new versions might break something.

**Comment by cmichaelgraham** [comment]
you do good work, sir !!!!  thanks !!!!

**Comment by ToddThomson** [comment]
@ivogabe Thank-you for your work! I also ask that you support the typescript compiler -p arg for project builds.

**Comment by ivogabe** [comment]
@cmichaelgraham I've tested gulp-typescript against the new version and the tests passed. Your error has probably something to do with ES6 style imports. Those are not fully implemented yet in the compiler I think, declaration emitting is probably (partial) missing. This should be completed in the next stable release.

**Comment by cmichaelgraham** [comment]
thank you, @ivogabe - i appreciate your efforts !!

**Comment by cmichaelgraham** [comment]
@ivogabe - getting Gulp-TypeScript to build Aurelia `.ts` files and generate `.d.ts` and ES6 `.js` files is VERY important to @EisenbergEffect and the Aurelia team.

I am sincerely grateful for any help you can provide.

I've been trying to reconcile the different behavior I see when compiling using [Atom-TypeScript](https://github.com/TypeStrong/atom-typescript) and compiling using `Gulp-TypeScript`.

I did play with different commit versions of the TypeScript compiler, but get consistent behavior.  I don't think this is the issue.

I keep thinking that the difference in behavior between Atom-TypeScript and Gulp-TypeScript must be in the `CompilerOptions` that are being sent to the TypeScript compiler.

I can't seem to get `Gulp-TypeScript` to emit ES6 `.js`.  I get an error if I don't specify `module`, but if I set it to `amd`, I get the amd style output even though I specify `es6` for `target`.

The options for Gulp-TypeScript are specified in [gulpfile.js](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/gulpfile.js)
The options for Atom-TypeScript are specified in [tsconfig.json](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/tsconfig.json)

From [dependency-injection/index.ts](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/dependency-injection/index.ts)
Atom-TypeScript generates [dependency-injection/index.js](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/output/dependency-injection/index.js) and [dependency-injection/index.d.ts](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/output/dependency-injection/index.d.ts)
Gulp-TypeScript generates [[dependency-injection/index.js](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/output-gulp/dependency-injection/index.js) and [dependency-injection/index.d.ts](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/aurelia-ts-lib/aurelia-ts/output-gulp/dependency-injection/index.d.ts)

**Comment by ivogabe** [comment]
I think I found it, you need to do this:
```
cd node_modules/TypeScript
npm install
npm install -g jake
jake local
jake LKG
```
TypeScript works with a LKG (last known good), which hasn't been updated for about two weeks on their repository. You need to do that manually. After that, you can remove the `module` option from your gulpfile.

**Comment by cmichaelgraham** [comment]
pure genius, @ivogabe !!  that fixed it right up.  i am so grateful for your help :)

**Comment by EisenbergEffect** [comment]
@ivogabe Thanks for helping us out on this!

**Comment by ToddThomson** [comment]
The problem with a gulp plugin supporting the -p tsconfig.json feature is that there is no vinyl fs src stream. It looks like a vinyl adaptor for the tsconfig.json project file will be needed to provide the src stream. @ivogabe I would be interested in what your thoughts are.

**Comment by ivogabe** [comment]
I was thinking about something like:

1
```javascript
gulp.src('tsconfig.json')
  .pipe(typescript.resolveProjects())
  // You can add a typescript preprocessor here
  .pipe(typescript({ noExternalResolve: true }))
```

2
```javascript
gulp.src('tsconfig.json')
  .pipe(typescript())
```

3
```javascript
gulp.src(['tsconfig.json', 'src/**/*.ts'])
  .pipe(typescript({ noExternalResolve: true }))
```
I think these 3 should be supported in gulp-typescript.

A new filter based on tsconfig files might also be useful.

**Comment by ToddThomson** [comment]
@ivogabe - The use of tsconfig.json as the single source file for the gulp pipeline does not feel right to me. I think that a typescript project built with tsc -p should be handled by a node app. I'm going to prototype this to see what the pros and cons are.

**Comment by ivogabe** [comment]
@ToddThomson You're right about that, style 2 is also not consistent with other features of gulp-typescript. But I think option 1 is an imported use case, you could see typescript.resolveProjects as a gulp.src alternative, that only loads files. tsconfig.json is a standard, users add their list of files there and they don't want to have that list of files on two different locations.

 Using source maps would still be possible that way:
```javascript
gulp.src('tsconfig.json')
  .pipe(typescript.resolveProjects())
  .pipe(sourcemaps.init())
  .pipe(typescript({ noExternalResolve: true }))
  .pipe(sourcemaps.write())
```

**Comment by ToddThomson** [comment]
@ivogabe Yes. Typescript 1.5 now exports parseConfigFile() so the project files (names ) could easily be streamed through the pipeline. I'm not sure about the compilerOptions though ( I haven't looked at this ).
I've written a prototype node module that handles this ( as well as compilation as it is an easy step ). However, I'm more interested in augmenting the tsconfig.json file to support module bundles. I'm experimenting with that right now. I'll share the code when I'm done.

**Comment by niemyjski** [comment]
+1, it also has an out property that concats to a single file.. I need this really really badly.

**Comment by cbeams** [comment]
@niemyjski I'm looking forward to tsconfig support as well, but in the meantime the `out` option to gulp-typescript can already achieve output to a single .js file: https://github.com/ivogabe/gulp-typescript#options

**Comment by niemyjski** [comment]
I don't think that works when you are using modules does it? I'm currently running into this behavior: 

![image](https://cloud.githubusercontent.com/assets/1020579/7353071/87a50d26-ecd6-11e4-96de-ba63459dc48f.png)

![image](https://cloud.githubusercontent.com/assets/1020579/7353075/8a792de8-ecd6-11e4-9e12-1503b4cdddbf.png)

When I tried to use this node module. I was running into issues where it was trying to concat everything and there were errors due to the module defs. Is this still an issue or is there a sample?

**Comment by markogresak** [comment]
To everyone who desperately needs support for project config (I know it's a dirty fix, but hey, it works):

    require('child_process').exec("[path/to/node_modules]/typescript/bin/tsc -p [path/to/tsconfig.json]");

Also requires typescript installed locally. If you don't want that, remove the path part and use just the `typescript -p [path/to/tsconfig.json]`.

**Comment by ivogabe** [comment]
As a temporary solution I'd use:
```javascript
var tsconfig = require('./tsconfig.json');

return gulp.src(tsconfig.files)
  .pipe(typescript(tsconfig.compilerOptions))
  .pipe(gulp.dest('release'))
```

A tsconfig file is only a different way to write your configuration, there are **not** new options you can specify to the compiler.

@niemyjski The `out` option does work with internal modules (namespaces), not with external modules (commonjs, amd, systemjs). It looks like you are using internal modules. Tsconfig won't change your output.

**Comment by markogresak** [comment]
@ivogabe would this support custom forks of Typescript? Also how would `outDir` option work with `gulp.dest`?

**Comment by ivogabe** [comment]
@markogresak you can use a fork like this:
```javascript
tsconfig.typescript = require('my-fork-of-typescript');
```

Currently `outDir` is not supported, but you can just pass the release directory to gulp.dest. Probably this will work:
```javascript
.pipe(gulp.dest(tsconfig.compilerOptions.outDir));
```

**Comment by markogresak** [comment]
Does the typescript compiler support streams? What I'm asking is if there is `outDir` option set, will this make typescript compiler output the files to `outDir`, or into the stream? Not a hard thing to fix, but just something to be aware of.

**Comment by ivogabe** [comment]
gulp-typescript doesn't write to the file-system, only to the stream. If outDir will be supported, it will change the paths of the files that are written to the output stream. Plugins after gulp-typescript will then see the new paths.

**Comment by ivogabe** [comment]
I've implemented outDir in #97. Since all options of TypeScript are now supported, the next step will be to implement tsconfig. The design I'll implement will look like:
```javascript
var tsProject = ts.createProject('tsconfig.json');
[...]
return tsProject.src()
    .pipe(ts(tsProject))
    .pipe(gulp.dest('release'))
```

The tsconfig file will not be a part of the stream. That's because:
1. It will make it easier to implement
2. It will make gulpfiles cleaner
3. I didn't see use-cases for them
4. It keeps the stream universal (only ts files), which makes it easier to add a preprocessor.

You can specify extra options like this:
```javascript
var tsProject = ts.createProject('tsconfig.json', {
    typescript: require('typescript-fork'),
    sortOutput: true
});
```

**Comment by ivogabe** [comment]
Implemented in PR #99.

**Comment by lilred** [comment]
How does outDir support work with `tsconfig.json`?

**Comment by ivogabe** [comment]
You can just set it like any other option. That will only change the virtual file paths, when you write the files to disk you still need to specify the directory as an argument of `gulp.dest`.
