### ISSUE TITLE
Add Typescript 4 to list of peer dependancies

### ISSUE THREAD

**Issue by tkilb** [ivogabe/gulp-typescript#668]
In my gulp build, I would like to leverage the tsconfig compiler option "jsx": "react-jsx"

I believe Typscript 4.1 + is required to make this happen.  May I trouble you to add TS 4 to the peer deps?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#react-17-jsx-factories

**Comment by mannie-exe** [comment]
Hey -- is there any reason why this was closed?

I'm trying to install `gulp-typescript` in a package that's already running `typescript@4.7.0-dev.20220408` -- I'm able to install everything using `npm i --force` just fine, and then use the nightly TypeScript build by specifying the `typescript` key on `createProject`'s settings object.

However, I would at least like to be able to use TypeScript 4.x without forcefully adding dependencies.
