### ISSUE TITLE
Build fails on node v0.12.0

### ISSUE THREAD

**Issue by jamime** [ivogabe/gulp-typescript#67]
When upgrading to node v0.12.0 I have noticed intermittent build errors.

`src/main/webapp/resources/--js/definitions/models/SiteConfig.d.ts(11,3): 1161 Unterminated regular expression literal.`

Sometimes it throws errors for different files e.g `Referrer.d.ts(8,2): 1161 Unterminated regular expression literal.`

```` javascript
declare module abc.models {
  export interface ISiteConfig {
    configValue?: string;
    siteId?: any;
    subsiteCode?: any;
    subsiteSpecific?: boolean;
    type?: ISiteConfigType;
    isEditing: boolean;
    isDeleting: boolean;
  }
}
````

``` javascript
declare module abc.models {
  export interface ISiteConfigType {
    configDescription: string;
    configKey?: number;
    configName: string;
    dataType: string;
    used: boolean;
    isEditing?: boolean;
    isDeleting?: boolean;
  }
}
````

Build works fine on `0.10.36`, `0.10.32`, `0.11.0`, `0.11.10`, `0.11.13`, `0.11.14`.
Broken in first broken in `0.11.15`, `0.11.16`, `0.12.0`

Any ideas?

**Comment by ivogabe** [comment]
I don't know why that's happening. I can't replicate it, can you create a small project that reproduces this. Also, do you have the latest version of gulp-typescript installed?

**Comment by ivogabe** [comment]
Closed because I can't replicate it. If you have found a way to replicate it, I'll take a look.
