### ISSUE TITLE
The stream never end

### ISSUE THREAD

**Issue by fdecampredon** [ivogabe/gulp-typescript#70]
This stream never emit end, that's bothersome if we want to aggregate the ouput :( in something like browserify

**Comment by ivogabe** [comment]
If I'm not mistaken, it does end the stream. Take a look at https://github.com/ivogabe/gulp-typescript/blob/706e97d3161fe5da7f0ed5dca6031576e40a1f84/lib/main.ts#L70-71, `null` is pushed to the streams to end them. Or is there something more that needs to be done to end the stream?

**Comment by fdecampredon** [comment]
Oups, sorry completely forgot to answer. 
I don't know why but consuming the stream with through2 I was completely unable to get the `flushFunction` to be triggered :/ I finally switched to something else so I can't really tell more about it, anyway sorry again for not answering.

**Comment by ivogabe** [comment]
I tried it with this gulp file:
```javascript
var gulp = require('gulp');
var ts = require('gulp-typescript');
var through2 = require('through2');

var test = through2.obj(function(chunk, enc, callback) {
	console.log(chunk);
	callback();
}, function(callback) {
	console.log('flush!');
	callback();
});

gulp.task('default', function() {
	return gulp.src('test.ts')
		.pipe(ts())
		.pipe(test)
});
```
The flush function was called. So I couldn't reproduce it, probably everything is just working fine :)
