### ISSUE TITLE
Incremental Compilation appears to be broken

### ISSUE THREAD

**Issue by pspeter3** [ivogabe/gulp-typescript#74]
I think that the cache is still working but the build times do not seem to be any faster when using a project. I'm investigating and will report.

**Comment by ivogabe** [comment]
Have you finished your investigations? I think it's because of TypeScript, after the rewrite the compile time was reduced, but there was almost no benefit left of incremental compilation. Now they are working to get it back. Maybe you can compare the times of gulp-typescript with tsc?

**Comment by pspeter3** [comment]
I have looked a bit but scheduled time to really look at it this week. I think that your description is likely which makes me believe the onus is on us to add real in memory caching.

**Comment by ivogabe** [comment]
You can also try to use the master of typescript from github, the latest release of gulp-typescript added support for it. Maybe that version has faster incremental builds.

**Comment by konstantin-azarov** [comment]
I may be missing something, but how is incremental compilation supposed to work? It looks like it is necessary to call `typescript.createProgram` to compile anything, and I don't see any hooks for caching there (apart from caching file contents).

**Comment by ivogabe** [comment]
SourceFile objects of files that are not changed are re-used. That's the same as how tsc handles it. I did a test with `gulp watch` on this project using the latest releases from npm. Initial build time was around 1.6 s, incremental builds were 0.5 - 0.6. So it looks to me everything is working fine.
