### ISSUE TITLE
Singleton source files seem to be ignored

### ISSUE THREAD

**Issue by iislucas** [ivogabe/gulp-typescript#75]
To reproduce: 
1. clone this repo: 
https://github.com/uProxy/node-chrome-runner/tree/f56d0b0b5eaf6e15947c9f953649706e28b4d770
2. Run gulp and observe there is a type-error in chrome-runner.ts
3. Remove the file src/foo.ts (note it is empty), so that only a single file is compiled
4. Run gulp and observe: no errors are printed, no JS file is created. grunt-typescript ignored the file. :(

**Comment by ivogabe** [comment]
It looks like this is an issue with gulp-copy. The last file passed to gulp-copy is removed from the stream. In step 2 `foo.ts` is not passed through, only `chrome-runner.ts` is passed through to gulp-typescript. In step 4 the last file, `chrome-runner.ts` is removed from the stream, thus no file is passed to gulp-typescript. Can you log an issue [here](https://github.com/klaascuvelier/gulp-copy)?

**Comment by iislucas** [comment]
Done: https://github.com/klaascuvelier/gulp-copy/issues/3
