### ISSUE TITLE
allow the build to fail on compile errors

### ISSUE THREAD

**Issue by alexeagle** [ivogabe/gulp-typescript#78]
Currently, if I make a code change and re-run my test task, and there is a compile error, the tests still run, on the old code (if emitOnError:false) or on potentially incorrect code (if emitOnError:true)

I would instead like the build to terminate after the compile task, and short-circuit any further execution.

Looks like JSHint does this with a fail reporter. I imagine I could write a custom reporter to do this, but it feels like a basic capability which would be nice to have built in.

**Comment by ivogabe** [comment]
You can use gulp-plumber? See also #23

**Comment by alexeagle** [comment]
Thanks, looks like a duplicate issue.
It would be great to mention this in the README, others probably will run
into the same question.

Also, an example would be helpful. I've tried gulp-plumber and .on('error',
...) but haven't found something that stops the pipe from continuing,
without exiting the process and ending a watch() task.

**Comment by ivogabe** [comment]
I think it's more about how gulp is working, not gulp-typescript.

As far as I know you can't stop the pipeline without ending the watch.. You can use noEmitOnError, such that no files are pushed to other plugins, and you can save in a variable that the compilation failed, which you can set to true in the error event. If the tests are run in a different task, you can stop that task if the variable is true. Something like:

```javascript
var hasError;
gulp.task('scripts', function() {
  hasError = false;
  return gulp.src(...)
     .pipe(...)
     .on('error', function() { hasError = true; });
});
gulp.task('test', ['scripts'], function(callback) {
  if (hasError) {
    callback();
    return;
  }
  // Run tests
});

**Comment by alexeagle** [comment]
Thanks, that is horribly awkward but it works. I think we'll move to broccoli sometime soon so I guess I won't try to make this work better.
