### ISSUE TITLE
Duplicate string index signature

### ISSUE THREAD

**Issue by uaKorona** [ivogabe/gulp-typescript#87]
Hello 

I use gulp for my angular + TypeScript project. 
*.d.ts declaration files I take from https://github.com/DefinitelyTyped/tsd
But when I run plugin 'gulp-typescript' - I get many errors like this: 
```javascript
E:/MyProjects/20150323__typescript/bower_components/dt-angular/angular.d.ts(13,5): 2300 Duplicate identifier '$inject'.
E:/MyProjects/20150323__typescript/bower_components/dt-jquery/jquery.d.ts(28,5): 2300 Duplicate identifier 'accepts'.
Error in plugin 'gulp-typescript'
```    
I use
"gulp-typescript": "~2.3.0"
"gulp-typescript-compiler": "^1.0.1",
"typescript": "^1.4.1

Could you help me?

**Comment by ivogabe** [comment]
This is not an issue of gulp-typescript, but something with your project. `$inject` and `accepts` are already defined when the compiler reads angular.d.ts & jquery.d.ts. Do you have saved the definition files twice, under different file names? Did you reference files with different casings?

**Comment by uaKorona** [comment]
Oh, thanks. 
You was right! I put reference on angular.d.ts in each controller. But when I removed this reference I had another error: 
```javascript
 E:/MyProjects/20150323__typescript/src/components/navbar/navbar.controller.ts(5,34): error TS2304: Cannot find name 'ng'. 
```
Do you have any idea ?
