### ISSUE TITLE
error message contains [Object object] rather than the message from typescript

### ISSUE THREAD

**Issue by alexeagle** [ivogabe/gulp-typescript#88]
This is because project.ts assumes the messageText property of a diagnostic is a string, but sometimes it is an Object.

See https://github.com/Microsoft/TypeScript/issues/2549#issuecomment-87758677

**Comment by mhegazy** [comment]
some times messages are chained. this is when you have a structural comparison between two nested structures:
e.g.:

```ts
var x = [[{ x: 0 }]];
var y = [[{ y: "" }]];

x = y;
```

```
test.ts(14,1): error TS2322: Type '{ y: string; }[][]' is not assignable to type '{ x: number; }[][]'.
  Type '{ y: string; }[]' is not assignable to type '{ x: number; }[]'.
    Type '{ y: string; }' is not assignable to type '{ x: number; }'.
      Property 'x' is missing in type '{ y: string; }'.
```

you will need to call ts.flatenDiagnosticMessageText before emitting the message, something along the lines of: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsc.ts#L93

**Comment by ivogabe** [comment]
Thanks for reporting! It looks like this is a breaking change between the 1.4 & 1.5 api. gulp-typescript supports TS 1.4 at the moment, and there is some support for the current master ('1.5'). There are a few changes between these two versions I discovered recently, that weren't handled yet by gulp-typescript. I've added this one to the list. I'll try to fix this as soon as possible.

**Comment by ivogabe** [comment]
I've fixed it in #89. There were some issues, which caused that the type checking against the master of TypeScript actually worked against version 1.4, thus errors in the support for 1.5 were not reported. That has been fixed now.

**Comment by alexeagle** [comment]
That is awesome, thank you for the quick fix. One small nit: in the
structured data, there are two error codes, but in the output of
gulp-typescript, I only see the first one. I don't really care because the
code isn't useful to me, but maybe it is somewhere else (eg. some tooling
will want to parse failed builds to understand what errors were there.)

**Comment by ivogabe** [comment]
That's indeed a good point. `longReporter` (which was made for IDE support) & `fullReporter` now show all error codes of nested errors.
