### ISSUE TITLE
gulp-typescript generates wrong source maps

### ISSUE THREAD

**Issue by tkrotoff** [ivogabe/gulp-typescript#90]
I've setup a simple example with gulp-typescript and the generated source maps are wrong: https://github.com/tkrotoff/gulp-typescript-issues

Might be gulp-sourcemaps? no, the example includes .scss files that are compiled through gulp-sass and no problem:

```JavaScript
function sass(src, dest) {
  return gulp.src(src)
    .pipe($.sourcemaps.init())
    .pipe($.sass())
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest(dest));
}

gulp.task('styles', function() {
  return sass('app/app.scss', '.tmp/app')
    .pipe($.debug({title: 'styles:'}));
});
```

`./node_modules/.bin/gulp styles` generates:
```JavaScript
{"version":3,"sources":["app.scss"],"names":[],"mappings":"AAIA;EAFc,AAGZ","file":"app.css","sourcesContent":["// app/app.scss\n\n$font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n\nbody {\n  font-family: $font-family;\n}\n"],"sourceRoot":"/source/"}
```

Now the same with gulp-typescript:

```TypeScript
function tsc(src, dest, out) {
  var tsResult = gulp.src(src)
    .pipe($.sourcemaps.init())
    .pipe($.typescript({
      noImplicitAny: true,
      target: 'ES5',
      declarationFiles: true,
      out: out,
      noExternalResolve: false
    }));

  var js = tsResult.js
    // btw your documentation specify write(), this is wrong, it should be write('.') otherwise it outputs nothing
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest(dest));

  var dts = tsResult.dts
    .pipe(gulp.dest(dest));

  return merge([js, dts]);
}

gulp.task('scripts', function() {
  return tsc('app/_all.ts', '.tmp/app', 'app.js')
    .pipe($.debug({title: 'scripts:'}));
});
```

`./node_modules/.bin/gulp scripts` generates:
```JavaScript
{"version":3,"sources":["app.ts","_all.ts"],"names":[],"mappings":"AAAA,IAAI,GAAG,GAAG;IACR,OAAO,CAAC,GAAG,CAAC,aAAa,CAAC,CAAC;AAC7B,CAAC,CAAC;ACFF,oEAAoE;AAEpE,+BAA+B","file":"app.js","sourceRoot":"/Users/tanguy/gulp-typescript-issues/","sourcesContent":[null,"/// <reference path=\"../node_modules/typescript/bin/lib.es6.d.ts\" />\n\n/// <reference path=\"app.ts\" />\n"]}
```

See the null inside `"sourcesContent":[null,...`? it means it failed.
You can run index.html and see that `app.ts` does not get fetched (404), no problem for `app.scss` and `test.scss`.

**Comment by ivogabe** [comment]
Thanks for your example code. I've investigated it. In your source map, only `_all.ts` is an input file in `gulp.src()`. The content of that file is included in the source map. `app.ts` isn't included in `gulp.src`, before the `sourcemaps.init` call. I think that's the reason why the source isn't included in the source map. You can fix this by adding all the sourcefiles to your gulp file like:
```javascript
gulp.src('src/**/*.ts') // All TypeScript files
gulp.src(['src/a.ts', 'src/b.ts']) // Or use an array to list all files.
```

I'll add a warning to the documentation about this.

Also, you can use `write()` to write source maps. The difference is that `write()` will inline the source map, `write('.')` will create separate map files for them.

**Comment by tkrotoff** [comment]
> only _all.ts is an input file in gulp.src()

I thought that was supported: _all.ts is a regular list of .ts files (`/// <reference path="..." />`) for tsc.

What is very strange is if add this line to _all.ts:
```TypeScript
/// [...]
/// <reference path="../lib/lib.ts" />
```

Then gulp-typescript generates the right source maps:

```JavaScript
{"version":3,"sources":["app/app.ts","lib/lib.ts","app/_all.ts"],"names":[],"mappings":"AAAA,IAAI,GAAG,GAAG;IACR,OAAO,CAAC,GAAG,CAAC,aAAa,CAAC,CAAC;AAC7B,CAAC,CAAC;ACFF,IAAI,GAAG,GAAG;IACR,OAAO,CAAC,GAAG,CAAC,aAAa,CAAC,CAAC;AAC7B,CAAC,CAAC;ACFF,oEAAoE;AAEpE,+BAA+B;AAC/B,sCAAsC","file":"app.js","sourceRoot":"/Users/tanguy/gulp-typescript-issues/","sourcesContent":["var app = () => {\n  console.log('Hello, app!');\n};\n","var lib = () => {\n  console.log('Hello, lib!');\n};\n","/// <reference path=\"../node_modules/typescript/bin/lib.es6.d.ts\" />\n\n/// <reference path=\"app.ts\" />\n/// <reference path=\"../lib/lib.ts\" />\n"]}
```

The "equivalent" for `/// <reference path="..." />` in Sass would be `@import` and gulp-sass handles them without problems (i.e the source maps generated are OK).

I've updated the example to include these findings: https://github.com/tkrotoff/gulp-typescript-issues/commit/4704c0c7e00a54974efa60bbb7efbcd1d80707ed
