### ISSUE TITLE
typescript 1.5 support

### ISSUE THREAD

**Issue by maku** [ivogabe/gulp-typescript#91]
Is it possible to use ts 1.5 with gulp-typescript (1.5.0-alpha is currently available) ?

**Comment by ivogabe** [comment]
Yes. You should add `typescript` as a devDependency:
```
npm install typescript@1.5.0-alpha
```
Then you should add `typescript: require('typescript')` to your gulpfile like this:
```javascript
.pipe(ts({
    typescript: require('typescript')
})
```
(Or change it in the `ts.createProject` call if you use that)

**Comment by swirlycheetah** [comment]
I can't quite get this working, wondering if you can offer any help. I'm seeing the below error after installing typescript 1.5 as a dev dependency then trying to install gulp-typescript, also as a dev dependency:

![screen shot 2015-04-03 at 22 55 52](https://cloud.githubusercontent.com/assets/894092/6989549/aa83def6-da54-11e4-8eb8-5f43fe49c193.png)

**Comment by mikehaas763** [comment]
+1

**Comment by mikehaas763** [comment]
Will a peerDependency of ">=1.4.1 <2.0.0" match a dependency with a version like "1.5.0-alpha"? I get the exact same thing as @swirlycheetah when I run `npm install --save-dev gulp-typescript`. It doesn't even add the dependency to my devDeps in my package.json file when that happens.

**Comment by ivogabe** [comment]
I would expect that `1.5.0-alpha` would match `>=1.4.1 <2.0.0`, but apparently it doesn't. I've removed TypeScript as a peerDependency (see #84), now it should work again. Make sure you download `gulp-typescript@2.6.0` before you download TypeScript.

**Comment by maku** [comment]
Ok. great, seems that this works.
Thank you
