### ISSUE TITLE
typo on help page - missing word in description

### ISSUE THREAD

**Issue by rjperrella** [ivogabe/gulp-typescript#93]
Current: "You can set options, project or filter to if you don't want to set them. Available reporters are:"

Should be: "You can set options, project or filter to **null** if you don't want to set them. Available reporters are:"

(missing the word "null") I think.

**Comment by mikehaas763** [comment]
@rjperrella Is this from the readme.md file? The file I'm seeing says `undefined`.

>You can set options, project or filter to undefined if you don't want to set them. Available reporters are:

**Comment by rjperrella** [comment]
I'm looking at the copy on npmjs.org

https://www.npmjs.com/package/gulp-typescript

And you are correct - it should read undefined. I just saw that in the unit tests.

**Comment by mikehaas763** [comment]
@rjperrella I see, that is odd. I verified that the package version currently published to npm is 2.6.0. My guess is there is a bug in the markdown rendering engine that npmjs.com is using.

**Comment by ivogabe** [comment]
Looks like it's fixed again, I don't know how but it shows `undefined` again on npm.
