### ISSUE TITLE
ES6: lib.es6.d.ts not included

### ISSUE THREAD

**Issue by alshain** [ivogabe/gulp-typescript#94]
When setting the target to es6, it still loads the ES3/5 `lib.d.ts` file.

````typescript
var content = fs.readFileSync(path.resolve(path.dirname(filename) + '/lib.d.ts')).toString('utf8');
return this.libDefault[filename] = tsApi.createSourceFile(typescript, '__lib.d.ts', content, typescript.ScriptTarget.ES3); // Will also work for ES5 & 6
````

I suppose you need to expose `options` to `Host` so you can conditionally include one or the other.

On my local installation, I've hardcoded it to `lib.es6.d.ts` and it seems to do the trick.

https://github.com/ivogabe/gulp-typescript/blob/4a3890b4136967764319f5866d54b61e4ce852e8/lib/host.ts#L28

**Comment by ivogabe** [comment]
Fixed in master
